const urls = require('./urls.js')
const terms = require('./terms.js')

const icons = {
  "ece-icon": `image:https://doc-icons.s3.us-east-2.amazonaws.com/logo_cloud_ece.svg[link=\"${urls['ess-trial']}\", title=\"Supported on ${terms['ece']}\"]`,
  "yes-icon": "image:https://doc-icons.s3.us-east-2.amazonaws.com/icon-yes.png[Yes,20,15]",
  "no-icon": "image:https://doc-icons.s3.us-east-2.amazonaws.com/icon-no.png[No,20,15]",
  "eui-icon-addDataApp": "\"\"",
  "eui-icon-aggregate": "\"\"",
  "eui-icon-alert": "\"\"",
  "eui-icon-apmTrace": "\"\"",
  "eui-icon-arrowDown": "\"\"",
  "eui-icon-arrowLeft": "\"\"",
  "eui-icon-arrowRight": "\"\"",
  "eui-icon-beaker": "\"\"",
  "eui-icon-boxesHorizontal": "\"\"",
  "eui-icon-calendar": "\"\"",
  "eui-icon-casesApp": "\"\"",
  "eui-icon-clock": "\"\"",
  "eui-icon-controlsVertical": "\"\"",
  "eui-icon-copyClipboard": "\"\"",
  "eui-icon-cross": "\"\"",
  "eui-icon-discoverApp": "\"\"",
  "eui-icon-document": "\"\"",
  "eui-icon-documentation": "\"\"",
  "eui-icon-editorComment": "\"\"",
  "eui-icon-eraser": "\"\"",
  "eui-icon-error": "\"\"",
  "eui-icon-expand": "\"\"",
  "eui-icon-eye": "\"\"",
  "eui-icon-filter": "\"\"",
  "eui-icon-filterInCircle": "\"\"",
  "eui-icon-folderCheck": "\"\"",
  "eui-icon-frameNext": "\"\"",
  "eui-icon-framePrevious": "\"\"",
  "eui-icon-gear": "\"\"",
  "eui-icon-gisApp": "\"\"",
  "eui-icon-globe": "\"\"",
  "eui-icon-grab": "\"\"",
  "eui-icon-grabHorizontal": "\"\"",
  "eui-icon-help": "\"\"",
  "eui-icon-iInCircle": "\"\"",
  "eui-icon-indexMapping": "\"\"",
  "eui-icon-indexOpen": "\"\"",
  "eui-icon-inspect": "\"\"",
  "eui-icon-kqlFunction": "\"\"",
  "eui-icon-lensApp": "\"\"",
  "eui-icon-link": "\"\"",
  "eui-icon-list": "\"\"",
  "eui-icon-menuRight": "\"\"",
  "eui-icon-merge": "\"\"",
  "eui-icon-minus": "\"\"",
  "eui-icon-pencil": "\"\"",
  "eui-icon-pinFilled": "\"\"",
  "eui-icon-play": "\"\"",
  "eui-icon-plusInCircle": "\"\"",
  "eui-icon-plusInCircleFilled": "\"\"",
  "eui-icon-popout": "\"\"",
  "eui-icon-refresh": "\"\"",
  "eui-icon-save": "\"\"",
  "eui-icon-sortDown": "\"\"",
  "eui-icon-sortUp": "\"\"",
  "eui-icon-spaces": "\"\"",
  "eui-icon-timeline": "\"\"",
  "eui-icon-timeslider": "\"\"",
  "eui-icon-trash": "\"\"",
  "eui-icon-visText": "\"\"",
  "eui-icon-wrench": "\"\"",
  "dynamic-config": "\"\"",
}

module.exports = icons