const group1 = {
  "dataframe": "data frame",
  "dataframe-cap": "Data frame", 
}

const group2 = {
  "ess": "Elasticsearch Service",
  "ece": "Elastic Cloud Enterprise",
  "eck": "Elastic Cloud on Kubernetes",
  "stack": "Elastic Stack",
  "es": "Elasticsearch",
  "agent": "Elastic Agent",
  "security-features": "security features",
  "webhook": "Webhook",
  "monitor-features": "monitoring features",
  "ml-features": "machine learning features",
  "rollup": "rollup",
  "rollup-cap": "Rollup",
  "ml": "machine learning",
  "ml-cap": "Machine learning",
  "anomaly-detect": "anomaly detection",
  "anomaly-detect-cap": "Anomaly detection",
  "transform": "transform",
  "transform-cap": "Transform",
  "transforms": "transforms",
  "transforms-cap": "Transforms",
  "dfanalytics": `${group1['dataframe']} analytics`,
  "dfanalytics-cap": `${group1['dataframe-cap']} analytics`,
  "dataframes": "data frames",
}

const group3 = {
  //////////
  // Elastic Cloud
  //////////
  "ecloud": "Elastic Cloud",
  "esf": "Elastic Serverless Forwarder",
  "ess-console-name": `${group2['ess']} Console`,
  "ess-skip-section": `If you use ${group2['ess']}, skip this section. ${group2['ess']} handles these changes for you.`,
  "es-feature-flag": "This feature is in development and not yet available for use. This documentation is provided for informational purposes only.",

  //////////
  // Kibana app and UI names
  //////////
  "apm-app": "APM app",
  "uptime-app": "Uptime app",
  "logs-app": "Logs app",
  "metrics-app": "Metrics app",
  "infrastructure-app": "Infrastructure app",
  "siem-app": "SIEM app",
  "security-app": "Elastic Security app",
  "ml-app": "Machine Learning",
  "dev-tools-app": "Dev Tools",
  "ingest-manager-app": "Ingest Manager",
  "stack-manage-app": "Stack Management",
  "stack-monitor-app": "Stack Monitoring",
  "alerts-ui": "Alerts and Actions",
  "rules-ui": "Rules",
  "rac-ui": "Rules and Connectors",
  "connectors-ui": "Connectors",
  "connectors-feature": "Actions and Connectors",
  "stack-rules-feature": "Stack Rules",
  "user-experience": "User Experience",
  "ems": "Elastic Maps Service",
  "ems-init": "EMS",
  "hosted-ems": "Elastic Maps Server",
  "ipm-app": "Index Pattern Management",
  "Data-Sources": "Data Views",
  "Data-source": "Data view",
  "data-source": "data view",
  "Data-sources": "Data views",
  "data-sources": "data views",
  "data-source-caps": "Data View",
  "data-sources-caps": "Data Views",
  "data-source-cap": "Data view",
  "data-sources-cap": "Data views",
  "A-data-source": "A data view",
  "a-data-source": "a data view",

  //////////
  // Enterprise Search
  //////////
  "crawler": "Enterprise Search web crawler",
  "ents": "Enterprise Search",
  "app-search-crawler": "App Search web crawler",

  //////////
  // Ingest terms
  //////////
  "agents": "Elastic Agents",
  "fleet": "Fleet",
  "fleet-server": "Fleet Server",
  "integrations-server": "Integrations Server",
  "ingest-manager": "Ingest Manager",
  "ingest-management": "ingest management",
  "package-manager": "Elastic Package Manager",
  "integrations": "Integrations",

  //////////
  // Common words and phrases
  //////////
  'artifact-registry': 'Elastic Artifact Registry',
  "package-registry": "Elastic Package Registry",
  "xpack": "X-Pack",
  "kib": "Kibana",
  "esms": `${group2['stack']} Monitoring Service`,
  "esms-init": "ESMS",
  "ls": "Logstash",
  "beats": "Beats",
  "auditbeat": "Auditbeat",
  "filebeat": "Filebeat",
  "heartbeat": "Heartbeat",
  "metricbeat": "Metricbeat",
  "packetbeat": "Packetbeat",
  "winlogbeat": "Winlogbeat",
  "functionbeat": "Functionbeat",
  "journalbeat": "Journalbeat",
  "es-sql": `${group2['es']} SQL`,
  esql: 'ES|QL',
  "elastic-agent": `${group2['agent']}`,
  "k8s": "Kubernetes",
  "log-driver-long": "Elastic Logging Plugin for Docker",
  "security": "X-Pack security",
  "operator-feature": "operator privileges feature",
  "es-security-features": `${group2['es']} ${group2['security-features']}`,
  "stack-security-features": `${group2['stack']} ${group2['security-features']}`,
  "endpoint-sec": "Endpoint Security",
  //////////
  // Do not use `endpoint-sec` in versions 8.3.0 and newer
  // Do not use `endpoint-cloud-sec` in versions 8.5.0 and newer
  //////////
  "endpoint-cloud-sec": "Endpoint and Cloud Security",
  "elastic-defend": "Elastic Defend",
  "elastic-sec": "Elastic Security",
  "elastic-endpoint": "Elastic Endpoint",
  "swimlane": "Swimlane",
  "sn": "ServiceNow",
  "sn-itsm": "ServiceNow ITSM",
  "sn-itom": "ServiceNow ITOM",
  "sn-sir": "ServiceNow SecOps",
  "jira": "Jira",
  "ibm-r": "IBM Resilient",
  "webhook-cm": `${group2['webhook']} - Case Management`,
  "opsgenie": "Opsgenie",
  "monitoring": "X-Pack monitoring",
  "stack-monitor-features": `${group2['stack']} ${group2['monitor-features']}`,
  "watcher": "Watcher",
  "alert-features": "alerting features",
  "reporting": "X-Pack reporting",
  "report-features": "reporting features",
  "graph": "X-Pack graph",
  "graph-features": "graph analytics features",
  "searchprofiler": "Search Profiler",
  "xpackml": "X-Pack machine learning",
  "ml-init": "ML",
  "stack-ml-features": `${group2['stack']} ${group2['ml-features']}`,
  "ccr": "cross-cluster replication",
  "ccr-cap": "Cross-cluster replication",
  "ccr-init": "CCR",
  "ccs": "cross-cluster search",
  "ccs-cap": "Cross-cluster search",
  "ccs-init": "CCS",
  "ilm": "index lifecycle management",
  "ilm-cap": "Index lifecycle management",
  "ilm-init": "ILM",
  "dlm": "data lifecycle management",
  "dlm-cap": "Data lifecycle management",
  "dlm-init": "DLM",
  "search-snap": "searchable snapshot",
  "search-snaps": "searchable snapshots",
  "search-snaps-cap": "Searchable snapshots",
  "slm": "snapshot lifecycle management",
  "slm-cap": "Snapshot lifecycle management",
  "slm-init": "SLM",
  "rollup-features": "data rollup features",
  "ipm": "index pattern management",
  "ipm-cap": "Index pattern",
  "rollups": "rollups",
  "rollups-cap": "Rollups",
  "rollup-job": `${group2['rollup']} job`,
  "rollup-jobs": `${group2['rollup']} jobs`,
  "rollup-jobs-cap": `${group2['rollup-cap']} jobs`,
  "dfeed": "datafeed",
  "dfeeds": "datafeeds",
  "dfeed-cap": "Datafeed",
  "dfeeds-cap": "Datafeeds",
  "ml-jobs": `${group2['ml']} jobs`,
  "ml-jobs-cap": `${group2['ml-cap']} jobs`,
  "anomaly-job": `${group2['anomaly-detect']} job`,
  "anomaly-jobs": `${group2['anomaly-detect']} jobs`,
  "anomaly-jobs-cap": `${group2['anomaly-detect-cap']} jobs`,
  "dataframes-cap": "Data frames",
  "watcher-transform": "payload transform",
  "watcher-transforms": "payload transforms",
  "watcher-transform-cap": "Payload transform",
  "watcher-transforms-cap": "Payload transforms",
  "dataframe-transform": `${group2['transform']}`,
  "dataframe-transform-cap": `${group2['transform-cap']}`,
  "dataframe-transforms": `${group2['transforms']}`,
  "dataframe-transforms-cap": `${group2['transforms-cap']}`,
  "dataframe-analytics-config": `${group2['dfanalytics']} config`,
  "dfanalytics-job": `${group2['dfanalytics']} job`,
  "dfanalytics-jobs": `${group2['dfanalytics']} jobs`,
  "dfanalytics-jobs-cap": `${group2['dfanalytics-cap']} jobs`,
  "cdataframe": `continuous ${group2['dataframe']}`,
  "cdataframes": `continuous ${group2['dataframes']}`,
  "cdataframe-cap": `Continuous ${group2['dataframe']}`,
  "cdataframes-cap": `Continuous ${group2['dataframes']}`,
  "cdataframe-transform": `continuous ${group2['transform']}`,
  "cdataframe-transforms": `continuous ${group2['transforms']}`,
  "cdataframe-transforms-cap": `Continuous ${group2['transforms']}`,
  "ctransform": `continuous ${group2['transform']}`,
  "ctransform-cap": `Continuous ${group2['transform']}`,
  "ctransforms": `continuous ${group2['transforms']}`,
  "ctransforms-cap": `Continuous ${group2['transforms']}`,
  "oldetection": "outlier detection",
  "oldetection-cap": "Outlier detection",
  "olscore": "outlier score",
  "olscores": "outlier scores",
  "fiscore": "feature influence score",
  "evaluatedf-api": `evaluate ${group2['dfanalytics']} API`,
  "evaluatedf-api-cap": `Evaluate ${group2['dfanalytics']} API`,
  "binarysc": "binary soft classification",
  "binarysc-cap": "Binary soft classification",
  "regression": "regression",
  "regression-cap": "Regression",
  "reganalysis": "regression analysis",
  "reganalysis-cap": "Regression analysis",
  "depvar": "dependent variable",
  "feature-var": "feature variable",
  "feature-vars": "feature variables",
  "feature-vars-cap": "Feature variables",
  "classification": "classification",
  "classification-cap": "Classification",
  "classanalysis": "classification analysis",
  "classanalysis-cap": "Classification analysis",
  "infer-cap": "Inference",
  "infer": "inference",
  "lang-ident-cap": "Language identification",
  "lang-ident": "language identification",
  "data-viz": "Data Visualizer",
  "file-data-viz": "File Data Visualizer",
  "feat-imp": "feature importance",
  "feat-imp-cap": "Feature importance",
  "nlp": "natural language processing",
  "nlp-cap": "Natural language processing",
  "apm-agent": "APM agent",
  "apm-go-agent": "Elastic APM Go agent",
  "apm-go-agents": "Elastic APM Go agents",
  "apm-ios-agent": "Elastic APM iOS agent",
  "apm-ios-agents": "Elastic APM iOS agents",
  "apm-java-agent": "Elastic APM Java agent",
  "apm-java-agents": "Elastic APM Java agents",
  "apm-dotnet-agent": "Elastic APM .NET agent",
  "apm-dotnet-agents": "Elastic APM .NET agents",
  "apm-node-agent": "Elastic APM Node.js agent",
  "apm-node-agents": "Elastic APM Node.js agents",
  "apm-php-agent": "Elastic APM PHP agent",
  "apm-php-agents": "Elastic APM PHP agents",
  "apm-py-agent": "Elastic APM Python agent",
  "apm-py-agents": "Elastic APM Python agents",
  "apm-ruby-agent": "Elastic APM Ruby agent",
  "apm-ruby-agents": "Elastic APM Ruby agents",
  "apm-rum-agent": "Elastic APM Real User Monitoring (RUM) JavaScript agent",
  "apm-rum-agents": "Elastic APM RUM JavaScript agents",
  "apm-lambda-ext": "Elastic APM AWS Lambda extension",
  "pwd": "YOUR_PASSWORD",
  "esh": "ES-Hadoop",
  "default-dist": "default distribution",
  "oss-dist": "OSS-only distribution",
  "observability": "Observability",
  "api-request-title": "Request",
  "api-prereq-title": "Prerequisites",
  "api-description-title": "Description",
  "api-path-parms-title": "Path parameters",
  "api-query-parms-title": "Query parameters",
  "api-request-body-title": "Request body",
  "api-response-codes-title": "Response codes",
  "api-response-body-title": "Response body",
  "api-example-title": "Example",
  "api-examples-title": "Examples",
  "api-definitions-title": "Properties",
}

const terms = {
  ...group1,
  ...group2,
  ...group3
}

module.exports = terms