[[a-scheduled-task-was-updated]]
=== A scheduled task was updated

Indicates the update of a scheduled task using Windows event logs. Adversaries can use these to establish persistence, by changing the configuration of a legit scheduled task. Some changes such as disabling or enabling a scheduled task are common and may may generate noise.

*Rule type*: eql

<<<<<<< HEAD
*Rule indices*: 

* winlogbeat-*
* logs-system.*
* logs-windows.*

*Severity*: medium

*Risk score*: 47

*Runs every*: 5m
=======
*Rule indices*:

* winlogbeat-*
* logs-system.*

*Severity*: low

*Risk score*: 21

*Runs every*: 5 minutes
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

<<<<<<< HEAD
*References*: 

* https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4698

*Tags*: 

* Domain: Endpoint
* OS: Windows
* Use Case: Threat Detection
* Tactic: Persistence
* Data Source: System

*Version*: 109

*Rule authors*: 

* Elastic

*Rule license*: Elastic License v2

=======
*References*:

* https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4698

*Tags*:

* Elastic
* Host
* Windows
* Threat Detection
* Persistence

*Version*: 2 (<<a-scheduled-task-was-updated-history, version history>>)

*Added ({stack} release)*: 8.5.0

*Last modified ({stack} release)*: 8.6.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Potential false positives

Legitimate scheduled tasks may be created during installation of new software.
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

==== Rule query


<<<<<<< HEAD
[source, js]
----------------------------------
iam where event.action == "scheduled-task-updated" and

 /* excluding tasks created by the computer account */
 not user.name : "*$" and 
 not winlog.event_data.TaskName : "*Microsoft*" and 
 not winlog.event_data.TaskName :
          ("\\User_Feed_Synchronization-*",
           "\\OneDrive Reporting Task-S-1-5-21*",
           "\\OneDrive Reporting Task-S-1-12-1-*",
           "\\Hewlett-Packard\\HP Web Products Detection",
           "\\Hewlett-Packard\\HPDeviceCheck", 
           "\\Microsoft\\Windows\\UpdateOrchestrator\\UpdateAssistant", 
           "\\IpamDnsProvisioning",  
           "\\Microsoft\\Windows\\UpdateOrchestrator\\UpdateAssistantAllUsersRun", 
           "\\Microsoft\\Windows\\UpdateOrchestrator\\UpdateAssistantCalendarRun", 
           "\\Microsoft\\Windows\\UpdateOrchestrator\\UpdateAssistantWakeupRun", 
           "\\Microsoft\\Windows\\.NET Framework\\.NET Framework NGEN v*", 
           "\\Microsoft\\VisualStudio\\Updates\\BackgroundDownload") and 
  not winlog.event_data.SubjectUserSid :  ("S-1-5-18", "S-1-5-19", "S-1-5-20")

----------------------------------

=======
[source,js]
----------------------------------
iam where event.action == "scheduled-task-updated" and /* excluding
tasks created by the computer account */ not user.name : "*$" and
not winlog.event_data.TaskName :
("\\User_Feed_Synchronization-*", "\\OneDrive Reporting
Task-S-1-5-21*", "\\OneDrive Reporting Task-S-1-12-1-*",
"\\Hewlett-Packard\\HP Web Products Detection", "\\Hewlett-
Packard\\HPDeviceCheck")
----------------------------------

==== Threat mapping

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))
*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Persistence
** ID: TA0003
** Reference URL: https://attack.mitre.org/tactics/TA0003/
* Technique:
** Name: Scheduled Task/Job
** ID: T1053
** Reference URL: https://attack.mitre.org/techniques/T1053/
<<<<<<< HEAD
* Sub-technique:
** Name: Scheduled Task
** ID: T1053.005
** Reference URL: https://attack.mitre.org/techniques/T1053/005/
=======

[[a-scheduled-task-was-updated-history]]
==== Rule version history

Version 2 (8.6.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
iam where event.action == "scheduled-task-updated" and /* excluding
tasks created by the computer account */ not user.name : "*$" and
not winlog.event_data.TaskName :
("\\User_Feed_Synchronization-*", "\\OneDrive Reporting
Task-S-1-5-21*", "\\Hewlett-Packard\\HP Web Products
Detection", "\\Hewlett-Packard\\HPDeviceCheck")
----------------------------------

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))
