[[abnormally-large-dns-response]]
=== Abnormally Large DNS Response

Specially crafted DNS requests can manipulate a known overflow vulnerability in some Windows DNS servers which result in Remote Code Execution (RCE) or a Denial of Service (DoS) from crashing the service.

*Rule type*: query

*Rule indices*:

* packetbeat-*
* filebeat-*

*Severity*: medium

*Risk score*: 47

*Runs every*: 5 minutes

*Searches indices from*: now-6m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*:

* https://research.checkpoint.com/2020/resolving-your-way-into-domain-admin-exploiting-a-17-year-old-bug-in-windows-dns-servers/
* https://msrc-blog.microsoft.com/2020/07/14/july-2020-security-update-cve-2020-1350-vulnerability-in-windows-domain-name-system-dns-server/
* https://github.com/maxpl0it/CVE-2020-1350-DoS

*Tags*:

* Elastic
* Network
* Threat Detection
* Lateral Movement

*Version*: 2 (<<abnormally-large-dns-response-history, version history>>)

*Added ({stack} release)*: 7.10.0

*Last modified ({stack} release)*: 7.11.2

*Rule authors*: Elastic

*Rule license*: Elastic License

==== Potential false positives

Environments that leverage DNS responses over 60k bytes will result in false positives - if this traffic is predictable and expected, it should be filtered out. Additionally, this detection rule could be triggered by an authorized vulnerability scan or compromise assessment.

==== Investigation guide

Detection alerts from this rule indicate an attempt was made to exploit
CVE-2020-1350 (SigRed) through the use of large DNS responses on a Windows DNS
server. Here are some possible avenues of investigation:

* Investigate any corresponding Intrusion Detection Signatures (IDS) alerts that can validate this detection alert.
* Examine the `dns.question_type` network fieldset with a protocol analyzer, such as Zeek, Packetbeat, or Suricata, for `SIG` or `RRSIG` data.
* Validate the patch level and OS of the targeted DNS server to validate the observed activity was not large-scale Internet vulnerability scanning.
* Validate that the source of the network activity was not from an authorized vulnerability scan or compromise assessment.

==== Rule query


[source,js]
----------------------------------
event.category:(network or network_traffic) and destination.port:53
and (event.dataset:zeek.dns or type:dns or event.type:connection) and
network.bytes > 60000
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Lateral Movement
** ID: TA0008
** Reference URL: https://attack.mitre.org/tactics/TA0008/
* Technique:
** Name: Exploitation of Remote Services
** ID: T1210
** Reference URL: https://attack.mitre.org/techniques/T1210/

[[abnormally-large-dns-response-history]]
==== Rule version history

Version 2 (7.11.2 release)::
* Formatting only

