[[account-discovery-command-via-system-account]]
=== Account Discovery Command via SYSTEM Account

Identifies when the SYSTEM account uses an account discovery utility. This could be a sign of discovery activity after an adversary has achieved privilege escalation.

*Rule type*: eql

*Rule indices*:

* winlogbeat-*
* logs-endpoint.events.*
* logs-windows.*

*Severity*: low

*Risk score*: 21

*Runs every*: 5 minutes

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*Tags*:

* Elastic
* Host
* Windows
* Threat Detection
* Discovery

*Version*: 11 (<<account-discovery-command-via-system-account-history, version history>>)

*Added ({stack} release)*: 7.7.0

*Last modified ({stack} release)*: 8.2.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Investigation guide


[source,markdown]
----------------------------------
## Config

If enabling an EQL rule on a non-elastic-agent index (such as beats) for versions <8.2, events will not define `event.ingested` and default fallback for EQL rules was not added until 8.2, so you will need to add a custom pipeline to populate `event.ingested` to @timestamp for this rule to work.

----------------------------------


==== Rule query


[source,js]
----------------------------------
process where event.type in ("start", "process_started") and
(?process.Ext.token.integrity_level_name : "System" or
?winlog.event_data.IntegrityLevel : "System") and (process.name :
"whoami.exe" or (process.name : "net1.exe" and not
process.parent.name : "net.exe"))
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Discovery
** ID: TA0007
** Reference URL: https://attack.mitre.org/tactics/TA0007/
* Technique:
** Name: System Owner/User Discovery
** ID: T1033
** Reference URL: https://attack.mitre.org/techniques/T1033/

[[account-discovery-command-via-system-account-history]]
==== Rule version history

Version 11 (8.2.0 release)::
* Rule name changed from: Net command via SYSTEM account
+
* Updated query, changed from:
+
[source, js]
----------------------------------
process where event.type in ("start", "process_started") and
(process.Ext.token.integrity_level_name : "System" or
winlog.event_data.IntegrityLevel : "System") and process.name :
"whoami.exe" or (process.name : "net1.exe" and not
process.parent.name : "net.exe")
----------------------------------

Version 9 (8.1.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
process where event.type in ("start", "process_started") and
user.id in ("S-1-5-18", "S-1-5-19", "S-1-5-20") and process.name :
"whoami.exe" or (process.name : "net1.exe" and not
process.parent.name : "net.exe")
----------------------------------

Version 8 (7.16.0 release)::
* Formatting only

Version 7 (7.13.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.category:process and event.type:(start or process_started) and
(process.name:(whoami.exe or net.exe) or process.name:net1.exe and not
process.parent.name:net.exe) and user.name:SYSTEM
----------------------------------

Version 6 (7.12.0 release)::
* Formatting only

Version 5 (7.11.2 release)::
* Formatting only

Version 4 (7.10.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.category:process and event.type:(start or process_started) and
(process.name:net.exe or process.name:net1.exe and not
process.parent.name:net.exe) and user.name:SYSTEM
----------------------------------

Version 3 (7.9.1 release)::
* Formatting only

Version 2 (7.9.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
(process.name:net.exe or process.name:net1.exe and not
process.parent.name:net.exe) and user.name:SYSTEM and
event.action:"Process Create (rule: ProcessCreate)"
----------------------------------

