[[account-configured-with-never-expiring-password]]
=== Account configured with never Expiring Password

Detects the creation and modification of an account with the "Don't Expire Password" option Enabled. Attackers can abuse this misconfiguration to persist in the domain and maintain long-term access using compromised accounts with this property.

*Rule type*: query

*Rule indices*:

* winlogbeat-*
* logs-system.*

*Severity*: medium

*Risk score*: 47

*Runs every*: 5 minutes

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*:

* https://www.cert.ssi.gouv.fr/uploads/guide-ad.html#dont_expire
* https://blog.menasec.net/2019/02/threat-hunting-26-persistent-password.html

*Tags*:

* Elastic
* Host
* Windows
* Threat Detection
* Persistence
* Active Directory

*Version*: 1

*Added ({stack} release)*: 8.2.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Potential false positives

User accounts can be used as service accounts and have their password set never to expire. This is a bad security practice that exposes the account to Credential Access attacks. For cases in which user accounts cannot be avoided, Microsoft provides the Group Managed Service Accounts (gMSA) feature, which ensures that the account password is robust and changed regularly and automatically.

==== Rule query


[source,js]
----------------------------------
event.action:"modified-user-account" and event.code:"4738" and
message:"'Don't Expire Password' - Enabled" and not user.id:"S-1-5-18"
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Persistence
** ID: TA0003
** Reference URL: https://attack.mitre.org/tactics/TA0003/
* Technique:
** Name: Account Manipulation
** ID: T1098
** Reference URL: https://attack.mitre.org/techniques/T1098/
