[[adobe-hijack-persistence]]
=== Adobe Hijack Persistence

Detects the creation of an executable file or files that will be automatically
run by Acrobat Reader when it starts.

*Rule type*: query

*Rule indices*:

* winlogbeat-*
* logs-endpoint.events.*

*Severity*: low

*Risk score*: 21

*Runs every*: 5 minutes

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*Tags*:

* Elastic
* Host
* Windows
* Threat Detection
* Persistence

*Version*: 6 (<<adobe-hijack-persistence-history, version history>>)

*Added ({stack} release)*: 7.6.0

*Last modified ({stack} release)*: 7.11.0

*Rule authors*: Elastic

*Rule license*: Elastic License

==== Rule query


[source,js]
----------------------------------
event.category:file and event.type:creation and file.path:("C:\Program
Files (x86)\Adobe\Acrobat Reader DC\Reader\AcroCEF\RdrCEF.exe" or
"C:\Program Files\Adobe\Acrobat Reader DC\Reader\AcroCEF\RdrCEF.exe")
and not process.name:msiexec.exe
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Persistence
** ID: TA0003
** Reference URL: https://attack.mitre.org/tactics/TA0003/
* Technique:
** Name: Hijack Execution Flow
** ID: T1574
** Reference URL: https://attack.mitre.org/techniques/T1574/

[[adobe-hijack-persistence-history]]
==== Rule version history

Version 6 (7.11.0 release)::
* Formatting only

Version 5 (7.10.0 release)::
* Formatting only

Version 4 (7.9.1 release)::
* Formatting only

Version 3 (7.9.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
file.path:("C:\Program Files (x86)\Adobe\Acrobat Reader
DC\Reader\AcroCEF\RdrCEF.exe" or "C:\Program Files\Adobe\Acrobat
Reader DC\Reader\AcroCEF\RdrCEF.exe") and event.action:"File created
(rule: FileCreate)" and not process.name:msiexec.exe
----------------------------------

Version 2 (7.6.2 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
file.path:("C:\Program Files (x86)\Adobe\Acrobat Reader
DC\Reader\AcroCEF\RdrCEF.exe" or "C:\Program Files\Adobe\Acrobat
Reader DC\Reader\AcroCEF\RdrCEF.exe") and event.action:"File created
(rule: FileCreate)" and not process.name:msiexeec.exe
----------------------------------

