[[adversary-behavior-detected-elastic-endgame]]
=== Adversary Behavior - Detected - Elastic Endgame

Elastic Endgame detected an Adversary Behavior. Click the Elastic Endgame icon in the event.module column or the link in the rule.reference column for additional information.

*Rule type*: query

<<<<<<< HEAD
*Rule indices*: 
=======
*Rule indices*:
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

* endgame-*

*Severity*: medium

*Risk score*: 47

<<<<<<< HEAD
*Runs every*: 10m
=======
*Runs every*: 10 minutes
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Searches indices from*: now-15m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 10000

<<<<<<< HEAD
*References*: None

*Tags*: 

* Data Source: Elastic Endgame

*Version*: 104

*Rule authors*: 

* Elastic

*Rule license*: Elastic License v2


==== Setup



*Setup*


This rule is configured to generate more **Max alerts per run** than the default 1000 alerts per run set for all rules. This is to ensure that it captures as many alerts as possible.

**IMPORTANT:** The rule's **Max alerts per run** setting can be superseded by the `xpack.alerting.rules.run.alerts.max` Kibana config setting, which determines the maximum alerts generated by _any_ rule in the Kibana alerting framework. For example, if `xpack.alerting.rules.run.alerts.max` is set to 1000, this rule will still generate no more than 1000 alerts even if its own **Max alerts per run** is set higher.

To make sure this rule can generate as many alerts as it's configured in its own **Max alerts per run** setting, increase the `xpack.alerting.rules.run.alerts.max` system setting accordingly.

**NOTE:** Changing `xpack.alerting.rules.run.alerts.max` is not possible in Serverless projects.

==== Rule query


[source, js]
----------------------------------
event.kind:alert and event.module:endgame and (event.action:behavior_protection_event or endgame.event_subtype_full:behavior_protection_event)

----------------------------------
=======
*Tags*:

* Elastic
* Elastic Endgame

*Version*: 101 (<<adversary-behavior-detected-elastic-endgame-history, version history>>)

*Added ({stack} release)*: 7.6.0

*Last modified ({stack} release)*: 8.6.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Rule query


[source,js]
----------------------------------
event.kind:alert and event.module:endgame and
(event.action:behavior_protection_event or
endgame.event_subtype_full:behavior_protection_event)
----------------------------------


[[adversary-behavior-detected-elastic-endgame-history]]
==== Rule version history

Version 101 (8.6.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.kind:alert and event.module:endgame and
(event.action:rules_engine_event or
endgame.event_subtype_full:rules_engine_event)
----------------------------------

Version 100 (8.5.0 release)::
* Formatting only

Version 8 (8.4.0 release)::
* Formatting only

Version 7 (8.0.0 release)::
* Formatting only

Version 6 (7.12.1 release)::
* Formatting only

Version 5 (7.12.0 release)::
* Rule name changed from: Adversary Behavior - Detected - Endpoint Security
Version 4 (7.10.0 release)::
* Rule name changed from: Adversary Behavior - Detected - Elastic Endpoint Security
Version 3 (7.9.0 release)::
* Rule name changed from: Adversary Behavior - Detected - Elastic Endpoint
Version 2 (7.7.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.kind:alert and event.module:endgame and
event.action:rules_engine_event
----------------------------------

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))
