[[attempt-to-modify-okta-network-zone]]
=== Attempt to Modify Okta Network Zone

Okta network zones can be configured to limit or restrict access to a network
based on IP addresses or geolocations. An adversary may attempt to modify,
delete, or deactivate an Okta network zone in order to remove or weaken an
organization's security controls.

*Rule type*: query

*Rule indices*:

* filebeat-*
* logs-okta*

*Severity*: medium

*Risk score*: 47

*Runs every*: 5 minutes

*Searches indices from*: now-6m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*:

* https://developer.okta.com/docs/reference/api/system-log/
* https://developer.okta.com/docs/reference/api/event-types/

*Tags*:

* Elastic
* Okta
* SecOps
* Network
* Continuous Monitoring

*Version*: 2 (<<attempt-to-modify-okta-network-zone-history, version history>>)

*Added ({stack} release)*: 7.9.0

*Last modified ({stack} release)*: 7.10.0

*Rule authors*: Elastic

*Rule license*: Elastic License

==== Potential false positives

Consider adding exceptions to this rule to filter false positives if your
organization's Okta network zones are regularly modified.

==== Investigation guide

The Okta Filebeat module must be enabled to use this rule.

==== Rule query


[source,js]
----------------------------------
event.dataset:okta.system and event.action:(zone.update or
zone.deactivate or zone.delete or network_zone.rule.disabled or
zone.remove_blacklist)
----------------------------------


[[attempt-to-modify-okta-network-zone-history]]
==== Rule version history

Version 2 (7.10.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.module:okta and event.dataset:okta.system and
event.action:(zone.update or zone.deactivate or zone.delete or
network_zone.rule.disabled or zone.remove_blacklist)
----------------------------------

