[[attempt-to-modify-an-okta-network-zone]]
=== Attempt to Modify an Okta Network Zone

Detects attempts to modify an Okta network zone. Okta network zones can be configured to limit or restrict access to a network based on IP addresses or geolocations. An adversary may attempt to modify, delete, or deactivate an Okta network zone in order to remove or weaken an organization's security controls.

*Rule type*: query

*Rule indices*:

* filebeat-*
* logs-okta*

*Severity*: medium

*Risk score*: 47

*Runs every*: 5 minutes

*Searches indices from*: now-6m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*:

* https://help.okta.com/en/prod/Content/Topics/Security/network/network-zones.htm
* https://developer.okta.com/docs/reference/api/system-log/
* https://developer.okta.com/docs/reference/api/event-types/

*Tags*:

* Elastic
* Identity
* Okta
* Continuous Monitoring
* SecOps
* Network Security
* Defense Evasion

*Version*: 101 (<<attempt-to-modify-an-okta-network-zone-history, version history>>)

*Added ({stack} release)*: 7.9.0

*Last modified ({stack} release)*: 8.6.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Potential false positives

Consider adding exceptions to this rule to filter false positives if Oyour organization's Okta network zones are regularly modified.

==== Investigation guide


[source,markdown]
----------------------------------

----------------------------------


==== Rule query


[source,js]
----------------------------------
event.dataset:okta.system and event.action:(zone.update or
network_zone.rule.disabled or zone.remove_blacklist)
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Defense Evasion
** ID: TA0005
** Reference URL: https://attack.mitre.org/tactics/TA0005/
* Technique:
** Name: Impair Defenses
** ID: T1562
** Reference URL: https://attack.mitre.org/techniques/T1562/

[[attempt-to-modify-an-okta-network-zone-history]]
==== Rule version history

Version 101 (8.6.0 release)::
* Formatting only

Version 100 (8.5.0 release)::
* Formatting only

Version 8 (8.4.0 release)::
* Formatting only

Version 6 (7.13.0 release)::
* Formatting only

Version 5 (7.12.0 release)::
* Formatting only

Version 4 (7.11.2 release)::
* Formatting only

Version 3 (7.11.0 release)::
* Rule name changed from: Attempt to Modify Okta Network Zone
+
* Updated query, changed from:
+
[source, js]
----------------------------------
event.dataset:okta.system and event.action:(zone.update or
zone.deactivate or zone.delete or network_zone.rule.disabled or
zone.remove_blacklist)
----------------------------------

Version 2 (7.10.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.module:okta and event.dataset:okta.system and
event.action:(zone.update or zone.deactivate or zone.delete or
network_zone.rule.disabled or zone.remove_blacklist)
----------------------------------

