[[aws-iam-group-creation]]
=== AWS IAM Group Creation

Identifies the creation of a group in AWS Identity and Access Management (IAM). Groups specify permissions for multiple users. Any user in a group automatically has the permissions that are assigned to the group.

*Rule type*: query

<<<<<<< HEAD
*Rule indices*: 

* filebeat-*
* logs-aws.cloudtrail-*
=======
*Rule indices*:

* filebeat-*
* logs-aws*
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Severity*: low

*Risk score*: 21

<<<<<<< HEAD
*Runs every*: 10m
=======
*Runs every*: 10 minutes
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Searches indices from*: now-60m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

<<<<<<< HEAD
*References*: 
=======
*References*:
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

* https://awscli.amazonaws.com/v2/documentation/api/latest/reference/iam/create-group.html
* https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreateGroup.html

<<<<<<< HEAD
*Tags*: 

* Domain: Cloud
* Data Source: AWS
* Data Source: Amazon Web Services
* Data Source: AWS IAM
* Use Case: Identity and Access Audit
* Tactic: Persistence

*Version*: 206

*Rule authors*: 

* Elastic

*Rule license*: Elastic License v2

=======
*Tags*:

* Elastic
* Cloud
* AWS
* Continuous Monitoring
* SecOps
* Identity and Access

*Version*: 101 (<<aws-iam-group-creation-history, version history>>)

*Added ({stack} release)*: 7.9.0

*Last modified ({stack} release)*: 8.6.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Potential false positives

A group may be created by a system or network administrator. Verify whether the user identity, user agent, and/or hostname should be making changes in your environment. Group creations by unfamiliar users or hosts should be investigated. If known behavior is causing false positives, it can be exempted from the rule.
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

==== Investigation guide


<<<<<<< HEAD


==== Setup


The AWS Fleet integration, Filebeat module, or similarly structured data is required to be compatible with this rule.
=======
[source,markdown]
----------------------------------

----------------------------------

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

==== Rule query


<<<<<<< HEAD
[source, js]
----------------------------------
event.dataset:aws.cloudtrail and event.provider:iam.amazonaws.com and event.action:CreateGroup and event.outcome:success

----------------------------------
=======
[source,js]
----------------------------------
event.dataset:aws.cloudtrail and event.provider:iam.amazonaws.com and
event.action:CreateGroup and event.outcome:success
----------------------------------

==== Threat mapping
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Persistence
** ID: TA0003
** Reference URL: https://attack.mitre.org/tactics/TA0003/
* Technique:
** Name: Create Account
** ID: T1136
** Reference URL: https://attack.mitre.org/techniques/T1136/
<<<<<<< HEAD
* Sub-technique:
** Name: Cloud Account
** ID: T1136.003
** Reference URL: https://attack.mitre.org/techniques/T1136/003/
=======

[[aws-iam-group-creation-history]]
==== Rule version history

Version 101 (8.6.0 release)::
* Formatting only

Version 100 (8.5.0 release)::
* Formatting only

Version 9 (8.4.0 release)::
* Formatting only

Version 7 (8.1.0 release)::
* Formatting only

Version 6 (7.13.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.action:CreateGroup and event.dataset:aws.cloudtrail and
event.provider:iam.amazonaws.com and event.outcome:success
----------------------------------

Version 5 (7.12.0 release)::
* Formatting only

Version 4 (7.11.2 release)::
* Formatting only

Version 3 (7.11.0 release)::
* Formatting only

Version 2 (7.10.0 release)::
* Formatting only

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))
