[[aws-deletion-of-rds-instance-or-cluster]]
=== AWS Deletion of RDS Instance or Cluster

Identifies the deletion of an Amazon Relational Database Service (RDS) Aurora database cluster, global database cluster, or database instance.

*Rule type*: query

*Rule indices*:

* filebeat-*
* logs-aws*

*Severity*: medium

*Risk score*: 47

*Runs every*: 10 minutes

*Searches indices from*: now-60m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*:

* https://awscli.amazonaws.com/v2/documentation/api/latest/reference/rds/delete-db-cluster.html
* https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DeleteDBCluster.html
* https://awscli.amazonaws.com/v2/documentation/api/latest/reference/rds/delete-global-cluster.html
* https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DeleteGlobalCluster.html
* https://awscli.amazonaws.com/v2/documentation/api/latest/reference/rds/delete-db-instance.html
* https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DeleteDBInstance.html

*Tags*:

* Elastic
* Cloud
* AWS
* Continuous Monitoring
* SecOps
* Asset Visibility

*Version*: 101 (<<aws-deletion-of-rds-instance-or-cluster-history, version history>>)

*Added ({stack} release)*: 7.9.0

*Last modified ({stack} release)*: 8.6.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Potential false positives

Clusters or instances may be deleted by a system administrator. Verify whether the user identity, user agent, and/or hostname should be making changes in your environment. Cluster or instance deletions by unfamiliar users or hosts should be investigated. If known behavior is causing false positives, it can be exempted from the rule.

==== Investigation guide


[source,markdown]
----------------------------------

----------------------------------


==== Rule query


[source,js]
----------------------------------
event.dataset:aws.cloudtrail and event.provider:rds.amazonaws.com and
event.action:(DeleteDBCluster or DeleteGlobalCluster or
DeleteDBInstance) and event.outcome:success
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Impact
** ID: TA0040
** Reference URL: https://attack.mitre.org/tactics/TA0040/
* Technique:
** Name: Data Destruction
** ID: T1485
** Reference URL: https://attack.mitre.org/techniques/T1485/

[[aws-deletion-of-rds-instance-or-cluster-history]]
==== Rule version history

Version 101 (8.6.0 release)::
* Formatting only

Version 100 (8.5.0 release)::
* Formatting only

Version 9 (8.4.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.dataset:aws.cloudtrail and event.provider:rds.amazonaws.com and
event.action:(DeleteDBCluster or DeleteGlobalCluster or
DeleteDBInstance) and event.outcome:success
----------------------------------

Version 7 (8.2.0 release)::
* Rule name changed from: AWS RDS Cluster Deletion
+
* Updated query, changed from:
+
[source, js]
----------------------------------
event.dataset:aws.cloudtrail and event.provider:rds.amazonaws.com and
event.action:(DeleteDBCluster or DeleteGlobalCluster) and
event.outcome:success
----------------------------------

Version 6 (8.1.0 release)::
* Formatting only

Version 5 (7.13.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.action:(DeleteDBCluster or DeleteGlobalCluster) and
event.dataset:aws.cloudtrail and event.provider:rds.amazonaws.com and
event.outcome:success
----------------------------------

Version 4 (7.12.0 release)::
* Formatting only

Version 3 (7.11.2 release)::
* Formatting only

Version 2 (7.10.0 release)::
* Formatting only

