[[aws-root-login-without-mfa]]
=== AWS Root Login Without MFA

Identifies attempts to login to AWS as the root user without using multi-factor
authentication (MFA). Amazon AWS best practices indicate that the root user
should be protected by MFA.

*Rule type*: query

*Rule indices*:

* filebeat-*
* logs-aws*

*Severity*: high

*Risk score*: 73

*Runs every*: 10 minutes

*Searches indices from*: now-60m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*:

* https://docs.aws.amazon.com/IAM/latest/UserGuide/id_root-user.html

*Tags*:

* Elastic
* Cloud
* AWS
* Continuous Monitoring
* SecOps
* Identity and Access

*Version*: 3 (<<aws-root-login-without-mfa-history, version history>>)

*Added ({stack} release)*: 7.9.0

*Last modified ({stack} release)*: 7.11.2

*Rule authors*: Elastic

*Rule license*: Elastic License

==== Potential false positives

Some organizations allow root-user logins without MFA, however this is not
considered best practice by AWS and increases the risk of compromised
credentials.

==== Investigation guide

The AWS Filebeat module must be enabled to use this rule.

==== Rule query


[source,js]
----------------------------------
event.dataset:aws.cloudtrail and event.provider:signin.amazonaws.com
and event.action:ConsoleLogin and
aws.cloudtrail.user_identity.type:Root and
aws.cloudtrail.console_login.additional_eventdata.mfa_used:false and
event.outcome:success
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Privilege Escalation
** ID: TA0004
** Reference URL: https://attack.mitre.org/tactics/TA0004/
* Technique:
** Name: Valid Accounts
** ID: T1078
** Reference URL: https://attack.mitre.org/techniques/T1078/

[[aws-root-login-without-mfa-history]]
==== Rule version history

Version 3 (7.11.2 release)::
* Formatting only

Version 2 (7.10.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.module:aws and event.dataset:aws.cloudtrail and
event.provider:signin.amazonaws.com and event.action:ConsoleLogin and
aws.cloudtrail.user_identity.type:Root and
aws.cloudtrail.console_login.additional_eventdata.mfa_used:false and
event.outcome:success
----------------------------------

