[[aws-management-console-root-login]]
=== AWS Management Console Root Login

Identifies a successful login to the AWS Management Console by the Root user.

*Rule type*: query

*Rule indices*:

* filebeat-*
* logs-aws*

*Severity*: high

*Risk score*: 73

*Runs every*: 10 minutes

*Searches indices from*: now-60m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*:

* https://docs.aws.amazon.com/IAM/latest/UserGuide/id_root-user.html

*Tags*:

* Elastic
* Cloud
* AWS
* Continuous Monitoring
* SecOps
* Identity and Access

*Version*: 5 (<<aws-management-console-root-login-history, version history>>)

*Added ({stack} release)*: 7.9.0

*Last modified ({stack} release)*: 7.13.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Potential false positives

It's strongly recommended that the root user is not used for everyday tasks, including the administrative ones. Verify whether the IP address, location, and/or hostname should be logging in as root in your environment. Unfamiliar root logins should be investigated immediately. If known behavior is causing false positives, it can be exempted from the rule.

==== Investigation guide


[source,markdown]
----------------------------------
## Config

The AWS Fleet integration, Filebeat module, or similarly structured data is required to be compatible with this rule.
----------------------------------


==== Rule query


[source,js]
----------------------------------
event.dataset:aws.cloudtrail and event.provider:signin.amazonaws.com
and event.action:ConsoleLogin and
aws.cloudtrail.user_identity.type:Root and event.outcome:success
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Initial Access
** ID: TA0001
** Reference URL: https://attack.mitre.org/tactics/TA0001/
* Technique:
** Name: Valid Accounts
** ID: T1078
** Reference URL: https://attack.mitre.org/techniques/T1078/


* Tactic:
** Name: Persistence
** ID: TA0003
** Reference URL: https://attack.mitre.org/tactics/TA0003/
* Technique:
** Name: Valid Accounts
** ID: T1078
** Reference URL: https://attack.mitre.org/techniques/T1078/

[[aws-management-console-root-login-history]]
==== Rule version history

Version 5 (7.13.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.action:ConsoleLogin and event.dataset:aws.cloudtrail and
event.provider:signin.amazonaws.com and
aws.cloudtrail.user_identity.type:Root and event.outcome:success
----------------------------------

Version 4 (7.12.0 release)::
* Formatting only

Version 3 (7.11.2 release)::
* Formatting only

Version 2 (7.10.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.action:ConsoleLogin and event.module:aws and
event.dataset:aws.cloudtrail and event.provider:signin.amazonaws.com
and aws.cloudtrail.user_identity.type:Root and event.outcome:success
----------------------------------

