[[aws-route-table-created]]
=== AWS Route Table Created

Identifies when an AWS Route Table has been created.

*Rule type*: query

<<<<<<< HEAD
*Rule indices*: 

* filebeat-*
* logs-aws.cloudtrail-*
=======
*Rule indices*:

* filebeat-*
* logs-aws*
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Severity*: low

*Risk score*: 21

<<<<<<< HEAD
*Runs every*: 10m
=======
*Runs every*: 10 minutes
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Searches indices from*: now-60m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

<<<<<<< HEAD
*References*: 
=======
*References*:
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

* https://docs.datadoghq.com/security_platform/default_rules/aws-ec2-route-table-modified/
* https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateRoute.html
* https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateRouteTable

<<<<<<< HEAD
*Tags*: 

* Domain: Cloud
* Data Source: AWS
* Data Source: Amazon Web Services
* Data Source: AWS Route53
* Use Case: Network Security Monitoring
* Tactic: Persistence

*Version*: 207

*Rule authors*: 

* Elastic
* Austin Songer

*Rule license*: Elastic License v2

=======
*Tags*:

* Elastic
* Cloud
* AWS
* Continuous Monitoring
* SecOps
* Network Security
* Persistence

*Version*: 101 (<<aws-route-table-created-history, version history>>)

*Added ({stack} release)*: 7.16.0

*Last modified ({stack} release)*: 8.6.0

*Rule authors*: Elastic, Austin Songer

*Rule license*: Elastic License v2

==== Potential false positives

Route Tables may be created by a system or network administrators. Verify whether the user identity, user agent, and/or hostname should be making changes in your environment. Route Table creation by unfamiliar users or hosts should be investigated. If known behavior is causing false positives, it can be exempted from the rule. Automated processes that use Terraform may lead to false positives.
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

==== Investigation guide


<<<<<<< HEAD


==== Setup


The AWS Fleet integration, Filebeat module, or similarly structured data is required to be compatible with this rule.
=======
[source,markdown]
----------------------------------

----------------------------------

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

==== Rule query


<<<<<<< HEAD
[source, js]
----------------------------------
event.dataset:aws.cloudtrail and event.provider:ec2.amazonaws.com and event.action:(CreateRoute or CreateRouteTable) and
event.outcome:success

----------------------------------
=======
[source,js]
----------------------------------
event.dataset:aws.cloudtrail and
event.provider:cloudtrail.amazonaws.com and event.action:(CreateRoute
or CreateRouteTable) and event.outcome:success
----------------------------------

==== Threat mapping
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Persistence
** ID: TA0003
** Reference URL: https://attack.mitre.org/tactics/TA0003/
<<<<<<< HEAD
=======

[[aws-route-table-created-history]]
==== Rule version history

Version 101 (8.6.0 release)::
* Formatting only

Version 100 (8.5.0 release)::
* Formatting only

Version 5 (8.4.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.dataset:aws.cloudtrail and
event.provider:cloudtrail.amazonaws.com and event.action:(CreateRoute
or CreateRouteTable) and event.outcome:success
----------------------------------

Version 3 (8.3.0 release)::
* Formatting only

Version 2 (8.1.0 release)::
* Formatting only

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))
