[[aws-waf-rule-or-rule-group-deletion]]
=== AWS WAF Rule or Rule Group Deletion

Identifies the deletion of a specified AWS Web Application Firewall (WAF) rule or rule group.

*Rule type*: query

<<<<<<< HEAD
*Rule indices*: 

* filebeat-*
* logs-aws.cloudtrail-*
=======
*Rule indices*:

* filebeat-*
* logs-aws*
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Severity*: medium

*Risk score*: 47

<<<<<<< HEAD
*Runs every*: 10m
=======
*Runs every*: 10 minutes
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Searches indices from*: now-60m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

<<<<<<< HEAD
*References*: 
=======
*References*:
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

* https://awscli.amazonaws.com/v2/documentation/api/latest/reference/waf/delete-rule-group.html
* https://docs.aws.amazon.com/waf/latest/APIReference/API_waf_DeleteRuleGroup.html

<<<<<<< HEAD
*Tags*: 

* Domain: Cloud
* Data Source: AWS
* Data Source: Amazon Web Services
* Use Case: Network Security Monitoring
* Tactic: Defense Evasion

*Version*: 206

*Rule authors*: 

* Elastic

*Rule license*: Elastic License v2

=======
*Tags*:

* Elastic
* Cloud
* AWS
* Continuous Monitoring
* SecOps
* Network Security

*Version*: 101 (<<aws-waf-rule-or-rule-group-deletion-history, version history>>)

*Added ({stack} release)*: 7.9.0

*Last modified ({stack} release)*: 8.6.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Potential false positives

WAF rules or rule groups may be deleted by a system or network administrator. Verify whether the user identity, user agent, and/or hostname should be making changes in your environment. Rule deletions by unfamiliar users or hosts should be investigated. If known behavior is causing false positives, it can be exempted from the rule.
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

==== Investigation guide


<<<<<<< HEAD


==== Setup


The AWS Fleet integration, Filebeat module, or similarly structured data is required to be compatible with this rule.
=======
[source,markdown]
----------------------------------

----------------------------------

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

==== Rule query


<<<<<<< HEAD
[source, js]
----------------------------------
event.dataset:aws.cloudtrail and event.provider:(waf.amazonaws.com or waf-regional.amazonaws.com or wafv2.amazonaws.com) and event.action:(DeleteRule or DeleteRuleGroup) and event.outcome:success

----------------------------------
=======
[source,js]
----------------------------------
event.dataset:aws.cloudtrail and event.provider:(waf.amazonaws.com or
waf-regional.amazonaws.com or wafv2.amazonaws.com) and
event.action:(DeleteRule or DeleteRuleGroup) and event.outcome:success
----------------------------------

==== Threat mapping
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Defense Evasion
** ID: TA0005
** Reference URL: https://attack.mitre.org/tactics/TA0005/
* Technique:
** Name: Impair Defenses
** ID: T1562
** Reference URL: https://attack.mitre.org/techniques/T1562/
<<<<<<< HEAD
* Sub-technique:
** Name: Disable or Modify Tools
** ID: T1562.001
** Reference URL: https://attack.mitre.org/techniques/T1562/001/
=======

[[aws-waf-rule-or-rule-group-deletion-history]]
==== Rule version history

Version 101 (8.6.0 release)::
* Formatting only

Version 100 (8.5.0 release)::
* Formatting only

Version 10 (8.4.0 release)::
* Formatting only

Version 8 (8.2.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.dataset:aws.cloudtrail and event.action:(DeleteRule or
DeleteRuleGroup) and event.outcome:success
----------------------------------

Version 7 (8.1.0 release)::
* Formatting only

Version 6 (7.13.0 release)::
* Formatting only

Version 5 (7.12.0 release)::
* Formatting only

Version 4 (7.11.2 release)::
* Formatting only

Version 3 (7.11.0 release)::
* Formatting only

Version 2 (7.10.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.module:aws and event.dataset:aws.cloudtrail and
event.action:(DeleteRule or DeleteRuleGroup) and event.outcome:success
----------------------------------

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))
