[[aws-iam-brute-force-of-assume-role-policy]]
=== AWS IAM Brute Force of Assume Role Policy

Identifies a high number of failed attempts to assume an AWS Identity and Access Management (IAM) role. IAM roles are used to delegate access to users or services. An adversary may attempt to enumerate IAM roles in order to determine if a role exists before attempting to assume or hijack the discovered role.

*Rule type*: threshold

*Rule indices*:

* filebeat-*
* logs-aws*

*Severity*: medium

*Risk score*: 47

*Runs every*: 5 minutes

*Searches indices from*: now-20m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*:

* https://www.praetorian.com/blog/aws-iam-assume-role-vulnerabilities
* https://rhinosecuritylabs.com/aws/assume-worst-aws-assume-role-enumeration/

*Tags*:

* Elastic
* Cloud
* AWS
* Continuous Monitoring
* SecOps
* Identity and Access

*Version*: 5 (<<aws-iam-brute-force-of-assume-role-policy-history, version history>>)

*Added ({stack} release)*: 7.9.0

*Last modified ({stack} release)*: 7.13.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Investigation guide


[source,markdown]
----------------------------------
## Config

The AWS Fleet integration, Filebeat module, or similarly structured data is required to be compatible with this rule.
----------------------------------


==== Rule query


[source,js]
----------------------------------
event.dataset:aws.cloudtrail and event.provider:iam.amazonaws.com
and event.action:UpdateAssumeRolePolicy and
aws.cloudtrail.error_code:MalformedPolicyDocumentException and
event.outcome:failure
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Credential Access
** ID: TA0006
** Reference URL: https://attack.mitre.org/tactics/TA0006/
* Technique:
** Name: Brute Force
** ID: T1110
** Reference URL: https://attack.mitre.org/techniques/T1110/

[[aws-iam-brute-force-of-assume-role-policy-history]]
==== Rule version history

Version 5 (7.13.0 release)::
* Formatting only

Version 4 (7.12.1 release)::
* Formatting only

Version 3 (7.12.0 release)::
* Formatting only

Version 2 (7.10.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.module:aws and event.dataset:aws.cloudtrail and
event.provider:iam.amazonaws.com and
event.action:UpdateAssumeRolePolicy and
aws.cloudtrail.error_code:MalformedPolicyDocumentException and
event.outcome:failure
----------------------------------

