[[azure-key-vault-modified]]
=== Azure Key Vault Modified

Identifies modifications to a Key Vault in Azure. The Key Vault is a service that safeguards encryption keys and secrets like certificates, connection strings, and passwords. Because this data is sensitive and business critical, access to key vaults should be secured to allow only authorized applications and users.

*Rule type*: query

*Rule indices*:

* filebeat-*

*Severity*: medium

*Risk score*: 47

*Runs every*: 5 minutes

*Searches indices from*: now-25m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*:

* https://docs.microsoft.com/en-us/azure/key-vault/general/basic-concepts
* https://docs.microsoft.com/en-us/azure/key-vault/general/secure-your-key-vault

*Tags*:

* Elastic
* Azure
* SecOps
* Continuous Monitoring
* Data Protection

*Version*: 1

*Added ({stack} release)*: 7.10.0

*Rule authors*: Elastic

*Rule license*: Elastic License

==== Potential false positives

Key vault modifications may be done by a system or network administrator. Verify whether the username, hostname, and/or resource name should be making changes in your environment. Key vault modifications from unfamiliar users or hosts should be investigated. If known behavior is causing false positives, it can be exempted from the rule.

==== Investigation guide

The Azure Filebeat module must be enabled to use this rule.

==== Rule query


[source,js]
----------------------------------
event.dataset:azure.activitylogs and
azure.activitylogs.operation_name:MICROSOFT.KEYVAULT/VAULTS/WRITE and
event.outcome:Success
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Credential Access
** ID: TA0006
** Reference URL: https://attack.mitre.org/tactics/TA0006/
* Technique:
** Name: Credentials in Files
** ID: T1081
** Reference URL: https://attack.mitre.org/techniques/T1081/
