[[azure-key-vault-modified]]
=== Azure Key Vault Modified

Identifies modifications to a Key Vault in Azure. The Key Vault is a service that safeguards encryption keys and secrets like certificates, connection strings, and passwords. Because this data is sensitive and business critical, access to key vaults should be secured to allow only authorized applications and users.

*Rule type*: query

<<<<<<< HEAD
*Rule indices*: 
=======
*Rule indices*:
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

* filebeat-*
* logs-azure*

*Severity*: medium

*Risk score*: 47

<<<<<<< HEAD
*Runs every*: 5m
=======
*Runs every*: 5 minutes
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Searches indices from*: now-25m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

<<<<<<< HEAD
*References*: 
=======
*References*:
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

* https://docs.microsoft.com/en-us/azure/key-vault/general/basic-concepts
* https://docs.microsoft.com/en-us/azure/key-vault/general/secure-your-key-vault
* https://www.elastic.co/security-labs/detect-credential-access

<<<<<<< HEAD
*Tags*: 

* Domain: Cloud
* Data Source: Azure
* Tactic: Credential Access

*Version*: 103

*Rule authors*: 

* Elastic

*Rule license*: Elastic License v2

=======
*Tags*:

* Elastic
* Cloud
* Azure
* Continuous Monitoring
* SecOps
* Data Protection

*Version*: 102 (<<azure-key-vault-modified-history, version history>>)

*Added ({stack} release)*: 7.10.0

*Last modified ({stack} release)*: 8.6.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Potential false positives

Key vault modifications may be done by a system or network administrator. Verify whether the username, hostname, and/or resource name should be making changes in your environment. Key vault modifications from unfamiliar users or hosts should be investigated. If known behavior is causing false positives, it can be exempted from the rule.
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

==== Investigation guide


<<<<<<< HEAD


==== Setup


The Azure Fleet integration, Filebeat module, or similarly structured data is required to be compatible with this rule.
=======
[source,markdown]
----------------------------------

----------------------------------

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

==== Rule query


<<<<<<< HEAD
[source, js]
----------------------------------
event.dataset:azure.activitylogs and azure.activitylogs.operation_name:"MICROSOFT.KEYVAULT/VAULTS/WRITE" and event.outcome:(Success or success)

----------------------------------
=======
[source,js]
----------------------------------
event.dataset:azure.activitylogs and
azure.activitylogs.operation_name:"MICROSOFT.KEYVAULT/VAULTS/WRITE"
and event.outcome:(Success or success)
----------------------------------

==== Threat mapping
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Credential Access
** ID: TA0006
** Reference URL: https://attack.mitre.org/tactics/TA0006/
* Technique:
** Name: Unsecured Credentials
** ID: T1552
** Reference URL: https://attack.mitre.org/techniques/T1552/
<<<<<<< HEAD
* Sub-technique:
** Name: Credentials In Files
** ID: T1552.001
** Reference URL: https://attack.mitre.org/techniques/T1552/001/
=======

[[azure-key-vault-modified-history]]
==== Rule version history

Version 102 (8.6.0 release)::
* Formatting only

Version 100 (8.5.0 release)::
* Formatting only

Version 7 (8.4.0 release)::
* Formatting only

Version 5 (7.13.0 release)::
* Formatting only

Version 4 (7.12.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.dataset:azure.activitylogs and
azure.activitylogs.operation_name:MICROSOFT.KEYVAULT/VAULTS/WRITE and
event.outcome:(Success or success)
----------------------------------

Version 3 (7.11.2 release)::
* Formatting only

Version 2 (7.11.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.dataset:azure.activitylogs and
azure.activitylogs.operation_name:MICROSOFT.KEYVAULT/VAULTS/WRITE and
event.outcome:Success
----------------------------------

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))
