[[azure-service-principal-credentials-added]]
=== Azure Service Principal Credentials Added

Identifies when new Service Principal credentials have been added in Azure. In most organizations, credentials will be added to service principals infrequently. Hijacking an application (by adding a rogue secret or certificate) with granted permissions will allow the attacker to access data that is normally protected by MFA requirements.

*Rule type*: query

*Rule indices*:

* filebeat-*
* logs-azure*

*Severity*: medium

*Risk score*: 47

*Runs every*: 10 minutes

*Searches indices from*: now-25m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*:

* https://www.fireeye.com/content/dam/collateral/en/wp-m-unc2452.pdf

*Tags*:

* Elastic
* Cloud
* Azure
* Continuous Monitoring
* SecOps
* Identity and Access

*Version*: 4 (<<azure-service-principal-credentials-added-history, version history>>)

*Added ({stack} release)*: 7.14.0

*Last modified ({stack} release)*: 8.4.0

*Rule authors*: Elastic, Austin Songer

*Rule license*: Elastic License v2

==== Potential false positives

Service principal credential additions may be done by a system or network administrator. Verify whether the username, hostname, and/or resource name should be making changes in your environment. Credential additions from unfamiliar users or hosts should be investigated. If known behavior is causing false positives, it can be exempted from the rule.

==== Investigation guide


[source,markdown]
----------------------------------

----------------------------------


==== Rule query


[source,js]
----------------------------------
event.dataset:azure.auditlogs and azure.auditlogs.operation_name:"Add
service principal credentials" and event.outcome:(success or Success)
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Impact
** ID: TA0040
** Reference URL: https://attack.mitre.org/tactics/TA0040/
* Technique:
** Name: Resource Hijacking
** ID: T1496
** Reference URL: https://attack.mitre.org/techniques/T1496/

[[azure-service-principal-credentials-added-history]]
==== Rule version history

Version 4 (8.4.0 release)::
* Formatting only

Version 2 (8.2.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.dataset:azure.auditlogs and azure.auditlogs.operation_name:"Add
service principal credentials." and event.outcome:(success or Success)
----------------------------------

