[[azure-blob-permissions-modification]]
=== Azure Blob Permissions Modification

Identifies when the Azure role-based access control (Azure RBAC) permissions are modified for an Azure Blob. An adversary may modify the permissions on a blob to weaken their target's security controls or an administrator may inadvertently modify the permissions, which could lead to data exposure or loss.

*Rule type*: query

*Rule indices*:

* filebeat-*
* logs-azure*

*Severity*: medium

*Risk score*: 47

*Runs every*: 5 minutes

*Searches indices from*: now-6m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*:

* https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles

*Tags*:

* Elastic
* Cloud
* Azure
* Continuous Monitoring
* SecOps
* Identity and Access

*Version*: 101 (<<azure-blob-permissions-modification-history, version history>>)

*Added ({stack} release)*: 7.16.0

*Last modified ({stack} release)*: 8.6.0

*Rule authors*: Austin Songer

*Rule license*: Elastic License v2

==== Potential false positives

Blob permissions may be modified by system administrators. Verify that the configuration change was expected. Exceptions can be added to this rule to filter expected behavior.

==== Investigation guide


[source,markdown]
----------------------------------

----------------------------------


==== Rule query


[source,js]
----------------------------------
event.dataset:azure.activitylogs and
azure.activitylogs.operation_name:( "MICROSOFT.STORAGE/STORAGEACC
OUNTS/BLOBSERVICES/CONTAINERS/BLOBS/MANAGEOWNERSHIP/ACTION" or "M
ICROSOFT.STORAGE/STORAGEACCOUNTS/BLOBSERVICES/CONTAINERS/BLOBS/MODIFYP
ERMISSIONS/ACTION") and event.outcome:(Success or success)
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Defense Evasion
** ID: TA0005
** Reference URL: https://attack.mitre.org/tactics/TA0005/
* Technique:
** Name: File and Directory Permissions Modification
** ID: T1222
** Reference URL: https://attack.mitre.org/techniques/T1222/

[[azure-blob-permissions-modification-history]]
==== Rule version history

Version 101 (8.6.0 release)::
* Formatting only

Version 100 (8.5.0 release)::
* Formatting only

Version 3 (8.4.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.dataset:azure.activitylogs and
azure.activitylogs.operation_name:( "MICROSOFT.STORAGE/STORAGEACC
OUNTS/BLOBSERVICES/CONTAINERS/BLOBS/MANAGEOWNERSHIP/ACTION" or "M
ICROSOFT.STORAGE/STORAGEACCOUNTS/BLOBSERVICES/CONTAINERS/BLOBS/MODIFYP
ERMISSIONS/ACTION") and event.outcome:(Success or success)
----------------------------------

