[[azure-virtual-network-device-modified-or-deleted]]
=== Azure Virtual Network Device Modified or Deleted

Identifies when a virtual network device is modified or deleted. This can be a network virtual appliance, virtual hub, or virtual router.

*Rule type*: query

<<<<<<< HEAD
*Rule indices*: 
=======
*Rule indices*:
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

* filebeat-*
* logs-azure*

*Severity*: low

*Risk score*: 21

<<<<<<< HEAD
*Runs every*: 5m
=======
*Runs every*: 5 minutes
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Searches indices from*: now-25m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

<<<<<<< HEAD
*References*: 

* https://docs.microsoft.com/en-us/azure/role-based-access-control/resource-provider-operations

*Tags*: 

* Domain: Cloud
* Data Source: Azure
* Use Case: Network Security Monitoring
* Tactic: Impact

*Version*: 102

*Rule authors*: 

* Austin Songer

*Rule license*: Elastic License v2

=======
*References*:

* https://docs.microsoft.com/en-us/azure/role-based-access-control/resource-provider-operations

*Tags*:

* Elastic
* Cloud
* Azure
* Continuous Monitoring
* SecOps
* Network Security
* Impact

*Version*: 101 (<<azure-virtual-network-device-modified-or-deleted-history, version history>>)

*Added ({stack} release)*: 7.16.0

*Last modified ({stack} release)*: 8.6.0

*Rule authors*: Austin Songer

*Rule license*: Elastic License v2

==== Potential false positives

Virtual Network Device modification or deletion may be performed by a system administrator. Verify whether the user identity, user agent, and/or hostname should be making changes in your environment. Virtual Network Device modification or deletion by unfamiliar users should be investigated. If known behavior is causing false positives, it can be exempted from the rule.
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

==== Investigation guide


<<<<<<< HEAD


==== Setup


The Azure Fleet integration, Filebeat module, or similarly structured data is required to be compatible with this rule.
=======
[source,markdown]
----------------------------------

----------------------------------

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

==== Rule query


<<<<<<< HEAD
[source, js]
----------------------------------
event.dataset:azure.activitylogs and azure.activitylogs.operation_name:("MICROSOFT.NETWORK/NETWORKINTERFACES/TAPCONFIGURATIONS/WRITE" or
"MICROSOFT.NETWORK/NETWORKINTERFACES/TAPCONFIGURATIONS/DELETE" or "MICROSOFT.NETWORK/NETWORKINTERFACES/WRITE" or
"MICROSOFT.NETWORK/NETWORKINTERFACES/JOIN/ACTION" or "MICROSOFT.NETWORK/NETWORKINTERFACES/DELETE" or
"MICROSOFT.NETWORK/NETWORKVIRTUALAPPLIANCES/DELETE" or "MICROSOFT.NETWORK/NETWORKVIRTUALAPPLIANCES/WRITE" or
"MICROSOFT.NETWORK/VIRTUALHUBS/DELETE" or "MICROSOFT.NETWORK/VIRTUALHUBS/WRITE" or
"MICROSOFT.NETWORK/VIRTUALROUTERS/WRITE" or "MICROSOFT.NETWORK/VIRTUALROUTERS/DELETE") and
event.outcome:(Success or success)

----------------------------------
=======
[source,js]
----------------------------------
event.dataset:azure.activitylogs and azure.activitylogs.operation_name
:("MICROSOFT.NETWORK/NETWORKINTERFACES/TAPCONFIGURATIONS/WRITE" or
"MICROSOFT.NETWORK/NETWORKINTERFACES/TAPCONFIGURATIONS/DELETE" or
"MICROSOFT.NETWORK/NETWORKINTERFACES/WRITE" or
"MICROSOFT.NETWORK/NETWORKINTERFACES/JOIN/ACTION" or
"MICROSOFT.NETWORK/NETWORKINTERFACES/DELETE" or
"MICROSOFT.NETWORK/NETWORKVIRTUALAPPLIANCES/DELETE" or
"MICROSOFT.NETWORK/NETWORKVIRTUALAPPLIANCES/WRITE" or
"MICROSOFT.NETWORK/VIRTUALHUBS/DELETE" or
"MICROSOFT.NETWORK/VIRTUALHUBS/WRITE" or
"MICROSOFT.NETWORK/VIRTUALROUTERS/WRITE" or
"MICROSOFT.NETWORK/VIRTUALROUTERS/DELETE") and event.outcome:(Success
or success)
----------------------------------

==== Threat mapping
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Impact
** ID: TA0040
** Reference URL: https://attack.mitre.org/tactics/TA0040/
<<<<<<< HEAD
=======

[[azure-virtual-network-device-modified-or-deleted-history]]
==== Rule version history

Version 101 (8.6.0 release)::
* Formatting only

Version 100 (8.5.0 release)::
* Formatting only

Version 4 (8.4.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.dataset:azure.activitylogs and azure.activitylogs.operation_name
:("MICROSOFT.NETWORK/NETWORKINTERFACES/TAPCONFIGURATIONS/WRITE" or
"MICROSOFT.NETWORK/NETWORKINTERFACES/TAPCONFIGURATIONS/DELETE" or
"MICROSOFT.NETWORK/NETWORKINTERFACES/WRITE" or
"MICROSOFT.NETWORK/NETWORKINTERFACES/JOIN/ACTION" or
"MICROSOFT.NETWORK/NETWORKINTERFACES/DELETE" or
"MICROSOFT.NETWORK/NETWORKVIRTUALAPPLIANCES/DELETE" or
"MICROSOFT.NETWORK/NETWORKVIRTUALAPPLIANCES/WRITE" or
"MICROSOFT.NETWORK/VIRTUALHUBS/DELETE" or
"MICROSOFT.NETWORK/VIRTUALHUBS/WRITE" or
"MICROSOFT.NETWORK/VIRTUALROUTERS/WRITE" or
"MICROSOFT.NETWORK/VIRTUALROUTERS/DELETE") and event.outcome:(Success
or success)
----------------------------------

Version 2 (8.1.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.dataset:azure.activitylogs and azure.activitylogs.operation_name
:("MICROSOFT.NETWORK/NETWORKINTERFACES/TAPCONFIGURATIONS/WRITE" or
"MICROSOFT.NETWORK/NETWORKINTERFACES/TAPCONFIGURATIONS/DELETE" or
"MICROSOFT.NETWORK/NETWORKINTERFACES/WRITE" or
"MICROSOFT.NETWORK/NETWORKINTERFACES/JOIN/ACTION" or
"MICROSOFT.NETWORK/NETWORKINTERFACES/DELETE"or
"MICROSOFT.NETWORK/NETWORKVIRTUALAPPLIANCES/DELETE" or
"MICROSOFT.NETWORK/NETWORKVIRTUALAPPLIANCES/WRITE" or
"MICROSOFT.NETWORK/VIRTUALHUBS/DELETE" or
"MICROSOFT.NETWORK/VIRTUALHUBS/WRITE" or
"MICROSOFT.NETWORK/VIRTUALROUTERS/WRITE" or
"MICROSOFT.NETWORK/VIRTUALROUTERS/DELETE") and event.outcome:(Success
or success)
----------------------------------

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))
