[[azure-event-hub-authorization-rule-created-or-updated]]
=== Azure Event Hub Authorization Rule Created or Updated

Identifies when an Event Hub Authorization Rule is created or updated in Azure. An authorization rule is associated with specific rights, and carries a pair of cryptographic keys. When you create an Event Hubs namespace, a policy rule named RootManageSharedAccessKey is created for the namespace. This has manage permissions for the entire namespace and it's recommended that you treat this rule like an administrative root account and don't use it in your application.

*Rule type*: query

<<<<<<< HEAD
*Rule indices*: 
=======
*Rule indices*:
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

* filebeat-*
* logs-azure*

*Severity*: medium

*Risk score*: 47

<<<<<<< HEAD
*Runs every*: 5m
=======
*Runs every*: 5 minutes
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Searches indices from*: now-25m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

<<<<<<< HEAD
*References*: 

* https://docs.microsoft.com/en-us/azure/event-hubs/authorize-access-shared-access-signature

*Tags*: 

* Domain: Cloud
* Data Source: Azure
* Use Case: Log Auditing
* Tactic: Collection

*Version*: 103

*Rule authors*: 

* Elastic

*Rule license*: Elastic License v2

=======
*References*:

* https://docs.microsoft.com/en-us/azure/event-hubs/authorize-access-shared-access-signature

*Tags*:

* Elastic
* Cloud
* Azure
* Continuous Monitoring
* SecOps
* Log Auditing

*Version*: 101 (<<azure-event-hub-authorization-rule-created-or-updated-history, version history>>)

*Added ({stack} release)*: 7.10.0

*Last modified ({stack} release)*: 8.6.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Potential false positives

Authorization rule additions or modifications may be done by a system or network administrator. Verify whether the username, hostname, and/or resource name should be making changes in your environment. Authorization rule additions or modifications from unfamiliar users or hosts should be investigated. If known behavior is causing false positives, it can be exempted from the rule.
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

==== Investigation guide


<<<<<<< HEAD


==== Setup


The Azure Fleet integration, Filebeat module, or similarly structured data is required to be compatible with this rule.
=======
[source,markdown]
----------------------------------

----------------------------------

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

==== Rule query


<<<<<<< HEAD
[source, js]
----------------------------------
event.dataset:azure.activitylogs and azure.activitylogs.operation_name:"MICROSOFT.EVENTHUB/NAMESPACES/AUTHORIZATIONRULES/WRITE" and event.outcome:(Success or success)

----------------------------------
=======
[source,js]
----------------------------------
event.dataset:azure.activitylogs and azure.activitylogs.operation_name
:"MICROSOFT.EVENTHUB/NAMESPACES/AUTHORIZATIONRULES/WRITE" and
event.outcome:(Success or success)
----------------------------------

==== Threat mapping
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Collection
** ID: TA0009
** Reference URL: https://attack.mitre.org/tactics/TA0009/
* Technique:
<<<<<<< HEAD
** Name: Data from Cloud Storage
** ID: T1530
** Reference URL: https://attack.mitre.org/techniques/T1530/
=======
** Name: Data from Cloud Storage Object
** ID: T1530
** Reference URL: https://attack.mitre.org/techniques/T1530/


>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))
* Tactic:
** Name: Exfiltration
** ID: TA0010
** Reference URL: https://attack.mitre.org/tactics/TA0010/
* Technique:
** Name: Transfer Data to Cloud Account
** ID: T1537
** Reference URL: https://attack.mitre.org/techniques/T1537/
<<<<<<< HEAD
=======

[[azure-event-hub-authorization-rule-created-or-updated-history]]
==== Rule version history

Version 101 (8.6.0 release)::
* Formatting only

Version 100 (8.5.0 release)::
* Formatting only

Version 7 (8.4.0 release)::
* Formatting only

Version 5 (7.13.0 release)::
* Formatting only

Version 4 (7.12.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.dataset:azure.activitylogs and azure.activitylogs.operation_name
:MICROSOFT.EVENTHUB/NAMESPACES/AUTHORIZATIONRULES/WRITE and
event.outcome:(Success or success)
----------------------------------

Version 3 (7.11.2 release)::
* Formatting only

Version 2 (7.11.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.dataset:azure.activitylogs and azure.activitylogs.operation_name
:MICROSOFT.EVENTHUB/NAMESPACES/AUTHORIZATIONRULES/WRITE and
event.outcome:Success
----------------------------------

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))
