[[azure-event-hub-deletion]]
=== Azure Event Hub Deletion

Identifies an Event Hub deletion in Azure. An Event Hub is an event processing service that ingests and processes large volumes of events and data. An adversary may delete an Event Hub in an attempt to evade detection.

*Rule type*: query

*Rule indices*:

* filebeat-*

*Severity*: medium

*Risk score*: 47

*Runs every*: 5 minutes

*Searches indices from*: now-25m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*:

* https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-about
* https://azure.microsoft.com/en-in/services/event-hubs/
* https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-features

*Tags*:

* Azure
* Elastic
* SecOps
* Continuous Monitoring
* Logging

*Version*: 1

*Added ({stack} release)*: 7.10.0

*Rule authors*: Elastic

*Rule license*: Elastic License

==== Potential false positives

Event Hub deletions may be done by a system or network administrator. Verify whether the username, hostname, and/or resource name should be making changes in your environment. Event Hub deletions from unfamiliar users or hosts should be investigated. If known behavior is causing false positives, it can be exempted from the rule.

==== Investigation guide

The Azure Filebeat module must be enabled to use this rule.

==== Rule query


[source,js]
----------------------------------
event.dataset:azure.activitylogs and azure.activitylogs.operation_name
:MICROSOFT.EVENTHUB/NAMESPACES/EVENTHUBS/DELETE and
event.outcome:Success
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Defense Evasion
** ID: TA0005
** Reference URL: https://attack.mitre.org/tactics/TA0005/
* Technique:
** Name: Disabling Security Tools
** ID: T1089
** Reference URL: https://attack.mitre.org/techniques/T1089/
