[[azure-full-network-packet-capture-detected]]
=== Azure Full Network Packet Capture Detected

Identifies potential full network packet capture in Azure. Packet Capture is an Azure Network Watcher feature that can be used to inspect network traffic. This feature can potentially be abused to read sensitive data from unencrypted internal traffic.

*Rule type*: query

<<<<<<< HEAD
*Rule indices*: 
=======
*Rule indices*:
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

* filebeat-*
* logs-azure*

*Severity*: medium

*Risk score*: 47

<<<<<<< HEAD
*Runs every*: 5m
=======
*Runs every*: 5 minutes
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Searches indices from*: now-25m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

<<<<<<< HEAD
*References*: 

* https://docs.microsoft.com/en-us/azure/role-based-access-control/resource-provider-operations

*Tags*: 

* Domain: Cloud
* Data Source: Azure
* Tactic: Credential Access

*Version*: 103

*Rule authors*: 

* Austin Songer

*Rule license*: Elastic License v2

=======
*References*:

* https://docs.microsoft.com/en-us/azure/role-based-access-control/resource-provider-operations

*Tags*:

* Elastic
* Cloud
* Azure
* Continuous Monitoring
* SecOps
* Monitoring

*Version*: 101 (<<azure-full-network-packet-capture-detected-history, version history>>)

*Added ({stack} release)*: 7.16.0

*Last modified ({stack} release)*: 8.6.0

*Rule authors*: Austin Songer

*Rule license*: Elastic License v2

==== Potential false positives

Full Network Packet Capture may be done by a system or network administrator. Verify whether the user identity, user agent, and/or hostname should be making changes in your environment. Full Network Packet Capture from unfamiliar users or hosts should be investigated. If known behavior is causing false positives, it can be exempted from the rule.
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

==== Investigation guide


<<<<<<< HEAD


==== Setup


The Azure Fleet integration, Filebeat module, or similarly structured data is required to be compatible with this rule.
=======
[source,markdown]
----------------------------------

----------------------------------

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

==== Rule query


<<<<<<< HEAD
[source, js]
----------------------------------
event.dataset:azure.activitylogs and azure.activitylogs.operation_name:
    (
        MICROSOFT.NETWORK/*/STARTPACKETCAPTURE/ACTION or
        MICROSOFT.NETWORK/*/VPNCONNECTIONS/STARTPACKETCAPTURE/ACTION or
        MICROSOFT.NETWORK/*/PACKETCAPTURES/WRITE
    ) and
event.outcome:(Success or success)

----------------------------------

=======
[source,js]
----------------------------------
event.dataset:azure.activitylogs and
azure.activitylogs.operation_name: (
"MICROSOFT.NETWORK/*/STARTPACKETCAPTURE/ACTION" or
"MICROSOFT.NETWORK/*/VPNCONNECTIONS/STARTPACKETCAPTURE/ACTION" or
"MICROSOFT.NETWORK/*/PACKETCAPTURES/WRITE" ) and
event.outcome:(Success or success)
----------------------------------

==== Threat mapping

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))
*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Credential Access
** ID: TA0006
** Reference URL: https://attack.mitre.org/tactics/TA0006/
* Technique:
** Name: Network Sniffing
** ID: T1040
** Reference URL: https://attack.mitre.org/techniques/T1040/
<<<<<<< HEAD
=======

[[azure-full-network-packet-capture-detected-history]]
==== Rule version history

Version 101 (8.6.0 release)::
* Formatting only

Version 100 (8.5.0 release)::
* Formatting only

Version 3 (8.4.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.dataset:azure.activitylogs and
azure.activitylogs.operation_name: (
"MICROSOFT.NETWORK/*/STARTPACKETCAPTURE/ACTION" or
"MICROSOFT.NETWORK/*/VPNCONNECTIONS/STARTPACKETCAPTURE/ACTION" or
"MICROSOFT.NETWORK/*/PACKETCAPTURES/WRITE" ) and
event.outcome:(Success or success)
----------------------------------

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))
