[[azure-storage-account-key-regenerated]]
=== Azure Storage Account Key Regenerated

Identifies a rotation to storage account access keys in Azure. Regenerating access keys can affect any applications or Azure services that are dependent on the storage account key. Adversaries may regenerate a key as a means of acquiring credentials to access systems and resources.

*Rule type*: query

<<<<<<< HEAD
*Rule indices*: 
=======
*Rule indices*:
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

* filebeat-*
* logs-azure*

*Severity*: low

*Risk score*: 21

<<<<<<< HEAD
*Runs every*: 5m
=======
*Runs every*: 5 minutes
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Searches indices from*: now-25m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

<<<<<<< HEAD
*References*: 

* https://docs.microsoft.com/en-us/azure/storage/common/storage-account-keys-manage?tabs=azure-portal

*Tags*: 

* Domain: Cloud
* Data Source: Azure
* Use Case: Identity and Access Audit
* Tactic: Credential Access

*Version*: 102

*Rule authors*: 

* Elastic

*Rule license*: Elastic License v2

=======
*References*:

* https://docs.microsoft.com/en-us/azure/storage/common/storage-account-keys-manage?tabs=azure-portal

*Tags*:

* Elastic
* Cloud
* Azure
* Continuous Monitoring
* SecOps
* Identity and Access

*Version*: 101 (<<azure-storage-account-key-regenerated-history, version history>>)

*Added ({stack} release)*: 7.10.0

*Last modified ({stack} release)*: 8.6.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Potential false positives

It's recommended that you rotate your access keys periodically to help keep your storage account secure. Normal key rotation can be exempted from the rule. An abnormal time frame and/or a key rotation from unfamiliar users, hosts, or locations should be investigated.
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

==== Investigation guide


<<<<<<< HEAD


==== Setup


The Azure Fleet integration, Filebeat module, or similarly structured data is required to be compatible with this rule.
=======
[source,markdown]
----------------------------------

----------------------------------

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

==== Rule query


<<<<<<< HEAD
[source, js]
----------------------------------
event.dataset:azure.activitylogs and azure.activitylogs.operation_name:"MICROSOFT.STORAGE/STORAGEACCOUNTS/REGENERATEKEY/ACTION" and event.outcome:(Success or success)

----------------------------------
=======
[source,js]
----------------------------------
event.dataset:azure.activitylogs and azure.activitylogs.operation_name
:"MICROSOFT.STORAGE/STORAGEACCOUNTS/REGENERATEKEY/ACTION" and
event.outcome:(Success or success)
----------------------------------

==== Threat mapping
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Credential Access
** ID: TA0006
** Reference URL: https://attack.mitre.org/tactics/TA0006/
* Technique:
** Name: Steal Application Access Token
** ID: T1528
** Reference URL: https://attack.mitre.org/techniques/T1528/
<<<<<<< HEAD
=======

[[azure-storage-account-key-regenerated-history]]
==== Rule version history

Version 101 (8.6.0 release)::
* Formatting only

Version 100 (8.5.0 release)::
* Formatting only

Version 7 (8.4.0 release)::
* Formatting only

Version 5 (7.13.0 release)::
* Formatting only

Version 4 (7.12.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.dataset:azure.activitylogs and azure.activitylogs.operation_name
:MICROSOFT.STORAGE/STORAGEACCOUNTS/REGENERATEKEY/ACTION and
event.outcome:(Success or success)
----------------------------------

Version 3 (7.11.2 release)::
* Formatting only

Version 2 (7.11.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.dataset:azure.activitylogs and azure.activitylogs.operation_name
:MICROSOFT.STORAGE/STORAGEACCOUNTS/REGENERATEKEY/ACTION and
event.outcome:Success
----------------------------------

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))
