[[binary-executed-from-shared-memory-directory]]
=== Binary Executed from Shared Memory Directory

Identifies the execution of a binary by root in Linux shared memory directories: (/dev/shm/, /run/shm/, /var/run/, /var/lock/). This activity is to be considered highly abnormal and should be investigated. Threat actors have placed executables used for persistence on high-uptime servers in these directories as system backdoors.

*Rule type*: eql

*Rule indices*:

* logs-endpoint.events.*

*Severity*: high

*Risk score*: 73

*Runs every*: 5 minutes

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*:

* https://linuxsecurity.com/features/fileless-malware-on-linux
* https://twitter.com/GossiTheDog/status/1522964028284411907

*Tags*:

* Elastic
* Host
* Linux
* Threat Detection
* Execution
* BPFDoor

*Version*: 1

*Added ({stack} release)*: 8.3.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Potential false positives

Directories /dev/shm and /run/shm are temporary file storage directories in Linux. They are intended to appear as a mounted file system, but uses virtual memory instead of a persistent storage device and thus are used for mounting file systems in legitimate purposes.

==== Rule query


[source,js]
----------------------------------
process where event.type == "start" and event.action == "exec"
and user.name == "root" and process.executable : (
"/dev/shm/*", "/run/shm/*", "/var/run/*",
"/var/lock/*" )
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Execution
** ID: TA0002
** Reference URL: https://attack.mitre.org/tactics/TA0002/
* Technique:
** Name: Command and Scripting Interpreter
** ID: T1059
** Reference URL: https://attack.mitre.org/techniques/T1059/
