[[cobalt-strike-command-and-control-beacon]]
=== Cobalt Strike Command and Control Beacon

Cobalt Strike is a threat emulation platform commonly modified and used by adversaries to conduct network attack and exploitation campaigns. This rule detects a network activity algorithm leveraged by Cobalt Strike implant beacons for command and control.

*Rule type*: query

<<<<<<< HEAD
*Rule indices*: 

* packetbeat-*
* auditbeat-*
* filebeat-*
* logs-network_traffic.*
=======
*Rule indices*:

* auditbeat-*
* filebeat-*
* packetbeat-*
* logs-endpoint.events.*
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Severity*: high

*Risk score*: 73

<<<<<<< HEAD
*Runs every*: 5m
=======
*Runs every*: 5 minutes
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

<<<<<<< HEAD
*References*: 
=======
*References*:
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

* https://blog.morphisec.com/fin7-attacks-restaurant-industry
* https://www.fireeye.com/blog/threat-research/2017/04/fin7-phishing-lnk.html
* https://www.elastic.co/security-labs/collecting-cobalt-strike-beacons-with-the-elastic-stack

<<<<<<< HEAD
*Tags*: 

* Use Case: Threat Detection
* Tactic: Command and Control
* Domain: Endpoint

*Version*: 105

*Rule authors*: 

* Elastic

*Rule license*: Elastic License v2

=======
*Tags*:

* Elastic
* Network
* Threat Detection
* Command and Control
* Host

*Version*: 101 (<<cobalt-strike-command-and-control-beacon-history, version history>>)

*Added ({stack} release)*: 7.10.0

*Last modified ({stack} release)*: 8.6.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Potential false positives

This rule should be tailored to either exclude systems, as sources or destinations, in which this behavior is expected.
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

==== Investigation guide


<<<<<<< HEAD

*Threat intel*


This activity has been observed in FIN7 campaigns.
=======
[source,markdown]
----------------------------------
## Threat intel

This activity has been observed in FIN7 campaigns.
----------------------------------

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

==== Rule query


<<<<<<< HEAD
[source, js]
----------------------------------
((event.category: (network OR network_traffic) AND type: (tls OR http))
    OR event.dataset: (network_traffic.tls OR network_traffic.http)
) AND destination.domain:/[a-z]{3}.stage.[0-9]{8}\..*/

----------------------------------
=======
[source,js]
----------------------------------
event.category:(network OR network_traffic) AND type:(tls OR http) AND
network.transport:tcp AND
destination.domain:/[a-z]{3}.stage.[0-9]{8}\..*/
----------------------------------

==== Threat mapping
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Command and Control
** ID: TA0011
** Reference URL: https://attack.mitre.org/tactics/TA0011/
* Technique:
** Name: Application Layer Protocol
** ID: T1071
** Reference URL: https://attack.mitre.org/techniques/T1071/
<<<<<<< HEAD
* Technique:
** Name: Dynamic Resolution
** ID: T1568
** Reference URL: https://attack.mitre.org/techniques/T1568/
* Sub-technique:
** Name: Domain Generation Algorithms
** ID: T1568.002
** Reference URL: https://attack.mitre.org/techniques/T1568/002/
=======

[[cobalt-strike-command-and-control-beacon-history]]
==== Rule version history

Version 101 (8.6.0 release)::
* Formatting only

Version 100 (8.5.0 release)::
* Formatting only

Version 6 (7.14.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.category:(network OR network_traffic) AND type:(tls OR http) AND
network.transport:tcp AND
destination.domain:/[a-z]{3}.stage.[0-9]{8}\..*/
----------------------------------

Version 5 (7.13.0 release)::
* Formatting only

Version 4 (7.12.0 release)::
* Formatting only

Version 3 (7.11.2 release)::
* Formatting only

Version 2 (7.11.0 release)::
* Formatting only

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))
