[[conhost-spawned-by-suspicious-parent-process]]
=== Conhost Spawned By Suspicious Parent Process

Detects when the Console Window Host (conhost.exe) process is spawned by a suspicious parent process, which could be indicative of code injection.

*Rule type*: eql

*Rule indices*:

* winlogbeat-*
* logs-endpoint.events.*
* logs-windows.*

*Severity*: high

*Risk score*: 73

*Runs every*: 5 minutes

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*:

* https://www.fireeye.com/blog/threat-research/2017/08/monitoring-windows-console-activity-part-one.html

*Tags*:

* Elastic
* Host
* Windows
* Threat Detection
* Execution

*Version*: 4 (<<conhost-spawned-by-suspicious-parent-process-history, version history>>)

*Added ({stack} release)*: 7.10.0

*Last modified ({stack} release)*: 7.13.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Rule query


[source,js]
----------------------------------
process where event.type in ("start", "process_started") and
process.name : "conhost.exe" and process.parent.name :
("svchost.exe", "lsass.exe", "services.exe", "smss.exe",
"winlogon.exe", "explorer.exe",
"dllhost.exe", "rundll32.exe", "regsvr32.exe", "userinit.exe",
"wininit.exe", "spoolsv.exe", "wermgr.exe",
"csrss.exe", "ctfmon.exe")
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Execution
** ID: TA0002
** Reference URL: https://attack.mitre.org/tactics/TA0002/
* Technique:
** Name: Command and Scripting Interpreter
** ID: T1059
** Reference URL: https://attack.mitre.org/techniques/T1059/

[[conhost-spawned-by-suspicious-parent-process-history]]
==== Rule version history

Version 4 (7.13.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.category:process and event.type:(start or process_started) and
process.name:conhost.exe and process.parent.name:(svchost.exe or
lsass.exe or services.exe or smss.exe or winlogon.exe or explorer.exe
or dllhost.exe or rundll32.exe or regsvr32.exe or userinit.exe or
wininit.exe or spoolsv.exe or wermgr.exe or csrss.exe or ctfmon.exe)
----------------------------------

Version 3 (7.12.0 release)::
* Formatting only

Version 2 (7.11.2 release)::
* Formatting only

