[[control-panel-process-with-unusual-arguments]]
=== Control Panel Process with Unusual Arguments

Identifies unusual instances of Control Panel with suspicious keywords or paths in the process command line value. Adversaries may abuse control.exe to proxy execution of malicious code.

*Rule type*: eql

<<<<<<< HEAD
*Rule indices*: 

* logs-endpoint.events.process-*
* winlogbeat-*
* logs-windows.forwarded*
* logs-windows.sysmon_operational-*
* endgame-*
* logs-system.security*
* logs-m365_defender.event-*
* logs-sentinel_one_cloud_funnel.*
* logs-crowdstrike.fdr*
=======
*Rule indices*:

* logs-endpoint.events.*
* winlogbeat-*
* logs-windows.*
* endgame-*
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Severity*: high

*Risk score*: 73

<<<<<<< HEAD
*Runs every*: 5m
=======
*Runs every*: 5 minutes
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

<<<<<<< HEAD
*References*: 

* https://www.joesandbox.com/analysis/476188/1/html

*Tags*: 

* Domain: Endpoint
* OS: Windows
* Use Case: Threat Detection
* Tactic: Defense Evasion
* Tactic: Execution
* Data Source: Elastic Endgame
* Data Source: Elastic Defend
* Data Source: System
* Data Source: Microsoft Defender for Endpoint
* Data Source: Sysmon
* Data Source: SentinelOne
* Data Source: Crowdstrike

*Version*: 313

*Rule authors*: 

* Elastic

*Rule license*: Elastic License v2

=======
*References*:

* https://www.joesandbox.com/analysis/476188/1/html

*Tags*:

* Elastic
* Host
* Windows
* Threat Detection
* Defense Evasion
* Elastic Endgame

*Version*: 102 (<<control-panel-process-with-unusual-arguments-history, version history>>)

*Added ({stack} release)*: 7.16.0

*Last modified ({stack} release)*: 8.6.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Investigation guide


[source,markdown]
----------------------------------

----------------------------------

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

==== Rule query


<<<<<<< HEAD
[source, js]
----------------------------------
process where host.os.type == "windows" and event.type == "start" and
  process.name : "control.exe" and 
  process.command_line : (
    "*.jpg*", "*.png*",
    "*.gif*", "*.bmp*",
    "*.jpeg*", "*.TIFF*",
    "*.inf*", "*.cpl:*/*",
    "*../../..*",
    "*/AppData/Local/*",
    "*:\\Users\\Public\\*",
    "*\\AppData\\Local\\*"
)

----------------------------------
=======
[source,js]
----------------------------------
process where event.type == "start" and process.executable :
("?:\\Windows\\SysWOW64\\control.exe",
"?:\\Windows\\System32\\control.exe") and process.command_line :
("*.jpg*", "*.png*", "*.gif*",
"*.bmp*", "*.jpeg*", "*.TIFF*",
"*.inf*", "*.cpl:*/*", "*../../..*",
"*/AppData/Local/*", "*:\\Users\\Public\\*",
"*\\AppData\\Local\\*")
----------------------------------

==== Threat mapping
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Defense Evasion
** ID: TA0005
** Reference URL: https://attack.mitre.org/tactics/TA0005/
* Technique:
** Name: System Binary Proxy Execution
** ID: T1218
** Reference URL: https://attack.mitre.org/techniques/T1218/
<<<<<<< HEAD
* Sub-technique:
** Name: Control Panel
** ID: T1218.002
** Reference URL: https://attack.mitre.org/techniques/T1218/002/
=======

[[control-panel-process-with-unusual-arguments-history]]
==== Rule version history

Version 102 (8.6.0 release)::
* Formatting only

Version 101 (8.5.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
process where event.type in ("start", "process_started") and
process.executable : ("?:\\Windows\\SysWOW64\\control.exe",
"?:\\Windows\\System32\\control.exe") and process.command_line :
("*.jpg*", "*.png*", "*.gif*",
"*.bmp*", "*.jpeg*", "*.TIFF*",
"*.inf*", "*.cpl:*/*", "*../../..*",
"*/AppData/Local/*", "*:\\Users\\Public\\*",
"*\\AppData\\Local\\*")
----------------------------------

Version 5 (8.4.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
process where event.type in ("start", "process_started") and
process.executable : ("?:\\Windows\\SysWOW64\\control.exe",
"?:\\Windows\\System32\\control.exe") and process.command_line :
("*.jpg*", "*.png*", "*.gif*",
"*.bmp*", "*.jpeg*", "*.TIFF*",
"*.inf*", "*.dat*", "*.cpl:*/*",
"*../../..*", "*/AppData/Local/*",
"*:\\Users\\Public\\*", "*\\AppData\\Local\\*")
----------------------------------

Version 3 (8.2.0 release)::
* Formatting only

Version 2 (8.0.0 release)::
* Formatting only

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))
