[[creation-or-modification-of-a-new-gpo-scheduled-task-or-service]]
=== Creation or Modification of a new GPO Scheduled Task or Service

Detects the creation or modification of a new Group Policy based scheduled task or service. These methods are used for legitimate system administration, but can also be abused by an attacker with domain admin permissions to execute a malicious payload remotely on all or a subset of the domain joined machines.

*Rule type*: eql

*Rule indices*:

* winlogbeat-*
* logs-endpoint.events.*
* logs-windows.*

*Severity*: low

*Risk score*: 21

*Runs every*: 5 minutes

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*Tags*:

* Elastic
* Host
* Windows
* Threat Detection
* Persistence

*Version*: 101 (<<creation-or-modification-of-a-new-gpo-scheduled-task-or-service-history, version history>>)

*Added ({stack} release)*: 7.10.0

*Last modified ({stack} release)*: 8.5.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Investigation guide


[source,markdown]
----------------------------------

----------------------------------


==== Rule query


[source,js]
----------------------------------
file where event.type != "deletion" and file.path : ("?:\\Windows\\S
YSVOL\\domain\\Policies\\*\\MACHINE\\Preferences\\ScheduledTasks\\Sche
duledTasks.xml", "?:\\Windows\\SYSVOL\\domain\\Policies
\\*\\MACHINE\\Preferences\\Services\\Services.xml") and not
process.name : "dfsrs.exe"
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Persistence
** ID: TA0003
** Reference URL: https://attack.mitre.org/tactics/TA0003/
* Technique:
** Name: Scheduled Task/Job
** ID: T1053
** Reference URL: https://attack.mitre.org/techniques/T1053/

[[creation-or-modification-of-a-new-gpo-scheduled-task-or-service-history]]
==== Rule version history

Version 101 (8.5.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
file where event.type != "deletion" and file.path : ("?:\\Windows\\S
YSVOL\\domain\\Policies\\*\\MACHINE\\Preferences\\ScheduledTasks\\Sche
duledTasks.xml", "?:\\Windows\\SYSVOL\\domain\\Policies
\\*\\MACHINE\\Preferences\\Preferences\\Services\\Services.xml") and
not process.name : "dfsrs.exe"
----------------------------------

Version 9 (8.4.0 release)::
* Formatting only

Version 7 (8.2.0 release)::
* Formatting only

Version 6 (7.16.0 release)::
* Formatting only

Version 5 (7.13.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.category:file and not event.type:deletion and file.path:(C\:\\Wi
ndows\\SYSVOL\\domain\\Policies\\*\\MACHINE\\Preferences\\ScheduledTas
ks\\ScheduledTasks.xml or C\:\\Windows\\SYSVOL\\domain\\Policies\\*\\M
ACHINE\\Preferences\\Preferences\\Services\\Services.xml) and not
process.name:dfsrs.exe
----------------------------------

Version 4 (7.12.0 release)::
* Formatting only

Version 3 (7.11.2 release)::
* Formatting only

Version 2 (7.11.0 release)::
* Formatting only

