[[credential-acquisition-via-registry-hive-dumping]]
=== Credential Acquisition via Registry Hive Dumping

Identifies attempts to export a registry hive which may contain credentials using the Windows reg.exe tool.

*Rule type*: eql

*Rule indices*:

* winlogbeat-*
* logs-endpoint.events.*
* logs-windows.*

*Severity*: high

*Risk score*: 73

*Runs every*: 5 minutes

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*:

* https://medium.com/threatpunter/detecting-attempts-to-steal-passwords-from-the-registry-7512674487f8

*Tags*:

* Elastic
* Host
* Windows
* Threat Detection
* Credential Access

*Version*: 4 (<<credential-acquisition-via-registry-hive-dumping-history, version history>>)

*Added ({stack} release)*: 7.11.0

*Last modified ({stack} release)*: 7.16.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Rule query


[source,js]
----------------------------------
process where event.type in ("start", "process_started") and
process.pe.original_file_name == "reg.exe" and process.args :
("save", "export") and process.args : ("hklm\\sam", "hklm\\security")
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Credential Access
** ID: TA0006
** Reference URL: https://attack.mitre.org/tactics/TA0006/
* Technique:
** Name: OS Credential Dumping
** ID: T1003
** Reference URL: https://attack.mitre.org/techniques/T1003/

[[credential-acquisition-via-registry-hive-dumping-history]]
==== Rule version history

Version 4 (7.16.0 release)::
* Formatting only

Version 3 (7.12.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
process where event.type in ("start", "process_started") and
process.pe.original_file_name == "reg.exe" and process.args :
("save", "export") and process.args : ("hklm\\sam", "hklm\\security")
and not process.parent.executable : "C:\\Program
Files*\\Rapid7\\Insight
Agent\\components\\insight_agent\\*\\ir_agent.exe"
----------------------------------

Version 2 (7.11.2 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
process where event.type in ("start", "process_started") and
process.pe.original_file_name == "reg.exe" and process.args :
("save", "export") and process.args : ("hklm\\sam", "hklm\\security")
and not process.parent.executable : "C:\\Program
Files*\\Rapid7\\Insight
Agent\\components\\insight_agent\\*\\ir_agent.exe"
----------------------------------

