[[enumeration-command-spawned-via-wmiprvse]]
=== Enumeration Command Spawned via WMIPrvSE

Identifies native Windows host and network enumeration commands spawned by the Windows Management Instrumentation Provider Service (WMIPrvSE).

*Rule type*: eql

<<<<<<< HEAD
*Rule indices*: 

* winlogbeat-*
* logs-endpoint.events.process-*
* logs-windows.forwarded*
* logs-windows.sysmon_operational-*
* endgame-*
* logs-system.security*
* logs-m365_defender.event-*
* logs-sentinel_one_cloud_funnel.*
* logs-crowdstrike.fdr*
=======
*Rule indices*:

* winlogbeat-*
* logs-endpoint.events.*
* logs-windows.*
* endgame-*
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Severity*: low

*Risk score*: 21

<<<<<<< HEAD
*Runs every*: 5m
=======
*Runs every*: 5 minutes
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

<<<<<<< HEAD
*References*: None

*Tags*: 

* Domain: Endpoint
* OS: Windows
* Use Case: Threat Detection
* Tactic: Execution
* Data Source: Elastic Endgame
* Data Source: Elastic Defend
* Data Source: System
* Data Source: Microsoft Defender for Endpoint
* Data Source: Sysmon
* Data Source: SentinelOne
* Data Source: Crowdstrike

*Version*: 314

*Rule authors*: 

* Elastic

*Rule license*: Elastic License v2

=======
*Tags*:

* Elastic
* Host
* Windows
* Threat Detection
* Execution
* Elastic Endgame

*Version*: 102 (<<enumeration-command-spawned-via-wmiprvse-history, version history>>)

*Added ({stack} release)*: 7.12.0

*Last modified ({stack} release)*: 8.6.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Investigation guide


[source,markdown]
----------------------------------

----------------------------------

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

==== Rule query


<<<<<<< HEAD
[source, js]
----------------------------------
process where host.os.type == "windows" and event.type == "start" and process.command_line != null and 
  process.name:
  (
    "arp.exe", "dsquery.exe", "dsget.exe", "gpresult.exe", "hostname.exe", "ipconfig.exe", "nbtstat.exe",
    "net.exe", "net1.exe", "netsh.exe", "netstat.exe", "nltest.exe", "ping.exe", "qprocess.exe", "quser.exe",
    "qwinsta.exe", "reg.exe", "sc.exe", "systeminfo.exe", "tasklist.exe", "tracert.exe", "whoami.exe"
  ) and
  process.parent.name:"wmiprvse.exe" and 
  not (
    process.name : "sc.exe" and process.args : "RemoteRegistry" and process.args : "start=" and 
    process.args : ("demand", "disabled")
  ) and
  not process.args : "tenable_mw_scan"

----------------------------------
=======
[source,js]
----------------------------------
process where event.type == "start" and process.name: (
"arp.exe", "dsquery.exe", "dsget.exe", "gpresult.exe",
"hostname.exe", "ipconfig.exe", "nbtstat.exe", "net.exe",
"net1.exe", "netsh.exe", "netstat.exe", "nltest.exe",
"ping.exe", "qprocess.exe", "quser.exe", "qwinsta.exe",
"reg.exe", "sc.exe", "systeminfo.exe", "tasklist.exe",
"tracert.exe", "whoami.exe" ) and
process.parent.name:"wmiprvse.exe"
----------------------------------

==== Threat mapping
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Execution
** ID: TA0002
** Reference URL: https://attack.mitre.org/tactics/TA0002/
* Technique:
** Name: Windows Management Instrumentation
** ID: T1047
** Reference URL: https://attack.mitre.org/techniques/T1047/
<<<<<<< HEAD
=======


>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))
* Tactic:
** Name: Discovery
** ID: TA0007
** Reference URL: https://attack.mitre.org/tactics/TA0007/
* Technique:
<<<<<<< HEAD
** Name: System Network Configuration Discovery
** ID: T1016
** Reference URL: https://attack.mitre.org/techniques/T1016/
* Sub-technique:
** Name: Internet Connection Discovery
** ID: T1016.001
** Reference URL: https://attack.mitre.org/techniques/T1016/001/
* Technique:
** Name: Remote System Discovery
** ID: T1018
** Reference URL: https://attack.mitre.org/techniques/T1018/
* Technique:
** Name: Process Discovery
** ID: T1057
** Reference URL: https://attack.mitre.org/techniques/T1057/
* Technique:
** Name: Account Discovery
** ID: T1087
** Reference URL: https://attack.mitre.org/techniques/T1087/
* Technique:
** Name: Software Discovery
** ID: T1518
** Reference URL: https://attack.mitre.org/techniques/T1518/
=======
** Name: Remote System Discovery
** ID: T1018
** Reference URL: https://attack.mitre.org/techniques/T1018/

[[enumeration-command-spawned-via-wmiprvse-history]]
==== Rule version history

Version 102 (8.6.0 release)::
* Formatting only

Version 101 (8.5.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
process where event.type in ("start", "process_started") and
process.name: ( "arp.exe", "dsquery.exe", "dsget.exe",
"gpresult.exe", "hostname.exe", "ipconfig.exe",
"nbtstat.exe", "net.exe", "net1.exe", "netsh.exe",
"netstat.exe", "nltest.exe", "ping.exe", "qprocess.exe",
"quser.exe", "qwinsta.exe", "reg.exe", "sc.exe",
"systeminfo.exe", "tasklist.exe", "tracert.exe",
"whoami.exe" ) and process.parent.name:"wmiprvse.exe"
----------------------------------

Version 5 (8.4.0 release)::
* Formatting only

Version 3 (8.2.0 release)::
* Formatting only

Version 2 (7.16.0 release)::
* Formatting only

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))
