[[enumeration-of-administrator-accounts]]
=== Enumeration of Administrator Accounts

Identifies instances of lower privilege accounts enumerating Administrator accounts or groups using built-in Windows tools.

*Rule type*: eql

*Rule indices*:

* logs-endpoint.events.*
* winlogbeat-*

*Severity*: low

*Risk score*: 21

*Runs every*: 5 minutes

*Searches indices from*: now-6m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*Tags*:

* Elastic
* Host
* Windows
* Threat Detection
* Discovery

*Version*: 2 (<<enumeration-of-administrator-accounts-history, version history>>)

*Added ({stack} release)*: 7.11.0

*Last modified ({stack} release)*: 7.11.2

*Rule authors*: Elastic

*Rule license*: Elastic License

==== Rule query


[source,js]
----------------------------------
process where event.type in ("start", "process_started") and
(((process.name : "net.exe" or process.pe.original_file_name ==
"net.exe") or ((process.name : "net1.exe" or
process.pe.original_file_name == "net1.exe") and not
process.parent.name : "net.exe")) and process.args : ("group",
"user", "localgroup") and process.args : ("admin", "Domain Admins",
"Remote Desktop Users", "Enterprise Admins", "Organization
Management") and not process.args : "/add") or
((process.name : "wmic.exe" or process.pe.original_file_name ==
"wmic.exe") and process.args : ("group", "useraccount"))
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Discovery
** ID: TA0007
** Reference URL: https://attack.mitre.org/tactics/TA0007/
* Technique:
** Name: Permission Groups Discovery
** ID: T1069
** Reference URL: https://attack.mitre.org/techniques/T1069/

[[enumeration-of-administrator-accounts-history]]
==== Rule version history

Version 2 (7.11.2 release)::
* Formatting only

