[[enumeration-of-administrator-accounts]]
=== Enumeration of Administrator Accounts

Identifies instances of lower privilege accounts enumerating Administrator accounts or groups using built-in Windows tools.

*Rule type*: eql

<<<<<<< HEAD
*Rule indices*: 

* logs-endpoint.events.process-*
* winlogbeat-*
* logs-windows.forwarded*
* endgame-*
* logs-system.security*
* logs-m365_defender.event-*
* logs-crowdstrike.fdr*
=======
*Rule indices*:

* logs-endpoint.events.*
* winlogbeat-*
* logs-windows.*
* endgame-*
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Severity*: low

*Risk score*: 21

<<<<<<< HEAD
*Runs every*: 5m
=======
*Runs every*: 5 minutes
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

<<<<<<< HEAD
*References*: None

*Tags*: 

* Domain: Endpoint
* OS: Windows
* Use Case: Threat Detection
* Tactic: Discovery
* Resources: Investigation Guide
* Data Source: Elastic Endgame
* Data Source: Elastic Defend
* Data Source: System
* Data Source: Microsoft Defender for Endpoint
* Data Source: Crowdstrike

*Version*: 215

*Rule authors*: 

* Elastic

*Rule license*: Elastic License v2


==== Investigation guide



*Triage and analysis*



*Investigating Enumeration of Administrator Accounts*


After successfully compromising an environment, attackers may try to gain situational awareness to plan their next steps. This can happen by running commands to enumerate network resources, users, connections, files, and installed security software.

This rule looks for the execution of the `net` and `wmic` utilities to enumerate administrator-related users or groups in the domain and local machine scope. Attackers can use this information to plan their next steps of the attack, such as mapping targets for credential compromise and other post-exploitation activities.


*Possible investigation steps*


- Investigate the process execution chain (parent process tree) for unknown processes. Examine their executable files for prevalence, whether they are located in expected locations, and if they are signed with valid digital signatures.
- Identify the user account that performed the action and whether it should perform this kind of action.
- Investigate other alerts associated with the user/host during the past 48 hours.
- Investigate any abnormal account behavior, such as command executions, file creations or modifications, and network connections.


*False positive analysis*


- Discovery activities are not inherently malicious if they occur in isolation. As long as the analyst did not identify suspicious activity related to the user or host, such alerts can be dismissed.


*Related rules*


- AdFind Command Activity - eda499b8-a073-4e35-9733-22ec71f57f3a


*Response and remediation*


- Initiate the incident response process based on the outcome of the triage.
- Isolate the involved hosts to prevent further post-compromise behavior.
- Investigate credential exposure on systems compromised or used by the attacker to ensure all compromised accounts are identified. Reset passwords for these accounts and other potentially compromised credentials, such as email, business systems, and web services.
- Run a full antimalware scan. This may reveal additional artifacts left in the system, persistence mechanisms, and malware components.
- Determine the initial vector abused by the attacker and take action to prevent reinfection through the same vector.
- Using the incident response data, update logging and audit policies to improve the mean time to detect (MTTD) and the mean time to respond (MTTR).
=======
*Tags*:

* Elastic
* Host
* Windows
* Threat Detection
* Discovery
* Investigation Guide
* Elastic Endgame

*Version*: 102 (<<enumeration-of-administrator-accounts-history, version history>>)

*Added ({stack} release)*: 7.11.0

*Last modified ({stack} release)*: 8.6.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Investigation guide


[source,markdown]
----------------------------------
## Triage and analysis

### Investigating Enumeration of Administrator Accounts

After successfully compromising an environment, attackers may try to gain situational awareness to plan their next steps.
This can happen by running commands to enumerate network resources, users, connections, files, and installed security
software.

This rule looks for the execution of the `net` and `wmic` utilities to enumerate administrator-related users or groups
in the domain and local machine scope. Attackers can use this information to plan their next steps of the attack, such
as mapping targets for credential compromise and other post-exploitation activities.

#### Possible investigation steps

- Investigate the process execution chain (parent process tree) for unknown processes. Examine their executable files
for prevalence, whether they are located in expected locations, and if they are signed with valid digital signatures.
- Identify the user account that performed the action and whether it should perform this kind of action.
- Investigate other alerts associated with the user/host during the past 48 hours.
- Investigate any abnormal account behavior, such as command executions, file creations or modifications, and network
connections.

### False positive analysis

- Discovery activities are not inherently malicious if they occur in isolation. As long as the analyst did not identify
suspicious activity related to the user or host, such alerts can be dismissed.

### Related rules

- AdFind Command Activity - eda499b8-a073-4e35-9733-22ec71f57f3a

### Response and remediation

- Initiate the incident response process based on the outcome of the triage.
- Isolate the involved hosts to prevent further post-compromise behavior.
- Investigate credential exposure on systems compromised or used by the attacker to ensure all compromised accounts are
identified. Reset passwords for these accounts and other potentially compromised credentials, such as email, business
systems, and web services.
- Run a full antimalware scan. This may reveal additional artifacts left in the system, persistence mechanisms, and
malware components.
- Determine the initial vector abused by the attacker and take action to prevent reinfection through the same vector.
- Using the incident response data, update logging and audit policies to improve the mean time to detect (MTTD) and the
mean time to respond (MTTR).
----------------------------------
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))


==== Rule query


<<<<<<< HEAD
[source, js]
----------------------------------
process where host.os.type == "windows" and event.type == "start" and
(
  (
    (
      (process.name : "net.exe" or ?process.pe.original_file_name == "net.exe") or
      ((process.name : "net1.exe" or ?process.pe.original_file_name == "net1.exe") and not process.parent.name : "net.exe")
    ) and
    process.args : ("group", "user", "localgroup") and
    process.args : ("*admin*", "Domain Admins", "Remote Desktop Users", "Enterprise Admins", "Organization Management")
    and not process.args : ("/add", "/delete")
  ) or
  (
    (process.name : "wmic.exe" or ?process.pe.original_file_name == "wmic.exe") and
    process.args : ("group", "useraccount")
  )
) and not user.id : ("S-1-5-18", "S-1-5-19", "S-1-5-20")

----------------------------------
=======
[source,js]
----------------------------------
process where event.type == "start" and (((process.name : "net.exe"
or process.pe.original_file_name == "net.exe") or ((process.name :
"net1.exe" or process.pe.original_file_name == "net1.exe") and
not process.parent.name : "net.exe")) and process.args : ("group",
"user", "localgroup") and process.args : ("admin", "Domain Admins",
"Remote Desktop Users", "Enterprise Admins", "Organization
Management") and not process.args : "/add") or
((process.name : "wmic.exe" or process.pe.original_file_name ==
"wmic.exe") and process.args : ("group", "useraccount"))
----------------------------------

==== Threat mapping
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Discovery
** ID: TA0007
** Reference URL: https://attack.mitre.org/tactics/TA0007/
* Technique:
** Name: Permission Groups Discovery
** ID: T1069
** Reference URL: https://attack.mitre.org/techniques/T1069/
<<<<<<< HEAD
* Sub-technique:
** Name: Local Groups
** ID: T1069.001
** Reference URL: https://attack.mitre.org/techniques/T1069/001/
* Sub-technique:
** Name: Domain Groups
** ID: T1069.002
** Reference URL: https://attack.mitre.org/techniques/T1069/002/
* Technique:
** Name: Account Discovery
** ID: T1087
** Reference URL: https://attack.mitre.org/techniques/T1087/
* Sub-technique:
** Name: Local Account
** ID: T1087.001
** Reference URL: https://attack.mitre.org/techniques/T1087/001/
* Sub-technique:
** Name: Domain Account
** ID: T1087.002
** Reference URL: https://attack.mitre.org/techniques/T1087/002/
=======

[[enumeration-of-administrator-accounts-history]]
==== Rule version history

Version 102 (8.6.0 release)::
* Formatting only

Version 101 (8.5.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
process where event.type in ("start", "process_started") and
(((process.name : "net.exe" or process.pe.original_file_name ==
"net.exe") or ((process.name : "net1.exe" or
process.pe.original_file_name == "net1.exe") and not
process.parent.name : "net.exe")) and process.args : ("group",
"user", "localgroup") and process.args : ("admin", "Domain Admins",
"Remote Desktop Users", "Enterprise Admins", "Organization
Management") and not process.args : "/add") or
((process.name : "wmic.exe" or process.pe.original_file_name ==
"wmic.exe") and process.args : ("group", "useraccount"))
----------------------------------

Version 8 (8.4.0 release)::
* Formatting only

Version 6 (8.3.0 release)::
* Formatting only

Version 5 (8.2.0 release)::
* Formatting only

Version 4 (7.16.0 release)::
* Formatting only

Version 3 (7.12.0 release)::
* Formatting only

Version 2 (7.11.2 release)::
* Formatting only

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))
