[[execution-of-file-written-or-modified-by-microsoft-office]]
=== Execution of File Written or Modified by Microsoft Office

Identifies an executable created by a Microsoft Office application and subsequently executed. These processes are often launched via scripts inside documents or during exploitation of MS Office applications.

*Rule type*: eql

*Rule indices*:

* logs-endpoint.events.*
* winlogbeat-*

*Severity*: high

*Risk score*: 21

*Runs every*: 5 minutes

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*Tags*:

* Elastic
* Host
* Windows
* Threat Detection
* Execution

*Version*: 1

*Added ({stack} release)*: 7.10.0

*Rule authors*: Elastic

*Rule license*: Elastic License

==== Rule query


[source,js]
----------------------------------
sequence with maxspan=2h [file where event.type != "deletion" and
file.extension : "exe" and (process.name : "WINWORD.EXE" or
process.name : "EXCEL.EXE" or process.name : "OUTLOOK.EXE" or
process.name : "POWERPNT.EXE" or process.name : "eqnedt32.exe"
or process.name : "fltldr.exe" or process.name :
"MSPUB.EXE" or process.name : "MSACCESS.EXE") ] by host.id,
file.path [process where event.type in ("start", "process_started")]
by host.id, process.executable
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Execution
** ID: TA0002
** Reference URL: https://attack.mitre.org/tactics/TA0002/
* Technique:
** Name: Scripting
** ID: T1064
** Reference URL: https://attack.mitre.org/techniques/T1064/
