[[gcp-virtual-private-cloud-network-deletion]]
=== GCP Virtual Private Cloud Network Deletion

Identifies when a Virtual Private Cloud (VPC) network is deleted in Google Cloud Platform (GCP). A VPC network is a virtual version of a physical network within a GCP project. Each VPC network has its own subnets, routes, and firewall, as well as other elements. An adversary may delete a VPC network in order to disrupt their target's network and business operations.

*Rule type*: query

*Rule indices*:

* filebeat-*
* logs-gcp*

*Severity*: medium

*Risk score*: 47

*Runs every*: 5 minutes

*Searches indices from*: now-6m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*:

* https://cloud.google.com/vpc/docs/vpc

*Tags*:

* Elastic
* Cloud
* GCP
* Continuous Monitoring
* SecOps
* Configuration Audit

*Version*: 5 (<<gcp-virtual-private-cloud-network-deletion-history, version history>>)

*Added ({stack} release)*: 7.10.0

*Last modified ({stack} release)*: 7.13.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Potential false positives

Virtual Private Cloud networks may be deleted by system administrators. Verify that the configuration change was expected. Exceptions can be added to this rule to filter expected behavior.

==== Investigation guide


[source,markdown]
----------------------------------
## Config

The GCP Fleet integration, Filebeat module, or similarly structured data is required to be compatible with this rule.
----------------------------------


==== Rule query


[source,js]
----------------------------------
event.dataset:(googlecloud.audit or gcp.audit) and
event.action:v*.compute.networks.delete and event.outcome:success
----------------------------------


[[gcp-virtual-private-cloud-network-deletion-history]]
==== Rule version history

Version 5 (7.13.0 release)::
* Formatting only

Version 4 (7.12.0 release)::
* Formatting only

Version 3 (7.11.2 release)::
* Formatting only

Version 2 (7.11.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.dataset:googlecloud.audit and
event.action:v*.compute.networks.delete and event.outcome:success
----------------------------------

