[[gcp-storage-bucket-configuration-modification]]
=== GCP Storage Bucket Configuration Modification

Identifies when the configuration is modified for a storage bucket in Google Cloud Platform (GCP). An adversary may modify the configuration of a storage bucket in order to weaken the security controls of their target's environment.

*Rule type*: query

*Rule indices*:

* filebeat-*

*Severity*: medium

*Risk score*: 47

*Runs every*: 5 minutes

*Searches indices from*: now-6m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*:

* https://cloud.google.com/storage/docs/key-terms#buckets

*Tags*:

* Elastic
* GCP
* Continuous Monitoring
* SecOps
* Identity and Access

*Version*: 1

*Added ({stack} release)*: 7.10.0

*Rule authors*: Elastic

*Rule license*: Elastic License

==== Potential false positives

Storage bucket configuration may be modified by system administrators. Verify that the configuration change was expected. Exceptions can be added to this rule to filter expected behavior.

==== Investigation guide

The GCP Filebeat module must be enabled to use this rule.

==== Rule query


[source,js]
----------------------------------
event.dataset:googlecloud.audit and
event.action:storage.buckets.update and event.outcome:success
----------------------------------

