[[gcp-pub-sub-topic-creation]]
=== GCP Pub/Sub Topic Creation

Identifies the creation of a topic in Google Cloud Platform (GCP). In GCP, the publisher-subscriber relationship (Pub/Sub) is an asynchronous messaging service that decouples event-producing and event-processing services. A topic is used to forward messages from publishers to subscribers.

*Rule type*: query

*Rule indices*:

* filebeat-*
* logs-gcp*

*Severity*: low

*Risk score*: 21

*Runs every*: 5 minutes

*Searches indices from*: now-6m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*:

* https://cloud.google.com/pubsub/docs/admin

*Tags*:

* Elastic
* Cloud
* GCP
* Continuous Monitoring
* SecOps
* Log Auditing

*Version*: 8 (<<gcp-pub-sub-topic-creation-history, version history>>)

*Added ({stack} release)*: 7.10.0

*Last modified ({stack} release)*: 8.4.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Potential false positives

Topic creations may be done by a system or network administrator. Verify whether the user email, resource name, and/or hostname should be making changes in your environment. Topic creations by unfamiliar users or hosts should be investigated. If known behavior is causing false positives, it can be exempted from the rule.

==== Investigation guide


[source,markdown]
----------------------------------

----------------------------------


==== Rule query


[source,js]
----------------------------------
event.dataset:gcp.audit and
event.action:google.pubsub.v*.Publisher.CreateTopic and
event.outcome:success
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Collection
** ID: TA0009
** Reference URL: https://attack.mitre.org/tactics/TA0009/
* Technique:
** Name: Data from Cloud Storage Object
** ID: T1530
** Reference URL: https://attack.mitre.org/techniques/T1530/

[[gcp-pub-sub-topic-creation-history]]
==== Rule version history

Version 8 (8.4.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.dataset:(googlecloud.audit or gcp.audit) and
event.action:google.pubsub.v*.Publisher.CreateTopic and
event.outcome:success
----------------------------------

Version 6 (8.1.0 release)::
* Formatting only

Version 5 (7.13.0 release)::
* Formatting only

Version 4 (7.12.0 release)::
* Formatting only

Version 3 (7.11.2 release)::
* Formatting only

Version 2 (7.11.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.dataset:googlecloud.audit and
event.action:google.pubsub.v*.Publisher.CreateTopic and
event.outcome:success
----------------------------------

