[[halfbaked-command-and-control-beacon]]
=== Halfbaked Command and Control Beacon

Halfbaked is a malware family used to establish persistence in a contested network. This rule detects a network activity algorithm leveraged by Halfbaked implant beacons for command and control.

*Rule type*: query

*Rule indices*:

* auditbeat-*
* filebeat-*
* packetbeat-*
* logs-endpoint.events.*

*Severity*: high

*Risk score*: 73

*Runs every*: 5 minutes

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*:

* https://www.fireeye.com/blog/threat-research/2017/04/fin7-phishing-lnk.html
* https://attack.mitre.org/software/S0151/

*Tags*:

* Elastic
* Network
* Threat Detection
* Command and Control
* Host

*Version*: 100 (<<halfbaked-command-and-control-beacon-history, version history>>)

*Added ({stack} release)*: 7.10.0

*Last modified ({stack} release)*: 8.5.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Potential false positives

This rule should be tailored to exclude systems, either as sources or destinations, in which this behavior is expected.

==== Investigation guide


[source,markdown]
----------------------------------
## Threat intel

This activity has been observed in FIN7 campaigns.
----------------------------------


==== Rule query


[source,js]
----------------------------------
event.category:(network OR network_traffic) AND network.protocol:http
AND network.transport:tcp AND
url.full:/http:\/\/[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}\/cd/
AND destination.port:(53 OR 80 OR 8080 OR 443)
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Command and Control
** ID: TA0011
** Reference URL: https://attack.mitre.org/tactics/TA0011/
* Technique:
** Name: Application Layer Protocol
** ID: T1071
** Reference URL: https://attack.mitre.org/techniques/T1071/

[[halfbaked-command-and-control-beacon-history]]
==== Rule version history

Version 100 (8.5.0 release)::
* Formatting only

Version 6 (7.14.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.category:(network OR network_traffic) AND network.protocol:http
AND network.transport:tcp AND
url.full:/http:\/\/[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}\/cd/
AND destination.port:(53 OR 80 OR 8080 OR 443)
----------------------------------

Version 5 (7.13.0 release)::
* Formatting only

Version 4 (7.12.0 release)::
* Formatting only

Version 3 (7.11.2 release)::
* Formatting only

Version 2 (7.11.0 release)::
* Formatting only

