[[ipsec-nat-traversal-port-activity]]
=== IPSEC NAT Traversal Port Activity

This rule detects events that could be describing IPSEC NAT Traversal traffic. IPSEC is a VPN technology that allows one system to talk to another using encrypted tunnels. NAT Traversal enables these tunnels to communicate over the Internet where one of the sides is behind a NAT router gateway. This may be common on your network, but this technique is also used by threat actors to avoid detection.

*Rule type*: query

<<<<<<< HEAD
*Rule indices*: 

* packetbeat-*
* auditbeat-*
* filebeat-*
* logs-network_traffic.*
* logs-panw.*
=======
*Rule indices*:

* auditbeat-*
* filebeat-*
* packetbeat-*
* logs-endpoint.events.*
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Severity*: low

*Risk score*: 21

<<<<<<< HEAD
*Runs every*: 5m
=======
*Runs every*: 5 minutes
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

<<<<<<< HEAD
*References*: None

*Tags*: 

* Tactic: Command and Control
* Domain: Endpoint
* Use Case: Threat Detection
* Data Source: PAN-OS

*Version*: 105

*Rule authors*: 

* Elastic

*Rule license*: Elastic License v2

=======
*Tags*:

* Elastic
* Host
* Network
* Threat Detection
* Command and Control
* Host

*Version*: 100 (<<ipsec-nat-traversal-port-activity-history, version history>>)

*Added ({stack} release)*: 7.6.0

*Last modified ({stack} release)*: 8.5.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Potential false positives

Some networks may utilize these protocols but usage that is unfamiliar to local network administrators can be unexpected and suspicious. Because this port is in the ephemeral range, this rule may false under certain conditions, such as when an application server with a public IP address replies to a client which has used a UDP port in the range by coincidence. This is uncommon but such servers can be excluded.
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

==== Rule query


<<<<<<< HEAD
[source, js]
----------------------------------
(event.dataset: network_traffic.flow or (event.category: (network or network_traffic))) and network.transport:udp and destination.port:4500

----------------------------------
=======
[source,js]
----------------------------------
event.category:(network or network_traffic) and network.transport:udp
and destination.port:4500
----------------------------------

==== Threat mapping
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Command and Control
** ID: TA0011
** Reference URL: https://attack.mitre.org/tactics/TA0011/
<<<<<<< HEAD
=======

[[ipsec-nat-traversal-port-activity-history]]
==== Rule version history

Version 100 (8.5.0 release)::
* Formatting only

Version 9 (8.4.0 release)::
* Formatting only

Version 8 (7.14.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.category:(network or network_traffic) and network.transport:udp
and destination.port:4500
----------------------------------

Version 7 (7.12.0 release)::
* Formatting only

Version 6 (7.11.2 release)::
* Formatting only

Version 5 (7.11.0 release)::
* Formatting only

Version 4 (7.10.0 release)::
* Formatting only

Version 3 (7.9.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
network.transport:udp and destination.port:4500
----------------------------------

Version 2 (7.6.1 release)::
* Removed auditbeat-\*, packetbeat-*, and winlogbeat-* from the rule indices.

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))
