[[lsass-memory-dump-creation]]
=== LSASS Memory Dump Creation

Identifies the creation of a Local Security Authority Subsystem Service (lsass.exe) default memory dump. This may indicate a credential access attempt via trusted system utilities such as Task Manager (taskmgr.exe) and SQL Dumper (sqldumper.exe) or known pentesting tools such as Dumpert and AndrewSpecial.

*Rule type*: eql

*Rule indices*:

* winlogbeat-*
* logs-endpoint.events.*
* logs-windows.*
* endgame-*

*Severity*: high

*Risk score*: 73

*Runs every*: 5 minutes

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*:

* https://github.com/outflanknl/Dumpert
* https://github.com/hoangprod/AndrewSpecial

*Tags*:

* Elastic
* Host
* Windows
* Threat Detection
* Credential Access
* Elastic Endgame

*Version*: 101 (<<lsass-memory-dump-creation-history, version history>>)

*Added ({stack} release)*: 7.11.0

*Last modified ({stack} release)*: 8.6.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Investigation guide


[source,markdown]
----------------------------------

----------------------------------


==== Rule query


[source,js]
----------------------------------
file where file.name : ("lsass*.dmp", "dumpert.dmp", "Andrew.dmp",
"SQLDmpr*.mdmp", "Coredump.dmp") and not (process.executable :
("?:\\Program Files\\Microsoft SQL Server\\*\\Shared\\SqlDumper.exe",
"?:\\Windows\\System32\\dllhost.exe") and file.path :
("?:\\Program Files\\Microsoft SQL
Server\\*\\Shared\\ErrorDumps\\SQLDmpr*.mdmp",
"?:\\*\\Reporting Services\\Logfiles\\SQLDmpr*.mdmp")) and not
(process.executable : "?:\\WINDOWS\\system32\\WerFault.exe" and
file.path : "?:\\Windows\\System32\\config\\systemprofile\\AppData\\Lo
cal\\CrashDumps\\lsass.exe.*.dmp")
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Credential Access
** ID: TA0006
** Reference URL: https://attack.mitre.org/tactics/TA0006/
* Technique:
** Name: OS Credential Dumping
** ID: T1003
** Reference URL: https://attack.mitre.org/techniques/T1003/

[[lsass-memory-dump-creation-history]]
==== Rule version history

Version 101 (8.6.0 release)::
* Formatting only

Version 100 (8.5.0 release)::
* Formatting only

Version 11 (8.4.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
file where file.name : ("lsass*.dmp", "dumpert.dmp", "Andrew.dmp",
"SQLDmpr*.mdmp", "Coredump.dmp")
----------------------------------

Version 9 (8.3.0 release)::
* Formatting only

Version 7 (8.2.0 release)::
* Formatting only

Version 5 (7.16.0 release)::
* Formatting only

Version 4 (7.13.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.category:file and file.name:(lsass.DMP or lsass*.dmp or
dumpert.dmp or Andrew.dmp or SQLDmpr*.mdmp or Coredump.dmp)
----------------------------------

Version 3 (7.12.0 release)::
* Formatting only

Version 2 (7.11.2 release)::
* Formatting only

