[[macos-installer-spawns-network-event]]
=== macOS Installer Spawns Network Event

Identifies when the built in macOS Installer program generates a network event after attempting to install a .pkg file. This activity has been observed being leveraged by malware.

*Rule type*: eql

*Rule indices*:

* logs-endpoint.events.*

*Severity*: medium

*Risk score*: 47

*Runs every*: 5 minutes

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*:

* https://redcanary.com/blog/clipping-silver-sparrows-wings
* https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml

*Tags*:

* Elastic
* Host
* macOS
* Threat Detection
* Execution

*Version*: 4 (<<macos-installer-spawns-network-event-history, version history>>)

*Added ({stack} release)*: 7.12.0

*Last modified ({stack} release)*: 8.2.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Potential false positives

Custom organization-specific macOS packages that use .pkg files to run cURL could trigger this rule. If known behavior is causing false positives, it can be excluded from the rule.

==== Rule query


[source,js]
----------------------------------
sequence by process.entity_id with maxspan=1m [process where
event.type == "start" and host.os.family == "macos" and
process.parent.executable in ("/usr/sbin/installer",
"/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer")
] [network where not cidrmatch(destination.ip, "10.0.0.0/8",
"127.0.0.0/8", "169.254.0.0/16", "172.16.0.0/12", "192.0.0.0/24",
"192.0.0.0/29", "192.0.0.8/32", "192.0.0.9/32", "192.0.0.10/32",
"192.0.0.170/32", "192.0.0.171/32", "192.0.2.0/24", "192.31.196.0/24",
"192.52.193.0/24", "192.168.0.0/16", "192.88.99.0/24", "224.0.0.0/4",
"100.64.0.0/10", "192.175.48.0/24", "198.18.0.0/15",
"198.51.100.0/24", "203.0.113.0/24", "240.0.0.0/4", "::1",
"FE80::/10", "FF00::/8")]
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Execution
** ID: TA0002
** Reference URL: https://attack.mitre.org/tactics/TA0002/
* Technique:
** Name: Command and Scripting Interpreter
** ID: T1059
** Reference URL: https://attack.mitre.org/techniques/T1059/


* Tactic:
** Name: Command and Control
** ID: TA0011
** Reference URL: https://attack.mitre.org/tactics/TA0011/
* Technique:
** Name: Application Layer Protocol
** ID: T1071
** Reference URL: https://attack.mitre.org/techniques/T1071/

[[macos-installer-spawns-network-event-history]]
==== Rule version history

Version 4 (8.2.0 release)::
* Formatting only

Version 3 (7.15.0 release)::
* Formatting only

Version 2 (7.14.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
sequence by process.entity_id with maxspan=1m [ process where
event.type == "start" and host.os.family == "macos" and
process.parent.executable in ("/usr/sbin/installer",
"/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer")
] [ network where not cidrmatch(destination.ip,
"192.168.0.0/16", "10.0.0.0/8", "172.16.0.0/12",
"224.0.0.0/8", "127.0.0.0/8", "169.254.0.0/16",
"::1", "FE80::/10", "FF00::/8") ]
----------------------------------

