[[microsoft-iis-service-account-password-dumped]]
=== Microsoft IIS Service Account Password Dumped

Identifies the Internet Information Services (IIS) command-line tool, AppCmd, being used to list passwords. An attacker with IIS web server access via a web shell can decrypt and dump the IIS AppPool service account password using AppCmd.

*Rule type*: eql

*Rule indices*:

* winlogbeat-*
* logs-endpoint.events.*
* logs-windows.*

*Severity*: high

*Risk score*: 73

*Runs every*: 5 minutes

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 33

*References*:

* https://blog.netspi.com/decrypting-iis-passwords-to-break-out-of-the-dmz-part-1/

*Tags*:

* Elastic
* Host
* Windows
* Threat Detection
* Credential Access

*Version*: 7 (<<microsoft-iis-service-account-password-dumped-history, version history>>)

*Added ({stack} release)*: 7.10.0

*Last modified ({stack} release)*: 8.4.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Investigation guide


[source,markdown]
----------------------------------

----------------------------------


==== Rule query


[source,js]
----------------------------------
process where event.type in ("start", "process_started") and
(process.name : "appcmd.exe" or process.pe.original_file_name ==
"appcmd.exe") and process.args : "/list" and process.args :
"/text*password"
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Credential Access
** ID: TA0006
** Reference URL: https://attack.mitre.org/tactics/TA0006/
* Technique:
** Name: OS Credential Dumping
** ID: T1003
** Reference URL: https://attack.mitre.org/techniques/T1003/

[[microsoft-iis-service-account-password-dumped-history]]
==== Rule version history

Version 7 (8.4.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
process where event.type in ("start", "process_started") and
(process.name : "appcmd.exe" or process.pe.original_file_name ==
"appcmd.exe") and process.args : "/list" and process.args :
"/text*password"
----------------------------------

Version 5 (8.2.0 release)::
* Formatting only

Version 4 (7.12.0 release)::
* Formatting only

Version 3 (7.11.2 release)::
* Formatting only

Version 2 (7.11.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.category:process AND event.type:(start OR process_started) AND
(process.name:appcmd.exe OR process.pe.original_file_name:appcmd.exe
or winlog.event_data.OriginalFileName:appcmd.exe) AND
process.args:(/[lL][iI][sS][tT]/ AND
/\/[tT][eE][xX][tT]\:[pP][aA][sS][sS][wW][oO][rR][dD]/)
----------------------------------

