[[microsoft-365-impossible-travel-activity]]
=== Microsoft 365 Impossible travel activity

Identifies when a Microsoft Cloud App Security reported a risky sign-in attempt due to a login associated with an impossible travel.

*Rule type*: query

*Rule indices*: 

* filebeat-*
* logs-o365*

*Severity*: medium

*Risk score*: 47

*Runs every*: 5m

*Searches indices from*: now-30m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*: 

* https://docs.microsoft.com/en-us/cloud-app-security/anomaly-detection-policy
* https://docs.microsoft.com/en-us/cloud-app-security/policy-template-reference

*Tags*: 

* Domain: Cloud
* Data Source: Microsoft 365
* Use Case: Configuration Audit
* Tactic: Initial Access

*Version*: 1

*Rule authors*: 

* Austin Songer

*Rule license*: Elastic License v2


==== Investigation guide



*Important*


This rule is no longer applicable based on changes to Microsoft Defender for Office 365. Please refer to the following rules for similar detections:

- Microsoft 365 Portal Logins from Impossible Travel Locations (3896d4c0-6ad1-11ef-8c7b-f661ea17fbcc)
- Microsoft 365 Portal Login from Rare Location (32d3ad0e-6add-11ef-8c7b-f661ea17fbcc)

Reference: https://learn.microsoft.com/en-us/defender-cloud-apps/cloud-discovery-anomaly-detection-policy


==== Setup



*Setup*


The Office 365 Logs Fleet integration, Filebeat module, or similarly structured data is required to be compatible with this rule.


==== Rule query


[source, js]
----------------------------------
event.dataset:o365.audit and event.provider:SecurityComplianceCenter and event.category:web and event.action:"Impossible travel activity" and event.outcome:success

----------------------------------

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Initial Access
** ID: TA0001
** Reference URL: https://attack.mitre.org/tactics/TA0001/
* Technique:
** Name: Valid Accounts
** ID: T1078
** Reference URL: https://attack.mitre.org/techniques/T1078/
