[[mknod-process-activity]]
=== Mknod Process Activity

The Linux `mknod` program is sometimes used in the command payload of a remote
command injection (RCI) and other exploits. It is used to export a command shell
when the traditional version of `netcat` is not available to the payload.

*Rule type*: query

*Rule indices*:

* auditbeat-*
* logs-endpoint.events.*

*Severity*: low

*Risk score*: 21

*Runs every*: 5 minutes

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*:

* https://web.archive.org/web/20191218024607/https://pen-testing.sans.org/blog/2013/05/06/netcat-without-e-no-problem/

*Tags*:

* Elastic
* Host
* Linux
* Threat Detection

*Version*: 6 (<<mknod-process-activity-history, version history>>)

*Added ({stack} release)*: 7.6.0

*Last modified ({stack} release)*: 7.11.2

*Rule authors*: Elastic

*Rule license*: Elastic License

==== Potential false positives

Mknod is a Linux system program. Some normal use of this program, at varying levels of frequency, may originate from scripts, automation tools, and frameworks. Usage by web servers is more likely to be suspicious.

==== Rule query


[source,js]
----------------------------------
event.category:process and event.type:(start or process_started) and
process.name:mknod
----------------------------------


[[mknod-process-activity-history]]
==== Rule version history

Version 6 (7.11.2 release)::
* Formatting only

Version 5 (7.10.0 release)::
* Formatting only

Version 4 (7.9.1 release)::
* Formatting only

Version 3 (7.9.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
process.name:mknod and event.action:executed
----------------------------------

Version 2 (7.7.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
process.name: mknod and event.action:executed
----------------------------------

