[[modification-of-standard-authentication-module-or-configuration]]
=== Modification of Standard Authentication Module or Configuration

Adversaries may modify the standard authentication module for persistence via patching the normal authorization process or modifying the login configuration to allow unauthorized access or elevate privileges.

<<<<<<< HEAD
*Rule type*: new_terms

*Rule indices*: 
=======
*Rule type*: query

*Rule indices*:
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

* auditbeat-*
* logs-endpoint.events.*

*Severity*: medium

*Risk score*: 47

<<<<<<< HEAD
*Runs every*: 5m
=======
*Runs every*: 5 minutes
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

<<<<<<< HEAD
*References*: 
=======
*References*:
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

* https://github.com/zephrax/linux-pam-backdoor
* https://github.com/eurialo/pambd
* http://0x90909090.blogspot.com/2016/06/creating-backdoor-in-pam-in-5-line-of.html
* https://www.trendmicro.com/en_us/research/19/i/skidmap-linux-malware-uses-rootkit-capabilities-to-hide-cryptocurrency-mining-payload.html

<<<<<<< HEAD
*Tags*: 

* Domain: Endpoint
* OS: macOS
* OS: Linux
* Use Case: Threat Detection
* Tactic: Credential Access
* Tactic: Persistence
* Data Source: Elastic Defend

*Version*: 204

*Rule authors*: 

* Elastic

*Rule license*: Elastic License v2

=======
*Tags*:

* Elastic
* Host
* macOS
* Linux
* Threat Detection
* Credential Access
* Persistence

*Version*: 100 (<<modification-of-standard-authentication-module-or-configuration-history, version history>>)

*Added ({stack} release)*: 7.12.0

*Last modified ({stack} release)*: 8.5.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Potential false positives

Trusted system module updates or allowed Pluggable Authentication Module (PAM) daemon configuration changes.
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

==== Rule query


<<<<<<< HEAD
[source, js]
----------------------------------
event.category:file and event.type:change and
  (file.name:pam_*.so or file.path:(/etc/pam.d/* or /private/etc/pam.d/* or /usr/lib64/security/*)) and
  process.executable:
    (* and
      not
      (
        /usr/libexec/packagekitd or
        /usr/bin/vim or
        /usr/libexec/xpcproxy or
        /usr/bin/bsdtar or
        /usr/local/bin/brew or
        "/System/Library/PrivateFrameworks/PackageKit.framework/Versions/A/XPCServices/package_script_service.xpc/Contents/MacOS/package_script_service"
      )
    ) and
  not file.path:
         (
           /tmp/snap.rootfs_*/pam_*.so or
           /tmp/newroot/lib/*/pam_*.so or
           /private/var/folders/*/T/com.apple.fileprovider.ArchiveService/TemporaryItems/*/lib/security/pam_*.so or
           /tmp/newroot/usr/lib64/security/pam_*.so
         ) and
  not process.name:
         (
           yum or dnf or rsync or platform-python or authconfig or rpm or pdkg or apk or dnf-automatic or btrfs or
           dpkg or pam-auth-update or steam or platform-python3.6 or pam-config or microdnf or yum_install or yum-cron or
           systemd or containerd or pacman
         )

----------------------------------
=======
[source,js]
----------------------------------
event.category:file and event.type:change and (file.name:pam_*.so or
file.path:(/etc/pam.d/* or /private/etc/pam.d/*)) and
process.executable: (* and not ( /bin/yum or
"/usr/sbin/pam-auth-update" or /usr/libexec/packagekitd or
/usr/bin/dpkg or /usr/bin/vim or /usr/libexec/xpcproxy
or /usr/bin/bsdtar or /usr/local/bin/brew or
/usr/bin/rsync or /usr/bin/yum or
/var/lib/docker/*/bin/yum or /var/lib/docker/*/bin/dpkg or
./merged/var/lib/docker/*/bin/dpkg or "/System/Library/Private
Frameworks/PackageKit.framework/Versions/A/XPCServices/package_script_
service.xpc/Contents/MacOS/package_script_service" ) ) and
not file.path: ( /tmp/snap.rootfs_*/pam_*.so or
/tmp/newroot/lib/*/pam_*.so or /private/var/folders/*/T/com
.apple.fileprovider.ArchiveService/TemporaryItems/*/lib/security/pam_*
.so or /tmp/newroot/usr/lib64/security/pam_*.so )
----------------------------------

==== Threat mapping
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Persistence
** ID: TA0003
** Reference URL: https://attack.mitre.org/tactics/TA0003/
* Technique:
** Name: Create or Modify System Process
** ID: T1543
** Reference URL: https://attack.mitre.org/techniques/T1543/
<<<<<<< HEAD
=======


>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))
* Tactic:
** Name: Credential Access
** ID: TA0006
** Reference URL: https://attack.mitre.org/tactics/TA0006/
* Technique:
** Name: Modify Authentication Process
** ID: T1556
** Reference URL: https://attack.mitre.org/techniques/T1556/
<<<<<<< HEAD
=======

[[modification-of-standard-authentication-module-or-configuration-history]]
==== Rule version history

Version 100 (8.5.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.category:file and event.type:change and (file.name:pam_*.so
or file.path:(/etc/pam.d/* or /private/etc/pam.d/*)) and
process.executable: (* and not ( /bin/yum or
"/usr/sbin/pam-auth-update" or /usr/libexec/packagekitd or
/usr/bin/dpkg or /usr/bin/vim or
/usr/libexec/xpcproxy or /usr/bin/bsdtar or
/usr/local/bin/brew or /usr/bin/rsync or /usr/bin/yum
or /var/lib/docker/*/bin/yum or
/var/lib/docker/*/bin/dpkg or
./merged/var/lib/docker/*/bin/dpkg or "/System/Library/Private
Frameworks/PackageKit.framework/Versions/A/XPCServices/package_script_
service.xpc/Contents/MacOS/package_script_service" ) ) and
not file.path: ( /tmp/snap.rootfs_*/pam_*.so or
/tmp/newroot/lib/*/pam_*.so or /private/var/folders/*/T/com
.apple.fileprovider.ArchiveService/TemporaryItems/*/lib/security/pam_*
.so or /tmp/newroot/usr/lib64/security/pam_*.so )
----------------------------------

Version 3 (8.4.0 release)::
* Formatting only

Version 2 (7.13.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.category:file and event.type:change and (file.name:pam_*.so or
file.path:(/etc/pam.d/* or /private/etc/pam.d/*)) and
process.executable: (* and not ( /bin/yum or "/usr/sbin/pam-auth-
update" or /usr/libexec/packagekitd or /usr/bin/dpkg or /usr/bin/vim
or /usr/libexec/xpcproxy or /usr/bin/bsdtar or /usr/local/bin/brew ) )
----------------------------------

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))
