[[mounting-hidden-or-webdav-remote-shares]]
=== Mounting Hidden or WebDav Remote Shares

Identifies the use of net.exe to mount a WebDav or hidden remote share. This may indicate lateral movement or preparation for data exfiltration.

*Rule type*: eql

*Rule indices*:

* logs-endpoint.events.*
* winlogbeat-*
* logs-windows.*

*Severity*: medium

*Risk score*: 21

*Runs every*: 5 minutes

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*Tags*:

* Elastic
* Host
* Windows
* Threat Detection
* Lateral Movement

*Version*: 4 (<<mounting-hidden-or-webdav-remote-shares-history, version history>>)

*Added ({stack} release)*: 7.11.0

*Last modified ({stack} release)*: 8.2.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Investigation guide


[source,markdown]
----------------------------------
## Config

If enabling an EQL rule on a non-elastic-agent index (such as beats) for versions <8.2, events will not define `event.ingested` and default fallback for EQL rules was not added until 8.2, so you will need to add a custom pipeline to populate `event.ingested` to @timestamp for this rule to work.

----------------------------------


==== Rule query


[source,js]
----------------------------------
process where event.type in ("start", "process_started") and
((process.name : "net.exe" or process.pe.original_file_name ==
"net.exe") or ((process.name : "net1.exe" or
process.pe.original_file_name == "net1.exe") and not
process.parent.name : "net.exe")) and process.args : "use" and /*
including hidden and webdav based online shares such as onedrive */
process.args : ("\\\\*\\*$*", "\\\\*@SSL\\*", "http*") and /*
excluding shares deletion operation */ not process.args : "/d*"
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Lateral Movement
** ID: TA0008
** Reference URL: https://attack.mitre.org/tactics/TA0008/
* Technique:
** Name: Remote Services
** ID: T1021
** Reference URL: https://attack.mitre.org/techniques/T1021/

[[mounting-hidden-or-webdav-remote-shares-history]]
==== Rule version history

Version 4 (8.2.0 release)::
* Formatting only

Version 3 (7.12.0 release)::
* Formatting only

Version 2 (7.11.2 release)::
* Formatting only

