[[mounting-hidden-or-webdav-remote-shares]]
=== Mounting Hidden or WebDav Remote Shares

Identifies the use of net.exe to mount a WebDav or hidden remote share. This may indicate lateral movement or preparation for data exfiltration.

*Rule type*: eql

<<<<<<< HEAD
*Rule indices*: 

* logs-endpoint.events.process-*
* winlogbeat-*
* logs-windows.forwarded*
* logs-windows.sysmon_operational-*
* endgame-*
* logs-system.security*
* logs-m365_defender.event-*
* logs-sentinel_one_cloud_funnel.*
* logs-crowdstrike.fdr*
=======
*Rule indices*:

* logs-endpoint.events.*
* winlogbeat-*
* logs-windows.*
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Severity*: medium

*Risk score*: 47

<<<<<<< HEAD
*Runs every*: 5m
=======
*Runs every*: 5 minutes
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

<<<<<<< HEAD
*References*: None

*Tags*: 

* Domain: Endpoint
* OS: Windows
* Use Case: Threat Detection
* Tactic: Initial Access
* Tactic: Lateral Movement
* Data Source: Elastic Endgame
* Data Source: Elastic Defend
* Data Source: System
* Data Source: Microsoft Defender for Endpoint
* Data Source: Sysmon
* Data Source: SentinelOne
* Data Source: Crowdstrike

*Version*: 311

*Rule authors*: 

* Elastic

*Rule license*: Elastic License v2

=======
*Tags*:

* Elastic
* Host
* Windows
* Threat Detection
* Initial Access
* Lateral Movement

*Version*: 102 (<<mounting-hidden-or-webdav-remote-shares-history, version history>>)

*Added ({stack} release)*: 7.11.0

*Last modified ({stack} release)*: 8.6.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Investigation guide


[source,markdown]
----------------------------------

----------------------------------

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

==== Rule query


<<<<<<< HEAD
[source, js]
----------------------------------
process where host.os.type == "windows" and event.type == "start" and
 ((process.name : "net.exe" or ?process.pe.original_file_name == "net.exe") or ((process.name : "net1.exe" or ?process.pe.original_file_name == "net1.exe") and
 not process.parent.name : "net.exe")) and
 process.args : "use" and
 /* including hidden and webdav based online shares such as onedrive  */
 process.args : ("\\\\*\\*$*", "\\\\*@SSL\\*", "http*") and
 /* excluding shares deletion operation */
 not process.args : "/d*"

----------------------------------
=======
[source,js]
----------------------------------
process where event.type == "start" and ((process.name : "net.exe" or
process.pe.original_file_name == "net.exe") or ((process.name :
"net1.exe" or process.pe.original_file_name == "net1.exe") and not
process.parent.name : "net.exe")) and process.args : "use" and /*
including hidden and webdav based online shares such as onedrive */
process.args : ("\\\\*\\*$*", "\\\\*@SSL\\*", "http*") and /*
excluding shares deletion operation */ not process.args : "/d*"
----------------------------------

==== Threat mapping
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Lateral Movement
** ID: TA0008
** Reference URL: https://attack.mitre.org/tactics/TA0008/
* Technique:
** Name: Remote Services
** ID: T1021
** Reference URL: https://attack.mitre.org/techniques/T1021/
<<<<<<< HEAD
* Sub-technique:
** Name: SMB/Windows Admin Shares
** ID: T1021.002
** Reference URL: https://attack.mitre.org/techniques/T1021/002/
=======


>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))
* Tactic:
** Name: Initial Access
** ID: TA0001
** Reference URL: https://attack.mitre.org/tactics/TA0001/
* Technique:
** Name: Valid Accounts
** ID: T1078
** Reference URL: https://attack.mitre.org/techniques/T1078/
<<<<<<< HEAD
* Sub-technique:
** Name: Local Accounts
** ID: T1078.003
** Reference URL: https://attack.mitre.org/techniques/T1078/003/
* Tactic:
** Name: Discovery
** ID: TA0007
** Reference URL: https://attack.mitre.org/tactics/TA0007/
* Technique:
** Name: Account Discovery
** ID: T1087
** Reference URL: https://attack.mitre.org/techniques/T1087/
* Sub-technique:
** Name: Local Account
** ID: T1087.001
** Reference URL: https://attack.mitre.org/techniques/T1087/001/
* Sub-technique:
** Name: Domain Account
** ID: T1087.002
** Reference URL: https://attack.mitre.org/techniques/T1087/002/
=======

[[mounting-hidden-or-webdav-remote-shares-history]]
==== Rule version history

Version 102 (8.6.0 release)::
* Formatting only

Version 101 (8.5.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
process where event.type in ("start", "process_started") and
((process.name : "net.exe" or process.pe.original_file_name ==
"net.exe") or ((process.name : "net1.exe" or
process.pe.original_file_name == "net1.exe") and not
process.parent.name : "net.exe")) and process.args : "use" and /*
including hidden and webdav based online shares such as onedrive */
process.args : ("\\\\*\\*$*", "\\\\*@SSL\\*", "http*") and /*
excluding shares deletion operation */ not process.args : "/d*"
----------------------------------

Version 6 (8.4.0 release)::
* Formatting only

Version 4 (8.2.0 release)::
* Formatting only

Version 3 (7.12.0 release)::
* Formatting only

Version 2 (7.11.2 release)::
* Formatting only

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))
