[[multiple-alerts-in-different-att-ck-tactics-on-a-single-host]]
=== Multiple Alerts in Different ATT&CK Tactics on a Single Host

This rule uses alert data to determine when multiple alerts in different phases of an attack involving the same host are triggered. Analysts can use this to prioritize triage and response, as these hosts are more likely to be compromised.

*Rule type*: threshold

<<<<<<< HEAD
*Rule indices*: 

* .alerts-security.*
=======
*Rule indices*:

* .alerts-*
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Severity*: high

*Risk score*: 73

<<<<<<< HEAD
*Runs every*: 1h
=======
*Runs every*: 1 hour
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Searches indices from*: now-24h ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

<<<<<<< HEAD
*References*: None

*Tags*: 

* Use Case: Threat Detection
* Rule Type: Higher-Order Rule

*Version*: 4

*Rule authors*: 

* Elastic

*Rule license*: Elastic License v2

=======
*Tags*:

* Elastic
* Threat Detection
* Higher-Order Rules

*Version*: 1

*Added ({stack} release)*: 8.6.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Potential false positives

False positives can occur because the rules may be mapped to a few MITRE ATT&CK tactics. Use the attached Timeline to determine which detections were triggered on the host.
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

==== Rule query


<<<<<<< HEAD
[source, js]
----------------------------------
signal.rule.name:* and kibana.alert.rule.threat.tactic.id:*

----------------------------------
=======
[source,js]
----------------------------------
signal.rule.name:* and kibana.alert.rule.threat.tactic.id:*
----------------------------------

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))
