[[net-command-via-system-account]]
=== Net command via SYSTEM account

Identifies the SYSTEM account using the Net utility. The Net utility is a
component of the Windows operating system. It is used in command line operations
for control of users, groups, services, and network connections.

*Rule type*: query

*Rule indices*:

* winlogbeat-*
* logs-endpoint.events.*

*Severity*: low

*Risk score*: 21

*Runs every*: 5 minutes

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*Tags*:

* Elastic
* Windows

*Version*: 4 (<<net-command-via-system-account-history, version history>>)

*Added ({stack} release)*: 7.7.0

*Last modified ({stack} release)*: 7.10.0

*Rule authors*: Elastic

*Rule license*: Elastic License

==== Rule query


[source,js]
----------------------------------
event.category:process and event.type:(start or process_started) and
(process.name:(whoami.exe or net.exe) or process.name:net1.exe and not
process.parent.name:net.exe) and user.name:SYSTEM
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Discovery
** ID: TA0007
** Reference URL: https://attack.mitre.org/tactics/TA0007/
* Technique:
** Name: Account Discovery
** ID: T1087
** Reference URL: https://attack.mitre.org/techniques/T1087/

[[net-command-via-system-account-history]]
==== Rule version history

Version 4 (7.10.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.category:process and event.type:(start or process_started) and
(process.name:net.exe or process.name:net1.exe and not
process.parent.name:net.exe) and user.name:SYSTEM
----------------------------------

Version 3 (7.9.1 release)::
* Formatting only

Version 2 (7.9.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
(process.name:net.exe or process.name:net1.exe and not
process.parent.name:net.exe) and user.name:SYSTEM and
event.action:"Process Create (rule: ProcessCreate)"
----------------------------------

