[[network-connection-via-msxsl]]
=== Network Connection via MsXsl

Identifies msxsl.exe making a network connection. This may indicate adversarial activity as msxsl.exe is often leveraged by adversaries to execute malicious scripts and evade detection.

*Rule type*: eql

*Rule indices*:

* winlogbeat-*
* logs-endpoint.events.*
* logs-windows.*

*Severity*: low

*Risk score*: 21

*Runs every*: 5 minutes

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*Tags*:

* Elastic
* Host
* Windows
* Threat Detection
* Defense Evasion

*Version*: 6 (<<network-connection-via-msxsl-history, version history>>)

*Added ({stack} release)*: 7.7.0

*Last modified ({stack} release)*: 7.12.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Rule query


[source,js]
----------------------------------
sequence by process.entity_id [process where process.name :
"msxsl.exe" and event.type == "start"] [network where process.name :
"msxsl.exe" and not cidrmatch(destination.ip, "10.0.0.0/8",
"172.16.0.0/12", "192.168.0.0/16")]
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Defense Evasion
** ID: TA0005
** Reference URL: https://attack.mitre.org/tactics/TA0005/
* Technique:
** Name: XSL Script Processing
** ID: T1220
** Reference URL: https://attack.mitre.org/techniques/T1220/

[[network-connection-via-msxsl-history]]
==== Rule version history

Version 6 (7.12.0 release)::
* Formatting only

Version 5 (7.11.0 release)::
* Formatting only

Version 4 (7.10.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.category:network and event.type:connection and
process.name:msxsl.exe and not destination.ip:(10.0.0.0/8 or
172.16.0.0/12 or 192.168.0.0/16)
----------------------------------

Version 3 (7.9.1 release)::
* Formatting only

Version 2 (7.9.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
process.name:msxsl.exe and event.action:"Network connection detected
(rule: NetworkConnect)" and not destination.ip:(10.0.0.0/8 or
172.16.0.0/12 or 192.168.0.0/16)
----------------------------------

