[[network-connection-via-registration-utility]]
=== Network Connection via Registration Utility

Identifies the native Windows tools regsvr32.exe, regsvr64.exe, RegSvcs.exe, or RegAsm.exe making a network connection. This may be indicative of an attacker bypassing allowlists or running arbitrary scripts via a signed Microsoft binary.

*Rule type*: eql

*Rule indices*:

* winlogbeat-*
* logs-endpoint.events.*

*Severity*: low

*Risk score*: 21

*Runs every*: 5 minutes

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*Tags*:

* Elastic
* Host
* Windows
* Threat Detection
* Execution

*Version*: 5 (<<network-connection-via-registration-utility-history, version history>>)

*Added ({stack} release)*: 7.6.0

*Last modified ({stack} release)*: 7.10.0

*Rule authors*: Elastic

*Rule license*: Elastic License

==== Potential false positives

Security testing may produce events like this. Activity of this kind performed by non-engineers and ordinary users is unusual.

==== Rule query


[source,js]
----------------------------------
sequence by process.entity_id [process where (process.name :
"regsvr32.exe" or process.name : "regsvr64.exe" or
process.name : "RegAsm.exe" or process.name : "RegSvcs.exe") and
event.type == "start"] [network where (process.name : "regsvr32.exe"
or process.name : "regsvr64.exe" or process.name :
"RegAsm.exe" or process.name : "RegSvcs.exe") and not
cidrmatch(destination.ip, "10.0.0.0/8", "169.254.169.254",
"172.16.0.0/12", "192.168.0.0/16")]
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Execution
** ID: TA0002
** Reference URL: https://attack.mitre.org/tactics/TA0002/
* Technique:
** Name: Regsvr32
** ID: T1117
** Reference URL: https://attack.mitre.org/techniques/T1117/


* Tactic:
** Name: Defense Evasion
** ID: TA0005
** Reference URL: https://attack.mitre.org/tactics/TA0005/
* Technique:
** Name: Signed Binary Proxy Execution
** ID: T1218
** Reference URL: https://attack.mitre.org/techniques/T1218/

[[network-connection-via-registration-utility-history]]
==== Rule version history

Version 5 (7.10.0 release)::
* Rule name changed from: Network Connection via Regsvr
+
* Updated query, changed from:
+
[source, js]
----------------------------------
event.category:network and event.type:connection and
process.name:(regsvr32.exe or regsvr64.exe) and not
destination.ip:(10.0.0.0/8 or 169.254.169.254 or 172.16.0.0/12 or
192.168.0.0/16)
----------------------------------

Version 4 (7.9.1 release)::
* Formatting only

Version 3 (7.9.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
process.name:(regsvr32.exe or regsvr64.exe) and event.action:"Network
connection detected (rule: NetworkConnect)" and not
destination.ip:(10.0.0.0/8 or 169.254.169.254 or 172.16.0.0/12 or
192.168.0.0/16)
----------------------------------

Version 2 (7.7.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
(process.name:regsvr32.exe or process.name:regsvr64.exe) and
event.action:"Network connection detected (rule: NetworkConnect)" and
not destination.ip:169.254.169.254/32 and not
destination.ip:10.0.0.0/8 and not destination.ip:172.16.0.0/12 and not
destination.ip:192.168.0.0/16
----------------------------------

