[[o365-excessive-single-sign-on-logon-errors]]
=== O365 Excessive Single Sign-On Logon Errors

Identifies accounts with a high number of single sign-on (SSO) logon errors. Excessive logon errors may indicate an attempt to brute force a password or SSO token.

*Rule type*: threshold

<<<<<<< HEAD
*Rule indices*: 
=======
*Rule indices*:
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

* filebeat-*
* logs-o365*

*Severity*: high

*Risk score*: 73

<<<<<<< HEAD
*Runs every*: 5m
=======
*Runs every*: 5 minutes
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Searches indices from*: now-20m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

<<<<<<< HEAD
*References*: None

*Tags*: 

* Domain: Cloud
* Data Source: Microsoft 365
* Use Case: Identity and Access Audit
* Tactic: Credential Access

*Version*: 207

*Rule authors*: 

* Elastic
* Austin Songer

*Rule license*: Elastic License v2

=======
*Tags*:

* Elastic
* Cloud
* Microsoft 365
* Continuous Monitoring
* SecOps
* Identity and Access

*Version*: 101 (<<o365-excessive-single-sign-on-logon-errors-history, version history>>)

*Added ({stack} release)*: 7.14.0

*Last modified ({stack} release)*: 8.6.0

*Rule authors*: Elastic, Austin Songer

*Rule license*: Elastic License v2

==== Potential false positives

Automated processes that attempt to authenticate using expired credentials and unbounded retries may lead to false positives.
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

==== Investigation guide


<<<<<<< HEAD


==== Setup


The Office 365 Logs Fleet integration, Filebeat module, or similarly structured data is required to be compatible with this rule.
=======
[source,markdown]
----------------------------------

----------------------------------

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

==== Rule query


<<<<<<< HEAD
[source, js]
----------------------------------
event.dataset:o365.audit and event.provider:AzureActiveDirectory and event.category:authentication and o365.audit.LogonError:"SsoArtifactInvalidOrExpired"

----------------------------------
=======
[source,js]
----------------------------------
event.dataset:o365.audit and event.provider:AzureActiveDirectory and
event.category:authentication and
o365.audit.LogonError:"SsoArtifactInvalidOrExpired"
----------------------------------

==== Threat mapping
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Credential Access
** ID: TA0006
** Reference URL: https://attack.mitre.org/tactics/TA0006/
* Technique:
** Name: Brute Force
** ID: T1110
** Reference URL: https://attack.mitre.org/techniques/T1110/
<<<<<<< HEAD
=======

[[o365-excessive-single-sign-on-logon-errors-history]]
==== Rule version history

Version 101 (8.6.0 release)::
* Formatting only

Version 100 (8.5.0 release)::
* Formatting only

Version 6 (8.4.0 release)::
* Formatting only

Version 4 (8.1.0 release)::
* Formatting only

Version 3 (8.0.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.dataset:o365.audit and event.provider:AzureActiveDirectory and
event.category:web and
o365.audit.LogonError:"SsoArtifactInvalidOrExpired"
----------------------------------

Version 2 (7.15.0 release)::
* Formatting only

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))
