[[o365-exchange-suspicious-mailbox-right-delegation]]
=== O365 Exchange Suspicious Mailbox Right Delegation

Identifies the assignment of rights to access content from another mailbox. An adversary may use the compromised account to send messages to other accounts in the network of the target organization while creating inbox rules, so messages can evade spam/phishing detection mechanisms.

*Rule type*: query

*Rule indices*:

* filebeat-*
* logs-o365*

*Severity*: low

*Risk score*: 21

*Runs every*: 5 minutes

*Searches indices from*: now-6m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*Tags*:

* Elastic
* Cloud
* Microsoft 365
* Continuous Monitoring
* SecOps
* Configuration Audit

*Version*: 101 (<<o365-exchange-suspicious-mailbox-right-delegation-history, version history>>)

*Added ({stack} release)*: 7.16.0

*Last modified ({stack} release)*: 8.6.0

*Rule authors*: Elastic, Austin Songer

*Rule license*: Elastic License v2

==== Potential false positives

Assignment of rights to a service account.

==== Investigation guide


[source,markdown]
----------------------------------

----------------------------------


==== Rule query


[source,js]
----------------------------------
event.dataset:o365.audit and event.provider:Exchange and
event.action:Add-MailboxPermission and
o365.audit.Parameters.AccessRights:(FullAccess or SendAs or
SendOnBehalf) and event.outcome:success and not user.id : "NT
AUTHORITY\SYSTEM (Microsoft.Exchange.Servicehost)"
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Persistence
** ID: TA0003
** Reference URL: https://attack.mitre.org/tactics/TA0003/
* Technique:
** Name: Account Manipulation
** ID: T1098
** Reference URL: https://attack.mitre.org/techniques/T1098/

[[o365-exchange-suspicious-mailbox-right-delegation-history]]
==== Rule version history

Version 101 (8.6.0 release)::
* Formatting only

Version 100 (8.5.0 release)::
* Formatting only

Version 4 (8.4.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.dataset:o365.audit and event.provider:Exchange and
event.action:Add-MailboxPermission and
o365.audit.Parameters.AccessRights:(FullAccess or SendAs or
SendOnBehalf) and event.outcome:success and not user.id : "NT
AUTHORITY\SYSTEM (Microsoft.Exchange.Servicehost)"
----------------------------------

Version 2 (8.1.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.dataset:o365.audit and event.provider:Exchange and
event.action:Add-MailboxPermission and
o365.audit.Parameters.AccessRights:(FullAccess or SendAs or
SendOnBehalf) and event.outcome:success
----------------------------------

