[[persistence-via-wmi-event-subscription]]
=== Persistence via WMI Event Subscription

An adversary can use Windows Management Instrumentation (WMI) to install event filters, providers, consumers, and bindings that execute code when a defined event occurs. Adversaries may use the capabilities of WMI to subscribe to an event and execute arbitrary code when that event occurs, providing persistence on a system.

*Rule type*: eql

*Rule indices*:

* logs-endpoint.events.*
* winlogbeat-*
* logs-windows.*

*Severity*: low

*Risk score*: 21

*Runs every*: 5 minutes

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*Tags*:

* Elastic
* Host
* Windows
* Threat Detection
* Persistence

*Version*: 7 (<<persistence-via-wmi-event-subscription-history, version history>>)

*Added ({stack} release)*: 7.11.0

*Last modified ({stack} release)*: 8.4.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Investigation guide


[source,markdown]
----------------------------------

----------------------------------


==== Rule query


[source,js]
----------------------------------
process where event.type in ("start", "process_started") and
(process.name : "wmic.exe" or process.pe.original_file_name ==
"wmic.exe") and process.args : "create" and process.args :
("ActiveScriptEventConsumer", "CommandLineEventConsumer")
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Persistence
** ID: TA0003
** Reference URL: https://attack.mitre.org/tactics/TA0003/
* Technique:
** Name: Event Triggered Execution
** ID: T1546
** Reference URL: https://attack.mitre.org/techniques/T1546/

[[persistence-via-wmi-event-subscription-history]]
==== Rule version history

Version 7 (8.4.0 release)::
* Formatting only

Version 5 (8.2.0 release)::
* Formatting only

Version 4 (7.16.0 release)::
* Formatting only

Version 3 (7.12.0 release)::
* Formatting only

Version 2 (7.11.2 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
process where event.type in ("start", "process_started") and
(process.name : "wmic.exe" or process.pe.original_file_name ==
"wmic.exe") and process.args : "create" and process.args :
("ActiveScriptEventConsumer", "CommandLineEventConsumer")
----------------------------------

