[[potential-command-and-control-via-internet-explorer]]
=== Potential Command and Control via Internet Explorer

Identifies instances of Internet Explorer (iexplore.exe) being started via the Component Object Model (COM) making unusual network connections. Adversaries could abuse Internet Explorer via COM to avoid suspicious processes making network connections and bypass host-based firewall restrictions.

*Rule type*: eql

*Rule indices*:

* winlogbeat-*
* logs-endpoint.events.*
* logs-windows.*

*Severity*: medium

*Risk score*: 47

*Runs every*: 5 minutes

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*Tags*:

* Elastic
* Host
* Windows
* Threat Detection
* Command and Control

*Version*: 2 (<<potential-command-and-control-via-internet-explorer-history, version history>>)

*Added ({stack} release)*: 7.11.0

*Last modified ({stack} release)*: 7.12.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Rule query


[source,js]
----------------------------------
sequence by host.id, process.entity_id with maxspan = 1s [process
where event.type == "start" and process.parent.name : "iexplore.exe"
and process.parent.args : "-Embedding"] /* IE started via COM in
normal conditions makes few connections, mainly to Microsoft and OCSP
related domains, add FPs here */ [network where network.protocol ==
"dns" and process.name : "iexplore.exe" and not dns.question.name :
( "*.microsoft.com", "*.digicert.com", "*.msocsp.com",
"*.windowsupdate.com", "*.bing.com", "*.identrust.com" )
]
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Command and Control
** ID: TA0011
** Reference URL: https://attack.mitre.org/tactics/TA0011/
* Technique:
** Name: Application Layer Protocol
** ID: T1071
** Reference URL: https://attack.mitre.org/techniques/T1071/

[[potential-command-and-control-via-internet-explorer-history]]
==== Rule version history

Version 2 (7.12.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
sequence by host.id, process.entity_id with maxspan = 1s [process
where event.type:"start" and process.parent.name:"iexplore.exe" and
process.parent.args:"-Embedding"] /* IE started via COM in normal
conditions makes few connections, mainly to Microsoft and OCSP related
domains, add FPs here */ [network where network.protocol : "dns" and
process.name:"iexplore.exe" and not wildcard(dns.question.name,
"*.microsoft.com",
"*.digicert.com", "*.msocsp.com",
"*.windowsupdate.com",
"*.bing.com", "*.identrust.com")
]
----------------------------------

