[[potential-shell-via-web-server]]
=== Potential Shell via Web Server

Identifies suspicious commands executed via a web server, which may suggest a vulnerability and remote shell access.

*Rule type*: query

*Rule indices*:

* auditbeat-*
* logs-endpoint.events.*

*Severity*: medium

*Risk score*: 47

*Runs every*: 5 minutes

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*:

* https://pentestlab.blog/tag/web-shell/

*Tags*:

* Elastic
* Host
* Linux
* Threat Detection
* Persistence

*Version*: 100 (<<potential-shell-via-web-server-history, version history>>)

*Added ({stack} release)*: 7.6.0

*Last modified ({stack} release)*: 8.5.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Potential false positives

Network monitoring or management products may have a web server component that runs shell commands as part of normal behavior.

==== Rule query


[source,js]
----------------------------------
event.category:process and event.type:(start or process_started) and
process.name:(bash or dash or ash or zsh or "python*" or "perl*" or
"php*") and process.parent.name:("apache" or "nginx" or "www" or
"apache2" or "httpd" or "www-data")
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Persistence
** ID: TA0003
** Reference URL: https://attack.mitre.org/tactics/TA0003/
* Technique:
** Name: Server Software Component
** ID: T1505
** Reference URL: https://attack.mitre.org/techniques/T1505/

[[potential-shell-via-web-server-history]]
==== Rule version history

Version 100 (8.5.0 release)::
* Formatting only

Version 11 (8.4.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.category:process and event.type:(start or process_started) and
process.name:(bash or dash) and user.name:(apache or nginx or www or
"www-data")
----------------------------------

Version 9 (7.12.0 release)::
* Formatting only

Version 8 (7.11.2 release)::
* Formatting only

Version 7 (7.11.0 release)::
* Formatting only

Version 6 (7.10.0 release)::
* Formatting only

Version 5 (7.9.1 release)::
* Formatting only

Version 4 (7.9.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
process.name:(bash or dash) and user.name:(apache or nginx or www or
"www-data") and event.action:executed
----------------------------------

Version 3 (7.8.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
process.name:bash and user.name:(apache or www or www-data) and
event.action:executed
----------------------------------

Version 2 (7.6.1 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
process.name: bash and user.name: (apache or www or "wwww-data") and
event.action:executed
----------------------------------

