[[potential-command-and-control-via-internet-explorer]]
=== Potential Command and Control via Internet Explorer

Identifies instances of Internet Explorer (iexplore.exe) being started via the Component Object Model (COM) making unusual network connections. Adversaries could abuse Internet Explorer via COM to avoid suspicious processes making network connections and bypass host-based firewall restrictions.

*Rule type*: eql

<<<<<<< HEAD
*Rule indices*: 

* logs-endpoint.events.library-*
* logs-endpoint.events.process-*
* logs-endpoint.events.network-*
=======
*Rule indices*:

* winlogbeat-*
* logs-endpoint.events.*
* logs-windows.*
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Severity*: medium

*Risk score*: 47

<<<<<<< HEAD
*Runs every*: 5m
=======
*Runs every*: 5 minutes
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

<<<<<<< HEAD
*References*: None

*Tags*: 

* Domain: Endpoint
* OS: Windows
* Use Case: Threat Detection
* Tactic: Command and Control
* Data Source: Elastic Defend

*Version*: 106

*Rule authors*: 

* Elastic

*Rule license*: Elastic License v2

=======
*Tags*:

* Elastic
* Host
* Windows
* Threat Detection
* Command and Control

*Version*: 100 (<<potential-command-and-control-via-internet-explorer-history, version history>>)

*Added ({stack} release)*: 7.11.0

*Last modified ({stack} release)*: 8.5.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Potential false positives

Processes such as MS Office using IEproxy to render HTML content.
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

==== Rule query


<<<<<<< HEAD
[source, js]
----------------------------------
sequence by host.id, user.name with maxspan = 5s
  [library where host.os.type == "windows" and dll.name : "IEProxy.dll" and process.name : ("rundll32.exe", "regsvr32.exe")]
  [process where host.os.type == "windows" and event.type == "start" and process.parent.name : "iexplore.exe" and process.parent.args : "-Embedding"]
  /* IE started via COM in normal conditions makes few connections, mainly to Microsoft and OCSP related domains, add FPs here */
  [network where host.os.type == "windows" and network.protocol == "dns" and process.name : "iexplore.exe" and
   not dns.question.name :
   (
    "*.microsoft.com",
    "*.digicert.com",
    "*.msocsp.com",
    "*.windowsupdate.com",
    "*.bing.com",
    "*.identrust.com",
    "*.sharepoint.com",
    "*.office365.com",
    "*.office.com"
    )
  ] /* with runs=5 */

----------------------------------
=======
[source,js]
----------------------------------
sequence by host.id, user.name with maxspan = 5s [library where
dll.name : "IEProxy.dll" and process.name : ("rundll32.exe",
"regsvr32.exe")] [process where event.type == "start" and
process.parent.name : "iexplore.exe" and process.parent.args :
"-Embedding"] /* IE started via COM in normal conditions makes few
connections, mainly to Microsoft and OCSP related domains, add FPs
here */ [network where network.protocol == "dns" and process.name :
"iexplore.exe" and not dns.question.name : (
"*.microsoft.com", "*.digicert.com", "*.msocsp.com",
"*.windowsupdate.com", "*.bing.com", "*.identrust.com",
"*.sharepoint.com", "*.office365.com", "*.office.com" )
] /* with runs=5 */
----------------------------------

==== Threat mapping
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Command and Control
** ID: TA0011
** Reference URL: https://attack.mitre.org/tactics/TA0011/
* Technique:
** Name: Application Layer Protocol
** ID: T1071
** Reference URL: https://attack.mitre.org/techniques/T1071/
<<<<<<< HEAD
=======


>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))
* Tactic:
** Name: Execution
** ID: TA0002
** Reference URL: https://attack.mitre.org/tactics/TA0002/
* Technique:
** Name: Inter-Process Communication
** ID: T1559
** Reference URL: https://attack.mitre.org/techniques/T1559/
<<<<<<< HEAD
* Sub-technique:
** Name: Component Object Model
** ID: T1559.001
** Reference URL: https://attack.mitre.org/techniques/T1559/001/
=======

[[potential-command-and-control-via-internet-explorer-history]]
==== Rule version history

Version 100 (8.5.0 release)::
* Formatting only

Version 6 (8.4.0 release)::
* Formatting only

Version 5 (8.1.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
sequence by host.id, user.id with maxspan = 5s [library where
dll.name : "IEProxy.dll" and process.name : ("rundll32.exe",
"regsvr32.exe")] [process where event.type == "start" and
process.parent.name : "iexplore.exe" and process.parent.args :
"-Embedding"] /* IE started via COM in normal conditions makes few
connections, mainly to Microsoft and OCSP related domains, add FPs
here */ [network where network.protocol == "dns" and process.name :
"iexplore.exe" and not dns.question.name : (
"*.microsoft.com", "*.digicert.com", "*.msocsp.com",
"*.windowsupdate.com", "*.bing.com", "*.identrust.com",
"*.sharepoint.com", "*.office365.com", "*.office.com" )
]
----------------------------------

Version 4 (7.16.0 release)::
* Formatting only

Version 3 (7.13.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
sequence by host.id, process.entity_id with maxspan = 1s [process
where event.type == "start" and process.parent.name : "iexplore.exe"
and process.parent.args : "-Embedding"] /* IE started via COM in
normal conditions makes few connections, mainly to Microsoft and OCSP
related domains, add FPs here */ [network where network.protocol ==
"dns" and process.name : "iexplore.exe" and not dns.question.name :
( "*.microsoft.com", "*.digicert.com", "*.msocsp.com",
"*.windowsupdate.com", "*.bing.com", "*.identrust.com" )
]
----------------------------------

Version 2 (7.12.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
sequence by host.id, process.entity_id with maxspan = 1s [process
where event.type:"start" and process.parent.name:"iexplore.exe" and
process.parent.args:"-Embedding"] /* IE started via COM in normal
conditions makes few connections, mainly to Microsoft and OCSP related
domains, add FPs here */ [network where network.protocol : "dns" and
process.name:"iexplore.exe" and not wildcard(dns.question.name,
"*.microsoft.com",
"*.digicert.com", "*.msocsp.com",
"*.windowsupdate.com",
"*.bing.com", "*.identrust.com")
]
----------------------------------

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))
