[[potential-credential-access-via-duplicatehandle-in-lsass]]
=== Potential Credential Access via DuplicateHandle in LSASS

Identifies suspicious access to an LSASS handle via DuplicateHandle from an unknown call trace module. This may indicate an attempt to bypass the NtOpenProcess API to evade detection and dump LSASS memory for credential access.

*Rule type*: eql

<<<<<<< HEAD
*Rule indices*: 

* winlogbeat-*
* logs-windows.sysmon_operational-*
=======
*Rule indices*:

* winlogbeat-*
* logs-windows.*
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Severity*: medium

*Risk score*: 47

<<<<<<< HEAD
*Runs every*: 5m
=======
*Runs every*: 5 minutes
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

<<<<<<< HEAD
*References*: 

* https://github.com/CCob/MirrorDump

*Tags*: 

* Domain: Endpoint
* OS: Windows
* Use Case: Threat Detection
* Tactic: Credential Access
* Data Source: Sysmon

*Version*: 308

*Rule authors*: 

* Elastic

*Rule license*: Elastic License v2


==== Setup



*Setup*


If enabling an EQL rule on a non-elastic-agent index (such as beats) for versions <8.2,
events will not define `event.ingested` and default fallback for EQL rules was not added until version 8.2.
Hence for this rule to work effectively, users will need to add a custom ingest pipeline to populate
`event.ingested` to @timestamp.
For more details on adding a custom ingest pipeline refer - https://www.elastic.co/guide/en/fleet/current/data-streams-pipeline-tutorial.html
=======
*References*:

* https://github.com/CCob/MirrorDump

*Tags*:

* Elastic
* Host
* Windows
* Threat Detection
* Credential Access
* Sysmon Only

*Version*: 101 (<<potential-credential-access-via-duplicatehandle-in-lsass-history, version history>>)

*Added ({stack} release)*: 7.16.0

*Last modified ({stack} release)*: 8.6.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Investigation guide


[source,markdown]
----------------------------------

----------------------------------
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))


==== Rule query


<<<<<<< HEAD
[source, js]
----------------------------------
process where host.os.type == "windows" and event.code == "10" and

 /* LSASS requesting DuplicateHandle access right to another process */
 process.name : "lsass.exe" and winlog.event_data.GrantedAccess == "0x40" and

 /* call is coming from an unknown executable region */
 winlog.event_data.CallTrace : "*UNKNOWN*"

----------------------------------

=======
[source,js]
----------------------------------
process where event.code == "10" and /* LSASS requesting
DuplicateHandle access right to another process */ process.name :
"lsass.exe" and winlog.event_data.GrantedAccess == "0x40" and /*
call is coming from an unknown executable region */
winlog.event_data.CallTrace : "*UNKNOWN*"
----------------------------------

==== Threat mapping

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))
*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Credential Access
** ID: TA0006
** Reference URL: https://attack.mitre.org/tactics/TA0006/
* Technique:
** Name: OS Credential Dumping
** ID: T1003
** Reference URL: https://attack.mitre.org/techniques/T1003/
<<<<<<< HEAD
* Sub-technique:
** Name: LSASS Memory
** ID: T1003.001
** Reference URL: https://attack.mitre.org/techniques/T1003/001/
=======

[[potential-credential-access-via-duplicatehandle-in-lsass-history]]
==== Rule version history

Version 101 (8.6.0 release)::
* Formatting only

Version 100 (8.5.0 release)::
* Formatting only

Version 5 (8.4.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
process where event.code == "10" and /* LSASS requesting
DuplicateHandle access right to another process */ process.name :
"lsass.exe" and winlog.event_data.GrantedAccess == "0x40" and /*
call is coming from an unknown executable region */
winlog.event_data.CallTrace : "*UNKNOWN*"
----------------------------------

Version 3 (8.2.0 release)::
* Formatting only

Version 2 (8.0.0 release)::
* Formatting only

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))
