[[pptp-point-to-point-tunneling-protocol-activity]]
=== PPTP (Point to Point Tunneling Protocol) Activity

Detects events that may indicate use of a PPTP VPN connection. Some threat
actors use these types of connections to tunnel their traffic while avoiding
detection.

*Rule type*: query

*Rule indices*:

* filebeat-*
* packetbeat-*
* logs-endpoint.events.*

*Severity*: low

*Risk score*: 21

*Runs every*: 5 minutes

*Searches indices from*: now-6m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*Tags*:

* Elastic
* Host
* Network
* Threat Detection
* Command and Control

*Version*: 5 (<<pptp-point-to-point-tunneling-protocol-activity-history, version history>>)

*Added ({stack} release)*: 7.6.0

*Last modified ({stack} release)*: 7.11.0

*Rule authors*: Elastic

*Rule license*: Elastic License

==== Potential false positives

Some networks may utilize PPTP protocols but this is uncommon as more modern VPN technologies are available. Usage that is unfamiliar to local network administrators can be unexpected and suspicious. Torrenting applications may use this port. Because this port is in the ephemeral range, this rule may false under certain conditions, such as when an application server replies to a client that used this port by coincidence. This is uncommon but such servers can be excluded.

==== Rule query


[source,js]
----------------------------------
event.category:(network or network_traffic) and network.transport:tcp
and destination.port:1723
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Command and Control
** ID: TA0011
** Reference URL: https://attack.mitre.org/tactics/TA0011/

[[pptp-point-to-point-tunneling-protocol-activity-history]]
==== Rule version history

Version 5 (7.11.0 release)::
* Formatting only

Version 4 (7.10.0 release)::
* Formatting only

Version 3 (7.9.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
network.transport:tcp and destination.port:1723
----------------------------------

Version 2 (7.6.1 release)::
* Removed auditbeat-\*, packetbeat-*, and winlogbeat-* from the rule indices.

