[[rdp-remote-desktop-protocol-to-the-internet]]
=== RDP (Remote Desktop Protocol) to the Internet

Detects network events that may indicate the use of RDP traffic to the Internet.
RDP is commonly used by system administrators to remotely control a system for
maintenance or to use shared resources. It should almost never be directly
exposed to the Internet, as it is frequently targeted and exploited by threat
actors as an initial access or back-door vector.

*Rule type*: query

*Rule indices*:

* filebeat-*
* packetbeat-*
* logs-endpoint.events.*

*Severity*: low

*Risk score*: 21

*Runs every*: 5 minutes

*Searches indices from*: now-6m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*Tags*:

* Elastic
* Host
* Network
* Threat Detection
* Initial Access

*Version*: 6 (<<rdp-remote-desktop-protocol-to-the-internet-history, version history>>)

*Added ({stack} release)*: 7.6.0

*Last modified ({stack} release)*: 7.11.0

*Rule authors*: Elastic

*Rule license*: Elastic License

==== Potential false positives

RDP connections may be made directly to Internet destinations in order to access Windows cloud server instances but such connections are usually made only by engineers. In such cases, only RDP gateways, bastions or jump servers may be expected Internet destinations and can be exempted from this rule. RDP may be required by some work-flows such as remote access and support for specialized software products and servers. Such work-flows are usually known and not unexpected. Usage that is unfamiliar to server or network owners can be unexpected and suspicious.

==== Rule query


[source,js]
----------------------------------
event.category:(network or network_traffic) and network.transport:tcp
and (destination.port:3389 or event.dataset:zeek.rdp) and source.ip:(
10.0.0.0/8 or 172.16.0.0/12 or 192.168.0.0/16 ) and not
destination.ip:( 10.0.0.0/8 or 127.0.0.0/8 or 169.254.0.0/16 or
172.16.0.0/12 or 192.168.0.0/16 or 224.0.0.0/4 or "::1" or "FE80::/10"
or "FF00::/8" )
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Initial Access
** ID: TA0001
** Reference URL: https://attack.mitre.org/tactics/TA0001/
* Technique:
** Name: Exploit Public-Facing Application
** ID: T1190
** Reference URL: https://attack.mitre.org/techniques/T1190/


* Tactic:
** Name: Exfiltration
** ID: TA0010
** Reference URL: https://attack.mitre.org/tactics/TA0010/
* Technique:
** Name: Exfiltration Over Alternative Protocol
** ID: T1048
** Reference URL: https://attack.mitre.org/techniques/T1048/

[[rdp-remote-desktop-protocol-to-the-internet-history]]
==== Rule version history

Version 6 (7.11.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.category:(network or network_traffic) and network.transport:tcp
and (destination.port:3389 or event.dataset:zeek.rdp) and
source.ip:(10.0.0.0/8 or 172.16.0.0/12 or 192.168.0.0/16) and not
destination.ip:(10.0.0.0/8 or 127.0.0.0/8 or 172.16.0.0/12 or
192.168.0.0/16 or "::1")
----------------------------------

Version 5 (7.10.0 release)::
* Formatting only

Version 4 (7.9.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
network.transport:tcp and destination.port:3389 and
source.ip:(10.0.0.0/8 or 172.16.0.0/12 or 192.168.0.0/16) and not
destination.ip:(10.0.0.0/8 or 127.0.0.0/8 or 172.16.0.0/12 or
192.168.0.0/16 or "::1")
----------------------------------

Version 3 (7.7.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
network.transport: tcp and destination.port: 3389 and (
network.direction: outbound or ( source.ip: (10.0.0.0/8 or
172.16.0.0/12 or 192.168.0.0/16) and not destination.ip: (10.0.0.0/8
or 172.16.0.0/12 or 192.168.0.0/16) ) )
----------------------------------

Version 2 (7.6.1 release)::
* Removed auditbeat-\*, packetbeat-*, and winlogbeat-* from the rule indices.

