[[registry-persistence-via-appinit-dll]]
=== Registry Persistence via AppInit DLL

Attackers may maintain persistence by creating registry keys using AppInit DLLs. AppInit DLLs are loaded by every process using the common library, user32.dll.

*Rule type*: eql

*Rule indices*:

* winlogbeat-*
* logs-endpoint.events.*
* logs-windows.*

*Severity*: medium

*Risk score*: 47

*Runs every*: 5 minutes

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*Tags*:

* Elastic
* Host
* Windows
* Threat Detection
* Persistence

*Version*: 6 (<<registry-persistence-via-appinit-dll-history, version history>>)

*Added ({stack} release)*: 7.11.0

*Last modified ({stack} release)*: 8.4.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Investigation guide


[source,markdown]
----------------------------------

----------------------------------


==== Rule query


[source,js]
----------------------------------
registry where registry.path : ("HKLM\\SOFTWARE\\Microsoft\\Windows
NT\\CurrentVersion\\Windows\\AppInit_Dlls",
"HKLM\\SOFTWARE\\Wow6432Node\\Microsoft\\Windows
NT\\CurrentVersion\\Windows\\AppInit_Dlls") and not
process.executable : ("C:\\Windows\\System32\\msiexec.exe",
"C:\\Windows\\SysWOW64\\msiexec.exe",
"C:\\Program Files\\Commvault\\ContentStore*\\Base\\cvd.exe",
"C:\\Program Files (x86)\\Commvault\\ContentStore*\\Base\\cvd.exe")
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Persistence
** ID: TA0003
** Reference URL: https://attack.mitre.org/tactics/TA0003/
* Technique:
** Name: Event Triggered Execution
** ID: T1546
** Reference URL: https://attack.mitre.org/techniques/T1546/

[[registry-persistence-via-appinit-dll-history]]
==== Rule version history

Version 6 (8.4.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
registry where registry.path : ("HKLM\\SOFTWARE\\Microsoft\\Windows
NT\\CurrentVersion\\Windows\\AppInit_Dlls",
"HKLM\\SOFTWARE\\Wow6432Node\\Microsoft\\Windows
NT\\CurrentVersion\\Windows\\AppInit_Dlls") and not
process.executable : ("C:\\Windows\\System32\\msiexec.exe",
"C:\\Windows\\SysWOW64\\msiexec.exe",
"C:\\Program Files\\Commvault\\ContentStore*\\Base\\cvd.exe",
"C:\\Program Files (x86)\\Commvault\\ContentStore*\\Base\\cvd.exe")
----------------------------------

Version 4 (8.2.0 release)::
* Formatting only

Version 3 (7.12.0 release)::
* Formatting only

Version 2 (7.11.2 release)::
* Formatting only

