[[remote-file-download-via-mpcmdrun]]
=== Remote File Download via MpCmdRun

Identifies the Windows Defender configuration utility (MpCmdRun.exe) being used to download a remote file.

*Rule type*: eql

*Rule indices*:

* winlogbeat-*
* logs-endpoint.events.*
* logs-windows.*

*Severity*: medium

*Risk score*: 47

*Runs every*: 5 minutes

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*:

* https://twitter.com/mohammadaskar2/status/1301263551638761477
* https://www.bleepingcomputer.com/news/microsoft/microsoft-defender-can-ironically-be-used-to-download-malware/

*Tags*:

* Elastic
* Host
* Windows
* Threat Detection
* Command and Control

*Version*: 5 (<<remote-file-download-via-mpcmdrun-history, version history>>)

*Added ({stack} release)*: 7.10.0

*Last modified ({stack} release)*: 7.13.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Investigation guide

**Triage and analysis**

**Investigating Remote File Download via MpCmdRun**
Verify details such as the parent process, URL reputation, and downloaded file details. Additionally, `MpCmdRun` logs this information in the Appdata Temp folder in `MpCmdRun.log`.

==== Rule query


[source,js]
----------------------------------
process where event.type == "start" and (process.name :
"MpCmdRun.exe" or process.pe.original_file_name == "MpCmdRun.exe") and
process.args : "-DownloadFile" and process.args : "-url" and
process.args : "-path"
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Command and Control
** ID: TA0011
** Reference URL: https://attack.mitre.org/tactics/TA0011/
* Technique:
** Name: Ingress Tool Transfer
** ID: T1105
** Reference URL: https://attack.mitre.org/techniques/T1105/

[[remote-file-download-via-mpcmdrun-history]]
==== Rule version history

Version 5 (7.13.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.category:process and event.type:(start or process_started) and
(process.name:MpCmdRun.exe or
process.pe.original_file_name:MpCmdRun.exe) and
process.args:(("-DownloadFile" or "-downloadfile") and "-url" and
"-path")
----------------------------------

Version 4 (7.12.0 release)::
* Formatting only

Version 3 (7.11.2 release)::
* Formatting only

Version 2 (7.11.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.category:process and event.type:(start or process_started) and
(process.name:MpCmdRun.exe or
process.pe.original_file_name:MpCmdRun.exe or
winlog.event_data.OriginalFileName:MpCmdRun.exe) and
process.args:(("-DownloadFile" or "-downloadfile") and "-url" and
"-path")
----------------------------------

