[[renamed-autoit-scripts-interpreter]]
=== Renamed AutoIt Scripts Interpreter

Identifies a suspicious AutoIt process execution. Malware written as an AutoIt script tends to rename the AutoIt executable to avoid detection.

*Rule type*: eql

*Rule indices*:

* winlogbeat-*
* logs-endpoint.events.*
* logs-windows.*
* endgame-*

*Severity*: medium

*Risk score*: 47

*Runs every*: 5 minutes

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*Tags*:

* Elastic
* Host
* Windows
* Threat Detection
* Defense Evasion
* Elastic Endgame

*Version*: 102 (<<renamed-autoit-scripts-interpreter-history, version history>>)

*Added ({stack} release)*: 7.10.0

*Last modified ({stack} release)*: 8.6.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Investigation guide


[source,markdown]
----------------------------------

----------------------------------


==== Rule query


[source,js]
----------------------------------
process where event.type == "start" and
process.pe.original_file_name : "AutoIt*.exe" and not process.name :
"AutoIt*.exe"
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Defense Evasion
** ID: TA0005
** Reference URL: https://attack.mitre.org/tactics/TA0005/
* Technique:
** Name: Masquerading
** ID: T1036
** Reference URL: https://attack.mitre.org/techniques/T1036/

[[renamed-autoit-scripts-interpreter-history]]
==== Rule version history

Version 102 (8.6.0 release)::
* Formatting only

Version 101 (8.5.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
process where event.type in ("start", "process_started", "info") and
process.pe.original_file_name : "AutoIt*.exe" and not process.name :
"AutoIt*.exe"
----------------------------------

Version 8 (8.4.0 release)::
* Formatting only

Version 6 (8.2.0 release)::
* Formatting only

Version 5 (7.16.0 release)::
* Formatting only

Version 4 (7.12.0 release)::
* Formatting only

Version 3 (7.11.2 release)::
* Formatting only

Version 2 (7.11.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.category:process AND event.type:(start OR process_started) AND (
process.pe.original_file_name:/[aA][uU][tT][oO][iI][tT]\d\.[eE][xX][eE
]/ OR winlog.event_data.OriginalFileName:/[aA][uU][tT][oO][iI][tT]\d\.
[eE][xX][eE]/) AND NOT
process.name:/[aA][uU][tT][oO][iI][tT]\d{1,3}\.[eE][xX][eE]/
----------------------------------

