[[roshal-archive-rar-or-powershell-file-downloaded-from-the-internet]]
=== Roshal Archive (RAR) or PowerShell File Downloaded from the Internet

Detects a Roshal Archive (RAR) file or PowerShell script downloaded from the internet by an internal host. Gaining initial access to a system and then downloading encoded or encrypted tools to move laterally is a common practice for adversaries as a way to protect their more valuable tools and tactics, techniques, and procedures (TTPs). This may be atypical behavior for a managed network and can be indicative of malware, exfiltration, or command and control.

*Rule type*: query

<<<<<<< HEAD
*Rule indices*: 

* packetbeat-*
* auditbeat-*
* filebeat-*
* logs-network_traffic.*
* logs-panw.panos*
=======
*Rule indices*:

* auditbeat-*
* filebeat-*
* packetbeat-*
* logs-endpoint.events.*
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Severity*: medium

*Risk score*: 47

<<<<<<< HEAD
*Runs every*: 5m
=======
*Runs every*: 5 minutes
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

<<<<<<< HEAD
*References*: 
=======
*References*:
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

* https://www.fireeye.com/blog/threat-research/2017/04/fin7-phishing-lnk.html
* https://www.justice.gov/opa/press-release/file/1084361/download
* https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml

<<<<<<< HEAD
*Tags*: 

* Use Case: Threat Detection
* Tactic: Command and Control
* Domain: Endpoint
* Data Source: PAN-OS

*Version*: 104

*Rule authors*: 

* Elastic

*Rule license*: Elastic License v2

=======
*Tags*:

* Elastic
* Network
* Threat Detection
* Command and Control
* Host

*Version*: 100 (<<roshal-archive-rar-or-powershell-file-downloaded-from-the-internet-history, version history>>)

*Added ({stack} release)*: 7.10.0

*Last modified ({stack} release)*: 8.5.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Potential false positives

Downloading RAR or PowerShell files from the Internet may be expected for certain systems. This rule should be tailored to either exclude systems as sources or destinations in which this behavior is expected.
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

==== Investigation guide


<<<<<<< HEAD

*Threat intel*


This activity has been observed in FIN7 campaigns.
=======
[source,markdown]
----------------------------------
## Threat intel

This activity has been observed in FIN7 campaigns.
----------------------------------

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

==== Rule query


<<<<<<< HEAD
[source, js]
----------------------------------
(event.dataset: (network_traffic.http or network_traffic.tls) or
  (event.category: (network or network_traffic) and network.protocol: http)) and
  (url.extension:(ps1 or rar) or url.path:(*.ps1 or *.rar)) and
    not destination.ip:(
      10.0.0.0/8 or
      127.0.0.0/8 or
      169.254.0.0/16 or
      172.16.0.0/12 or
      192.0.0.0/24 or
      192.0.0.0/29 or
      192.0.0.8/32 or
      192.0.0.9/32 or
      192.0.0.10/32 or
      192.0.0.170/32 or
      192.0.0.171/32 or
      192.0.2.0/24 or
      192.31.196.0/24 or
      192.52.193.0/24 or
      192.168.0.0/16 or
      192.88.99.0/24 or
      224.0.0.0/4 or
      100.64.0.0/10 or
      192.175.48.0/24 or
      198.18.0.0/15 or
      198.51.100.0/24 or
      203.0.113.0/24 or
      240.0.0.0/4 or
      "::1" or
      "FE80::/10" or
      "FF00::/8"
    ) and
    source.ip:(
      10.0.0.0/8 or
      172.16.0.0/12 or
      192.168.0.0/16
    )

----------------------------------
=======
[source,js]
----------------------------------
event.category:(network or network_traffic) and network.protocol:http
and (url.extension:(ps1 or rar) or url.path:(*.ps1 or *.rar)) and
not destination.ip:( 10.0.0.0/8 or 127.0.0.0/8 or
169.254.0.0/16 or 172.16.0.0/12 or 192.0.0.0/24 or
192.0.0.0/29 or 192.0.0.8/32 or 192.0.0.9/32 or
192.0.0.10/32 or 192.0.0.170/32 or 192.0.0.171/32 or
192.0.2.0/24 or 192.31.196.0/24 or 192.52.193.0/24 or
192.168.0.0/16 or 192.88.99.0/24 or 224.0.0.0/4 or
100.64.0.0/10 or 192.175.48.0/24 or 198.18.0.0/15 or
198.51.100.0/24 or 203.0.113.0/24 or 240.0.0.0/4 or
"::1" or "FE80::/10" or "FF00::/8" ) and
source.ip:( 10.0.0.0/8 or 172.16.0.0/12 or
192.168.0.0/16 )
----------------------------------

==== Threat mapping
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Command and Control
** ID: TA0011
** Reference URL: https://attack.mitre.org/tactics/TA0011/
* Technique:
** Name: Ingress Tool Transfer
** ID: T1105
** Reference URL: https://attack.mitre.org/techniques/T1105/
<<<<<<< HEAD
=======

[[roshal-archive-rar-or-powershell-file-downloaded-from-the-internet-history]]
==== Rule version history

Version 100 (8.5.0 release)::
* Formatting only

Version 10 (8.4.0 release)::
* Formatting only

Version 9 (8.0.0 release)::
* Formatting only

Version 8 (7.16.0 release)::
* Formatting only

Version 7 (7.15.0 release)::
* Formatting only

Version 6 (7.14.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.category:(network OR network_traffic) AND network.protocol:http
AND url.path:/.*(rar|ps1)/ AND source.ip:(10.0.0.0\/8 OR
172.16.0.0\/12 OR 192.168.0.0\/16)
----------------------------------

Version 4 (7.13.0 release)::
* Formatting only

Version 3 (7.12.0 release)::
* Formatting only

Version 2 (7.11.2 release)::
* Formatting only

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))
