[[spike-in-network-traffic]]
=== Spike in Network Traffic

A machine learning job detected an unusually large spike in network traffic. Such a burst of traffic, if not caused by a surge in business activity, can be due to suspicious or malicious activity. Large-scale data exfiltration may produce a burst of network traffic; this could also be due to unusually large amounts of reconnaissance or enumeration traffic. Denial-of-service attacks or traffic floods may also produce such a surge in traffic.

*Rule type*: machine_learning

*Machine learning job*: high_count_network_events

*Machine learning anomaly threshold*: 75


*Severity*: low

*Risk score*: 21

*Runs every*: 15 minutes

*Searches indices from*: now-30m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*:

* https://www.elastic.co/guide/en/security/current/prebuilt-ml-jobs.html

*Tags*:

* Elastic
* Network
* Threat Detection
* ML

*Version*: 100 (<<spike-in-network-traffic-history, version history>>)

*Added ({stack} release)*: 7.13.0

*Last modified ({stack} release)*: 8.5.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Potential false positives

Business workflows that occur very occasionally, and involve an unusual surge in network traffic, can trigger this alert. A new business workflow or a surge in business activity may trigger this alert. A misconfigured network application or firewall may trigger this alert.

[[spike-in-network-traffic-history]]
==== Rule version history

Version 100 (8.5.0 release)::
* Formatting only

Version 3 (7.15.0 release)::
* Formatting only

Version 2 (7.14.0 release)::
* Formatting only

