[[sublime-plugin-or-application-script-modification]]
=== Sublime Plugin or Application Script Modification

Adversaries may create or modify the Sublime application plugins or scripts to execute a malicious payload each time the Sublime application is started.

*Rule type*: eql

*Rule indices*:

* auditbeat-*
* logs-endpoint.events.*

*Severity*: low

*Risk score*: 21

*Runs every*: 5 minutes

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*:

* https://posts.specterops.io/persistent-jxa-66e1c3cd1cf5

*Tags*:

* Elastic
* Host
* macOS
* Threat Detection
* Persistence

*Version*: 100 (<<sublime-plugin-or-application-script-modification-history, version history>>)

*Added ({stack} release)*: 7.12.0

*Last modified ({stack} release)*: 8.5.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Investigation guide


[source,markdown]
----------------------------------

----------------------------------


==== Rule query


[source,js]
----------------------------------
file where event.type in ("change", "creation") and file.extension :
"py" and file.path : ( "/Users/*/Library/Application
Support/Sublime Text*/Packages/*.py", "/Applications/Sublime
Text.app/Contents/MacOS/sublime.py" ) and not process.executable
: ( "/Applications/Sublime Text*.app/Contents/*",
"/usr/local/Cellar/git/*/bin/git",
"/Library/Developer/CommandLineTools/usr/bin/git",
"/usr/libexec/xpcproxy", "/System/Library/PrivateFrameworks/Desk
topServicesPriv.framework/Versions/A/Resources/DesktopServicesHelper"
)
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Persistence
** ID: TA0003
** Reference URL: https://attack.mitre.org/tactics/TA0003/
* Technique:
** Name: Compromise Client Software Binary
** ID: T1554
** Reference URL: https://attack.mitre.org/techniques/T1554/

[[sublime-plugin-or-application-script-modification-history]]
==== Rule version history

Version 100 (8.5.0 release)::
* Formatting only

Version 4 (8.4.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
file where event.type in ("change", "creation") and file.extension :
"py" and file.path : ( "/Users/*/Library/Application
Support/Sublime Text*/Packages/*.py", "/Applications/Sublime
Text.app/Contents/MacOS/sublime.py" ) and not process.executable
: ( "/Applications/Sublime Text*.app/Contents/MacOS/Sublime
Text*", "/usr/local/Cellar/git/*/bin/git",
"/usr/libexec/xpcproxy", "/System/Library/PrivateFrameworks/Des
ktopServicesPriv.framework/Versions/A/Resources/DesktopServicesHelper"
, "/Applications/Sublime Text.app/Contents/MacOS/plugin_host"
)
----------------------------------

Version 2 (8.2.0 release)::
* Formatting only

