[[suspicious-process-creation-calltrace]]
=== Suspicious Process Creation CallTrace

Identifies when a process is created and immediately accessed from an unknown memory code region and by the same parent process. This may indicate a code injection or hollowing attempt.

*Rule type*: eql

*Rule indices*:

* winlogbeat-*
* logs-windows.*

*Severity*: medium

*Risk score*: 43

*Runs every*: 5 minutes

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*Tags*:

* Elastic
* Host
* Windows
* Threat Detection
* Defense Evasion

*Version*: 2 (<<suspicious-process-creation-calltrace-history, version history>>)

*Added ({stack} release)*: 8.0.0

*Last modified ({stack} release)*: 8.2.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Rule query


[source,js]
----------------------------------
sequence by host.id with maxspan=1m [process where event.code == "1"
and /* sysmon process creation */ process.parent.name :
("winword.exe", "excel.exe", "outlook.exe", "powerpnt.exe",
"eqnedt32.exe", "fltldr.exe", "mspub.exe",
"msaccess.exe", "powershell.exe", "pwsh.exe",
"cscript.exe", "wscript.exe", "rundll32.exe", "regsvr32.exe",
"mshta.exe", "wmic.exe", "cmstp.exe",
"msxsl.exe")] by process.parent.entity_id, process.entity_id
[process where event.code == "10" and /* Sysmon process access
event from unknown module */ winlog.event_data.CallTrace :
"*UNKNOWN*"] by process.entity_id, winlog.event_data.TargetProcessGUID
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Defense Evasion
** ID: TA0005
** Reference URL: https://attack.mitre.org/tactics/TA0005/
* Technique:
** Name: Process Injection
** ID: T1055
** Reference URL: https://attack.mitre.org/techniques/T1055/

[[suspicious-process-creation-calltrace-history]]
==== Rule version history

Version 2 (8.2.0 release)::
* Formatting only

