[[suspicious-child-process-of-adobe-acrobat-reader-update-service]]
=== Suspicious Child Process of Adobe Acrobat Reader Update Service

Detects attempts to exploit privilege escalation vulnerabilities related to the Adobe Acrobat Reader PrivilegedHelperTool responsible for installing updates. For more information, refer to CVE-2020-9615, CVE-2020-9614 and CVE-2020-9613 and verify that the impacted system is patched.

*Rule type*: query

*Rule indices*:

* auditbeat-*
* logs-endpoint.events.*

*Severity*: high

*Risk score*: 73

*Runs every*: 5 minutes

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*:

* https://rekken.github.io/2020/05/14/Security-Flaws-in-Adobe-Acrobat-Reader-Allow-Malicious-Program-to-Gain-Root-on-macOS-Silently/

*Tags*:

* Elastic
* Host
* macOS
* Threat Detection
* Privilege Escalation
* CVE-2020-9615
* CVE-2020-9614
* CVE-2020-9613

*Version*: 100 (<<suspicious-child-process-of-adobe-acrobat-reader-update-service-history, version history>>)

*Added ({stack} release)*: 7.12.0

*Last modified ({stack} release)*: 8.5.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Potential false positives

Trusted system or Adobe Acrobat Related processes.

==== Rule query


[source,js]
----------------------------------
event.category:process and event.type:(start or process_started) and
process.parent.name:com.adobe.ARMDC.SMJobBlessHelper and
user.name:root and not process.executable:
(/Library/PrivilegedHelperTools/com.adobe.ARMDC.SMJobBlessHelper or
/usr/bin/codesign or
/private/var/folders/zz/*/T/download/ARMDCHammer or
/usr/sbin/pkgutil or /usr/bin/shasum or
/usr/bin/perl* or /usr/sbin/spctl or
/usr/sbin/installer or /usr/bin/csrutil)
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Privilege Escalation
** ID: TA0004
** Reference URL: https://attack.mitre.org/tactics/TA0004/
* Technique:
** Name: Exploitation for Privilege Escalation
** ID: T1068
** Reference URL: https://attack.mitre.org/techniques/T1068/

[[suspicious-child-process-of-adobe-acrobat-reader-update-service-history]]
==== Rule version history

Version 100 (8.5.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.category:process and event.type:(start or process_started) and
process.parent.name:com.adobe.ARMDC.SMJobBlessHelper and
user.name:root and not process.executable:
(/Library/PrivilegedHelperTools/com.adobe.ARMDC.SMJobBlessHelper or
/usr/bin/codesign or
/private/var/folders/zz/*/T/download/ARMDCHammer or
/usr/sbin/pkgutil or /usr/bin/shasum or
/usr/bin/perl* or /usr/sbin/spctl or
/usr/sbin/installer)
----------------------------------

Version 2 (8.4.0 release)::
* Formatting only

