[[suspicious-pdf-reader-child-process]]
=== Suspicious PDF Reader Child Process

Identifies suspicious child processes of PDF reader applications. These child processes are often launched via exploitation of PDF applications or social engineering.

*Rule type*: eql

*Rule indices*:

* winlogbeat-*
* logs-endpoint.events.*
* logs-windows.*
* endgame-*

*Severity*: low

*Risk score*: 21

*Runs every*: 5 minutes

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*Tags*:

* Elastic
* Host
* Windows
* Threat Detection
* Execution
* Investigation Guide
* Elastic Endgame

*Version*: 102 (<<suspicious-pdf-reader-child-process-history, version history>>)

*Added ({stack} release)*: 7.7.0

*Last modified ({stack} release)*: 8.6.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Investigation guide


[source,markdown]
----------------------------------
## Triage and analysis

### Investigating Suspicious PDF Reader Child Process

PDF is a common file type used in corporate environments and most machines have software to handle these files. This
creates a vector where attackers can exploit the engines and technology behind this class of software for initial access
or privilege escalation.

This rule looks for commonly abused built-in utilities spawned by a PDF reader process, which is likely a malicious behavior.

#### Possible investigation steps

- Investigate the process execution chain (parent process tree) for unknown processes. Examine their executable files
for prevalence, whether they are located in expected locations, and if they are signed with valid digital signatures.
- Investigate other alerts associated with the user/host during the past 48 hours.
- Retrieve PDF documents received and opened by the user that could cause this behavior. Common locations include, but
are not limited to, the Downloads and Document folders and the folder configured at the email client.
- Determine if the collected files are malicious:
  - Use a private sandboxed malware analysis system to perform analysis.
    - Observe and collect information about the following activities:
      - Attempts to contact external domains and addresses.
      - File and registry access, modification, and creation activities.
      - Service creation and launch activities.
      - Scheduled task creation.
  - Use the PowerShell `Get-FileHash` cmdlet to get the files' SHA-256 hash values.
    - Search for the existence and reputation of the hashes in resources like VirusTotal, Hybrid-Analysis, CISCO Talos, Any.run, etc.


### False positive analysis

- This activity is unlikely to happen legitimately. Benign true positives (B-TPs) can be added as exceptions if necessary.

### Response and remediation

- Initiate the incident response process based on the outcome of the triage.
- Isolate the involved host to prevent further post-compromise behavior.
- Investigate credential exposure on systems compromised or used by the attacker to ensure all compromised accounts are
identified. Reset passwords for these accounts and other potentially compromised credentials, such as email, business
systems, and web services.
- If the triage identified malware, search the environment for additional compromised hosts.
  - Implement temporary network rules, procedures, and segmentation to contain the malware.
  - Stop suspicious processes.
  - Immediately block the identified indicators of compromise (IoCs).
  - Inspect the affected systems for additional malware backdoors like reverse shells, reverse proxies, or droppers that
  attackers could use to reinfect the system.
- Remove and block malicious artifacts identified during triage.
- Run a full scan using the antimalware tool in place. This scan can reveal additional artifacts left in the system,
persistence mechanisms, and malware components.
- Determine the initial vector abused by the attacker and take action to prevent reinfection through the same vector.
  - If the malicious file was delivered via phishing:
    - Block the email sender from sending future emails.
    - Block the malicious web pages.
    - Remove emails from the sender from mailboxes.
    - Consider improvements to the security awareness program.
- Using the incident response data, update logging and audit policies to improve the mean time to detect (MTTD) and the
mean time to respond (MTTR).
----------------------------------


==== Rule query


[source,js]
----------------------------------
process where event.type == "start" and process.parent.name :
("AcroRd32.exe", "Acrobat.exe",
"FoxitPhantomPDF.exe", "FoxitReader.exe") and
process.name : ("arp.exe", "dsquery.exe", "dsget.exe", "gpresult.exe",
"hostname.exe", "ipconfig.exe", "nbtstat.exe",
"net.exe", "net1.exe", "netsh.exe", "netstat.exe", "nltest.exe",
"ping.exe", "qprocess.exe", "quser.exe",
"qwinsta.exe", "reg.exe", "sc.exe", "systeminfo.exe", "tasklist.exe",
"tracert.exe", "whoami.exe", "bginfo.exe",
"cdb.exe", "cmstp.exe", "csi.exe", "dnx.exe", "fsi.exe", "ieexec.exe",
"iexpress.exe", "installutil.exe", "Microsoft.Workflow.Compiler.exe",
"msbuild.exe", "mshta.exe", "msxsl.exe",
"odbcconf.exe", "rcsi.exe", "regsvr32.exe", "xwizard.exe",
"atbroker.exe", "forfiles.exe", "schtasks.exe",
"regasm.exe", "regsvcs.exe", "cmd.exe", "cscript.exe",
"powershell.exe", "pwsh.exe", "wmic.exe", "wscript.exe",
"bitsadmin.exe", "certutil.exe", "ftp.exe")
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Execution
** ID: TA0002
** Reference URL: https://attack.mitre.org/tactics/TA0002/
* Technique:
** Name: User Execution
** ID: T1204
** Reference URL: https://attack.mitre.org/techniques/T1204/

[[suspicious-pdf-reader-child-process-history]]
==== Rule version history

Version 102 (8.6.0 release)::
* Formatting only

Version 101 (8.5.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
process where event.type in ("start", "process_started") and
process.parent.name : ("AcroRd32.exe",
"Acrobat.exe", "FoxitPhantomPDF.exe",
"FoxitReader.exe") and process.name : ("arp.exe", "dsquery.exe",
"dsget.exe", "gpresult.exe", "hostname.exe", "ipconfig.exe",
"nbtstat.exe", "net.exe", "net1.exe", "netsh.exe",
"netstat.exe", "nltest.exe", "ping.exe", "qprocess.exe",
"quser.exe", "qwinsta.exe", "reg.exe", "sc.exe", "systeminfo.exe",
"tasklist.exe", "tracert.exe", "whoami.exe",
"bginfo.exe", "cdb.exe", "cmstp.exe", "csi.exe", "dnx.exe", "fsi.exe",
"ieexec.exe", "iexpress.exe", "installutil.exe",
"Microsoft.Workflow.Compiler.exe", "msbuild.exe", "mshta.exe",
"msxsl.exe", "odbcconf.exe", "rcsi.exe", "regsvr32.exe",
"xwizard.exe", "atbroker.exe", "forfiles.exe",
"schtasks.exe", "regasm.exe", "regsvcs.exe", "cmd.exe", "cscript.exe",
"powershell.exe", "pwsh.exe", "wmic.exe", "wscript.exe",
"bitsadmin.exe", "certutil.exe", "ftp.exe")
----------------------------------

Version 11 (8.4.0 release)::
* Formatting only

Version 9 (8.3.0 release)::
* Formatting only

Version 8 (8.2.0 release)::
* Formatting only

Version 7 (7.13.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.category:process and event.type:(start or process_started) and
process.parent.name:(AcroRd32.exe or Acrobat.exe or
FoxitPhantomPDF.exe or FoxitReader.exe) and process.name:(arp.exe or
dsquery.exe or dsget.exe or gpresult.exe or hostname.exe or
ipconfig.exe or nbtstat.exe or net.exe or net1.exe or netsh.exe or
netstat.exe or nltest.exe or ping.exe or qprocess.exe or quser.exe or
qwinsta.exe or reg.exe or sc.exe or systeminfo.exe or tasklist.exe or
tracert.exe or whoami.exe or bginfo.exe or cdb.exe or cmstp.exe or
csi.exe or dnx.exe or fsi.exe or ieexec.exe or iexpress.exe or
installutil.exe or Microsoft.Workflow.Compiler.exe or msbuild.exe or
mshta.exe or msxsl.exe or odbcconf.exe or rcsi.exe or regsvr32.exe or
xwizard.exe or atbroker.exe or forfiles.exe or schtasks.exe or
regasm.exe or regsvcs.exe or cmd.exe or cscript.exe or powershell.exe
or pwsh.exe or wmic.exe or wscript.exe or bitsadmin.exe or
certutil.exe or ftp.exe)
----------------------------------

Version 6 (7.12.0 release)::
* Formatting only

Version 5 (7.11.2 release)::
* Formatting only

Version 4 (7.10.0 release)::
* Formatting only

Version 3 (7.9.1 release)::
* Formatting only

Version 2 (7.9.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.action:"Process Create (rule: ProcessCreate)" and
process.parent.name:(AcroRd32.exe or Acrobat.exe or
FoxitPhantomPDF.exe or FoxitReader.exe) and process.name:(arp.exe or
dsquery.exe or dsget.exe or gpresult.exe or hostname.exe or
ipconfig.exe or nbtstat.exe or net.exe or net1.exe or netsh.exe or
netstat.exe or nltest.exe or ping.exe or qprocess.exe or quser.exe or
qwinsta.exe or reg.exe or sc.exe or systeminfo.exe or tasklist.exe or
tracert.exe or whoami.exe or bginfo.exe or cdb.exe or cmstp.exe or
csi.exe or dnx.exe or fsi.exe or ieexec.exe or iexpress.exe or
installutil.exe or Microsoft.Workflow.Compiler.exe or msbuild.exe or
mshta.exe or msxsl.exe or odbcconf.exe or rcsi.exe or regsvr32.exe or
xwizard.exe or atbroker.exe or forfiles.exe or schtasks.exe or
regasm.exe or regsvcs.exe or cmd.exe or cscript.exe or powershell.exe
or pwsh.exe or wmic.exe or wscript.exe or bitsadmin.exe or
certutil.exe or ftp.exe)
----------------------------------

