[[suspicious-pdf-reader-child-process]]
=== Suspicious PDF Reader Child Process

Identifies suspicious child processes of PDF reader applications. These child processes are often launched via exploitation of PDF applications or social engineering.

*Rule type*: eql

*Rule indices*:

* winlogbeat-*
* logs-endpoint.events.*
* logs-windows.*

*Severity*: low

*Risk score*: 21

*Runs every*: 5 minutes

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*Tags*:

* Elastic
* Host
* Windows
* Threat Detection
* Execution

*Version*: 7 (<<suspicious-pdf-reader-child-process-history, version history>>)

*Added ({stack} release)*: 7.7.0

*Last modified ({stack} release)*: 7.13.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Rule query


[source,js]
----------------------------------
process where event.type in ("start", "process_started") and
process.parent.name : ("AcroRd32.exe",
"Acrobat.exe", "FoxitPhantomPDF.exe",
"FoxitReader.exe") and process.name : ("arp.exe", "dsquery.exe",
"dsget.exe", "gpresult.exe", "hostname.exe", "ipconfig.exe",
"nbtstat.exe", "net.exe", "net1.exe", "netsh.exe",
"netstat.exe", "nltest.exe", "ping.exe", "qprocess.exe",
"quser.exe", "qwinsta.exe", "reg.exe", "sc.exe", "systeminfo.exe",
"tasklist.exe", "tracert.exe", "whoami.exe",
"bginfo.exe", "cdb.exe", "cmstp.exe", "csi.exe", "dnx.exe", "fsi.exe",
"ieexec.exe", "iexpress.exe", "installutil.exe",
"Microsoft.Workflow.Compiler.exe", "msbuild.exe", "mshta.exe",
"msxsl.exe", "odbcconf.exe", "rcsi.exe", "regsvr32.exe",
"xwizard.exe", "atbroker.exe", "forfiles.exe",
"schtasks.exe", "regasm.exe", "regsvcs.exe", "cmd.exe", "cscript.exe",
"powershell.exe", "pwsh.exe", "wmic.exe", "wscript.exe",
"bitsadmin.exe", "certutil.exe", "ftp.exe")
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Execution
** ID: TA0002
** Reference URL: https://attack.mitre.org/tactics/TA0002/
* Technique:
** Name: User Execution
** ID: T1204
** Reference URL: https://attack.mitre.org/techniques/T1204/

[[suspicious-pdf-reader-child-process-history]]
==== Rule version history

Version 7 (7.13.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.category:process and event.type:(start or process_started) and
process.parent.name:(AcroRd32.exe or Acrobat.exe or
FoxitPhantomPDF.exe or FoxitReader.exe) and process.name:(arp.exe or
dsquery.exe or dsget.exe or gpresult.exe or hostname.exe or
ipconfig.exe or nbtstat.exe or net.exe or net1.exe or netsh.exe or
netstat.exe or nltest.exe or ping.exe or qprocess.exe or quser.exe or
qwinsta.exe or reg.exe or sc.exe or systeminfo.exe or tasklist.exe or
tracert.exe or whoami.exe or bginfo.exe or cdb.exe or cmstp.exe or
csi.exe or dnx.exe or fsi.exe or ieexec.exe or iexpress.exe or
installutil.exe or Microsoft.Workflow.Compiler.exe or msbuild.exe or
mshta.exe or msxsl.exe or odbcconf.exe or rcsi.exe or regsvr32.exe or
xwizard.exe or atbroker.exe or forfiles.exe or schtasks.exe or
regasm.exe or regsvcs.exe or cmd.exe or cscript.exe or powershell.exe
or pwsh.exe or wmic.exe or wscript.exe or bitsadmin.exe or
certutil.exe or ftp.exe)
----------------------------------

Version 6 (7.12.0 release)::
* Formatting only

Version 5 (7.11.2 release)::
* Formatting only

Version 4 (7.10.0 release)::
* Formatting only

Version 3 (7.9.1 release)::
* Formatting only

Version 2 (7.9.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
event.action:"Process Create (rule: ProcessCreate)" and
process.parent.name:(AcroRd32.exe or Acrobat.exe or
FoxitPhantomPDF.exe or FoxitReader.exe) and process.name:(arp.exe or
dsquery.exe or dsget.exe or gpresult.exe or hostname.exe or
ipconfig.exe or nbtstat.exe or net.exe or net1.exe or netsh.exe or
netstat.exe or nltest.exe or ping.exe or qprocess.exe or quser.exe or
qwinsta.exe or reg.exe or sc.exe or systeminfo.exe or tasklist.exe or
tracert.exe or whoami.exe or bginfo.exe or cdb.exe or cmstp.exe or
csi.exe or dnx.exe or fsi.exe or ieexec.exe or iexpress.exe or
installutil.exe or Microsoft.Workflow.Compiler.exe or msbuild.exe or
mshta.exe or msxsl.exe or odbcconf.exe or rcsi.exe or regsvr32.exe or
xwizard.exe or atbroker.exe or forfiles.exe or schtasks.exe or
regasm.exe or regsvcs.exe or cmd.exe or cscript.exe or powershell.exe
or pwsh.exe or wmic.exe or wscript.exe or bitsadmin.exe or
certutil.exe or ftp.exe)
----------------------------------

