[[suspicious-image-load-taskschd.dll-from-ms-office]]
=== Suspicious Image Load (taskschd.dll) from MS Office

Identifies a suspicious image load (taskschd.dll) from Microsoft Office processes. This behavior may indicate adversarial activity where a scheduled task is configured via Windows Component Object Model (COM). This technique can be used to configure persistence and evade monitoring by avoiding the usage of the traditional Windows binary (schtasks.exe) used to manage scheduled tasks.

*Rule type*: eql

*Rule indices*:

* winlogbeat-*
* logs-endpoint.events.*
* logs-windows.*

*Severity*: low

*Risk score*: 21

*Runs every*: 5 minutes

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*:

* https://medium.com/threatpunter/detecting-adversary-tradecraft-with-image-load-event-logging-and-eql-8de93338c16
* https://www.clearskysec.com/wp-content/uploads/2020/10/Operation-Quicksand.pdf

*Tags*:

* Elastic
* Host
* Windows
* Threat Detection
* Persistence

*Version*: 100 (<<suspicious-image-load-taskschd.dll-from-ms-office-history, version history>>)

*Added ({stack} release)*: 7.11.0

*Last modified ({stack} release)*: 8.5.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Investigation guide


[source,markdown]
----------------------------------

----------------------------------


==== Rule query


[source,js]
----------------------------------
any where (event.category == "library" or (event.category ==
"process" and event.action : "Image loaded*")) and process.name :
("WINWORD.EXE", "EXCEL.EXE", "POWERPNT.EXE", "MSPUB.EXE",
"MSACCESS.EXE") and (dll.name : "taskschd.dll" or file.name :
"taskschd.dll")
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Persistence
** ID: TA0003
** Reference URL: https://attack.mitre.org/tactics/TA0003/
* Technique:
** Name: Scheduled Task/Job
** ID: T1053
** Reference URL: https://attack.mitre.org/techniques/T1053/

[[suspicious-image-load-taskschd.dll-from-ms-office-history]]
==== Rule version history

Version 100 (8.5.0 release)::
* Formatting only

Version 6 (8.4.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
library where process.name : ("WINWORD.EXE", "EXCEL.EXE",
"POWERPNT.EXE", "MSPUB.EXE", "MSACCESS.EXE") and event.action :
"load" and event.category : "library" and dll.name :
"taskschd.dll"
----------------------------------

Version 4 (8.2.0 release)::
* Formatting only

Version 3 (7.12.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
library where process.name in ("WINWORD.EXE", "EXCEL.EXE",
"POWERPNT.EXE", "MSPUB.EXE", "MSACCESS.EXE") and event.action ==
"load" and event.category == "library" and file.name ==
"taskschd.dll"
----------------------------------

Version 2 (7.11.2 release)::
* Formatting only

