[[suspicious-wmi-image-load-from-ms-office]]
=== Suspicious WMI Image Load from MS Office

Identifies a suspicious image load (wmiutils.dll) from Microsoft Office processes. This behavior may indicate adversarial activity where child processes are spawned via Windows Management Instrumentation (WMI). This technique can be used to execute code and evade traditional parent/child processes spawned from Microsoft Office products.

*Rule type*: eql

<<<<<<< HEAD
*Rule indices*: 

* winlogbeat-*
* logs-endpoint.events.library-*
* logs-windows.sysmon_operational-*
=======
*Rule indices*:

* winlogbeat-*
* logs-endpoint.events.*
* logs-windows.*
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))
* endgame-*

*Severity*: low

*Risk score*: 21

<<<<<<< HEAD
*Runs every*: 5m
=======
*Runs every*: 5 minutes
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

<<<<<<< HEAD
*References*: 

* https://medium.com/threatpunter/detecting-adversary-tradecraft-with-image-load-event-logging-and-eql-8de93338c16

*Tags*: 

* Domain: Endpoint
* OS: Windows
* Use Case: Threat Detection
* Tactic: Execution
* Data Source: Elastic Endgame
* Data Source: Elastic Defend
* Data Source: Sysmon

*Version*: 208

*Rule authors*: 

* Elastic

*Rule license*: Elastic License v2


==== Setup



*Setup*


If enabling an EQL rule on a non-elastic-agent index (such as beats) for versions <8.2,
events will not define `event.ingested` and default fallback for EQL rules was not added until version 8.2.
Hence for this rule to work effectively, users will need to add a custom ingest pipeline to populate
`event.ingested` to @timestamp.
For more details on adding a custom ingest pipeline refer - https://www.elastic.co/guide/en/fleet/current/data-streams-pipeline-tutorial.html
=======
*References*:

* https://medium.com/threatpunter/detecting-adversary-tradecraft-with-image-load-event-logging-and-eql-8de93338c16

*Tags*:

* Elastic
* Host
* Windows
* Threat Detection
* Execution
* Elastic Endgame

*Version*: 101 (<<suspicious-wmi-image-load-from-ms-office-history, version history>>)

*Added ({stack} release)*: 7.11.0

*Last modified ({stack} release)*: 8.6.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Investigation guide


[source,markdown]
----------------------------------

----------------------------------
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))


==== Rule query


<<<<<<< HEAD
[source, js]
----------------------------------
any where host.os.type == "windows" and
 (event.category : ("library", "driver") or (event.category == "process" and event.action : "Image loaded*")) and
  process.name : ("WINWORD.EXE", "EXCEL.EXE", "POWERPNT.EXE", "MSPUB.EXE", "MSACCESS.EXE") and
  (?dll.name : "wmiutils.dll" or file.name : "wmiutils.dll")

----------------------------------
=======
[source,js]
----------------------------------
any where (event.category : ("library", "driver") or (event.category
== "process" and event.action : "Image loaded*")) and process.name :
("WINWORD.EXE", "EXCEL.EXE", "POWERPNT.EXE", "MSPUB.EXE",
"MSACCESS.EXE") and (dll.name : "wmiutils.dll" or file.name :
"wmiutils.dll")
----------------------------------

==== Threat mapping
>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Execution
** ID: TA0002
** Reference URL: https://attack.mitre.org/tactics/TA0002/
* Technique:
** Name: Windows Management Instrumentation
** ID: T1047
** Reference URL: https://attack.mitre.org/techniques/T1047/
<<<<<<< HEAD
=======

[[suspicious-wmi-image-load-from-ms-office-history]]
==== Rule version history

Version 101 (8.6.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
any where (event.category == "library" or (event.category ==
"process" and event.action : "Image loaded*")) and process.name :
("WINWORD.EXE", "EXCEL.EXE", "POWERPNT.EXE", "MSPUB.EXE",
"MSACCESS.EXE") and (dll.name : "wmiutils.dll" or file.name :
"wmiutils.dll")
----------------------------------

Version 100 (8.5.0 release)::
* Formatting only

Version 7 (8.4.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
library where process.name : ("WINWORD.EXE", "EXCEL.EXE",
"POWERPNT.EXE", "MSPUB.EXE", "MSACCESS.EXE") and event.action :
"load" and event.category : "library" and dll.name :
"wmiutils.dll"
----------------------------------

Version 5 (8.2.0 release)::
* Formatting only

Version 4 (7.15.0 release)::
* Formatting only

Version 3 (7.12.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
library where process.name in ("WINWORD.EXE", "EXCEL.EXE",
"POWERPNT.EXE", "MSPUB.EXE", "MSACCESS.EXE") and event.action ==
"load" and event.category == "library" and file.name ==
"wmiutils.dll"
----------------------------------

Version 2 (7.11.2 release)::
* Formatting only

>>>>>>> 7c79a644 (8.17.0 Release notes  (#6224))
