[[unusual-child-process-of-dns.exe]]
=== Unusual Child Process of dns.exe

Identifies an unexpected process spawning from dns.exe, the process responsible for Windows DNS server services, which may indicate activity related to remote code execution or other forms of exploitation.

*Rule type*: query

*Rule indices*:

* winlogbeat-*
* logs-endpoint.events.*

*Severity*: high

*Risk score*: 73

*Runs every*: 5 minutes

*Searches indices from*: now-6m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*:

* https://research.checkpoint.com/2020/resolving-your-way-into-domain-admin-exploiting-a-17-year-old-bug-in-windows-dns-servers/
* https://msrc-blog.microsoft.com/2020/07/14/july-2020-security-update-cve-2020-1350-vulnerability-in-windows-domain-name-system-dns-server/
* https://github.com/maxpl0it/CVE-2020-1350-DoS

*Tags*:

* Elastic
* Host
* Windows
* Threat Detection
* Execution

*Version*: 2 (<<unusual-child-process-of-dns.exe-history, version history>>)

*Added ({stack} release)*: 7.10.0

*Last modified ({stack} release)*: 7.11.0

*Rule authors*: Elastic

*Rule license*: Elastic License

==== Potential false positives

Werfault.exe will legitimately spawn when dns.exe crashes, but the DNS service is very stable and so this is a low occurring event. Denial of Service (DoS) attempts by intentionally crashing the service will also cause werfault.exe to spawn.

==== Investigation guide

Detection alerts from this rule indicate potential suspicious child processes
spawned after exploitation from CVE-2020-1350 (SigRed) has occurred. Here are
some possible avenues of investigation:

* Any suspicious or abnormal child process spawned from dns.exe should be reviewed and investigated with care. It's impossible to predict what an adversary may deploy as the follow-on process after the exploit, but built-in discovery/enumeration utilities should be top of mind (whoami.exe, netstat.exe, systeminfo.exe, tasklist.exe).
* Built-in Windows programs that contain capabilities used to download and execute additional payloads should also be considered. This is not an exhaustive list, but ideal candidates to start out would be: mshta.exe, powershell.exe, regsvr32.exe, rundll32.exe, wscript.exe, wmic.exe.
* If the DoS exploit is successful and DNS Server service crashes, be mindful of potential child processes related to werfault.exe occurring.
* Any subsequent activity following the child process spawned related to execution/network activity should be thoroughly reviewed from the endpoint.

==== Rule query


[source,js]
----------------------------------
event.category:process and event.type:start and
process.parent.name:dns.exe and not process.name:conhost.exe
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Initial Access
** ID: TA0001
** Reference URL: https://attack.mitre.org/tactics/TA0001/
* Technique:
** Name: External Remote Services
** ID: T1133
** Reference URL: https://attack.mitre.org/techniques/T1133/

[[unusual-child-process-of-dns.exe-history]]
==== Rule version history

Version 2 (7.11.0 release)::
* Formatting only

