[[unusual-process-execution-temp]]
=== Unusual Process Execution - Temp

Identifies processes running in a temporary folder. This is sometimes done by
adversaries to hide malware.

*Rule type*: query

*Rule indices*:

* auditbeat-*
* logs-endpoint.events.*

*Severity*: medium

*Risk score*: 47

*Runs every*: 5 minutes

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*Tags*:

* Elastic
* Host
* Linux
* Threat Detection

*Version*: 7 (<<unusual-process-execution-temp-history, version history>>)

*Added ({stack} release)*: 7.6.0

*Last modified ({stack} release)*: 7.12.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Potential false positives

Build systems, like Jenkins, may start processes in the `/tmp` directory. These can be exempted by name or by username.

==== Rule query


[source,js]
----------------------------------
event.category:process and event.type:(start or process_started) and
process.working_directory:/tmp
----------------------------------


[[unusual-process-execution-temp-history]]
==== Rule version history

Version 7 (7.12.0 release)::
* Formatting only

Version 6 (7.11.2 release)::
* Formatting only

Version 5 (7.10.0 release)::
* Formatting only

Version 4 (7.9.1 release)::
* Formatting only

Version 3 (7.9.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
process.working_directory:/tmp and event.action:executed
----------------------------------

Version 2 (7.7.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
process.working_directory: /tmp and event.action:executed
----------------------------------

