[[unusual-network-destination-domain-name]]
=== Unusual Network Destination Domain Name

A machine learning job detected an unusual network destination domain name. This can be due to initial access, persistence, command-and-control, or exfiltration activity. For example, when a user clicks on a link in a phishing email or opens a malicious document, a request may be sent to download and run a payload from an uncommon web server name. When malware is already running, it may send requests to an uncommon DNS domain the malware uses for command-and-control communication.

*Rule type*: machine_learning

*Machine learning job*: packetbeat_rare_server_domain

*Machine learning anomaly threshold*: 50


*Severity*: low

*Risk score*: 21

*Runs every*: 15 minutes

*Searches indices from*: now-45m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*:

* https://www.elastic.co/guide/en/security/current/prebuilt-ml-jobs.html

*Tags*:

* Elastic
* Network
* Threat Detection
* ML

*Version*: 100 (<<unusual-network-destination-domain-name-history, version history>>)

*Added ({stack} release)*: 7.7.0

*Last modified ({stack} release)*: 8.5.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Potential false positives

Web activity that occurs rarely in small quantities can trigger this alert. Possible examples are browsing technical support or vendor URLs that are used very sparsely. A user who visits a new and unique web destination may trigger this alert when the activity is sparse. Web applications that generate URLs unique to a transaction may trigger this when they are used sparsely. Web domains can be excluded in cases such as these.

[[unusual-network-destination-domain-name-history]]
==== Rule version history

Version 100 (8.5.0 release)::
* Formatting only

Version 4 (7.12.0 release)::
* Formatting only

Version 3 (7.10.0 release)::
* Formatting only

Version 2 (7.9.0 release)::
* Formatting only

