[[unusual-child-processes-of-rundll32]]
=== Unusual Child Processes of RunDLL32

Identifies child processes of unusual instances of RunDLL32 where the command line parameters were suspicious. Misuse of RunDLL32 could indicate malicious activity.

*Rule type*: eql

*Rule indices*:

* logs-endpoint.events.*
* winlogbeat-*
* logs-windows.*

*Severity*: high

*Risk score*: 73

*Runs every*: 30 minutes

*Searches indices from*: now-60m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*Tags*:

* Elastic
* Host
* Windows
* Threat Detection
* Defense Evasion

*Version*: 101 (<<unusual-child-processes-of-rundll32-history, version history>>)

*Added ({stack} release)*: 7.10.0

*Last modified ({stack} release)*: 8.5.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Rule query


[source,js]
----------------------------------
sequence with maxspan=1h [process where event.type == "start" and
(process.name : "rundll32.exe" or process.pe.original_file_name ==
"RUNDLL32.EXE") and process.args_count == 1 ] by
process.entity_id [process where event.type == "start" and
process.parent.name : "rundll32.exe" ] by process.parent.entity_id
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Defense Evasion
** ID: TA0005
** Reference URL: https://attack.mitre.org/tactics/TA0005/
* Technique:
** Name: System Binary Proxy Execution
** ID: T1218
** Reference URL: https://attack.mitre.org/techniques/T1218/

[[unusual-child-processes-of-rundll32-history]]
==== Rule version history

Version 101 (8.5.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
sequence with maxspan=1h [process where event.type in ("start",
"process_started") and (process.name : "rundll32.exe" or
process.pe.original_file_name == "RUNDLL32.EXE") and
process.args_count == 1 ] by process.entity_id [process where
event.type in ("start", "process_started") and process.parent.name :
"rundll32.exe" ] by process.parent.entity_id
----------------------------------

Version 6 (8.4.0 release)::
* Formatting only

Version 4 (7.14.0 release)::
* Formatting only

Version 3 (7.12.0 release)::
* Formatting only

Version 2 (7.11.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
sequence with maxspan=1h [process where event.type in ("start",
"process_started") and /*
uncomment once in winlogbeat */ (process.name : "rundll32.exe" /*
or process.pe.original_file_name == "RUNDLL32.EXE" */ ) and
process.args_count < 2 ] by process.entity_id [process where
event.type in ("start", "process_started") and process.parent.name :
"rundll32.exe" ] by process.parent.entity_id
----------------------------------

