[[virtual-machine-fingerprinting-via-grep]]
=== Virtual Machine Fingerprinting via Grep

An adversary may attempt to get detailed information about the operating system and hardware. This rule identifies common locations used to discover virtual machine hardware by a non-root user. This technique has been used by the Pupy RAT and other malware.

*Rule type*: eql

*Rule indices*:

* auditbeat-*
* logs-endpoint.events.*

*Severity*: medium

*Risk score*: 47

*Runs every*: 5 minutes

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*:

* https://objective-see.com/blog/blog_0x4F.html

*Tags*:

* Elastic
* Host
* macOS
* Linux
* Threat Detection
* Discovery

*Version*: 2 (<<virtual-machine-fingerprinting-via-grep-history, version history>>)

*Added ({stack} release)*: 7.16.0

*Last modified ({stack} release)*: 8.2.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Potential false positives

Certain tools or automated software may enumerate hardware information. These tools can be exempted via user name or process arguments to eliminate potential noise.

==== Investigation guide


[source,markdown]
----------------------------------
## Config

If enabling an EQL rule on a non-elastic-agent index (such as beats) for versions <8.2, events will not define `event.ingested` and default fallback for EQL rules was not added until 8.2, so you will need to add a custom pipeline to populate `event.ingested` to @timestamp for this rule to work.

----------------------------------


==== Rule query


[source,js]
----------------------------------
process where event.type == "start" and process.name in ("grep",
"egrep") and user.id != "0" and process.args : ("parallels*",
"vmware*", "virtualbox*") and process.args : "Manufacturer*" and not
process.parent.executable in
("/Applications/Docker.app/Contents/MacOS/Docker",
"/usr/libexec/kcare/virt-what")
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Discovery
** ID: TA0007
** Reference URL: https://attack.mitre.org/tactics/TA0007/
* Technique:
** Name: System Information Discovery
** ID: T1082
** Reference URL: https://attack.mitre.org/techniques/T1082/

[[virtual-machine-fingerprinting-via-grep-history]]
==== Rule version history

Version 2 (8.2.0 release)::
* Formatting only

