[[windows-network-enumeration]]
=== Windows Network Enumeration

Identifies attempts to enumerate hosts in a network using the built-in Windows net.exe tool.

*Rule type*: eql

*Rule indices*:

* logs-endpoint.events.*
* winlogbeat-*
* logs-windows.*

*Severity*: medium

*Risk score*: 47

*Runs every*: 5 minutes

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*Tags*:

* Elastic
* Host
* Windows
* Threat Detection
* Discovery

*Version*: 5 (<<windows-network-enumeration-history, version history>>)

*Added ({stack} release)*: 7.11.0

*Last modified ({stack} release)*: 8.2.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Investigation guide


[source,markdown]
----------------------------------
## Config

If enabling an EQL rule on a non-elastic-agent index (such as beats) for versions <8.2, events will not define `event.ingested` and default fallback for EQL rules was not added until 8.2, so you will need to add a custom pipeline to populate `event.ingested` to @timestamp for this rule to work.

----------------------------------


==== Rule query


[source,js]
----------------------------------
process where event.type in ("start", "process_started") and
((process.name : "net.exe" or process.pe.original_file_name ==
"net.exe") or ((process.name : "net1.exe" or
process.pe.original_file_name == "net1.exe") and not
process.parent.name : "net.exe")) and (process.args : "view" or
(process.args : "time" and process.args : "\\\\*")) /* expand when
ancestry is available and not descendant of [process where
event.type == ("start", "process_started") and process.name :
"cmd.exe" and ((process.parent.name :
"userinit.exe") or (process.parent.name :
"gpscript.exe") or (process.parent.name :
"explorer.exe" and process.args :
"C:\\*\\Start Menu\\Programs\\Startup\\*.bat*"))] */
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Discovery
** ID: TA0007
** Reference URL: https://attack.mitre.org/tactics/TA0007/
* Technique:
** Name: Remote System Discovery
** ID: T1018
** Reference URL: https://attack.mitre.org/techniques/T1018/

[[windows-network-enumeration-history]]
==== Rule version history

Version 5 (8.2.0 release)::
* Formatting only

Version 4 (7.15.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
process where event.type in ("start", "process_started") and
((process.name : "net.exe" or process.pe.original_file_name ==
"net.exe") or ((process.name : "net1.exe" or
process.pe.original_file_name == "net1.exe") and not
process.parent.name : "net.exe")) and (process.args : "view" or
(process.args : "time" and process.args : "\\\\*")) /* expand when
ancestory is available and not descendant of [process where
event.type == ("start", "process_started") and process.name :
"cmd.exe" and ((process.parent.name :
"userinit.exe") or (process.parent.name :
"gpscript.exe") or (process.parent.name :
"explorer.exe" and process.args :
"C:\\*\\Start Menu\\Programs\\Startup\\*.bat*"))] */
----------------------------------

Version 3 (7.12.0 release)::
* Formatting only

Version 2 (7.11.2 release)::
* Formatting only

