[[wmi-incoming-lateral-movement]]
=== WMI Incoming Lateral Movement

Identifies processes executed via Windows Management Instrumentation (WMI) on a remote host. This could be indicative of adversary lateral movement, but could be noisy if administrators use WMI to remotely manage hosts.

*Rule type*: eql

*Rule indices*:

* logs-endpoint.events.*
* winlogbeat-*
* logs-windows.*

*Severity*: medium

*Risk score*: 47

*Runs every*: 5 minutes

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*Tags*:

* Elastic
* Host
* Windows
* Threat Detection
* Lateral Movement

*Version*: 101 (<<wmi-incoming-lateral-movement-history, version history>>)

*Added ({stack} release)*: 7.11.0

*Last modified ({stack} release)*: 8.5.0

*Rule authors*: Elastic

*Rule license*: Elastic License v2

==== Rule query


[source,js]
----------------------------------
sequence by host.id with maxspan = 2s /* Accepted Incoming RPC
connection by Winmgmt service */ [network where process.name :
"svchost.exe" and network.direction : ("incoming", "ingress") and
source.ip != "127.0.0.1" and source.ip != "::1" and source.port >=
49152 and destination.port >= 49152 ] /* Excluding Common FPs
Nessus and SCCM */ [process where event.type == "start" and
process.parent.name : "WmiPrvSE.exe" and not process.args :
("C:\\windows\\temp\\nessus_*.txt",
"C:\\windows\\TEMP\\nessus_*.TMP",
"C:\\Windows\\CCM\\SystemTemp\\*",
"C:\\Windows\\CCMCache\\*",
"C:\\CCM\\Cache\\*") ]
----------------------------------

==== Threat mapping

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Lateral Movement
** ID: TA0008
** Reference URL: https://attack.mitre.org/tactics/TA0008/


* Tactic:
** Name: Execution
** ID: TA0002
** Reference URL: https://attack.mitre.org/tactics/TA0002/
* Technique:
** Name: Windows Management Instrumentation
** ID: T1047
** Reference URL: https://attack.mitre.org/techniques/T1047/

[[wmi-incoming-lateral-movement-history]]
==== Rule version history

Version 101 (8.5.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
sequence by host.id with maxspan = 2s /* Accepted Incoming RPC
connection by Winmgmt service */ [network where process.name :
"svchost.exe" and network.direction : ("incoming", "ingress") and
source.ip != "127.0.0.1" and source.ip != "::1" and source.port >=
49152 and destination.port >= 49152 ] /* Excluding Common FPs
Nessus and SCCM */ [process where event.type in ("start",
"process_started") and process.parent.name : "WmiPrvSE.exe" and not
process.args : ("C:\\windows\\temp\\nessus_*.txt",
"C:\\windows\\TEMP\\nessus_*.TMP",
"C:\\Windows\\CCM\\SystemTemp\\*",
"C:\\Windows\\CCMCache\\*",
"C:\\CCM\\Cache\\*") ]
----------------------------------

Version 5 (8.4.0 release)::
* Formatting only

Version 4 (8.0.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
sequence by host.id with maxspan = 2s /* Accepted Incoming RPC
connection by Winmgmt service */ [network where process.name :
"svchost.exe" and network.direction : ("incoming", "ingress") and
source.address != "127.0.0.1" and source.address != "::1" and
source.port >= 49152 and destination.port >= 49152 ] /* Excluding
Common FPs Nessus and SCCM */ [process where event.type in
("start", "process_started") and process.parent.name : "WmiPrvSE.exe"
and not process.args : ("C:\\windows\\temp\\nessus_*.txt",
"C:\\windows\\TEMP\\nessus_*.TMP",
"C:\\Windows\\CCM\\SystemTemp\\*",
"C:\\Windows\\CCMCache\\*",
"C:\\CCM\\Cache\\*") ]
----------------------------------

Version 3 (7.16.0 release)::
* Updated query, changed from:
+
[source, js]
----------------------------------
sequence by host.id with maxspan = 2s /* Accepted Incoming RPC
connection by Winmgmt service */ [network where process.name :
"svchost.exe" and network.direction == "incoming" and
source.address != "127.0.0.1" and source.address != "::1" and
source.port >= 49152 and destination.port >= 49152 ] /* Excluding
Common FPs Nessus and SCCM */ [process where event.type in
("start", "process_started") and process.parent.name : "WmiPrvSE.exe"
and not process.args : ("C:\\windows\\temp\\nessus_*.txt",
"C:\\windows\\TEMP\\nessus_*.TMP",
"C:\\Windows\\CCM\\SystemTemp\\*",
"C:\\Windows\\CCMCache\\*",
"C:\\CCM\\Cache\\*") ]
----------------------------------

Version 2 (7.12.0 release)::
* Formatting only

