[[prebuilt-rule-0-16-1-suspicious-startup-shell-folder-modification]]
=== Suspicious Startup Shell Folder Modification

Identifies suspicious startup shell folder modifications to change the default Startup directory in order to bypass detections monitoring file creation in the Windows Startup folder.

*Rule type*: eql

*Rule indices*: 

* logs-endpoint.events.*

*Severity*: high

*Risk score*: 73

*Runs every*: 5m

*Searches indices from*: now-9m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*: None

*Tags*: 

* Elastic
* Host
* Windows
* Threat Detection
* Persistence

*Version*: 4

*Rule authors*: 

* Elastic

*Rule license*: Elastic License v2


==== Investigation guide


[source, markdown]
----------------------------------
## Triage and analysis

### Investigating Suspicious Startup Shell Activity

Techniques used within malware and by adversaries often leverage the Windows registry to store malicious programs for
persistence. Startup shell folders are often targeted as they are not as prevalent as normal Startup folder paths so this
behavior may evade existing AV/EDR solutions. These programs may also run with higher privileges which can be ideal for
an attacker.

#### Possible investigation steps:
- Review the source process and related file tied to the Windows Registry entry
- Validate the activity is not related to planned patches, updates, network administrator activity or legitimate software
installations
- Determine if activity is unique by validating if other machines in same organization have similar entry

### False Positive Analysis
- There is a high possibility of benign legitimate programs being added to Shell folders. This activity could be based
on new software installations, patches, or any kind of network administrator related activity. Before entering further
investigation, it should be verified that this activity is not benign.

### Related Rules
- Startup or Run Key Registry Modification
- Persistent Scripts in the Startup Directory

### Response and Remediation
- Activity should first be validated as a true positive event if so then take immediate action to review,
investigate and potentially isolate activity to prevent further post-compromise behavior
- The respective binary or program tied to this persistence method should be further analyzed and reviewed to understand
its behavior and capabilities
- Since this activity is considered post-exploitation behavior, it's important to understand how the behavior was first
initialized such as through a macro-enabled document that was attached in a phishing email. By understanding the source
of the attack, this information can then be used to search for similar indicators on other machines in the same environment.

----------------------------------

==== Rule query


[source, js]
----------------------------------
registry where
 registry.path : (
     "HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\User Shell Folders\\Common Startup",
     "HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Shell Folders\\Common Startup",
     "HKEY_USERS\\*\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\User Shell Folders\\Startup",
     "HKEY_USERS\\*\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Shell Folders\\Startup"
     ) and
  registry.data.strings != null and
  /* Normal Startup Folder Paths */
  not registry.data.strings : (
           "C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Startup",
           "%ProgramData%\\Microsoft\\Windows\\Start Menu\\Programs\\Startup",
           "%USERPROFILE%\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup",
           "C:\\Users\\*\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup"
           )

----------------------------------

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Persistence
** ID: TA0003
** Reference URL: https://attack.mitre.org/tactics/TA0003/
* Technique:
** Name: Boot or Logon Autostart Execution
** ID: T1547
** Reference URL: https://attack.mitre.org/techniques/T1547/
* Sub-technique:
** Name: Registry Run Keys / Startup Folder
** ID: T1547.001
** Reference URL: https://attack.mitre.org/techniques/T1547/001/
