[[security-agentless-integrations]]
= Agentless integrations

// :description: Ingest data without deploying and managing an agent.
// :keywords: serverless, security, overview

beta:[]

Agentless integrations provide a means to ingest data while avoiding the orchestration, management, and maintenance needs associated with standard ingest infrastructure. Using agentless integrations makes manual agent deployment unnecessary, allowing you to focus on your data instead of the agent that collects it.

We currently support one agentless integration: cloud security posture management (CSPM). Using this integration's agentless deployment option, you can enable Elastic's CSPM capabilities just by providing the necessary credentials. Agentless CSPM deployments support AWS, Azure, and GCP accounts.

To learn more about agentless CSPM deployments, refer to <<security-cspm-get-started,Get started with CSPM for AWS>>, <<security-cspm-get-started-gcp,Get started with CSPM for GCP>>, or <<security-cspm-get-started-azure,Get started with CSPM for Azure>>.