[[security-ingest-data]]
= Ingest data to Elastic Security

:description: Learn how to add your own data to {elastic-sec}.
:keywords: serverless, security, how-to

++++
<titleabbrev>Ingest data</titleabbrev>
++++

preview:[]

To ingest data, you can use:

* The {fleet-guide}/fleet-overview.html[{agent}] with the **{elastic-defend}** integration, which protects
your hosts and sends logs, metrics, and endpoint security data to {elastic-sec}. See <<security-install-edr>>.
* The {agent} with other integrations, which are available in the {fleet-guide}/fleet-overview.html#package-registry-intro[Elastic Package Registry (EPR)]. To install an integration that works with {elastic-sec}, select **Add integrations** in the toolbar on most pages. On the **Integrations** page, select the **Security** category filter, then select an integration to view the installation instructions. For more information on integrations, refer to {integrations-docs}[{integrations}].
* **{beats}** shippers installed for each system you want to monitor.
* The {agent} to send data from Splunk to {elastic-sec}. See {observability-guide}/splunk-get-started.html[Get started with data from Splunk].
* Third-party collectors configured to ship ECS-compliant data. <<security-siem-field-reference>> provides a list of ECS fields used in {elastic-sec}.

[IMPORTANT]
====
If you use a third-party collector to ship data to {elastic-sec}, you must
map its fields to the {ecs-ref}[Elastic Common Schema (ECS)]. Additionally,
you must add its index to the {elastic-sec} indices (update the **`securitySolution:defaultIndex`** <<update-sec-indices,advanced setting>>).

{elastic-sec} uses the {ecs-ref}/ecs-host.html[`host.name`] ECS field as the
primary key for identifying hosts.
====

The {agent} with the
https://www.elastic.co/products/endpoint-security[{elastic-defend} integration]
ships these data sources:

* Process - Linux, macOS, Windows
* Network - Linux, macOS, Windows
* File - Linux, macOS, Windows
* DNS - Windows
* Registry - Windows
* DLL and Driver Load - Windows
* Security - Windows

[discrete]
[[install-beats]]
== Install {beats} shippers

To add hosts and populate {elastic-sec} with network security events, you need to install and
configure Beats on the hosts from which you want to ingest security events:

* https://www.elastic.co/products/beats/filebeat[{filebeat}] for forwarding and
centralizing logs and files
* https://www.elastic.co/products/beats/auditbeat[{auditbeat}] for collecting security events
* https://www.elastic.co/products/beats/winlogbeat[{winlogbeat}] for centralizing
Windows event logs
* https://www.elastic.co/products/beats/packetbeat[{packetbeat}] for analyzing
network activity

You can install {beats} using the UI guide or directly from the command line.

[discrete]
[[security-ingest-data-install-beats-using-the-ui-guide]]
=== Install {beats} using the UI guide

When you add integrations that use {beats}, you're guided through the {beats} installation process. To begin, go to the **Integrations** page (select **Add integrations** in the toolbar on most pages), and then follow the links for the types of data you want to collect.

[TIP]
====
On the Integrations page, you can select the **Beats only** filter to only view integrations using Beats.
====

[discrete]
[[security-ingest-data-download-and-install-beats-from-the-command-line]]
=== Download and install {beats} from the command line

To install {beats}, see these installation guides:

* {filebeat-ref}/filebeat-installation-configuration.html[{filebeat} quick start]
* {auditbeat-ref}/auditbeat-installation-configuration.html[{auditbeat} quick start]
* {winlogbeat-ref}/winlogbeat-installation-configuration.html[{winlogbeat} quick start]
* {packetbeat-ref}/packetbeat-installation-configuration.html[{packetbeat} quick start]

[discrete]
[[enable-beat-modules]]
=== Enable modules and configuration options

No matter how you installed {beats}, you need to enable modules in {auditbeat}
and {filebeat} to populate {elastic-sec} with data.

[TIP]
====
For a full list of security-related beat modules,
https://www.elastic.co/integrations?solution=security[click here].
====

To populate **Hosts** data, enable these modules:

* {auditbeat-ref}/auditbeat-module-system.html[Auditbeat system module  - Linux, macOS,
Windows]:
+
** packages
** processes
** logins
** sockets
** users and groups
* {auditbeat-ref}/auditbeat-module-auditd.html[Auditbeat auditd module - Linux kernel audit events]
* {auditbeat-ref}/auditbeat-module-file_integrity.html[Auditbeat file integrity
module - Linux, macOS, Windows]
* {filebeat-ref}/filebeat-module-system.html[Filebeat system module - Linux
system logs]
* {filebeat-ref}/filebeat-module-santa.html[Filebeat Santa module  - macOS
security events]
* {winlogbeat-ref}/_winlogbeat_overview.html[Winlogbeat - Windows event logs]

To populate **Network** data, enable Packetbeat protocols and Filebeat modules:

* {packetbeat-ref}/packetbeat-overview.html[{packetbeat}]
+
** {packetbeat-ref}/packetbeat-dns-options.html[DNS]
** {packetbeat-ref}/configuration-tls.html[TLS]
** {packetbeat-ref}/configuration-protocols.html[Other supported protocols]
* {filebeat-ref}/filebeat-overview.html[{filebeat}]
+
** {filebeat-ref}/filebeat-module-zeek.html[Zeek NMS module]
** {filebeat-ref}/filebeat-module-suricata.html[Suricata IDS module]
** {filebeat-ref}/filebeat-module-iptables.html[Iptables/Ubiquiti module]
** {filebeat-ref}/filebeat-module-coredns.html[CoreDNS module]
** {filebeat-ref}/filebeat-module-envoyproxy.html[Envoy proxy module (Kubernetes)]
** {filebeat-ref}/filebeat-module-panw.html[Palo Alto Networks firewall module]
** {filebeat-ref}/filebeat-module-cisco.html[Cisco ASA firewall module]
** {filebeat-ref}/filebeat-module-aws.html[AWS module]
** {filebeat-ref}/filebeat-module-cef.html[CEF module]
** {filebeat-ref}/filebeat-module-googlecloud.html[Google Cloud module]
** {filebeat-ref}/filebeat-module-netflow.html[NetFlow module]
