pull_request_rules:
  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
        comment:
          message: |
            This pull request is now in conflicts. Could you fix it @{{author}}? 🙏
            To fixup this pull request, you can check out it locally. See documentation: https://help.github.com/articles/checking-out-pull-requests-locally/
            ```
            git fetch upstream
            git checkout -b {{head}} upstream/{{head}}
            git merge upstream/{{base}}
            git push upstream {{head}}
            ```
  - name: backport patches to 8.15 branch
    conditions:
      - merged
      - base=main
      - label=v8.15.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.15"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
        labels:
          - backport
  - name: backport patches to 8.14 branch
    conditions:
      - merged
      - base=main
      - label=v8.14.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.14"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
        labels:
          - backport
  - name: backport patches to 8.13 branch
    conditions:
      - merged
      - base=main
      - label=v8.13.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.13"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
        labels:
          - backport
  - name: backport patches to 8.12 branch
    conditions:
      - merged
      - base=main
      - label=v8.12.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.12"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
        labels:
          - backport
  - name: backport patches to 8.11 branch
    conditions:
      - merged
      - base=main
      - label=v8.11.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.11"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
        labels:
          - backport
  - name: backport patches to 8.10 branch
    conditions:
      - merged
      - base=main
      - label=v8.10.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.10"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
        labels:
          - backport
  - name: backport patches to 8.9 branch
    conditions:
      - merged
      - base=main
      - label=v8.9.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.9"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
        labels:
          - backport
  - name: backport patches to 8.8 branch
    conditions:
      - merged
      - base=main
      - label=v8.8.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.8"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
        labels:
          - backport
  - name: backport patches to 8.7 branch
    conditions:
      - merged
      - base=main
      - label=v8.7.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.7"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
        labels:
          - backport
  - name: backport patches to 8.6 branch
    conditions:
      - merged
      - base=main
      - label=v8.6.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.6"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
        labels:
          - backport
  - name: backport patches to 8.5 branch
    conditions:
      - merged
      - base=main
      - label=v8.5.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.5"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
        labels:
          - backport
  - name: backport patches to 8.4 branch
    conditions:
      - merged
      - base=main
      - label=v8.4.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.4"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
        labels:
          - backport
  - name: backport patches to 8.3 branch
    conditions:
      - merged
      - base=main
      - label=v8.3.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.3"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
        labels:
          - backport
  - name: backport patches to 8.2 branch
    conditions:
      - merged
      - base=main
      - label=v8.2.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.2"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
        labels:
          - backport
  - name: backport patches to 8.1 branch
    conditions:
      - merged
      - base=main
      - label=v8.1.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.1"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
        labels:
          - backport
  - name: backport patches to 7.17 branch
    conditions:
      - merged
      - base=main
      - label=v7.17.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "7.17"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
        labels:
          - backport
  - name: backport patches to 8.0 branch
    conditions:
      - merged
      - base=main
      - label=v8.0.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.0"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
        labels:
          - backport
  - name: backport patches to 7.16 branch
    conditions:
      - merged
      - base=main
      - label=v7.16.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "7.16"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
        labels:
          - backport
  - name: backport patches to 7.15 branch
    conditions:
      - merged
      - base=main
      - label=v7.15.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "7.15"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
        labels:
          - backport
  - name: backport patches to 7.14 branch
    conditions:
      - merged
      - base=main
      - label=v7.14.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "7.14"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
        labels:
          - backport
  - name: notify the backport policy
    conditions:
      - -label~=(^v\d|backport-skip)
      - base=main
    actions:
      comment:
        message: |
          This pull request does not have a backport label. Could you fix it @{{author}}? 🙏
          To fixup this pull request, you need to add the backport labels for the needed
          branches, such as:
          * `v7.x` is the label to automatically backport to the `7.x` branch.
          * `v7./d./d` is the label to automatically backport to the `7./d` branch. `/d` is the digit

          **NOTE**: `backport-skip` has been added to this pull request.
      label:
        add:
          - backport-skip
  - name: remove backport-skip label
    conditions:
      - label~=^v\d
    actions:
      label:
        remove:
          - backport-skip
