[[security-connect-to-openai]]
= Connect to OpenAI

// :description: Set up an OpenAI LLM connector.
// :keywords: security, overview, get-started

This page provides step-by-step instructions for setting up an OpenAI connector for the first time. This connector type enables you to leverage OpenAI's large language models (LLMs) within {kib}. You'll first need to create an OpenAI API key, then configure the connector in {kib}.

[discrete]
[[security-connect-to-openai-configure-openai]]
== Configure OpenAI

[discrete]
[[security-connect-to-openai-select-a-model]]
=== Select a model

Before creating an API key, you must choose a model. Refer to the https://platform.openai.com/docs/models/gpt-4-turbo-and-gpt-4[OpenAI docs] to select a model. Take note of the specific model name (for example `gpt-4-turbo`); you'll need it when configuring {kib}.

[NOTE]
====
`GPT-4o` offers increased performance over previous versions. For more information on how different models perform for different tasks, refer to the <<security-llm-performance-matrix,LLM performance matrix>>.
====

[discrete]
[[security-connect-to-openai-create-an-api-key]]
=== Create an API key

To generate an API key:

. Log in to the OpenAI platform and navigate to **API keys**.
. Select **Create new secret key**.
. Name your key, select an OpenAI project, and set the desired permissions.
. Click **Create secret key** and then copy and securely store the key. It will not be accessible after you leave this screen.

The following video demonstrates these steps.

++++
 <iframe
  src="https://drive.google.com/file/d/1uRbdwAt7S0572QVNdxOBPGu7XB1xKeZx/preview?usp=sharing"
  width="100%"
  height="100%"
  style="border:none"
></iframe>
++++

[discrete]
[[security-connect-to-openai-configure-the-openai-connector]]
== Configure the OpenAI connector

Finally, configure the connector in {kib}:

. Log in to {kib}.
. Navigate to **Stack Management → Connectors → Create Connector → OpenAI**.
. Provide a name for your connector, such as `OpenAI (GPT-4 Turbo Preview)`, to help keep track of the model and version you are using.
. Under **Select an OpenAI provider**, choose **OpenAI**.
. The **URL** field can be left as default.
. Under **Default model**, specify which https://platform.openai.com/docs/models/gpt-4-turbo-and-gpt-4[model] you want to use.
. Paste the API key that you created into the corresponding field.
. Click **Save**.

The following video demonstrates these steps.

++++
 <iframe
  src="https://drive.google.com/file/d/1KOUSe4H5gklzTM5azl9p2kniEfCI-pof/preview?usp=sharing"
  width="100%"
  height="100%"
  style="border:none"
></iframe>
++++
