[[security-uninstall-agent]]
= Uninstall {agent}

// :description: Remove {agent} from a host.
// :keywords: serverless, security, how-to


To uninstall {agent} from a host, run the `uninstall` command from the directory where it's running. Refer to the {fleet-guide}/uninstall-elastic-agent.html[{fleet} and {agent} documentation] for more information.

If <<security-agent-tamper-protection,Agent tamper protection>> is enabled on the Agent policy for the host, you'll need to include the uninstall token in the command, using the `--uninstall-token` flag. You can <<fleet-uninstall-tokens,find the uninstall token>> on the Agent policy or at **{fleet}** -> **Uninstall tokens**.

For example:

++++
<div class="tabs" data-tab-group="edr-install-config-uninstall-agent">
  <div role="tablist" aria-label="edr-install-config-uninstall-agent">
    <button role="tab" aria-selected="true" aria-controls="edr-install-config-uninstall-agent-macos-panel" id="edr-install-config-uninstall-agent-macos-button">
      macOS
    </button>
    <button role="tab" aria-selected="false" aria-controls="edr-install-config-uninstall-agent-linux-panel" id="edr-install-config-uninstall-agent-linux-button">
      Linux
    </button>
    <button role="tab" aria-selected="false" aria-controls="edr-install-config-uninstall-agent-windows-panel" id="edr-install-config-uninstall-agent-windows-button" tabindex="-1">
      Windows
    </button>
  </div>
  <div tabindex="0" role="tabpanel" id="edr-install-config-uninstall-agent-macos-panel" aria-labelledby="edr-install-config-uninstall-agent-macos-button">
++++
[source,shell]
----
sudo elastic-agent uninstall --uninstall-token 12345678901234567890123456789012
----

++++
  </div>
  <div tabindex="0" role="tabpanel" id="edr-install-config-uninstall-agent-linux-panel" aria-labelledby="edr-install-config-uninstall-agent-linux-button" hidden="">
++++
[source,shell]
----
sudo elastic-agent uninstall --uninstall-token 12345678901234567890123456789012
----

++++
  </div>
  <div tabindex="0" role="tabpanel" id="edr-install-config-uninstall-agent-windows-panel" aria-labelledby="edr-install-config-uninstall-agent-windows-button" hidden="">
++++
[source,shell]
----
C:\"Program Files"\Elastic\Agent\elastic-agent.exe uninstall --uninstall-token 12345678901234567890123456789012
----

++++
  </div>
</div>
++++

[discrete]
[[multiple-uninstall-tokens]]
== Provide multiple uninstall tokens

If you have multiple tamper-protected {agent} policies, you may want to provide multiple uninstall tokens in a single command. There are two ways to do this:

* The `--uninstall-token` command can receive multiple uninstall tokens separated by a comma, without spaces.
+
[source,shell]
----------------------------------
sudo elastic-agent uninstall -f --uninstall-token 7b3d364db8e0deb1cda696ae85e42644,a7336b71e243e7c92d9504b04a774266
----------------------------------

* `--uninstall-token`'s argument can also be a path to a text file with one uninstall token per line. 
+
NOTE: You must use the full file path, otherwise the file may not be found.
+
[source,shell]
----------------------------------
sudo elastic-agent uninstall -f --uninstall-token /tmp/tokens.txt
----------------------------------
+
In this example, `tokens.txt` would contain:
+
[source,txt]
----------------------------------
7b3d364db8e0deb1cda696ae85e42644
a7336b71e243e7c92d9504b04a774266
----------------------------------

[discrete]
[[uninstall-endpoint]]
== Uninstall {elastic-endpoint}

Use these commands to uninstall {elastic-endpoint} from a host **ONLY** if {fleet-guide}/uninstall-elastic-agent.html[uninstalling an {agent}] is unsuccessful.

++++
<div class="tabs" data-tab-group="edr-install-config-uninstall-agent">
  <div role="tablist" aria-label="edr-install-config-uninstall-agent">
    <button role="tab" aria-selected="true" aria-controls="edr-uninstall-config-uninstall-agent-macos-panel" id="edr-install-config-uninstall-agent-macos-button">
      macOS
    </button>
    <button role="tab" aria-selected="false" aria-controls="edr-uninstall-config-uninstall-agent-linux-panel" id="edr-install-config-uninstall-agent-linux-button" tabindex="-1">
      Linux
    </button>
    <button role="tab" aria-selected="false" aria-controls="edr-uninstall-config-uninstall-agent-windows-panel" id="edr-install-config-uninstall-agent-windows-button" tabindex="-1">
      Windows
    </button>
  </div>
  <div tabindex="0" role="tabpanel" id="edr-uninstall-config-uninstall-agent-macos-panel" aria-labelledby="edr-install-config-uninstall-agent-macos-button">
++++
[source,shell]
----
cd /tmp
cp /Library/Elastic/Endpoint/elastic-endpoint elastic-endpoint
sudo ./elastic-endpoint uninstall
rm elastic-endpoint
----

++++
  </div>
  <div tabindex="0" role="tabpanel" id="edr-uninstall-config-uninstall-agent-linux-panel" aria-labelledby="edr-install-config-uninstall-agent-linux-button" hidden="">
++++
[source,shell]
----
cd /tmp
cp /opt/Elastic/Endpoint/elastic-endpoint elastic-endpoint
sudo ./elastic-endpoint uninstall
rm elastic-endpoint
----

++++
  </div>
  <div tabindex="0" role="tabpanel" id="edr-uninstall-config-uninstall-agent-windows-panel" aria-labelledby="edr-install-config-uninstall-agent-windows-button" hidden="">
++++
[source,shell]
----
cd %TEMP%
copy "c:\Program Files\Elastic\Endpoint\elastic-endpoint.exe" elastic-endpoint.exe
.\elastic-endpoint.exe uninstall
del .\elastic-endpoint.exe
----

++++
  </div>
</div>
++++
