[[asset-criticality-api-upsert]]
=== Upsert Asset Criticality Record

Create or update an Asset Criticality Record.

==== Request URL

`POST <kibana host>:<port>/api/asset_criticality`

==== Request body

A JSON object defining the Asset Criticality Record.

[width="100%",options="header"]
|==============================================
|Name |Type |Description |Required
|`id_field` |String |Which field contains the entity ID, must be either `user.name` or `host.name`.
|Yes
|`id_value` |String |The ID of the entity contained in the specified ID field.
|Yes
|`criticality_level` | The assigned criticality level, must be one of:

* `low_impact`
* `medium_impact`
* `high_impact`
* `extreme_impact`

For example, you can assign Extreme impact to business-critical entities, or Low impact to entities that pose minimal risk to your security posture.

|Yes

|==============================================

===== Example requests

[source,console]
--------------------------------------------------
POST /api/asset_criticality
{
  "id_field": "host.name",
  "id_value": "my_host",
  "criticality_level": "high_impact"
}

--------------------------------------------------

==== Response code

`200`::
    Indicates a successful call.

==== Example response

[source,json]
--------------------------------------------------
{
    "@timestamp": "2024-08-02T11:15:34.290Z"
    "id_field": "host.name",
    "id_value": "my_host",
    "criticality_level": "high_impact",
}
--------------------------------------------------