[[asset-criticality-api-list]]
=== List asset criticality records

Retrieve a list of asset criticality records.

Use the query parameters to filter and sort the results as needed. By default, the first page is returned, with 10 results per page.

==== Request URL

`GET <kibana host>:<port>/api/asset_criticality/list`

==== URL query parameters

[width="100%",options="header"]
|==============================================
|Name |Type |Description |Required

|`sort_field` |String a|The field to sort the results by, which must be one of the following:

* `id_value`
* `id_field`
* `criticality_level`
* `@timestamp`

|No
|`sort_direction` |String |The order to sort the results in, which must be either `asc` or `desc`.
|No
|`page` |Number | The page number to return, which must be at least 1. Defaults to `1`.
|No
|`per_page` |Number |The number of results to return per page, which must be between 1 and 1000. Defaults to `10`. 
|No
|`kuery` |String a|A KQL query to filter results by, for example `criticality_level:low_impact OR criticality_level:medium_impact`
|No
|==============================================

===== Example requests

[source,console]
--------------------------------------------------
GET api/asset_criticality/list?kuery=criticality_level:high_impact%20OR%20criticality_level:medium_impact

--------------------------------------------------

==== Response code

`200`::
    Indicates a successful call.

==== Example response

[source,json]
--------------------------------------------------
{
  "records": [
    {
      "id_field": "host.name",
      "id_value": "my_other_host",
      "criticality_level": "medium_impact",
      "@timestamp": "2024-08-02T14:40:35.705Z"
    },
    {
      "id_field": "host.name",
      "id_value": "my_host",
      "criticality_level": "high_impact",
      "@timestamp": "2024-08-02T11:15:34.290Z"
    }
  ],
  "total": 2,
  "page": 1,
  "per_page": 10
}
--------------------------------------------------
