[[conversation-api-create]]
=== Create Conversation

Creates a new Conversation.

==== Request URL

`POST <kibana host>:<port>/api/security_ai_assistant/current_user/conversations`

==== Request body

<DocTable columns={[
  {
    "title": "Name",
    "width": "30%"
  },
  {
    "title": "Type",
    "width": "20%"
  },
  {
    "title": "Description",
    "width": "50%"
  }
]}>
  <DocRow>
    <DocCell>`title`</DocCell>
    <DocCell>String</DocCell>
    <DocCell>
      Conversation title. By default is "New chat". Will be AI generated if not changed.
      
    </DocCell>
  </DocRow>
  <DocRow>
    <DocCell>`category`</DocCell>
    <DocCell>String</DocCell>
    <DocCell>
      Could be 'assistant' or 'insights' or not defined
      
    </DocCell>
  </DocRow>
  <DocRow>
    <DocCell>`isDefault`</DocCell>
    <DocCell>Boolean</DocCell>
    <DocCell>
      Define if conversation is a system conversation.
      
    </DocCell>
  </DocRow>
  <DocRow>
    <DocCell>`excludeFromLastConversationStorage`</DocCell>
    <DocCell>Boolean</DocCell>
    <DocCell>
      Defines if conversation should be displayed as the latest used conversation if it was used.
      
    </DocCell>
  </DocRow>
  <DocRow>
    <DocCell>`apiConfig`</DocCell>
    <DocCell><DocLink slug="/AI-for-security/api/conversation-api-create" section="apiConfig-object">ApiConfig</DocLink></DocCell>
    <DocCell>
      Conversation configuration.
      
    </DocCell>
  </DocRow>
  <DocRow>
    <DocCell>`messages`</DocCell>
    <DocCell><DocLink slug="/AI-for-security/api/conversation-api-create" section="message-object">Array<Message></DocLink></DocCell>
    <DocCell>
      Array of conversation messages.
      
    </DocCell>
  </DocRow>
  <DocRow>
    <DocCell>`replacements`</DocCell>
    <DocCell><DocLink slug="/AI-for-security/api/conversation-api-create" section="replacements-object">Replacements</DocLink></DocCell>
    <DocCell>
      List of the fields with anonymization.
      
    </DocCell>
  </DocRow>
</DocTable>

<div id="apiConfig-obj"></div>

## ApiConfig object

<DocTable columns={[
  {
    "title": "Name",
    "width": "30%"
  },
  {
    "title": "Type",
    "width": "20%"
  },
  {
    "title": "Description",
    "width": "50%"
  }
]}>
  <DocRow>
    <DocCell>`connectorId`</DocCell>
    <DocCell>String</DocCell>
    <DocCell>
      Kibana connector ID

      
    </DocCell>
  </DocRow>
  <DocRow>
    <DocCell>`actionTypeId`</DocCell>
    <DocCell>String</DocCell>
    <DocCell>
      Kibana connector ation type ID

      
    </DocCell>
  </DocRow>
  <DocRow>
    <DocCell>`defaultSystemPromptId`</DocCell>
    <DocCell>String</DocCell>
    <DocCell>
      Default system prompt ID

      
    </DocCell>
  </DocRow>
  <DocRow>
    <DocCell>`model`</DocCell>
    <DocCell>String</DocCell>
    <DocCell>
      LLM specific model

      
    </DocCell>
  </DocRow>
</DocTable>

<div id="message-obj"></div>

## Message object

<DocTable columns={[
  {
    "title": "Name",
    "width": "30%"
  },
  {
    "title": "Type",
    "width": "20%"
  },
  {
    "title": "Description",
    "width": "50%"
  }
]}>
  <DocRow>
    <DocCell>`role`</DocCell>
    <DocCell>String</DocCell>
    <DocCell>
      Message role. Could be "user", "assisatnt" or "system".

      
    </DocCell>
  </DocRow>
  <DocRow>
    <DocCell>`content`</DocCell>
    <DocCell>String</DocCell>
    <DocCell>
      Message content tot send to LLM

      
    </DocCell>
  </DocRow>
  <DocRow>
    <DocCell>`isError`</DocCell>
    <DocCell>String</DocCell>
    <DocCell>
      Define if the message is an error message and not LLM response.

      
    </DocCell>
  </DocRow>
  <DocRow>
    <DocCell>`timestamp`</DocCell>
    <DocCell>String</DocCell>
    <DocCell>
      Timestamp when the message was sent.

      
    </DocCell>
  </DocRow>
  <DocRow>
    <DocCell>`traceData`</DocCell>
    <DocCell>Object</DocCell>
    <DocCell>
      Tracing information.

      
    </DocCell>
  </DocRow>
</DocTable>

<div id="message-obj"></div>

## Replacements object

<DocTable columns={[
  {
    "title": "Name",
    "width": "30%"
  },
  {
    "title": "Type",
    "width": "20%"
  },
  {
    "title": "Description",
    "width": "50%"
  }
]}>
  <DocRow>
    <DocCell>`role`</DocCell>
    <DocCell>String</DocCell>
    <DocCell>
      Message role. Could be "user", "assisatnt" or "system".

      
    </DocCell>
  </DocRow>
  <DocRow>
    <DocCell>`content`</DocCell>
    <DocCell>String</DocCell>
    <DocCell>
      Message content tot send to LLM

      
    </DocCell>
  </DocRow>
  <DocRow>
    <DocCell>`isError`</DocCell>
    <DocCell>String</DocCell>
    <DocCell>
      Define if the message is an error message and not LLM response.

      
    </DocCell>
  </DocRow>
  <DocRow>
    <DocCell>`timestamp`</DocCell>
    <DocCell>String</DocCell>
    <DocCell>
      Timestamp when the message was sent.

      
    </DocCell>
  </DocRow>
  <DocRow>
    <DocCell>`traceData`</DocCell>
    <DocCell>Object</DocCell>
    <DocCell>
      Tracing information.

      
    </DocCell>
  </DocRow>
</DocTable>


=== Example requests

*Example 1*

Creates a new Conversation.

[source,console]
--------------------------------------------------
POST api/security_ai_assistant/current_user/conversations
{
  "title": "The conversation title.",
  "category": "assistant",
  "messages": [
    {
      "content": "test content",
      "role": "user",
      "isError": false,
      "timestamp": "2019-12-13T16:40:33.400Z",
      "traceData": {
        "traceId": "1234",
        "transactionId": "2"
      }
    }
  ],
  "apiConfig": {
    "actionTypeId": ".gen-ai",
    "connectorId": "86ab-471c-a00b-25b7e20c2d12",
    "defaultSystemPromptId": "Default",
    "model": "gpt-4o"
  },
  "isDefault": false,
  "excludeFromLastConversationStorage": true,
  "replacements": {
    "field1": "914beb92-86ab-471c-a00b"
  }
}
--------------------------------------------------

=== Response code

`200`::
    Indicates a successful call.

=== Response payload

A JSON Conversation object with a unique `id`.

*Example 1*

Conversation response payload:

[source,json]
--------------------------------------------------
{
    "id": "07805df2-6462-451a-b534-78da47873c42",
    "title": "The conversation title.",
    "category": "assistant",
    "timestamp": "2024-07-29T06:58:15.670Z",
    "updatedAt": "2024-07-29T06:58:15.670Z",
    "createdAt": "2024-07-29T06:58:15.670Z",
    "replacements": {
        "field1": "914beb92-86ab-471c-a00b"
    },
    "users": [
        {
            "name": "elastic"
        }
    ],
    "messages": [
        {
            "content": "test content",
            "role": "user",
            "timestamp": "2019-12-13T16:40:33.400Z",
            "traceData": {
                "transactionId": "2",
                "traceId": "1234"
            }
        }
    ],
    "apiConfig": {
        "connectorId": "86ab-471c-a00b-25b7e20c2d12",
        "actionTypeId": ".gen-ai",
        "defaultSystemPromptId": "Default",
        "model": "gpt-4o"
    },
    "isDefault": false,
    "excludeFromLastConversationStorage": true,
    "namespace": "default"
}
--------------------------------------------------

