[chapter]
[[upgrade-intro]]

= Upgrade {elastic-sec}

We highly recommend that all {elastic-sec} users keep their deployments up to date with the latest available {stack} version to access new features, security updates, and performance enhancements. This topic describes updates in 8.0.0 that require changes to your agents, existing data, user privileges, or system preferences.

For upgrading to the latest {stack} version, we recommend using the {kibana-ref}/upgrade-assistant.html[Kibana Upgrade Assistant].

NOTE: For detailed information about the 8.0.0 release, check out the <<release-notes-8.0.0, Release notes>>.

[discrete]
[[upgrade-reqs]]
== Upgrade requirements

*Track rules that are automatically disabled when upgrading*

Upon upgrading to 8.0.0, rules are automatically disabled. Once the upgrade completes, you should re-enable them again to avoid gaps in rule coverage. _We highly recommend that you track your active rules before upgrading so you can easily find and re-enable them after upgrading to 8.0.0_.

Before upgrading, use the <<rules-api-find, Find rules API>> to capture a list of enabled rules.

IMPORTANT: Use curl or another HTTP tool to run {elastic-sec} API commands.

Here is a curl command that you can run to find enabled rules:

[source,console]
--------------------------------------------------
GET /api/detection_engine/rules/_find?per_page=10000&filter=alert.attributes.enabled:true
--------------------------------------------------

To re-enable your rules from the Rules page:

. Go to the All rules table (*Detect -> Rules*).
. Select the rules that you want to enable.
. Click *Bulk actions -> Activate Selected* to re-enable the rules.

Alternatively, you can use the <<bulk-actions-rules-api, Bulk rule actions>> API to re-enable rules.


*New Full Disk Access approval needed for {elastic-endpoint}*

When you manually install {elastic-endpoint}, you must approve a system extension, kernel extension, and enable Full Disk Access (FDA). There is a new FDA requirement in 8.0.0. Refer to <<deploy-elastic-endpoint>> to review the required permissions.


*Upgrade agents*

Upgrade your {stack} and {agent}s to 7.17.0 first (refer to {fleet-guide}/upgrade-elastic-agent.html[Upgrade Fleet-managed Elastic Agents]). After this is complete, you can then {stack-ref}/upgrading-elastic-stack.html[upgrade the {stack}] to 8.0. Initially, {agent}s will be version 7.17.0; this is fine because {elastic-sec} supports the last minor in 7.x (7.17.0) and any subsequent {elastic-endpoint} versions in 8.x. After the {stack} upgrade, you can decide whether to upgrade {agent}s to 8.0.0, which is recommended to ensure you get the latest features and improvements.

NOTE: You do not need to shut down your {agent}s or endpoints to upgrade the {stack}.

*Requirements to display Data views in the {es-sec-app}*

To make the *Data view* option appear in an environment with legacy alerts, a user with elevated role privileges must visit the {es-sec-app}, open a page that displays alert data (such as the Overview page), then refresh the page. The user's role privileges must allow them to enable the detections feature in a Kibana space. Refer to <<enable-detections-ui, Enable and access detections>> for more information.

NOTE: If new alerts are generated in an upgraded environment without legacy alerts, refreshing any page with alert data in {elastic-sec} will make the *Data view* option appear in the {es-sec-ui}.

*New alert schema*

The system index for detection alerts has been renamed from `.siem-signals-<space-id>` to `.alerts-security.alerts-<space-id>` and is now a hidden index. Therefore, the schema used for alert documents in {elastic-sec} has changed. Users that access documents in the `.siem-signals` indices using the {elastic-sec} API must modify their API queries and scripts to operate properly on the new 8.0.0 alert documents. Refer to <<query-alert-indices, how to query alert indices>> and review the new <<alert-schema, Alert schema>>.

*New privileges required to view alerts and preview rules*

* To view alerts, users need `manage`, `write`, `read`, and `view_index_metadata` privileges to two new indices, `.alerts-security.alerts` and `.internal.alerts-security.alerts`. Existing users who are upgrading to 8.0.0 can retain their privileges to the `.siem-signals` index.

* To <<preview-rules, preview rules>>, users need `read` access to the new `.preview.alerts-security.alerts` index. Refer to <<detections-permissions-section>> for more information.

*Full Disk Access (FDA) approval for {elastic-endpoint}*

New FDA approval is needed when deploying {elastic-endpoint} on macOS. Refer to <<deploy-elastic-endpoint, Install {elastic-endpoint} manually>> for more information.

*Updates to indictor match rules*

Changes to the indicator match rule's <<rule-ui-advanced-params, default threat indicator path>> might require you to update existing rules, or create new ones, after upgrading to 8.0.0. Be mindful of the following:

* If an indicator match rule's default threat indicator path was not defined before the upgrade, it will default to `threatintel.indicator` after the upgrade. This allows the rule to continue using indicator data ingested by {filebeat} version 7.x. If a custom value was defined before the upgrade, the value will not change.
* If an existing indicator match rule was configured to use threat indicator indices generated from {filebeat} version 7.x, updating the default threat indicator path to `threat.indicator` after you upgrade to {stack} version 8.0.0 and {agent} or {filebeat} version 8.0.0 configures the rule to use threat indicator indices generated by those later versions.
* You must create separate rules to query threat intelligence indices created by {filebeat} version 7.x and version 8.0.0 because each version requires a different default threat indicator path value. Review the recommendations for <<query-alert-indices, querying alert indices>>.
