[chapter]
[[upgrade-intro]]


= Upgrade {elastic-sec}

We highly recommend that all {elastic-sec} users keep their deployments up to date with the latest available {stack} version to access new features, security updates, and performance enhancements.

For upgrading to the latest {stack} version, we recommend using the {kibana-ref}/upgrade-assistant.html[Kibana Upgrade Assistant].


[discrete]
[[pre-upgrade-security]]
== Pre-upgrade requirements for 8.0

Before you upgrade, review the following requirements specific to {elastic-sec}:

*Upgrade agents*

Upgrade your {stack} and {agent}s to 7.17 first (refer to {fleet-guide}/upgrade-elastic-agent.html[Upgrade Fleet-managed Elastic Agents]). After this is complete, you can then {stack-ref}/upgrading-elastic-stack.html[upgrade the {stack}] to 8.0. Initially, {agent}s will be version 7.17; this is fine because {elastic-sec} supports the last minor in 7.x (7.17) and any subsequent {elastic-endpoint} versions in 8.x. After the {stack} upgrade, you can decide whether to upgrade {agent}s to 8.0.0, which is recommended to ensure you get the latest features and improvements.

NOTE: You do not need to shut down your {agent}s or endpoints to upgrade the {stack}.

*Disable all rules*

Manually disable your rules before upgrading, then reactivate them after the process completes. If this is not done, rules are automatically disabled during the upgrade process, which can cause a gap in rule coverage.

To disable all rules:

. Go to *Detect* -> *Rules*.
. Click the *Select All Rules* button above the All rules table.
. Click *Bulk actions* -> *Deactivate selected*.

To reactivate all detection rules:

. Go to *Detect* -> *Rules*.
. Click the *Select All Rules* button above the All rules table.
. Click *Bulk actions* -> *Activate selected*.

NOTE: To use the {elastic-sec} API to re-enable rules, refer to <<bulk-actions-rules-api>>.

*New Full Disk Access approval needed for {elastic-endpoint}*

When you manually install {elastic-endpoint}, you must approve a system extension, kernel extension, and enable Full Disk Access (FDA). There is a new FDA requirement in 8.0.0. Refer to <<deploy-elastic-endpoint>> to review these required permissions.

* Rules must be manually disabled before upgrading to {stack} version 8.0.0, and then manually enabled after the process completes to avoid gaps in rule coverage. Refer to <<upgrade-intro, Upgrade {elastic-sec}>> for more information.
* To make the *Data view* option appear in an environment with legacy alerts, a user with elevated role privileges must visit the {es-sec-app}, open a page that displays alert data (such as the Overview page), then refresh the page. The user's role privileges must allow them to enable the detections feature in a Kibana space. Refer to <<enable-detections-ui, Enable and access detections>> for more information.

+
NOTE: If new alerts are generated in an upgraded environment without legacy alerts, refreshing any page with alert data in {elastic-sec} will make the *Data view* option appear in the {es-sec-ui}.


* The system index for detection alerts has been renamed from `.siem-signals-*` to `.alerts-security.alerts-*` and is now a hidden index. As such, the schema used for alert documents in {elastic-sec} has changed. Users that access documents in the `.siem-signals` indices via the {elastic-sec} API must modify their API queries and scripts to operate properly on the new 8.0 alert documents. The new schema is available at <<alert-schema, Alert schema>>.
* To view alerts, users need `manage`, `write`, `read`, and `view_index_metadata` privileges to two new indices, `.alerts-security.alerts` and `.internal.alerts-security.alerts`. Existing users who are upgrading to 8.0 can retain their privileges to the `.siem-signals` index. Refer to <<detections-permissions-section>> for more information.
* To <<preview-rules, preview rules>>, users need `read` access to the new `.preview.alerts-security.alerts` index. Refer to <<detections-permissions-section>> for more information.
* New Full Disk Access approval is needed when deploying {elastic-endpoint} on macOS. Refer to <<deploy-elastic-endpoint, Install {elastic-endpoint} manually>> for more information.
* Changes to the indicator match rule's <<rule-ui-advanced-params, default threat indicator path>> might require you to update existing rules, or create new ones, after upgrading to {stack} version 8.0.0. Be mindful of the following:
** If an indicator match rule's default threat indicator path was not defined before the upgrade, it will default to `threatintel.indicator` after the upgrade. This allows the rule to continue using indicator data ingested by {filebeat} version 7.x. If a custom value was defined before the upgrade, the value will not change.
** If an existing indicator match rule was configured to use threat indicator indices generated from {filebeat} version 7.x, updating the default threat indicator path to `threat.indicator` after you upgrade to {stack} version 8.0.0 and {agent} or {filebeat} version 8.0.0 configures the rule to use threat indicator indices generated by those later versions.
** You must create separate rules to query threat intelligence indices created by {filebeat} version 7.x and version 8.0.0 because each version requires a different default threat indicator path value.
