[[timeline-api-import]]
=== Import timelines and timeline templates

Imports timelines and timeline templates from an `ndjson` file.
NOTE: The {kib} Console supports only Elasticsearch APIs. You cannot interact with the {kib} APIs with the Console and must use `curl` or another HTTP tool instead. For more information, refer to https://www.elastic.co/guide/en/kibana/current/console-kibana.html[Console].

If you are updating an existing timeline template, make sure:

* You specify the relevant template's unique ID (`templateTimelineId`).
* You increment the timeline's version number (`templateTimelineVersion`).

==== Request URL

`POST <kibana host>:<port>/api/timeline/_import`

The request must include:

* The `Content-Type: multipart/form-data` HTTP header.
* A link to the ndjson file containing the timelines.

For example, using cURL:

[source,console]
--------------------------------------------------
curl -X POST "<KibanaURL>/api/timeline/_import"
-u <username>:<password> -H 'kbn-xsrf: true'
-H 'Content-Type: multipart/form-data'
--form "file=@<link to file>" <1>
--------------------------------------------------
<1> The relative link to the ndjson file containing the timelines.

===== Example request

Imports the rules in the `timelines_export.ndjson` file:

[source,console]
--------------------------------------------------
curl -X POST "api/detection_engine/rules/_import"
-H 'kbn-xsrf: true' -H 'Content-Type: multipart/form-data'
--form "file=@timelines_export.ndjson"
--------------------------------------------------

==== Response code

`200`::
    Indicates a successful call.
