[[osquery-placeholder-fields]]
== Use placeholder fields in Osquery queries 

Placeholder fields are fields that can be replaced with data about an alert or an event. You can use placeholder fields to turn hard-coded queries into dynamic and flexible ones. Any field within an event or alert document can be used as a placeholder field. Placeholder fields can be used in single queries or query packs.

[float]
[[placeholder-field-syntax]]
=== Placeholder field syntax

Placeholder fields use http://mustache.github.io/[mustache syntax] and must be wrapped in double curly brackets (`{{}}`), for example: `{{host.name}}`.  

Here is an example query using a placeholder field: 

`SELECT * FROM os_version WHERE name = `{{host.name}}`

When the query is ran, the `{{host.name}}` field will be replaced with the value that's stored in the alert or event's `host.name` field.

[float]
[[placeholder-field-run-query]]
=== Run queries with placeholder fields

Queries with placeholder fields _must_ be run against an alert or an event. If a placeholder field can't find an alert or event field value, the query status will be `Skipped`. 

Placeholder fields are supported for the following features:

* <<alerts-run-osquery,Live queries ran from alerts or events>>
* <<osquery-response-action,Osquery Response Action>>
+
NOTE: Placeholder fields within an Osquery Response Action query will only work if the rule has generated alerts.
* <<invest-guide-run-osquery,Investigation guides using Osquery queries>> 
