[[osquery-placeholder-fields]]
== Use placeholder fields in Osquery queries 

Placeholder fields dynamically inject alert and event data into queries that you run. To create a placeholder field, you must wrap the field in double curly brackets (`{{}}`); you can use any field in an event or alert document. 

Placeholder fields work in single queries and query packs. If you are running a live query that has placeholder fields, _you must run it from an alert or event_. Also note that placeholder fields within an Osquery Response Action query will only work if the rule has generated alerts.

If the placeholder field is unable to find a value for the field in the alert or event's document, the query status will be `Skipped` and the following error message displays:

TBD

[float]
[[placeholder-field-example]]
=== Example query using a placeholder field
Here is an example query that uses the `{{host.name}}` placeholder field:

`SELECT * FROM os_version WHERE name = `{{host.name}}

When this query is ran, it will select all columns from the `os_version` table where `name` is the value that's available in the alert or event's `host.name` field.

