[[security-requirements-overview]]
= {elastic-sec} requirements

// :description: Requirements for using and configuring {elastic-sec}.
// :keywords: serverless, security, how-to, manage

preview:[]

The https://www.elastic.co/support/matrix[Support Matrix] page lists officially
supported operating systems, platforms, and browsers on which components such as {beats}, {agent}, {elastic-defend}, and {elastic-endpoint} have been tested.

[discrete]
[[security-requirements-overview-space-and-index-privileges]]
== Space and index privileges

Provide access to {elastic-sec} by assigning a user the appropriate <<general-assign-user-roles,predefined user role>> or a <<custom-roles,custom role>> with specific privileges.

To use {elastic-sec}, your role must have at least:

* `Read` privilege for the `Security` feature in the <<security-spaces,space>>. This grants you `Read` access to all features in {elastic-sec} except cases. You need additional <<security-cases-requirements,minimum privileges>> to use cases.
* `Read` and `view_index_metadata` privileges for all {elastic-sec} indices, such as
`filebeat-*`, `packetbeat-*`, `logs-*`, and `endgame-*` indices.

[NOTE]
====
<<security-advanced-settings>> describes how to modify {elastic-sec} indices.
====

For more information about index privileges, refer to {ref}/security-privileges.html[{es} security privileges].

[discrete]
[[security-requirements-overview-feature-specific-requirements]]
== Feature-specific requirements

There are some additional requirements for specific features:

* <<security-detections-requirements>>
* <<security-cases-requirements>>
* <<security-ers-requirements>>
* <<security-ml-requirements>>
* <<security-elastic-endpoint-deploy-reqs>>
* <<security-conf-map-ui>>

[discrete]
[[security-requirements-overview-advanced-configuration-and-ui-options]]
== Advanced configuration and UI options

<<security-advanced-settings>> describes how to modify advanced settings, such as the
{elastic-sec} indices, default time intervals used in filters, and IP reputation
links.

[discrete]
[[security-requirements-overview-third-party-collectors-mapped-to-ecs]]
== Third-party collectors mapped to ECS

The {ecs-ref}[Elastic Common Schema (ECS)] defines a common set of fields to be used for storing event data in Elasticsearch. ECS helps users normalize their event data
to better analyze, visualize, and correlate the data represented in their
events. {elastic-sec} can ingest and normalize events from any ECS-compliant data source.

[IMPORTANT]
====
{elastic-sec} requires {ecs-ref}[ECS-compliant data]. If you use third-party data collectors to ship data to {es}, the data must be mapped to ECS. <<security-siem-field-reference,{elastic-sec} ECS field reference>> lists ECS fields used in {elastic-sec}.
====
