[[post-upgrade-req-cti-alerts]]

== Migrate detection alerts enriched with threat intelligence

After upgrading to {stack} version 7.15.x or newer from a release between 7.12.0 and 7.14.2, you need to migrate detection alerts enriched with threat intelligence data to ensure threat intelligence properly displays in {elastic-sec}.

To migrate detection alerts:

. Ensure that all <<deactivate-detect-rules, detection rules are deactivated>> prior to upgrading your {stack}.
. Upgrade Kibana. See {kibana-ref}/upgrade.html[Upgrade {kib}] for more information.
. Visit the Overview or Alerts page in {elastic-sec} to update the detection alert indices.
. Migrate old alerts using the <<signals-migration-api, Detection Alerts Migration API>>.
. <<reactivate-detect-rules, Reactivate all detection rules>>.

[float]
[[deactivate-detect-rules]]
=== Deactivate all detection rules

To deactivate all detection rules:

. Go to *Manage* -> *Rules*.
. Click the *Select all _x_ rules* option above the rules table.
. Click *Bulk actions* -> *Disable*.

[float]
[[reactivate-detect-rules]]
=== Reactivate all detection rules

To reactivate all detection rules:

. Go to *Manage* -> *Rules*.
. Click the *Select all _x_ rules* option above the rules table.
. Click *Bulk actions* -> *Enable*.
