name: "Bug report"
description: "Report a bug in the Elastic Security documentation"
title: "[BUG] "
labels: "bug"
body: 
  - type: markdown
    attributes:
      value: |
        Hello! Use this form to report an Elastic Security documentation bug to the [@elastic/security-docs](https://github.com/orgs/elastic/teams/security-docs) team.
  - type: textarea
    id: doc-links
    attributes:
      label: Documentation links
      description: Which doc(s) is affected?
      placeholder: |
        Elastic Security overview: https://www.elastic.co/guide/en/security/current/es-overview.html
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug. What needs to be removed, edited, added, or replaced? Please also include instructions on how to reproduce the bug, if necessary. 
    validations:
      required: true
  - type: dropdown
    id: doc-set
    attributes:
      label: Which documentation set(s) does this bug apply to?
      description: ESS (classic), serverless, or both?
      options:
        - ESS and serverless
        - ESS only
        - Serverless only
        - Unknown
      default: 0
    validations:
      required: true
  - type: textarea
    id: software-version
    attributes:
      label: Release version
      description: If you selected ESS above, please list which Stack version(s) this bug applies to. 
      placeholder: |
        For example:
        "This bug applies to Stack versions 8.10 and newer." 
         "N/A"
    validations:
      required: false
  - type: textarea
    id: testing-env
    attributes:
      label: Testing environment
      description: Please include the URL to the server or test environment, or include instructions on how to generate test data. 
      placeholder: |
        You can find this in the Kibana dev server: https://kibana.siem.estc.dev/
    validations:
      required: true
