name: "Internal documentation request (Elastic employees) "
description: Request a documentation change or enhancement. For tasks you don't want exposed to the public, create an issue in [elastic/security-docs-internal](https://github.com/elastic/security-docs-internal).
title: "[Request] "
body:
  - type: markdown
    attributes:
      value: |
        Hello! This form will create an issue that the Security docs team will triage and prioritize. Please do not add any labels to your issue — we'll take care of that.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe what needs to be documented. What details do users need to know about? What are typical workflows for the feature?
      placeholder: |
        What: We're introducing new feature A.
        Why: This feature will make X, Y, and Z easier for the user.
        How: The user navigates to *Foo* → *Bar*, then clicks the *Wow* button.
    validations:
      required: true
  - type: textarea
    id: related
    attributes:
      label: Background & resources
      description: |
        Please include relevant pull requests or issues, and at least one point of contact. 
        Also include any test environments where we can access the feature, and list steps to generate data we can test. 
      value: |
        * PRs: 
        * Issues/metas: 
        * Point of contact: 
        * Test environments: 
    validations:
      required: true
  - type: dropdown
    id: doc-set
    attributes:
      label: Which documentation set does this change impact?
      description: ESS (classic), serverless, or both?
      options:
        - ESS and serverless
        - ESS only
        - Serverless only
        - Unknown
      default: 0
    validations:
      required: true
  - type: dropdown
    id: version-ess
    attributes:
      label: ESS release
      description: Select a release version if your request is tied to the Elastic Stack release schedule.
      options:
        - '8.12'
        - '8.13'
        - '8.14'
        - '8.15'
        - '8.16'
        - 'N/A'
      default: 0
    validations:
      required: true
  - type: input
    id: release-serverless
    attributes:
      label: Serverless release
      description: When do you expect the feature to be promoted and available in the _**serverless production environment**_?
      placeholder: The week of April 1, 2024
    validations:
      required: true
  - type: textarea
    id: doc-set-differences
    attributes:
      label: Feature differences
      description: If you selected both ESS and serverless above, please describe how, if at all, the feature differs in each platform.
      placeholder: The feature is identical in ESS and serverless.
    validations:
      required: true
  - type: textarea
    id: api-docs
    attributes:
      label: API docs impact
      description: Please provide endpoint and parameter descriptions, and request and response examples.
      placeholder: |
        What: We're introducing new endpoint A.
        Why: Users can send a request to endpoint A to use feature A.
        How: The user provides the specific information in the request.   
    validations:
      required: true      
  - type: textarea
    id: prereqs
    attributes:
      label: Prerequisites, privileges, feature flags
      description: |
        What are the feature's requirements _**in both ESS and serverless**_? What subscription tiers or user role privileges are required?
        Is the feature behind a feature flag, and if so, what is it?
      placeholder: |
        * ESS: Requires Enterprise subscription; `write` privilege for `yada-yada-*` index
        * Serverless: Requires Security Analytics Complete tier and Endpoint Protection Complete add-on; X, Y, or Z user roles
        * Feature flag: None
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Thanks for completing this form to help us understand and plan accordingly. We'll be in touch soon!
