name: "Security docs enhancement request"
description: Submit an issue to request an improvement to Elastic Security documentation.
title: "[Enhancement]: "
labels: "enhancement"
body:
  - type: markdown
    attributes:
      value: |
        Hello! Use this form to submit an enhancement request to the [@elastic/security-docs](https://github.com/orgs/elastic/teams/security-docs) team. 
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Summarize your request here. What is the problem?
      placeholder: |
        What: We need documentation for X.
        Why: We've received support requests that indicate customers are struggling with Y in versions A and B. 
    validations:
      required: true
  - type: textarea
    id: related
    attributes:
      label: Related links / assets
      description: How can we learn more about the problem?
      value: |
        Please include each of the following, if applicable:
        Doc URL: 
        Subject matter expert:
        Figma link(s):
        Github epic link(s):
        Github issue link(s):
    validations:
      required: false
  - type: dropdown
    id: doc-set
    attributes:
      label: Which documentation set needs improvement?
      description: ESS, serverless, or both?
      options:
        - ESS and serverless
        - ESS only
        - Serverless only
        - Unknown / Not applicable
      default: 0
    validations:
      required: true
  - type: textarea
    id: software-version
    attributes:
      label: Software version
      description: Is the problem applicable to a particular release version? If so, which one(s)?
      placeholder: |
        For example:
        "The functionality was introduced in 8.11.0, so docs need updating for 8.11+"; 
        "The docs are good after version 8.10, but need updating in 8.7, 8.8, and 8.9"
    validations:
      required: true
  - type: textarea
    id: collaborators
    attributes:
      label: Collaborators
      description: If applicable, please include contact information for the relevant product manager, designer, and developer.
      value: |
        PM:
        Designer: 
        Developer:
        Others (if applicable):
    validations:
      required: false
  - type: textarea
    id: timeline
    attributes:
      label: Timeline / deliverables
      description: When would it be ideal for for us to complete the request?
      placeholder: |
        Please provide any information that would help us prioritize this request.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for submitting this issue! For urgent issues, we encourage you to send a message in the [#security-docs](https://elastic.slack.com/archives/C013W8WME2Z) Slack channel.
