name: "Request a documentation improvement"
description: Request a change to improve Elastic Security docs.
title: "[Suggestion] "
labels: "suggestion"
body:
  - type: markdown
    attributes:
      value: |
        Hello! Do you see something in our docs that needs clarification, more info, or something else we can improve? Use this form to submit a request to our [@elastic/security-docs](https://github.com/orgs/elastic/teams/security-docs) team. 
  - type: textarea
    id: description
    attributes:
      label: What can we change to make the docs better? 
      description: Please describe what the issue is and what we can do to improve it.  
      placeholder: |
        What: We need documentation for X.
        Why: We've received support requests that indicate customers are struggling with Y in versions A and B. 
    validations:
      required: true
  - type: textarea
    id: related
    attributes:
      label: Doc URL
      description: How can we learn more about the problem?
      value: |
        Please include the doc URL and any other related information where applicable:
        Doc URL: 
        Github issue link(s)/Other resources:
    validations:
      required: false
  - type: dropdown
    id: doc-set
    attributes:
      label: Which documentation set needs improvement?
      description: ESS, serverless, or both?
      options:
        - ESS and serverless
        - ESS only
        - Serverless only
        - Unknown / Not applicable
      default: 0
    validations:
      required: true
  - type: textarea
    id: software-version
    attributes:
      label: Software version
      description: Is the problem applicable to a particular release version? If so, which one(s)?
      placeholder: |
        For example:
        "The functionality was introduced in 8.11.0, so docs need updating for 8.11+"; 
        "The docs are good after version 8.10, but need updating in 8.7, 8.8, and 8.9"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for submitting this issue! For urgent issues, we encourage you to send a message in the [#security-docs](https://elastic.slack.com/archives/C013W8WME2Z) Slack channel.