name: "Known issue"
description: "Report a known issue for us to include in release notes."
title: "[Known Issue] "
labels: "known-issue, release-notes"
body: 
  - type: markdown
    attributes:
      value: |
        Hello! Use this form to submit a known issue to the [@elastic/security-docs](https://github.com/orgs/elastic/teams/security-docs) team.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the known issue and its impact on users. If there's a related issue or PR, link it.
    validations:
      required: true
  - type: textarea
    id: eng-team
    attributes:
      label: Area/Engineering team
      description: Which team owns the affected feature(s)?
      placeholder: |
        E.g. Detections & Response, Threat Hunting, Cloud, etc.
    validations:
      required: true
  - type: dropdown
    id: doc-set
    attributes:
      label: Which documentation set does this known issue impact?
      description: ESS (classic), serverless, or both?
      options:
        - ESS and serverless
        - ESS only
        - Serverless only
        - Unknown
      default: 0
    validations:
      required: true
  - type: textarea
    id: affected-versions
    attributes:
      label: Affected versions
      description: Which software versions are affected?
      placeholder: |
        E.g. This issue is present in serverless, and in ESS versions 8.11.x, 8.12.x, and 8.13.x
    validations:
      required: true
  - type: textarea
    id: fix-versions
    attributes:
      label: Fix version
      description: Which software version includes a fix for this issue? (If applicable.)
      placeholder: |
        E.g. This issue is fixed in the serverless release scheduled for [date], and in version 8.14.0 of ESS.
    validations:
      required: false
  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Are there any known workarounds for this issue? If so, please describe the steps users should take to implement a workaround.
    validations:
      required: false