[discrete]
[[release-notes-7.16.0]]
== 7.16.0

[discrete]
[[features-7.16.0]]
==== Features
* Adds the ability to configure trusted applications on a per-policy basis, allowing security administrators to target a set of hosts with specific configurations and settings. For example, trusted applications could be tailored to certain functions within an organization or for testing and troubleshooting purposes ({pull}112182[#112182], {pull}111051[#111051], {pull}110966[#110966]).
* Adds memory threat protection for macOS and Linux systems.
* Provides certified applications for {sn} Security Operations (SecOps) and {sn} IT Service Management (ITSM), and introduces a new {sn} IT Operations Management (ITOM) connector ({pull}105440[#105440], {pull}114125[#114125]).
* Adds logic to finding pending isolation or release statuses for endpoints added in {es-sec} version 7.16 or later ({pull}115441[#115441]).
* Adds {Fleet} actions and responses to the endpoint activity log and enriches the log by showing successful or failed action responses that were completed when the endpoint finished executing the action request ({pull}114905[#114905]).
* Resolves deep link IDs ({pull}111984[#111984]).
* Allows users to create host isolation exceptions ({pull}111253[#111253]).
* Allows cases to be imported and exported as saved objects ({pull}110148[#110148]).
* Adds the Risky Hosts view to the Overview page ({pull}109553[#109553]).
* Adds host risk metadata to alert details ({pull}113274[#113274]).

[discrete]
[[bug-fixes-7.16.0]]
==== Bug fixes and enhancements
* The *Analyze event* option has been moved from the overflow menu to the Actions column within the Alerts and Events tables. It now only displays events that can be opened in the visual event analyzer ({pull}115478[#115478]).
* Halts indicator match rule execution after the allotted time interval has passed ({pull}115288[#115288]).
* Allows migration of detection rule actions to centralized Kibana alerting framework. Users may receive notifications sooner after alerts have been generated, depending on rule configuration and actions frequency ({pull}115243[#115243], {pull}115101[#115101]).
* Changes the prebuilt indicator match rule's interval and lookback time to one hour ({pull}115185[#115185]).
* Allows exceptions to be exported with rules ({pull}115144[#115144]).
* Improves the formatting of array values and JSON in the *Table* and *JSON* tabs ({pull}115141[#115141]).
* Provides users with a new, simpler way to add data to their environments through the {agent} ({pull}115016[#115016], {pull}112142[#112142]).
* Enables the Index connector and action for the Detection engine ({pull}111813[#111813]).
* Hides building block rules on the Overview page ({pull}105611[#105611]).
* Stops the status badge from stretching in the Alert Details flyout ({pull}116237[#116237]).
* Improves rule statuses if the user doesn't have permissions to the source index ({pull}115114[#115114]).
* Fixes the exceptions export route ({pull}114920[#114920]).
* Restores local storage persistence for the Alerts table and the Remove Column action ({pull}114742[#114742]).
* Fixes issues that occurred when adding the {es-sec-endpoint} integration to an {agent} policy in {fleet} ({pull}114467[#114467]).
* Updates the Indexing Time and Query Time columns in the Rule Monitoring table to be SUM, instead of MAX ({pull}114023[#114023]).
* Fixes a bug that prevented modals on the Overview page from opening when the user clicked on the *Inspect* button ({pull}113161[#113161]).
* Sets a new default indicator index query that checks indicator index patterns for matched indicators that have occurred in the past 30 days ({pull}112300[#112300]).
* Decodes file names on uploaded value lists and fixes a bug that stopped value lists from being deleted ({pull}111838[#111838]).
* Fixes a bug that validated the form to create a trusted application when the name field was empty ({pull}111508[#111508]).

[discrete]
[[upcoming-breaking-changes-7.16.0]]
==== Upcoming breaking changes
To improve the detection engine's rule preview functionality in 8.0.0, preview alerts will be written to a new index called the signals preview index (`.siem-signals-preview*`). In order to view this index and use the updated rule preview functionality, roles must have `read` privileges to the new signals preview index. Also note that, other than their index lifecycle management policies, signal preview indices are nearly identical to existing signal indices.

To give a role `read` privileges to the new signals preview index:

. Open the main menu, then go to *Management -> Stack Management -> Security -> Roles*.
. Select the custom role you want to update.
. Modify the role's index privileges as follows:
.. *Indices*: Enter the signals preview indices for the role and space, or spaces.
.. *Privileges*: Enter `read`.
. Click *Update role* to save your changes.
