[[release-notes-header-8.0.0]]
== 8.0

[discrete]
[[release-notes-8.0.0]]
=== 8.0.0

[discrete]
[[post-upgrade-reqs-8.0.0]]
==== Post upgrade requirements
* Changes to the indicator match rule's default threat indicator path (<<rule-ui-advanced-params, *Indicator prefix override*>>) might require you to update existing rules, or create new ones, after upgrading to {stack} version 8.0.0 ({pull}118821[#118821]). Be mindful of the following:
** If an indicator match rule's default threat indicator path was not defined before the upgrade, it will default to `threatintel.indicator` after the upgrade. This allows the rule to continue using indicator data ingested by {filebeat} version 7.x. If a custom value was defined before the upgrade, the value will not change.
** If an existing indicator match rule was configured to use threat indicator indices generated from {filebeat} version 7.x, updating the default threat indicator path to `threat.indicator` after you upgrade to {stack} version 8.0.0 and {agent} or {filebeat} version 8.0.0 configures the rule to use threat indicator indices generated by {agent} or {filebeat} version 8.0.0.
** You must create separate rules to query threat intelligence indices created by {filebeat} version 7.x and version 8.0.0 because each version requires a different default threat indicator path value.

[discrete]
[[breaking-changes-8.0.0]]
==== Breaking Changes
* Removes the trusted application API. The trusted application interface maintains identical functionality but now uses the exception list API ({pull}120134[#120134]).
* Removes the list endpoint metadata API ({pull}119401[#119401]).

[discrete]
[[new-features-8.0.0]]
==== Features
* Shows all historical alerts for a given rule in Rule Details, including those associated with previous versions of the rule ({pull}120053[#120053]).
* Improves the Rules and Rule Monitoring tables and enables actions on the Rule Monitoring table ({pull}119644[#119644]).
* The Threat Intelligence view supports {agent}, {filebeat}, and custom integrations ({pull}116175[#116175]).

[discrete]
[[bug-fixes-8.0.0]]
==== Bug fixes and enhancements
* Redesigns and improves the Rules and Exceptions tables ({pull}118940[#118940]).
* Updates the mappings of the rule registry to ECS version 8.0.0, so that the detection rules can process ECS version 8.0.0 data ({pull}123012[#123012]).
* Updates rule import functionality to include exceptions ({pull}118816[#118816]).
* Improves how dates are displayed in the Rules and Exceptions tables ({pull}117643[#117643]).
* Allows you to create runtime fields from, and add them to, the Alerts and Timeline tables ({pull}117627[#117627], {pull}114806[#114806]).
* Enhances the *Data view* selection modal’s UI, and hides the *Data view* dropdown when no data is present ({pull}117601[#117601], {pull}119956[#119956]).
* Enhances previews and error flagging during rule creation ({pull}116374[#116374]).
* Lets you grant privileges for cases separately from {elastic-sec} privileges ({pull}113573[#113573], {pull}112980[#112980]).
* Updates rule actions to use `kibana.alert.*` fields instead of `signals.*` fields ({pull}116491[#116491]).
* Changes the insufficient permissions message type from an error to a warning ({pull}123777[#123777]).
* Fixes typos in the success messages that appear after you close Timelines or Timeline templates ({pull}123258[#123258]).
* Updates the Exceptions table header and the export icon ({pull}122870[#122870]).
* Fixes a bug that could break a rule’s details page after you edited, activated, or deactivated the rule ({pull}122024[#122024]).
* Fixes overlap between the rule query text field and Timeline banner ({pull}121967[#121967], {pull}121127[#121127]).
* Adds support for the threat feed name field (`threat.feed.name`) in the alert details flyout and Timeline view ({pull}120250[#120250]).
* Adds the default threat indicator path (`threat_indicator_path`) to indicator match rules where it was missing ({pull}118962[#118962]).
* Adds a default value for the threat indicator path that indicator match rules use when creating indicator match rules from the {es-sec-app} UI or the create rule API ({pull}118821[#118821]).
* Enhances the design of the Endpoint details flyout ({pull}117987[#117987]).
* Fixes a bug that prevented you from clearing a connector’s *Additional comments* field ({pull}117901[#117901]).
* Allows you to modify the default threat indicator path for the Threat Intel Filebeat Module (v7.x) Indicator Match prebuilt rule ({pull}116583[#116583]).

[discrete]
[[release-notes-8.0.0-rc2]]
=== 8.0.0-rc2

[discrete]
[[known-issues-8.0.0-rc2]]
==== Known issues

*The Data view option might not display in upgraded environments with legacy alerts*

To make the *Data view* option appear, a user with elevated role privileges must visit the {es-sec-app}, open a page that displays alert data (such as the Overview page), then refresh the page. ({pull}121390[#121390]).

The role must have the following privileges:

* *Cluster privileges*: The `manage` privilege
* *Index privileges*: The `manage`, `write`,`read`, and `view_index_metadata` index privileges for the following system indices where `<kib-space>` is the {kib} space name:

** `.siem-signals-<kib-space>`
** `.lists-<kib-space>`
** `.items-<kib-space>`
** `.alerts-security.alerts-<kib-space>`
** `.internal.alerts-security.alerts-<kib-space>-*`

* *{kib} space*: `All` privileges for the `Security` feature (visit
{kibana-ref}/xpack-spaces.html#spaces-control-user-access[Feature access based on user privileges] for more information)

NOTE: If new alerts are generated in an upgraded environment without legacy alerts, refreshing any page with alert data in {elastic-sec} will make the *Data view* option appear in the {es-sec-ui}.

*Detection rules may not generate alerts after upgrading to {stack} 8.0.0*

If you do not manually disable rules before upgrading to {stack} version 8.0.0, they're automatically disabled during the upgrade process and must be manually re-enabled after the process completes. Failure to do so could cause a gap in rule coverage ({pull}120906[#120906]).

NOTE: To use the {es-sec} API to re-enable rules, refer to <<bulk-actions-rules-api, Bulk rule actions>>.

To re-enable your rules from the Rules page:

. Go to the All rules table (*Detect -> Rules*).
. Click *Select all (number) rules* *Rule* select all rules.
. Click *Bulk actions -> Activate Selected* to re-enable all rules.
