[[release-notes-header-8.0.0]]
== 8.0

[discrete]
[[release-notes-8.0.0-rc2]]
=== 8.0.0-rc2

[discrete]
[[known-issues-8.0.0-rc2]]
==== Known issues

*After upgrading to {stack} version 8.0.0, the Data View option might not display if the environment contains legacy alerts:*

IMPORTANT: If new alerts are generated in an upgraded environment without legacy alerts, refreshing any page in {es-sec} will make the *Data View option appear in the {es-sec-ui}.

After upgrading, the *Data View* option might not display in the {es-sec-ui} if the environment contains legacy alerts. To resolve this, a user with elevated role privileges must visit the {es-sec-app}, open a page that displays alert data (such as the Overview page), and refresh the page ({pull}121390[#121390]).

The role must have the following privileges:

* *Cluster privileges*: The `manage` privilege
* *Index privileges*: The `manage`, `write`,`read`, and `view_index_metadata` index privileges for the following system indices where `<kib-space>` is the {kib} space name:

** `.siem-signals-<kib-space>`
** `.lists-<kib-space>`
** `.items-<kib-space>`
** `.alerts-security.alerts-<kib space>`
** `.internal.alerts-security.alerts-<kib space>-*`

* *{kib} space*: `All` privileges for the `Security` feature (see
{kibana-ref}/xpack-spaces.html#spaces-control-user-access[Feature access based on user privileges])

*Rules must be manually re-enabled after upgrading:*

Rules will be disabled as part of the upgrade process to {stack} version 8.0.0 and must be manually re-enabled after the upgrade is complete. Rules will not run until they're re-enabled, which could cause a gap in coverage ({pull}120906[#120906]).

To re-enable rules in {es-sec}, go to *Detect -> Rules*. Next, go to the All rules table, select all Rules, and then click *Bulk actions -> Activate Selected*.

For more information about re-enabling rules using the Bulk rule actions API, refer to <<bulk-actions-rules-api, Bulk rule actions>>.
