[[release-notes-header-8.1.0]]
== 8.1

[discrete]
[[release-notes-8.1.0]]
=== 8.1.0

[discrete]
[[known-issues-8.1.0]]
==== Known issues
TBD

[discrete]
[[breaking-changes-8.1.0]]
==== Breaking Changes
// tag::breaking-changes[]
// NOTE: The breaking-changes tagged regions are re-used in the Elastic Installation and Upgrade Guide. The pull tag is defined within this snippet so it properly resolves in the output.
:pull: https://github.com/elastic/kibana/pull/
There are no breaking changes in 8.1.0.
// end::breaking-changes[]

[discrete]
[[features-8.1.0]]
==== Features
* Update the copy text of the permission check for Endpoint ({pull}124118[#124118]).
* Adds host risk tab to Hosts page ({pull}122980[#122980]).
* Adds ability to bulk edit rules in rules management/monitoring tables. Available for bulk edit fields: tags and index patterns ({pull}122635[#122635]).
* Expands Endpoint per-policy artifact assignment to include endpoint event filters and host isolation IP exceptions ({pull}121879[#121879], {pull}121632[#121632], {pull}121393[#121393], {pull}121280[#121280], {pull}120598[#120598], {pull}120361[#120361], {pull}119828[#119828]).
* Host Risk score tab on Host details page ({pull}122586[#122586]).
* Adds Host risk data to host details page ({pull}122018[#122018]).
* Adds Host risk information flyout to Host risk KPI panel ({pull}121075[#121075]).
* Hosts Risk Step 2 - Hosts Page - Risk Column ({pull}120487[#120487]).
* Hosts Risk Step 1 - Hosts Page - Risky Hosts KPI ({pull}119734[#119734]).
* Adds Rule Execution UUID ({pull}113058[#113058]).
* Activate Case detail metrics ({pull}121336[#121336]).

[discrete]
[[bug-fixes-8.1.0]]
==== Bug fixes and enhancements
* Improves the performance of indicator match rules ({pull}123882[#123882], {pull}123677[#123677]).
* Changes the default indicator index query of custom and prebuilt indicator match rules to `@timestamp >= "now-30d/d"` ({pull}123590[#123590]).
* Improves the exceptions interface by replacing the exceptions modal with a flyout ({pull}123408[#123408]).
* Alert details flyout enhancements:
** Shows different “highlighted fields” in an alert’s details flyout based on its type, category, and code ({pull}123239[#123239]).
** Adds overview cards with key data to the alert details flyout ({pull}120347[#120347]).
** Allows you to aggregate alert data based on any aggregatable ECS field instead of just 10 preset options ({pull}120610[#120610]).
* Speeds up the rules table by implementing an in-memory rules cache ({pull}119611[#119611]).
* Adds another integrity check for endpoint transforms ({pull}121366[#121366]).
* Enrich threshold-related alert data from correct fields ({pull}125376[#125376]).
* Hides the delete button for disabled exception lists ({pull}122844[#122844]).
* Fixes various minor UX bugs ({pull}121410[#121410]).
