[[release-notes-header-8.10.0]]
== 8.10

[discrete]
[[release-notes-8.10.0]]
=== 8.10.0

[discrete]
[[known-issue-8.10.0]]
==== Known issues

* The alert prevalence feature behaves inconsistently and may not produce accurate results.

[discrete]
[[breaking-changes-8.10.0]]
==== Breaking changes
There are no breaking changes in 8.10.0.

[discrete]
[[features-8.10.0]]
==== New features
* Introduces a redesigned alert details flyout that enhances your investigative flows (https://github.com/elastic/security-docs/pull/3816)[#3816], https://github.com/elastic/security-docs/pull/3854[#3854]).
* Adds the MITRE ATT&CK® coverage page, which shows how well your active detection rules protect against adversary tactics and techniques ({pull}161556[#161556], {pull}163498[#163498], {pull}164613[#164613], {pull}164986[#164986]).
* Adds a component under the Elastic AI Assistant header that allows you to select a different connector ({pull}163666[#163666]).
* Adds role-based access control for the Elastic AI Assistant ({pull}163031[#163031]).
* Adds a flyout that allows you to examine rule details when installing or updating a prebuilt rule ({pull}163304[#163304]).
* Adds the ability to specify custom highlighted fields for an alert ({pull}163235[#163235]).
* Adds the **Reputation service** option to the malicious behavior protection setting on the Elastic Defend integration policy ({pull}161617[#161617]).

[discrete]
[[enhancements-8.10.0]]
==== Enhancements
* Modifies the {elastic-sec} main menu by adding the Rules main page and landing page, and shifting the order of the Cases and Explore pages ({pull}165061[#165061], {pull}163102[#163102], {pull}161667[#161667]).
* Adds a `resource.id` column to the "Top 10 vulnerable resources" table on the Cloud Native Vulnerability Management dashboard ({pull}162668[#162668]).
* Shows the most relevant tab when you open the Findings page, instead of always showing the Misconfigurations tab ({pull}162289[#162289]).
* Adds the **Building block** label to the rule details page for building block rules ({pull}162233[#162233]).
* Removes a filter that restricted the fields you could choose from when creating an Endpoint exception or event filter ({pull}162193[#162193]).
* Shows a confirmation message on the Rules page and rule details page when you delete rules ({pull}162477[#162477]). 

[discrete]
[[bug-fixes-8.10.0]]
==== Bug fixes
* Fixes a UI bug that caused the rule preview to break when you closed it ({pull}164973[#164973]).  
* Fixes a bug that stopped pre-configured connectors from working with the Elastic AI Assistant ({pull}164900[#164900]).
* Adds the new Elastic AI Assistant logo and global header menu item ({pull}164763[#164763]).
* Ensures that users see the appropriate message in the Elastic AI Assistant UI if they don't have the necessary connector and action privileges ({pull}164382[#164382]).
* Prevents threshold rule error messages from concealing shard failure messages ({pull}164231[#164231]).
* Removes filter in and out inline actions from the Alerts table on the case details page, and fixes issues with the **Top alerts by** inline action ({pull}161150[#161150]).
* Uses the {agent} `last_checkin` status for endpoints' `last seen` status ({pull}160506[#160506]).
* Hides the **Top alerts by** inline action for nested fields ({pull}159645[#159645]).