[[release-notes-header-8.10.0]]
== 8.10

[discrete]
[[release-notes-8.10.0]]
=== 8.10.0

[discrete]
[[breaking-changes-8.10.0]]
==== Breaking changes
* Use header-based versioned APIs instead of path-based. See ({pull}159839[#159839]) for details.

[discrete]
[[features-8.10.0]]
==== New features
* Adds Connector Selector to Assistant Title Header ({pull}163666[#163666]).
* Prebuilt rule installation / upgrade flyout ({pull}163304[#163304]).
* Adds custom highlighted fields option ({pull}163235[#163235]).
* Adds RBAC for Assistant ({pull}163031[#163031]).
* Unified IA Project Navigation ({pull}161667[#161667]).
* Reputation Service option added to Malicious Behavior Policy card ({pull}161617[#161617]).

[discrete]
[[enhancements-8.10.0]]
==== Enhancements
* New sections with landing page ({pull}163102[#163102]).
* Added resource.id as column to top 10 vuln resources ({pull}162668[#162668]).
* Findings tab redirection logic ({pull}162289[#162289]).
* Adds building block indication to the rule details page ({pull}162233[#162233]).
* Remove the filter on Endpoint Exceptions and Event Filters creation to allow more user flexibility ({pull}162193[#162193]).
* SideNav changes according to new Unified IA (ESS) ({pull}159185[#159185]).

[discrete]
[[bug-fixes-8.10.0]]
==== Bug fixes
* Adds new Elastic AI Assistant logo and global header menu item ({pull}164763[#164763]).
* Fixes Assistant Connector and Actions RBAC Flow ({pull}164382[#164382]).
* Display shard failure messages for threshold rules ({pull}164231[#164231]).
* Remove filter actions from Cases alerts table and fix show_top_n action ({pull}161150[#161150]).
* Use fleet agent `last_checkin` status to show endpoint last seen status ({pull}160506[#160506]).
* Fixes CellActions component should hide ShowTopN action for nested fields ({pull}159645[#159645]).