[[release-notes-header-8.10.0]]
== 8.10

[discrete]
[[release-notes-8.10.0]]
=== 8.10.0

[discrete]
[[breaking-changes-8.10.0]]
==== Breaking changes
There are no breaking changes in 8.10.0.

[discrete]
[[features-8.10.0]]
==== New features
* Adds a component under the Elastic AI Assistant header that allows you to select a different connector ({pull}163666[#163666]).
* Adds a flyout that allows you to examine rule details when installing or updating a prebuilt rule ({pull}163304[#163304]).
* Adds the ability to specify custom highlighted fields for an alert ({pull}163235[#163235]).
* Adds role-based access control privileges for the Elastic AI Assistant ({pull}163031[#163031]).
* Unified IA Project Navigation ({pull}161667[#161667]).
* Adds the **Reputation service** option to the malicious behavior protection setting on the Elastic Defend integration policy ({pull}161617[#161617]).

[discrete]
[[enhancements-8.10.0]]
==== Enhancements
* Move the Rules page up a level in the {elastic-sec} main menu  ({pull}165061[#165061]). 
* Modifies the {elastic-sec} main menu ({pull}159185[#159185]).
* New sections with landing page ({pull}163102[#163102]).
* Adds the `resource.id` column to top ten vulnerability resources ({pull}162668[#162668]).
* Findings tab redirection logic ({pull}162289[#162289]).
* Adds the **Building block** label to the rule details page to show whether a rule was a building block rule ({pull}162233[#162233]).
* Removes a filter that restricted the fields user could choose from when creating an Endpoint exception or event filter ({pull}162193[#162193]).


[discrete]
[[bug-fixes-8.10.0]]
==== Bug fixes
* Fixes a UI bug that caused the rule preview to break when you closed it.  
* Fixes a bug that stopped pre-configured connectors from working with the Elastic AI Assistant ({pull}164900[#164900]).

* Adds the new Elastic AI Assistant logo and global header menu item ({pull}164763[#164763]).
* Ensures that users see the appropriate message in the Elastic AI Assistant UI if they don't have the necessary connector and action privileges ({pull}164382[#164382]).
* Stops threshold rules from displaying error message that conceal shard failure messages ({pull}164231[#164231]).
* Remove filter actions from Cases alerts table and fix show_top_n action ({pull}161150[#161150]).
//Not sure what the show top action is
* Uses the {agent} `last_checkin` status to when showing the last seen status for endpoints ({pull}160506[#160506]).
hows agent last seen status on endpoint details/responder/hosts/alerts consistent with fleet agent status.
* Fixes CellActions component should hide ShowTopN action for nested fields ({pull}159645[#159645]).
//Same comment as above


