[[release-notes-header-8.12.0]]
== 8.12

[discrete]
[[release-notes-8.12.2]]
=== 8.12.2

[discrete]
[[known-issue-8.12.2]]
==== Known issues
// tag::known-issue-178207[]
[discrete]
.Rule filters can't be adjusted for custom query, indicator match, and new term rules using data views  
[%collapsible]
====
*Details* +
When creating or editing a custom query, indicator match, or new term rule, query filters can't be modified (added, edited, or removed) if the rule queries a data view. 

*Workaround* +
To resolve this issue, upgrade to 8.13 or later.
====
// end::known-issue-178207[]

[discrete]
[[bug-fixes-8.12.2]]
==== Bug fixes
* Fixes long-running queries in Timeline and Events tables within Explore pages ({kibana-pull}176838[#176838]).
* Updates the default {bedrock} connector API URL ({kibana-pull}176090[#176090]).
* Ensures the risk score query only searches through alerts associated with the current user ({kibana-pull}175903[#175903]).
* Fixes a bug that prevented scheduled query packs from running if a pack's ID was composed of numbers ({kibana-pull}176507[#176507]).
* Fixes a bug that affected the rule details page layout if rule filters were extremely long. Also fixes a bug that incorrectly caused rule filters to display instead of their custom labels ({kibana-pull}176590[#176590]).
* Fixes a bug that prevented rules from being successfully imported if any rules referenced preconfigured connectors ({kibana-pull}176284[#176284]).
* Fixes a bug that prevented rules from being successfully exported if you exported more than 1000 rules ({kibana-pull}175979[#175979]).
* Turns off the option to install rules if you don't have the appropriate privileges ({kibana-pull}176598[#176598]).
* Fixes a bug that caused data to be lost when you upgraded a prebuilt rule to a new version with a different rule type ({kibana-pull}176421[#176421]).

[discrete]
[[release-notes-8.12.1]]
=== 8.12.1

[discrete]
[[known-issue-8.12.1]]
==== Known issues
// tag::known-issue-178207[]
[discrete]
.Rule filters can't be adjusted for custom query, indicator match, and new term rules using data views  
[%collapsible]
====
*Details* +
When creating or editing a custom query, indicator match, or new term rule, query filters can't be modified (added, edited, or removed) if the rule queries a data view. 

*Workaround* +
To resolve this issue, upgrade to 8.13 or later.
====
// end::known-issue-178207[]

[discrete]
[[enhancements-8.12.1]]
==== Enhancements

* Provides performance improvements related to image load and registry write events ({kibana-pull}175486[#175486]).

[discrete]
[[bug-fixes-8.12.1]]
==== Bug fixes
* Fixes misaligned elements in the top navigation bar ({kibana-pull}175516[#175516]).
* Fixes a bug that affected search results when you entered an agent name that included a dash (`-`) ({kibana-pull}175134[#175134]).
* Fixes a UI bug that hid frequency options for rule actions when you created or edited a rule ({kibana-pull}175050[#175050]).
* Removes the option to select a data view when modifying a rule's filter ({kibana-pull}174922[#174922]).
* Hides the technical and runtime fields that shouldn't appear in the JSON diff view when you're upgrading a rule ({kibana-pull}174789[#174789]).
* Ensures the current user is used when querying threshold rule history ({kibana-pull}174723[#174723]).
* Updates the document ID used for the visual event analyzer preview and the related by ancestry section of the alert details flyout ({kibana-pull}174651[#174651]).
* Deletes saved searches that are associated with deleted Timelines, and prevents saved searches from being created twice ({kibana-pull}174562[#174562]).
* Fixes a bug that prevented the assignee column from appearing in the Alerts table after upgrading to 8.12.0 ({kibana-pull}174370[#174370]).

[discrete]
[[release-notes-8.12.0]]
=== 8.12.0

[discrete]
[[known-issue-8.12.0]]
==== Known issues

// tag::known-issue-173958[]
[discrete]
.Data view option incorrectly displays when editing a filter applied to the KQL query bar 
[%collapsible]
====
*Details* +
When editing the Alerts page KQL query bar filter or editing the KQL query bar filter on the rule edit page, you might encounter a UI bug requiring you to select a data view to proceed. 

*Workaround* +
Select the **Edit the query filter using DSL** option.
====
// end::known-issue-173958[]

// tag::known-issue-175043[]
[discrete]
.Action frequency settings hidden in the UI when creating and editing a rule
[%collapsible]
====
*Details* +
Configuration options for rule action frequency are unavailable when creating and editing rules. Rules with action frequencies that are already configured still run correctly.

*Workaround* +
Use the <<rules-api-update,update rule>> API to change a rule's action frequency settings. Alternatively, export a rule, update its action frequency settings, and then re-import the rule.
====
// end::known-issue-175043[]

// tag::known-issue-174844[]
[discrete]
.Unrelated property differences in prebuilt rule update comparison
[%collapsible]
====
*Details* +
The JSON comparison for updated prebuilt detection rules might display some properties used for internal processing, which doesn't accurately indicate how the rule will change if you update it.

For example, if you added automated actions or an exception list to an installed rule, the comparison shows the JSON properties `actions`, `response_actions`, or `exceptions_list` in the **Base version** (your installed version) but not in the **Update** column (Elastic's latest version). When you update the rule, it will still include your actions or exceptions — they will not be removed. 

Similarly, the comparison might show a difference in the `enabled` property, but upgrading the rule will not change whether your installed rule is enabled or not. Other properties that might display in the comparison but don't actually indicate rule configuration changes include `execution_summary`, `timestamp_override_fallback_disabled`, `meta`, `filters`, `updated_at`, and `output_index`.

*Workaround* +
No workaround is needed. You can ignore these unrelated property differences in the JSON comparison.
====
// end::known-issue-174844[]

[discrete]
[[breaking-changes-8.12.0]]
==== Breaking changes

There are no breaking changes in 8.12.0.

[discrete]
[[deprecations-8.12.0]]
==== Deprecations

There are no deprecations in 8.12.0.

[discrete]
[[features-8.12.0]]
==== New features

* Introduces the ability to assign alerts to specific users ({kibana-pull}170579[#170579], {kibana-pull}171589[#171589]).
* Introduces Retrieval Augmented Generation (RAG) for Alerts, allowing you to give Elastic AI Assistant context about more alerts in your environment ({kibana-pull}172542[#172542]).
* Enables alert suppression for threshold rules ({kibana-pull}171423[#171423]).
* Adds an *Updates* tab to the prebuilt rules upgrade flyout to show differences between the installed and updated versions ({kibana-pull}172535[#172535], {kibana-pull}173187[#173187]).
* Adds a setting that lets you exclude cold and frozen tiers from visual event analyzer queries ({kibana-pull}172162[#172162]).
* Adds a tour to guide users through Timelines UI changes ({kibana-pull}172030[#172030]).
* Adds a timeout option for Osquery queries, so you can customize the maximum time each query should run before timing out ({kibana-pull}169925[#169925]).
* Introduces new grouping capabilities for CSPM and KSPM Findings data ({kibana-pull}169884[#169884]).
* Adds the expandable alert details flyout to the rule preview panel ({kibana-pull}167902[#167902]).
* Introduces bidirectional response actions to isolate and release SentinelOne-protected hosts (technical preview).

[discrete]
[[enhancements-8.12.0]]
==== Enhancements

* Refactors the timeline UI — various minor updates ({kibana-pull}168230[#168230]).
* Introduces manual saving for Timeline ({kibana-pull}171027[#171027], {kibana-pull}169239[#169239]).
* Improves forward-compatibility for the rule schema ({kibana-pull}170861[#170861]).
* Simplifies the format of risk engine API error responses ({kibana-pull}170645[#170645]).
* Makes various UI improvements to the alert details flyout ({kibana-pull}170279[#170279], {kibana-pull}169035[#169035], {kibana-pull}173399[#173399], {kibana-pull}170078[#170078], {kibana-pull}168297[#168297]).
* Saves the state of the alert details flyout in the browser. For example, after you use the flyout's *Investigate in timeline* button, you can click your browser's back button to return to the flyout ({kibana-pull}169661[#169661]).
* Adds a button to rule execution error messages that lets you ask AI Assistant to diagnose errors ({kibana-pull}166778[#166778]).
* Integrates a new Event Tracing for Windows (ETW) provider (Microsoft-Windows-Win32k) to create new event types that can be used by prebuilt endpoint rules to detect keylogging activity.
* Allows for acting and target memory region buffers within behavior alerts to be scanned against {elastic-sec}'s collection of YARA signatures when collected. Detections are added to alerts.
* Adds a new ReadProcessMemory (lsass) event that can be used by prebuilt endpoint rules to detect credential dumping.
* Adds a link to the Amazon Bedrock connector edit UI that opens the token tracking dashboard ({kibana-pull}172115[#172115]).
* Allows you to use the `matches` and `does not match` operators when defining endpoint exceptions and event filters ({kibana-pull}166002[#166002], {kibana-pull}170495[#170495]).
* Adds support for Kafka as an output type for Endpoint.

[discrete]
[[bug-fixes-8.12.0]]
==== Bug fixes

* Fixes response action bugs by mapping the `unisolate` command to the `release` command and the `running-processes` command to the `processes` command ({kibana-pull}173831[#173831]).
* Fixes the dark theme for the alert details flyout footer ({kibana-pull}173577[#173577]).
* Makes the Timeline tour compatible with the Timeline template page ({kibana-pull}173526[#173526]).
* Stops the **{esql}** tab from rendering until you click on it in Timeline ({kibana-pull}173484[#173484]).
* Adds a feature flag (`timelineEsqlTabDisabled`) to show or hide the **{esql}** tab in Timeline ({kibana-pull}174029[#174029]).
* Removes the default query in the **{esql}** tab in Timeline ({kibana-pull}174393[#174393]).
* Fixes a bug that caused {ml} fetch jobs to fail when the default data view (`securitySolution:defaultIndex`) contained special characters ({kibana-pull}173426[#173426]).
* Remove the **Assignees** field from the event details flyout ({kibana-pull}173314[#173314]).
* Fixes a bug that caused the **Add to Case** action to fail if you didn't add a comment before isolating and releasing a host ({kibana-pull}172912[#172912]).
* Fixes a UI bug that overlaid **Default Risk score** values as you created a new rule ({kibana-pull}172677[#172677]).
* Fixes a bug that cleared configured fields in the exceptions flyout after the flyout reloaded and refocused ({kibana-pull}172666[#172666]).
* Limits the character length for exception comments to 3000 characters, and makes the error message more descriptive if the limit's exceeded ({kibana-pull}170764[#170764]).
* Re-adds the missing alerts index filtration to Data views ({kibana-pull}170484[#170484]).
* Fixes a bug that didn't allow exceptions to be created or edited after an error displayed ({kibana-pull}169801[#169801]).
* Stops {security-app} pages from crashing when there's a fields error in the **Stack by** component ({kibana-pull}168411[#168411]).
* Deletes saved searches that are associated with deleted Timelines and prevents saved searches from being created twice ({kibana-pull}174562[#174562]).
* Fixes a bug with the **Share alert** feature in the alert details flyout ({kibana-pull}174005[#174005]).