[[release-notes-header-8.12.0]]
== 8.11

[discrete]
[[release-notes-8.12.0]]
=== 8.12.0

[discrete]
[[known-issue-8.12.0]]
==== Known issues

There are no known issues in 8.12.0.

[discrete]
[[breaking-changes-8.12.0]]
==== Breaking changes

There are no breaking changes in 8.12.0.

[discrete]
[[deprecations-8.12.0]]
==== Deprecations

There are no deprecations in 8.12.0.

[discrete]
[[features-8.12.0]]
==== New features

* Introduces the ability to assign alerts and investigations to specific users ({pull}170579[#170579]), ({pull}171589[#171589]).
* Introduces Retrieval Augmented Generation (RAG) for Alerts, allowing you to give Elastic AI Assistant context about more alerts in your environment ({pull}172542[#172542]).
* Enables alerts suppression for Threshold rules ({pull}171423[#171423]).
* Adds an "Updates" tab to the prebuilt rules upgrade flyout that shows differences between the installed and updated versions ({pull}172535[#172535]).
* Adds a setting that lets you exclude cold and frozen tiers from Analyzer queries ({pull}172162[#172162]).
* Adds a tour that introduces new users to the current Timelines UI ({pull}172030[#172030]).
* Adds a Timeout option to Osquery configuration, so you can customize the maximum time each query should run before timing out ({pull}169925[#169925]).
* Introduces new grouping capabilities for CSPM and KSPM Findings data ({pull}169884[#169884]).
* Adds the expandable alert flyout to rule previews in the Create rule interface ({pull}167902[#167902]).
* Adds a button to error messages for rule execution errors that quickly asks security assistant to diagnose the error ({pull}166778[#166778]).

[discrete]
[[enhancements-8.12.0]]
==== Enhancements

* Improves token tracking for the Amazon Bedrock generative AI connector ({pull}172115[#172115], {pull}170815[#170815]) Elastic Assistant, OpenAI stream ({pull}169729[#169729]) (NEEDS CLARIFICATION - waiting on dev response).
* Refactors the timeline UI — various minor updates ({pull}168230[#168230]).
* Replaces timeline's autosave behavior with a new UI for manual saving ({pull}171027[#171027], {pull}169239[#169239]).
* Improves forward-compatibility for the rule schema ({pull}170861[#170861]).
* Simplifies the format of risk engine API error responses ({pull}170645[#170645]).
* Makes various minor improvements to the alert details flyout UI ({pull}170279[#170279], {pull}169035[#169035], {pull}173399[#173399], {pull}170078[#170078], {pull}168297[#168297]).
* Saves the state of the expanded alert details flyout in the URL. For example this means you use the flyout's **Investigate in timeline* button and then click your browser's back button to return to the flyout ({pull}169661[#169661]).

[discrete]
[[bug-fixes-8.12.0]]
==== Bug fixes
* Fixes response action bugs by mapping the `unisolate` command to the `release` command and the `running-processes` command to the `processes` command ({pull}173831[#173831]).
* Fixes the dark theme for the alert details flyout footer ({pull}173577[#173577]).
* Makes the Timeline tour compatible with the Timeline template page ({pull}173526[#173526]).
* Stops the {esql} tab from rendering when Timeline isn't open ({pull}173484[#173484]).
* Fixes a bug that caused {ml} fetch jobs to fail when the default data view (`securitySolution:defaultIndex`) contained special characters ({pull}173426[#173426]).
* Remove the **Assignees** field from the event details flyout ({pull}173314[#173314]).
* Fixes a bug that caused the **Add to Case** action to fail if you didn't add a comment before isolating and releasing a host ({pull}172912[#172912]).
* Fixes a UI bug that overlaid **Default Risk score** values as you created a new rule ({pull}172677[#172677]).
* Fixes a bug that cleared configured fields in the exceptions flyout after the flyout reloaded and refocused ({pull}172666[#172666]).
* Fixes the {esql} default query size and appends the query with a `keep` clause ({pull}171789[#171789]).
* Limits the character length for exception comments to 3000 characters, and makes the error message more descriptive if the limit's exceeded ({pull}170764[#170764]).
* Adds missing alerts index filtration from sourcerer that was removed during refactoring ({pull}170484[#170484]).
* Fixes a bug that didn't allow exceptions to be created or edited after an error displayed ({pull}169801[#169801]).
* Stops {security-app} pages from crashing when there's a fields error in the **Stack by** component ({pull}168411[#168411]).