[discrete]
[[release-notes-8.14.0]]
=== 8.14.0

[discrete]
[[features-8.14.0]]
==== New features
* Attack discovery ({kibana-pull}181818[#181818]).
* Unified Timeline - Implement Row Renderers ({kibana-pull}180669[#180669]).
* Adds Kibana e2e support for Auditbeat ({kibana-pull}179985[#179985]).
* Integrate new navigation in stateful ({kibana-pull}179971[#179971]).
* Create Asset Criticality CSV upload page ({kibana-pull}179891[#179891]).
* Adds alert suppression for New Terms rule type ({kibana-pull}178294[#178294]).
* Allow users to edit setup field for custom rules ({kibana-pull}178131[#178131]).
* Use expandable flyout in timeline ({kibana-pull}177087[#177087]).
* Adds asset criticality advanced setting to serverless ({kibana-pull}176991[#176991]).
* Adds Suppression to EQL Non-sequence based queries ({kibana-pull}176422[#176422]).
* Enables `xpack.ml.nlp.enabled` for Security Serverless project ({kibana-pull}175358[#175358]).
* Security AI Assistant persistent storage ({kibana-pull}173487[#173487]).

[discrete]
[[enhancements-8.14.0]]
==== Enhancements
* Attack discovery ({kibana-pull}181818[#181818]).
* Security solution ES|QL configurable via advanced setting ({kibana-pull}181616[#181616]).
* Prettify asset criticality alert column ({kibana-pull}180868[#180868]).
* Remove technical preview tag from ES|QL tab ({kibana-pull}180838[#180838]).
* Unified Timeline - Implement Row Renderers ({kibana-pull}180669[#180669]).
* Adds advanced setting to disable memory scan on behavior alerts ({kibana-pull}180636[#180636]).
* Adds _source back to security solution flyout ({kibana-pull}180477[#180477]).
* AI Assistant - Turn streaming on by default ({kibana-pull}180095[#180095]).
* Adds Kibana e2e support for Auditbeat ({kibana-pull}179985[#179985]).
* Integrate new navigation in stateful ({kibana-pull}179971[#179971]).
* Create Asset Criticality CSV upload page ({kibana-pull}179891[#179891]).
* Persists the alert details flyout right panel selected tab in localStorage ({kibana-pull}179511[#179511]).
* Bedrock Claude 3 Support ({kibana-pull}179304[#179304]).
* Defend Advanced Policy Option to Opt-Out of New Optimization ({kibana-pull}179179[#179179]).
* Persists the alert details flyout overview panel expandable section open/collapsed state in localStorage ({kibana-pull}178746[#178746]).
* Limit the number of alerts considered for an entities risk score to the top 10,000 highest risk ({kibana-pull}178324[#178324]).
* Adds alert suppression for New Terms rule type ({kibana-pull}178294[#178294]).
* Allow users to edit setup field for custom rules ({kibana-pull}178131[#178131]).
* Improves ES|QL investigation fields for detection rules ({kibana-pull}177746[#177746]).
* Use expandable flyout in timeline ({kibana-pull}177087[#177087]).
* Adds asset criticality advanced setting to serverless ({kibana-pull}176991[#176991]).
* Adds tooltip to asset criticality accordion ({kibana-pull}176927[#176927]).
* Adds Security AI assistant settings to the Stack management ({kibana-pull}176656[#176656]).
* Adds Suppression to EQL Non-sequence based queries ({kibana-pull}176422[#176422]).
* Enables `xpack.ml.nlp.enabled` for Security Serverless project ({kibana-pull}175358[#175358]).
* Updates MITRE ATT&CK framework to `v14.1` ({kibana-pull}174120[#174120]).
* Security AI Assistant persistent storage ({kibana-pull}173487[#173487]).

[discrete]
[[bug-fixes-8.14.0]]
==== Bug fixes
* Enable advanced setting assertion in the Asset Criticality upsert route ({kibana-pull}181780[#181780]).
* Escape username correctly ({kibana-pull}181709[#181709]).
* Fixes entity analytics UI issues on dark mode ({kibana-pull}181431[#181431]).
* Show `observer.serial_number` info on Table view for SentinelOne alerts (instead of agent status) ({kibana-pull}181038[#181038]).
* Fixes warning toasts on exception flyout ({kibana-pull}180800[#180800]).
* Migrate bulk enable/diable rules to Alerting methods ({kibana-pull}180796[#180796]).
* Fixes disabled preview for ML rule ({kibana-pull}180792[#180792]).
* Fixes 'is one of' filter dsl ({kibana-pull}180455[#180455]).
* Fixes threat intel edit filters ({kibana-pull}179607[#179607]).
* Fixes Entity Analytics dashboard fires many risk_score/index_status requests ({kibana-pull}179510[#179510]).
* Display rule type query text for non-custom query rule types ({kibana-pull}178821[#178821]).
* Fixes threat intelligence loading screen ({kibana-pull}178701[#178701]).
* Action not allowed (405) is shown for Duplicating Shared Exception Lists ({kibana-pull}178674[#178674]).
* Fixes behavior of pinnend events and comments on unsaved timelines ({kibana-pull}178212[#178212]).
* Fixes conflicting indicators in topN popover ({kibana-pull}177213[#177213]).
* Fixes wrong breadcrumbs for the risk score management page on Serverless ({kibana-pull}176999[#176999]).

