[[release-notes-header-8.3.0]]
== 8.3

[discrete]
[[release-notes-8.3.0]]
== 8.3.0

[discrete]
[[breaking-changes-8.3.0]]
==== Breaking changes
// tag::breaking-changes[]
// NOTE: The breaking-changes tagged regions are reused in the Elastic Installation and Upgrade Guide. The pull attribute is defined within this snippet so it properly resolves in the output.
:pull: https://github.com/elastic/kibana/pull/
* Adds confirmation modal with docs link when updating rules if V1/V2 jobs are installed ({pull}128334[#128334]).
// end::breaking-changes[]

[discrete]
[[features-8.3.0]]
==== Features
* Adds new fields to the rule model: Related Integrations, Required Fields, and Setup {pull}132409[#132409]
* 131827 Update Detections Response view with pagination and opening numbers in timeline {pull}131828[#131828]
* Adds UI for new Rule Fields: Related Integrations, Required Fields, and Setup {pull}131475[#131475]
* 131028 implement recently opened cases table {pull}131029[#131029]
* Adds Dashboards and Threat Hunting Landing pages {pull}130905[#130905]
* Cases by status {pull}130670[#130670]
* Adds risk tab to the user details page {pull}130256[#130256]
* Adds the authentication tab to the user details page {pull}129456[#129456]
* Open alerts by Rule {pull}129021[#129021]
* Adds to timeline button {pull}128596[#128596]
* Hosts and Users by severity {pull}128335[#128335]
* Soc dashboard - UI {pull}128087[#128087]

[discrete]
[[bug-fixes-8.3.0]]
==== Bug fixes and enhancements
* Separates array values in the Alerts table with commas ({pull}133297[#133297]).
* Exposes the EQL search configurations `event_category_field`, `tiebreaker_field`, and `timestamp_field` through the rules API and UI for Event Correlation rules ({pull}132247[#132247]).
* Adds the *Session ID* field to the *Highlighted fields* section on the Alert details flyout ({pull}132219[#132219]).
* Introduces a new design for the main navigation menu ({pull}132210[#132210]):
** New side navigation ({pull}131437[#131437]).
** Adds Dashboards and Threat Hunting Landing pages ({pull}130905[#130905]).
* Introduces the Detections & Response dashboard:
** Cases by status ({pull}130670[#130670]).
** Open alerts by Rule ({pull}129021[#129021]).
** Implements recently opened cases table ({pull}131029[#131029]).
** Hosts and Users by severity ({pull}128335[#128335])
** Soc dashboard - UI ({pull}128087[#128087])
** Update Detections Response view with pagination and opening numbers in Timeline ({pull}131828[#131828], {pull}131029[#131029]).
* Allows highlighted fields to be investigated in Timeline ({pull}131255[#131255]).
* Adds support to Osquery for multi-line queries ({pull}131224[#131224]).
* Adds integration of rulesClient.bulkEdit method to detections area ({pull}130924[#130924]).
* Adds the *User risk* tab to the user details page ({pull}130256[#130256]).
* Adds default osquery_saved_query objects ({pull}129461[#129461]).
* Fixes ungraceful failure when rule details page opened on non-existent rule ({pull}133867[#133867]).
* Allows threshold alerts to be investigated in Timeline if filters are not provided ({pull}133733[#133733]).
* Prevents events from being added to cases from Timeline ({pull}133410[#133410]).
* Fixes All Users and All Hosts page should reset the current page when sorting ({pull}133111[#133111]).
* Removes the filter and investigate in Timeline options from the Elastic Agent status in Highlighted fields ({pull}132829[#132829], {pull}132586[#132586]).
* Improves the copy of Timeline tooltips ({pull}132756[#132756]).
* Fixes a validation bug that occurred when users were building a rule exception and changed the exception statement’s operator ({pull}131989[#131989]).
* Adds a checkmark to the pagination selection on the *Exceptions lists* page ({pull}131979[#131979]).
* Re-adds the success message that displays when users export an exceptions list ({pull}131952[#131952]).
* Updates import toast logic ({pull}131873[#131873]).
* Fixes error while checking `agent.version` compatibility for host Isolation that causes Security Solution app to crash ({pull}131272[#131272]).
* Improves error checks for threshold rules ({pull}131088[#131088]).
* Make Osquery All with All base privillege ({pull}130523[#130523]).
* Expanded the scope of the export rule API to consider more complex scenarios ({pull}130511[#130511]).
* Fixes modal closure on addition of first exception list added to a rule ({pull}130187[#130187]).
* Fixes incorrect detection rules sort order ({pull}130105[#130105]).
