[[release-notes-header-8.4.0]]
== 8.4

[discrete]
[[release-notes-8.4.3]]
=== 8.4.3

[discrete]
[[bug-fixes-8.4.3]]
==== Bug fixes and enhancements
* Aligns the delete icon in the Add Rule Exception flyout ({kibana-pull}141365[#141365]).
* Aligns the warning message title on the Rule details page with the warning icon ({kibana-pull}140719[#140719]).
* Fixes a bug that sometimes caused {elastic-endpoint} to stop running on Windows endpoints (https://github.com/elastic/endpoint/issues/29[#29]).

[discrete]
[[release-notes-8.4.2]]
=== 8.4.2

[discrete]
[[known-issue-8.4.2]]
==== Known issues
* A new Lucene 9 validation change may cause event correlation rule (EQL) errors whenever rule queries contain regular expressions using wildcard fields and predefined character classes (for example, `\w`, `\s`, `\d`).
* In some situations, {elastic-endpoint} might change to a non-running state on Windows endpoints and fail to restart. {agent} will have an `Unhealthy` status when this happens (https://github.com/elastic/endpoint/issues/29[#29]).
+
To determine whether {elastic-endpoint} has stopped running because of this issue, run the following PowerShell command as an administrator:

+
[source,console]
--------------------------------------------------
PS C:\Users\user> Get-WinEvent Microsoft-Windows-CodeIntegrity/Operational | where Id -eq 3004 | where Message -match "elastic-endpoint.exe"


   ProviderName: Microsoft-Windows-CodeIntegrity

TimeCreated                      Id LevelDisplayName Message
-----------                      -- ---------------- -------
9/22/2022 10:47:35 AM          3004 Error            Windows is unable to verify the image integrity of the file \Device\HarddiskVolume3\Program Files\Elastic\Endpoint\elastic-endpo...
9/19/2022 2:10:14 PM           3004 Error            Windows is unable to verify the image integrity of the file \Device\HarddiskVolume3\Program Files\Elastic\Endpoint\elastic-endpo...
--------------------------------------------------

+

If {elastic-endpoint} is not running, there are several workarounds you can take:

** **Manually uninstall, then reinstall {elastic-endpoint} on affected hosts**: Remove an invalid {elastic-endpoint} installation by running the {elastic-endpoint} <<uninstall-endpoint,uninstall command>> on affected hosts. Once the uninstallation process has finished, run the following command to restart {agent}, which automatically reinstalls {elastic-endpoint}:
+
[source,console]
--------------------------------------------------
c:\Program Files\Elastic\Agent\elastic-agent.exe restart
--------------------------------------------------

** **Uninstall, then reinstall the {endpoint-cloud-sec} integration on affected hosts**: Uninstalling and reinstalling the {endpoint-cloud-sec} integration on affected hosts will also force the uninstallation and reinstallation of {elastic-endpoint} on these hosts.
+
NOTE: Uninstalling the {endpoint-cloud-sec} integration may temporarily cause {agent}'s status to be `Unhealthy`. The status will change to `Healthy` once the integration is reinstalled.

** **Downgrade {agent} and {elastic-endpoint} versions**: Downgrading to unaffected {agent} and {elastic-endpoint} versions resolves this issue.

[discrete]
[[bug-fixes-8.4.2]]
==== Bug fixes and enhancements
* Removes access to the **Notes** and **Pinned** tabs in Timeline templates ({kibana-pull}140478[#140478]).
* Fixes a bug with the **Attach to existing case** option in Timeline ({kibana-pull}139929[#139929]).
* Fixes bugs in the Rules table that affected the selected rule count and bulk select feature ({kibana-pull}139461[#139461]).
* Fixes a bug that caused the Rules page to incorrectly notify users that a prebuilt rules update was available, even after rules were fully updated ({kibana-pull}139287[#139287]).
* Fixes a bug that prevented users from accessing alert details if they didn't have the appropriate privileges to view the internal index `.internal.alerts-security.alerts-<Kibana-space>`. Now, the Alert details flyout correctly uses the public alias index `.alerts-security.alerts-<Kibana-space>` ({kibana-pull}138331[#138331]).

[discrete]
[[release-notes-8.4.1]]
=== 8.4.1

[discrete]
[[known-issue-8.4.1]]
==== Known issues
* A new Lucene 9 validation change may cause event correlation (EQL) rule errors whenever rule queries contain regular expressions using wildcard fields and predefined character classes (for example, `\w`, `\s`, `\d`).
* In some situations, {elastic-endpoint} might change to a non-running state on Windows endpoints and fail to restart. {agent} will have an `Unhealthy` status when this happens (https://github.com/elastic/endpoint/issues/29[#29]).
+
To determine whether {elastic-endpoint} has stopped running because of this issue, run the following PowerShell command as an administrator:

+
[source,console]
--------------------------------------------------
PS C:\Users\user> Get-WinEvent Microsoft-Windows-CodeIntegrity/Operational | where Id -eq 3004 | where Message -match "elastic-endpoint.exe"


   ProviderName: Microsoft-Windows-CodeIntegrity

TimeCreated                      Id LevelDisplayName Message
-----------                      -- ---------------- -------
9/22/2022 10:47:35 AM          3004 Error            Windows is unable to verify the image integrity of the file \Device\HarddiskVolume3\Program Files\Elastic\Endpoint\elastic-endpo...
9/19/2022 2:10:14 PM           3004 Error            Windows is unable to verify the image integrity of the file \Device\HarddiskVolume3\Program Files\Elastic\Endpoint\elastic-endpo...
--------------------------------------------------

+

If {elastic-endpoint} is not running, there are several workarounds you can take:

** **Manually uninstall, then reinstall {elastic-endpoint} on affected hosts**: Remove an invalid {elastic-endpoint} installation by running the {elastic-endpoint} <<uninstall-endpoint,uninstall command>> on affected hosts. Once the uninstallation process has finished, run the following command to restart {agent}, which automatically reinstalls {elastic-endpoint}:
+
[source,console]
--------------------------------------------------
c:\Program Files\Elastic\Agent\elastic-agent.exe restart
--------------------------------------------------

** **Uninstall, then reinstall the {endpoint-cloud-sec} integration on affected hosts**: Uninstalling and reinstalling the {endpoint-cloud-sec} integration on affected hosts will also force the uninstallation and reinstallation of {elastic-endpoint} on these hosts.
+
NOTE: Uninstalling the {endpoint-cloud-sec} integration may temporarily cause {agent}'s status to be `Unhealthy`. The status will change to `Healthy` once the integration is reinstalled.

** **Downgrade {agent} and {elastic-endpoint} versions**: Downgrading to unaffected {agent} and {elastic-endpoint} versions resolves this issue.

[discrete]
[[bug-fixes-8.4.1]]
==== Bug fixes and enhancements
* Fixes a bug that caused the Rules page to incorrectly notify users that a prebuilt rules update was available, even after rules were fully updated ({kibana-pull}139287[#139287]).

[discrete]
[[release-notes-8.4.0]]
=== 8.4.0

[discrete]
[[known-issue-8.4.0]]
==== Known issues
* If additional look-back time is set for the advanced query rule preview, alerts from source documents that are outside the preview time frame may not appear in the preview ({kibana-pull}137422[#137422]).
* A new Lucene 9 validation change may cause event correlation (EQL) rule errors whenever rule queries contain regular expressions using wildcard fields and predefined character classes (for example, `\w`, `\s`, `\d`).
* The Rules page incorrectly displays a notification that an update for prebuilt rules is available even if the rules have been fully updated. Currently, there is no way to remove or hide the notification ({kibana-pull}139095[#139095]).
* In some situations, {elastic-endpoint} might change to a non-running state on Windows endpoints and fail to restart. {agent} will appear `Unhealthy` when this happens (https://github.com/elastic/endpoint/issues/29[#29]).
+
To determine whether {elastic-endpoint} has stopped running because of this issue, run the following PowerShell command as an administrator:

+
[source,console]
--------------------------------------------------
PS C:\Users\user> Get-WinEvent Microsoft-Windows-CodeIntegrity/Operational | where Id -eq 3004 | where Message -match "elastic-endpoint.exe"


   ProviderName: Microsoft-Windows-CodeIntegrity

TimeCreated                      Id LevelDisplayName Message
-----------                      -- ---------------- -------
9/22/2022 10:47:35 AM          3004 Error            Windows is unable to verify the image integrity of the file \Device\HarddiskVolume3\Program Files\Elastic\Endpoint\elastic-endpo...
9/19/2022 2:10:14 PM           3004 Error            Windows is unable to verify the image integrity of the file \Device\HarddiskVolume3\Program Files\Elastic\Endpoint\elastic-endpo...
--------------------------------------------------

+

If {elastic-endpoint} is not running, there are several workarounds you can take:

** **Manually uninstall, then reinstall {elastic-endpoint} on affected hosts**: Remove an invalid {elastic-endpoint} installation by running the {elastic-endpoint} <<uninstall-endpoint,uninstall command>> on affected hosts. Once the uninstallation process has finished, run the following command to restart {agent}, which automatically reinstalls {elastic-endpoint}:
+
[source,console]
--------------------------------------------------
c:\Program Files\Elastic\Agent\elastic-agent.exe restart
--------------------------------------------------

** **Uninstall, then reinstall the {endpoint-cloud-sec} integration on affected hosts**: Uninstalling and reinstalling the {endpoint-cloud-sec} integration on affected hosts will also force the uninstallation and reinstallation of {elastic-endpoint} on these hosts.
+
NOTE: Uninstalling the {endpoint-cloud-sec} integration may put {agent}  in an `Unhealthy` state. This is temporary and the state will change to `Healthy` once the integration is reinstalled.

** **Downgrade {agent} and {elastic-endpoint} versions**: Downgrading to unaffected {agent} and {elastic-endpoint} versions resolves this issue.

[discrete]
[[breaking-changes-8.4.0]]
==== Breaking changes

There are no breaking changes in 8.4.0.

[discrete]
[[features-8.4.0]]
==== Features
* Creates a new rule type, New Terms, that creates an alert when a value appears for the first time in a particular field ({kibana-pull}134526[#134526]).
* Adds the Insights section to the Alert details flyout to show related cases and alerts ({kibana-pull}136009[#136009], {kibana-pull}138419[#138419])
* Shows process alerts in the event process analyzer ({kibana-pull}135340[#135340]).
* Adds support for wildcard exceptions for detection rules. New operators are `matches` and `does not match` ({kibana-pull}136147[#136147]).
* Adds a new search query parameter, `dry_run`, to the bulk actions API that allows you to simulate a bulk action without permanently updating rules ({kibana-pull}134664[#134664]).
* Creates the response console, an interface that enables you to take actions on specific hosts ({kibana-pull}135360[#135360], {kibana-pull}134520[#134520]).
* Includes integration policy errors and statuses in {fleet} and {elastic-sec} to help troubleshoot when an {agent} has an `Unhealthy` status ({kibana-pull}136241[#136241], {kibana-pull}136038[#136038]).
* Adds Attack surface reduction protections feature to reduce vulnerabilities on Windows endpoints. Credential hardening prevents attackers from stealing credentials stored in Windows system process memory.
* Adds an endpoint self-healing feature to roll back file changes and processes on Windows endpoints when a prevention alert is generated by enabled protection features.
* Adds the ability to run query packs as live queries ({kibana-pull}132198[#132198]).
* Provides support for process, file, and network events in Kubernetes. You must enable the session view data setting on your {endpoint-cloud-sec} integration policy to enrich these events with session data and Kubernetes metadata fields.
* Adds support for Amazon Elastic Kubernetes Service (EKS) to Kubernetes Security Posture Management (KSPM).
* Adds new fields to prebuilt detection rules' schemas: `related_integrations`, `required_fields`, and `setup` ({kibana-pull}132409[#132409]).
* Adds the *Related integrations*, *Required fields*, and *Setup guide* sections to the rule details page to help users identify and meet a rule's prerequisites. Also adds the related integrations badge to the Rules table ({kibana-pull}131475[#131475]).

[discrete]
[[bug-fixes-8.4.0]]
==== Bug fixes and enhancements
* Updates the Network page's UI to match the Hosts and Users pages ({kibana-pull}137541[#137541], {kibana-pull}136913[#136913]).
* Improves the experience of bulk editing index patterns on rules by warning users early that machine learning rules can’t be edited ({kibana-pull}134664[#134664]).
* Enhances rule previews with configurable rule intervals and look-back times ({kibana-pull}137102[#137102]).
* Enhances the `status pending` badge for endpoint actions with a detailed status when you hover on it ({kibana-pull}136966[#136966]).
* Turns grouped navigation on by default ({kibana-pull}136819[#136819]).
* Improves the experience of bulk exporting rules by informing users early which rules can and cannot be exported ({kibana-pull}136418[#136418]).
* Adds index pattern information to the Inspect panel ({kibana-pull}136407[#136407]).
* Adds a custom dashboards table to the Dashboards page ({kibana-pull}136221[#136221], {kibana-pull}136671[#136671]).
* Fixes a performance issue with creating alerts from source documents that contain a large number of fields ({kibana-pull}135956[#135956]).
* Updates the rule exceptions UI ({kibana-pull}135255[#135255]).
* Fixes performance issues with rules management ({kibana-pull}135311[#135311]).
* Allows you to disable `@timestamp` as a fallback timestamp field when you've defined a timestamp override ({kibana-pull}135116[#135116]).
* Enhances the host risk score UI ({kibana-pull}133708[#133708]).
* Updates the lists index template to use new logic ({kibana-pull}133067[#133067]).
* Adds event filters to event correlation rules ({kibana-pull}132507[#132507]).
* Allows you to define a data view as the rule's data source, making runtime fields available for rule configuration ({kibana-pull}130929[#130929]).
* Creates a single visualization pane on the Alerts page, and adds a treemap visualization that shows the distribution of alerts as nested, proportionally-sized tiles ({kibana-pull}126896[#126896]).
* Fixes an incorrect counter for exported rules ({kibana-pull}138598[#138598]).
* Fixes event filters based on OS version ({kibana-pull}138517[#138517]).
* Fixes a bug that could change the batch size for event search in indicator rules ({kibana-pull}138356[#138356]).
* Fixes a bug that prevented users from accessing alert details if they didn't have the appropriate privileges to view the internal index `.internal.alerts-security.alerts-<Kibana-space>`. Now, the Alert details flyout correctly uses the public alias index `.alerts-security.alerts-<Kibana-space>` ({kibana-pull}138331[#138331]).
* Fixes the preview button for {ml} rules ({kibana-pull}137878[#137878]).
* Fixes a bug that could crash the Endpoints list when a policy ID was missing ({kibana-pull}137788[#137788]).
* Fixes a bug that could interfere with opening host or user details pages ({kibana-pull}137719[#137719]).
* Fixes several bugs related to refreshing the Alerts page ({kibana-pull}137620[#137620]).
* Fixes a bug that prevented threshold rules' Timeline templates from being respected during investigations ({kibana-pull}137233[#137233]).
* Fixes a permissions bug related to the **Save Timeline** button ({kibana-pull}136724[#136724]).
* Fixes a bug with selecting Timeline templates with the same name ({kibana-pull}135694[#135694]).
* Fixes field aliases to `signal-threshold_result.*` ({kibana-pull}135565[#135565]).
* Fixes a bug that lost track of which rules you had selected after refreshing the Rules page ({kibana-pull}135533[#135533]).
* Fixes a bug that lost track of which rules you had selected after applying a bulk action on the Rules page ({kibana-pull}135291[#135291]).
* Fixes a bug that prevented the Rules table from pausing auto-refresh while bulk actions were being applied ({kibana-pull}135208[135208]).
* Fixes a bug that could cause queries with nested fields to fail when opened ({kibana-pull}134866[#134866]).
* Fixes a bug that slowed down the display of network details ({kibana-pull}133539[#133539]).
* Various minor bug fixes and enhancements ({kibana-pull}133079[#133079], {kibana-pull}138135[#138135], {kibana-pull}137588[#137588], {kibana-pull}137511[#137511], {kibana-pull}137492[#137492], {kibana-pull}135907[#135907], {kibana-pull}135426[#135426]).
* Fixes an {endpoint-cloud-sec} bug on macOS and Linux that could cause CPU spikes if malware protection is enabled on an {endpoint-cloud-sec} integration policy (https://github.com/elastic/endpoint/issues/22[#22]).
* Fixes a bug that could cause {endpoint-cloud-sec} to crash when outputting log data to {ls}.
* Allows {endpoint-cloud-sec} to be added to agents running on Ubuntu 22.04 and Debian 11.
