[[release-notes-header-8.7.0]]
== 8.7

[discrete]
[[release-notes-8.7.0]]
=== 8.7.0

[discrete]
[[known-issue-8.7.0]]
==== Known issues

[discrete]
[[breaking-changes-8.7.0]]
==== Breaking changes

// tag::breaking-changes[]
// NOTE: The breaking-changes tagged regions are reused in the Elastic Installation and Upgrade Guide. The pull attribute is defined within this snippet so it properly resolves in the output.
:pull: https://github.com/elastic/kibana/pull/
There are no breaking changes in 8.7.0.
// end::breaking-changes[]


[discrete]
[[deprecations-8.7.0]]
==== Deprecations
There are no deprecations in 8.7.0.


[discrete]
[[features-8.7.0]]
==== Features
* Creates a new dashboard, Data Quality, which highlights any issues in your ECS field mappings ({pull}150063[#150063]).
* Creates a Torq connector that can trigger Torq workflows ({pull}149405[#149405]).
* Adds more key performance indicator charts to the Alerts page ({pull}150242[#150242],{pull}149173[#149173], and {pull}146938[#146938]).
* Adds filters to the Alerts page ({pull}146989[#146989]).
* Enables you to set expiration dates for rule exceptions, and to choose whether to include expired exceptions when you export exception lists ({pull}145180[#145180]).
* Enables you to take additional actions on embedded Lens objects: "Copy to clipboard" and "Add to timeline investigation" ({pull}146779[#146779]).
* Enables you to include connectors when exporting and importing rules ({pull}148703[#148703]).
* Adds "Group by" functionality to the Alerts table (technical preview)({pull}149145[#149145]).
* Improves the UI for building an Investigation Guide query ({pull}150363[#150363]).
* Adds the option to "Create rule from timeline" to the more actions menu for individual timelines on the Timelines page ({pull}143020[#143020]).

[discrete]
[[bug-fixes-8.7.0]]
==== Bug fixes and enhancements
* Various bug fixes and UX enhancements for the Alerts page ({pull}152402[#152402]).
* Improves the formatting and readability of machine learning job names ({pull}148974[#148974],{pull}148780[#148780]).
* Improves the performance of Indicator Match rules by removing unnecessary source fields ({pull}149113[#149113]).
* Warns you about type conflicts and unmapped indices when you're creating rule exceptions ({pull}149149[#149149]).
* Improves sorting of the Rules table: allows you to sort it by any column, removes the "Advanced sorting" toggle, and removes the unnecessary "version" column ({pull}149840[#149840]).
* Adds a "Clear table filters" button to the Rules page so you can clear all filters in one click ({pull}150059[#150059]).
* Adds buttons to the Rules page that allow you to view only enabled or disabled rules ({pull}150153[#150153]).
* The Alert details page's "Related alerts by process ancestry" insight is now in GA. The beta tag has been removed from the UI ({pull}152011[#152011]).
* Adds the option to suppress Custom Query rule alerts per a custom time window. Duplicate alerts within that time window will be grouped ({pull}148868[#148868]).
* Reduces Alert creation errors by stopping the detection engine from writing non-ECS-compliant fields to Alerts from source events ({pull}147628[#147628]).
* Simplifies the interface for navigating from a rule details page back to the Rules page ({pull}147357[#147357]).
* Allows you to resize the Rule preview panel ({pull}147351[#147351]).
* Improves the Bulk Edit API by adding a "skipped" property to rules that weren't updated, and updates the toast message to show which were skipped ({pull}147345[#147345]).
* Enables Osquery queries triggered by an alert to include parameters from the alert ({pull}146598[#146598]).
* Makes the Rules table's state persist even after you refresh or navigate to another page ({pull}145111[#145111]).

* Fixes a bug that could cause your cursor to jump to the end of the text field when editing a rule action message ({pull}150823[#150823]).
* Fixes a bug that could result in incorrect links to machine learning jobs from search results ({pull}150881[#150881]).
* Fixes a bug that caused a fade in / fade out effect on alert descriptions ({pull}150998[#150998]).
