[[release-notes-header-8.7.0]]
== 8.7

[discrete]
[[release-notes-8.7.0]]
=== 8.7.0

[discrete]
[[known-issue-8.7.0]]
==== Known issues

[discrete]
[[breaking-changes-8.7.0]]
==== Breaking changes

// tag::breaking-changes[]
// NOTE: The breaking-changes tagged regions are reused in the Elastic Installation and Upgrade Guide. The pull attribute is defined within this snippet so it properly resolves in the output.
:pull: https://github.com/elastic/kibana/pull/
There are no breaking changes in 8.7.0.
// end::breaking-changes[]


[discrete]
[[deprecations-8.7.0]]
==== Deprecations
There are no deprecations in 8.7.0.


[discrete]
[[features-8.7.0]]
==== Features
* Creates a new dashboard, Data Quality, which highlights any issues in your ECS field mappings ({pull}150063[#150063]).
* Adds more key performance indicator charts to the Alerts page ({pull}150242[#150242],{pull}149173[#149173], and {pull}146938[#146938]).
* Adds filters to the Alerts page ({pull}146989[#146989]).
* Enables you to set expiration dates for rule exceptions, and to choose whether to include expired exceptions when you export exception lists ({pull}145180[#145180]).
* Enables you to take additional actions on embedded Lens objects: "Copy to clipboard" and "Add to timeline investigation" ({pull}146779[#146779]).
* Enables you to include connectors when exporting and importing rules ({pull}148703[#148703]).
* Adds "Group by" functionality to the Alerts table (technical preview)({pull}149145[#149145]).
* Improves the UI for building an Investigation Guide query ({pull}150363[#150363]).

[discrete]
[[bug-fixes-8.7.0]]
==== Bug fixes and enhancements
* Various bug fixes and UX enhancements for the Alerts page ({pull}152402[#152402]).
* Makes machine learning job names more readable in several places ({pull}148974[#148974]).
* Improves the performance of Indicator Match rules by removing unnecessary source fields ({pull}149113[#149113]).
* 
