[[release-notes-header-8.7.0]]
== 8.7

[discrete]
[[release-notes-8.7.0]]
=== 8.7.0

[discrete]
[[known-issue-8.7.0]]
==== Known issues
* After alerts are generated for the first time, you may have to refresh your browser before your alert data appears on pages that use data views (for example, Timeline). Navigating between pages will not work (https://github.com/elastic/security-docs/issues/3046[#3046]).

[discrete]
[[breaking-changes-8.7.0]]
==== Breaking changes

// tag::breaking-changes[]
// NOTE: The breaking-changes tagged regions are reused in the Elastic Installation and Upgrade Guide. The pull attribute is defined within this snippet so it properly resolves in the output.
:pull: https://github.com/elastic/kibana/pull/
There are no breaking changes in 8.7.0.
// end::breaking-changes[]


[discrete]
[[deprecations-8.7.0]]
==== Deprecations
There are no deprecations in 8.7.0.


[discrete]
[[features-8.7.0]]
==== Features
* Creates a new dashboard, Data Quality, which highlights any issues in your ECS field mappings ({pull}150063[#150063]).
* Introduces a new event type (`Credential access`) to represent credential dumping attempts on Windows by tools like Mimikatz or fgdump.
* Creates a Torq connector that can trigger Torq workflows ({pull}149405[#149405]).
* Adds more key performance indicator charts to the Alerts page ({pull}150242[#150242], {pull}149173[#149173], and {pull}146938[#146938]).
* Adds filters to the Alerts page ({pull}146989[#146989]).
* Enables you to set expiration dates for rule exceptions and choose whether to include expired exceptions when you export shared exception lists ({pull}145180[#145180]).
* Adds two more inline actions (*Copy to clipboard* and *Add to timeline investigation*) to chart legends and tables ({pull}146779[#146779]).
* Enables you to include connectors when exporting and importing rules ({pull}148703[#148703]).
* Adds "Group by" functionality to the Alerts table. (Technical preview only)({pull}149145[#149145]).
* Improves the UI for building an Investigation Guide query ({pull}150363[#150363]).
* Adds the ability to create a rule from a Timeline ({pull}143020[#143020]).

[discrete]
[[bug-fixes-8.7.0]]
==== Bug fixes and enhancements
* Various bug fixes and UX enhancements for the Alerts page ({pull}152402[#152402]).
* Improves the formatting and readability of machine learning job names ({pull}148974[#148974], {pull}148780[#148780]).
* Introduces cross-cluster search support for Indicator Match rules by improving rule performance ({pull}149113[#149113]).
* Warns you about type conflicts and unmapped indices when you're creating rule exceptions ({pull}149149[#149149]).
* Improves sorting of the Rules table: allows you to sort it by any column, removes the *Advanced sorting* toggle, and removes the unnecessary `Version` column ({pull}149840[#149840]).
* Adds a *Clear table filters* button to the Rules page so you can clear all filters in one click ({pull}150059[#150059]).
* Adds buttons to the Rules page that allow you to view only enabled or disabled rules ({pull}150153[#150153]).
* The *Related alerts by process ancestry* section of the Alert details flyout is now GA ({pull}152011[#152011]).
* Adds the option to suppress custom query rule alerts during a specific time window. Duplicate alerts within that time window will be grouped ({pull}148868[#148868]).
* Reduces alert creation errors by stopping the detection engine from writing non-ECS-compliant fields to alerts from source events ({pull}147628[#147628]).
* Simplifies the interface for navigating from a rule's details page back to the Rules page ({pull}147357[#147357]).
* Allows you to resize the Rule preview panel ({pull}147351[#147351]).
* Improves the Bulk Edit API by adding a `skipped` property to rules that weren't updated, and updates the toast message to show which were skipped ({pull}147345[#147345]).
* Allows placeholder fields in Osquery queries ({pull}146598[#146598]).
* Allows the Rules table state to persist even after you refresh or navigate to another page ({pull}145111[#145111]).
* Improves data fetch performance throughout {elastic-sec}, especially for deployments with large indices and many integrations ({pull}142904[#142904]).
* Fixes a bug that could cause your cursor to jump to the end of the text field when editing a rule action message ({pull}150823[#150823]).
* Fixes a bug that could result in incorrect links to machine learning jobs from search results ({pull}150881[#150881]).
* Fixes a bug that caused a fade in and out effect on alert descriptions ({pull}150998[#150998]).
* Fixes a bug that caused the Alerts page to default to the wrong chart type ({pull}151073[#151073]).
* Fixes a bug that could hide some shared exception lists when you changed the number of rows in the exceptions lists view ({pull}151393[#151393]).
* Removes a blank option from the *Field* browser in the Add rule exception flyout ({pull}151398[#151398]).
* Fixes a UI text bug that conflated Endpoint exceptions with regular rule exceptions ({pull}151532[#151532]).
* Fixes a bug that could cause an unnecessary warning to display in the Add rule exception flyout ({pull}151570[#151570]).
* Fixes a bug with the empty state that appears when your exception lists search yields no results ({pull}151530[#151530]).
* Fixes a bug that sometimes prevented a Timeline from saving when it was created using the *Investigate in timeline* action on an alert ({pull}151616[#151616]).
* Fixes a bug that could result in unnecessary validation errors in text entry fields in the Add rule exception flyout ({pull}151654[#151654]).
* Fixes a bug that caused some module names to be partially hidden on the Overview dashboard ({pull}151843[#151843]).
* Fixes a visual bug that affected empty rule previews ({pull}151869[#151869]).
* Fixes a bug that could cause alert details to incorrectly show installed integrations as not installed ({pull}152055[#152055]).
* Changes the *Import list* button name to *Import value list* ({pull}152281[#152281]).
* Improves the toast message that appears when you export an exception list ({pull}152301[#152301]).
* Fixes a bug that broke the visual analyzer for sysmon data ingested via {agent} ({pull}152418[#152418]).
* Fixes a bug that incorrectly allowed you to use custom fields in the Add Endpoint Exception flyout ({pull}152619[#152619]).
* Fixes a bug where the two breadcrumbs on shared exception lists pages did not use the same text ({pull}152629[#152629]).
* Fixes an issue in the Update exception item API that incorrectly merged existing objects with updated objects ({pull}151952[#151952]).