[[security-cases-requirements]]
= Cases requirements

:description: Requirements for using and managing cases.
:keywords: serverless, security, reference, manage

preview:[]

To access cases, you need either the appropriate <<general-assign-user-roles,predefined Security user role>> or a <<custom-roles,custom role>> with the right privileges.

You can create custom roles and define feature privileges at different levels to manage feature access in {kib}. {kib} privileges grant access to features within a specified {kib} space, and you can grant full or partial access. For more information, refer to <<custom-roles>>.

[NOTE]
====
To send cases to external systems, you need the Security Analytics Complete <<elasticsearch-manage-project,project feature>>.
====

[IMPORTANT]
====
Certain feature tiers and roles might be required to manage case attachments. For example, to add alerts to cases, you must have a role that allows <<enable-detections-ui,managing alerts>>.
====

To grant access to cases in a custom role, set the privileges for the **Cases** and **{connectors-feature}** features as follows:

|===
| Action | {kib} Privileges

| Give full access to manage cases and settings
a| * **All** for the **Cases** feature under **Security**
* **All** for the **{connectors-feature}** feature under **Management**

[NOTE]
====
Roles without **All** privileges for the **{connectors-feature}** feature cannot create, add, delete, or modify case connectors.

By default, **All** for the **Cases** feature allows you to delete cases, delete alerts and comments from cases, and edit case settings. You can customize the sub-feature privileges to limit feature access.
====

| Give assignee access to cases
a| **All** for the **Cases** feature under **Security**

[NOTE]
====
Before a user can be assigned to a case, they must log into {kib} at least
once, which creates a user profile.
====

| Give view-only access for cases
a| **Read** for the **Security** feature and **All** for the **Cases** feature

[NOTE]
====
You can customize the sub-feature privileges to allow access to deleting cases, deleting alerts and comments from cases, and viewing or editing case settings.
====

| Revoke all access to cases
| **None** for the **Cases** feature under **Security**
|===
