[[endpoint-protection-rules]]
= Endpoint protection rules

Endpoint protection rules are prebuilt rules designed to help you manage and respond to alerts generated by {elastic-defend}. These include the <<endpoint-security, {elastic-defend}>> rule as well as additional detection and prevention rules for different {elastic-defend} protection features.

[discrete]
== {elastic-defend} rule

The {elastic-defend} rule automatically creates an alert from all incoming Elastic Endpoint alerts. To receive Elastic Endpoint alerts, you must install the Endpoint agent on your hosts (see <<install-endpoint>>).

When this rule is enabled, the following Endpoint events are displayed as detection alerts:

** Malware Prevention Alert
** Malware Detection Alert

NOTE: When you load the prebuilt rules, this is the only rule that is enabled by default.

[discrete]
== Feature-specific protection rules

The following endpoint protection rules give you more granular control over how you handle the generated alerts. These rules are tailored for each of {elastic-defend}'s endpoint protection features—malware, ransomware, memory threats, and malicious behavior. Enabling these rules allows you to configure more specific actions based on the protection feature and whether the malicious activity was prevented or detected.

* Behavior - Detected - Elastic Defend
* Behavior - Prevented - Endpoint Defend
* Malicious File - Detected - Elastic Defend
* Malicious File - Prevented - Elastic Defend
* Memory Signature - Detected - Elastic Defend
* Memory Signature - Prevented - Elastic Defend
* Ransomware - Detected - Elastic Defend
* Ransomware - Prevented - Elastic Defend

To use these rules, you need to manually enable them on the **Rules** page of the {security-app}. Follow the instructions for <<load-prebuilt-rules,installing and enabling Elastic prebuilt rules>>.

[discrete]
== Exception handling

All endpoint protection rules share a common exception list called Endpoint Security Exception List. This ensures that if you switch between using the {elastic-defend} rule and the feature-specific protection rules, your existing exceptions continue to apply.