[[cases-api-add-comment]]
=== Add comment

Adds a comment to an existing case.

NOTE: Console supports only Elasticsearch APIs. Console doesn't allow interactions with {kib} APIs. You must use `curl` or another HTTP tool instead. For more information, refer to {kibana-ref}/console-kibana.html[Run {es} API requests].

==== Request URL

`POST <kibana host>:<port>/api/cases/<case ID>/comments`

===== URL parts

The URL must include the `case ID` of the case to which you are adding a
comment. Call <<cases-api-find-cases>> to retrieve case IDs.

==== Request body

A JSON object with a `comment` field:

[width="100%",options="header"]
|==============================================
|Name |Type |Description |Required

|`type` |String |The comment type, which must be `user` or `alert`. |Yes
|`comment` |String |The new comment. |Yes, only when type is `user`.
|`alertId` |String |The alert identifier. |Yes, only required when type is `alert`.
|`index` |String |The alert index. |Yes, only required when type is `alert`.
|`owner` |String a|The application that owns the case. Valid values are:

* `cases`
* `observability`
* `securitySolution`
|Yes, required whether the type is `user` or `alert`.
|`rule` |String a|The rule that is associated with the alert. The required properties are:

* `id` (string): The rule identifier.
* `name` (string): The rule name.

|Yes, only required when type is `alert`.
|==============================================

NOTE: Only alerts (signals) of {es-sec} are supported.

===== Example request

Adds a comment to case ID `293f1bc0-74f6-11ea-b83a-553aecdb28b6`:

[source,sh]
--------------------------------------------------
POST api/cases/293f1bc0-74f6-11ea-b83a-553aecdb28b6/comments
{
  "type": "user",
  "comment": "That is nothing - Ethan Hunt answered a targeted social
  media campaign promoting phishy pension schemes to IMF operatives.",
  "owner": "securitySolution"
}
--------------------------------------------------
// KIBANA

==== Response code

`200`::
   Indicates a successful call.

==== Response payload

The updated JSON case object with the new comment, the user who created the
comment, and the comment's ID, version, and creation time.

===== Example response

[source,json]
--------------------------------------------------

{
  "comments":[
    {
      "id": "8af6ac20-74f6-11ea-b83a-553aecdb28b6",
      "version": "WzIwNDMxLDFd",
      "type":"user",
      "owner":"cases",
      "comment":"That is nothing - Ethan Hunt answered a targeted social media campaign promoting phishy pension schemes to IMF operatives.",
      "created_at":"2022-03-24T00:49:47.716Z",
      "created_by": {
        "email": "moneypenny@hms.gov.uk",
        "full_name": "Ms Moneypenny",
        "username": "moneypenny"
      },
      "pushed_at":null,
      "pushed_by":null,
      "updated_at":null,
      "updated_by":null
    }
  ],
  "totalAlerts":0,
  "id":"293f1bc0-74f6-11ea-b83a-553aecdb28b6",
  "version":"WzIzMzgsMV0=",
  "totalComment":1,
  "title": "This case will self-destruct in 5 seconds",
  "tags": ["phishing","social engineering"],
  "description": "James Bond clicked on a highly suspicious email banner advertising cheap holidays for underpaid civil servants.",
  "settings": {
    "syncAlerts":false
  },
  "owner": "cases",
  "closed_at": null,
  "closed_by": null,
  "created_at": "2022-03-24T00:37:03.906Z",
  "created_by": {
    "email": "ahunley@imf.usa.gov",
    "full_name": "Alan Hunley",
    "username": "ahunley"
  },
  "status": "open",
  "updated_at": "2022-03-24T00:49:47.716Z",
  "updated_by": {
    "email": "moneypenny@hms.gov.uk",
    "full_name": "Ms Moneypenny",
    "username": "moneypenny"
  },
  "connector": {
    "id": "none",
    "name": "none",
    "type": ".none",
    "fields": null
  },
  "external_service": null
} 
--------------------------------------------------
