[[assign-connector]]
=== Set default {es-sec-ui} connector

Sets the default connector in the {es-sec-ui}.

Connectors are used to interface with external systems. You can only call this
method after you have created a connector (see <<register-connector>>). After a
connector has been created and assigned, call <<cases-actions-api-execute>> to
send cases to the external system.

NOTE: You can also set the default connector in the {es-sec-ui} for each case
individually (see <<cases-api-update>>).

==== Request URL

`POST <kibana host>:<port>/api/cases/configure`

==== Request body

A JSON object with these fields:

[width="100%",options="header"]
|==============================================
|Name |Type |Description |Required

|`connector` |<<assign-connector-connector-schema, connector>> |Object containing the connector's
configuration. |Yes
|`closure_type` |String a|Determines whether a case is automatically closed in
{es-sec} when it is pushed to external systems. Valid values are:

* `close-by-pushing`: {es-sec} cases are automatically closed when they
are pushed.
* `close-by-user`: {es-sec} cases are not automatically closed.

|Yes
|==============================================

[[assign-connector-connector-schema]]
*`connector` schema*

[width="100%",options="header"]
|==============================================
|Name |Type |Description |Required

|`id` |String |The ID of the connector you want to use for sending cases to external systems. |Yes
|`name` |String a|The connector name. |Yes
|`type` |String a|The type of the connector. 

Must be one of these:

* `.servicenow`
* `.jira`
* `.resilient`
* `.none`
|Yes
|`fields` |Object a| Object containing the connector's fields.

For {jira} connectors:

* `urgency` (string \| null): The urgency of the incident.
* `severity` (string \| null): The severity of the incident.
* `impact` (string \| null): The impact of the incident.

For {jira} connectors:

* `issueType` (string): The issue type of the issue.
* `priority` (string \| null): The priority of the issue.
* `parent` (string \| null): The key of the parent issue (Valid when the issue type is `Sub-task`).

For {ibm-r} connectors:

* `issueTypes` (number[]): The issue types of the issue.
* `severityCode` (number): The severity code of the issue.

|Yes
|==============================================

NOTE: Call <<cases-api-find-connectors>> to retrieve connector IDs and names.

NOTE: Fields can be set but are not being used by case configuration. You can set the fields of the connector at <<cases-api-create>>.

==== Example request

[source,sh]
--------------------------------------------------
POST api/cases/configure
{
  "connector": { 
    "id": "131d4448-abe0-4789-939d-8ef60680b498",
    "name": "Jira",
    "type": ".jira",
    "fields": null,
  },
  "closure_type": "close-by-user",
}
--------------------------------------------------

==== Response code

`200`:: 
   Indicates a successful call.
   
==== Example response

[source,json]
--------------------------------------------------
{
  "connector": { 
    "id": "131d4448-abe0-4789-939d-8ef60680b498",
    "name": "Jira",
    "type": ".jira",
    "fields": null,
  },
  "closure_type": "close-by-user",
  "created_at": "2020-03-30T13:31:38.083Z",
  "created_by": {
    "email": "moneypenny@hms.gov.uk",
    "full_name": "Ms Moneypenny",
    "username": "moneypenny"
  },
  "error": null,
  "mappings":[
    { 
      "source":"title", <1>
      "target":"summary",
      "action_type": "overwrite"
    },
    {
      "source":"description", <2>
      "target":"description",
      "action_type": "overwrite"
    },
    {
      "source":"comments", <3>
      "target":"comments",
      "action_type":"append"
    }
  ],
  "updated_at": null,
  "updated_by": null,
  "version": "WzE3NywxXQ=="
}
--------------------------------------------------

<1> {es-sec} case `title` fields are mapped to {jira} `summary`
fields. When a {es-sec} `title` field is updated and sent to {jira}, the {jira}
`summary` field is overwritten.

<2> {es-sec} case `description` fields are mapped to {jira} `description`
fields. When a {es-sec} `description` field is updated and sent to {jira},
the {jira} `description` field is overwritten.

<3> {es-sec} case `comments` fields are mapped to {jira} `comments` fields.
When a {es-sec} `comments` field is updated and sent to {jira}, the updated
text is appended to the {jira} `comments` field.