[[cases-api-find-cases-by-alert]]
=== Find cases by alert

Retrieves cases the alert is attached to.

NOTE: Console supports only Elasticsearch APIs. Console doesn't allow interactions with {kib} APIs. You must use `curl` or another HTTP tool instead. For more information, refer to {kibana-ref}/console-kibana.html[Run {es} API requests].

==== Request URL

`GET <kibana host>:<port>/api/cases/alerts/<alert ID>`

===== URL parts

The URL must include the ID of the alert (`alert ID`) attached to the case.

===== URL query parameters

[width="100%",options="header"]
|==============================================
|Name |Type |Description |Required

|`owner` |String or String[] |A filter to limit the retrieved case IDs to a specific set of applications. If this parameter is omitted, the response will contain all case IDs that the user has access to read. |No

|==============================================

===== Example request

Returns all case IDs with the alert `293f1bc0-74f6-11ea-b83a-553aecdb28b6` attached to them:

[source,sh]
--------------------------------------------------
GET api/cases/alerts/293f1bc0-74f6-11ea-b83a-553aecdb28b6
--------------------------------------------------
// KIBANA

==== Response code

`200`::
   Indicates a successful call.

==== Response payload

A JSON array with retrieved case IDs and titles.

TIP: The case ID is also the saved object ID.

===== Example response

[source,json]
--------------------------------------------------
[
    {
        "id": "8af6ac20-74f6-11ea-b83a-553aecdb28b6",
        "title": "Test 1"
    },
    {
        "id": "a18b38a0-71b0-11ea-a0b2-c51ea50a58e2",
        "title": "Test 2"
    }
]
--------------------------------------------------
