[[cases-api-update]]
=== Update case

Updates existing cases.

==== Request URL

`PATCH <kibana host>:<port>/api/cases`

==== Request body

A JSON array containing one or more case objects with updated field values:

[width="100%",options="header"]
|==============================================
|Name |Type |Description |Required

|`cases` |<<update-cases-schema, cases[]>> |Array containing one or more case objects. |Yes
|==============================================

[[update-cases-schema]]
===== `cases` schema
|==============================================
|Name |Type |Description |Required

|`id` |String |The ID of the case being updated. |Yes
|`connector` |<<case-update-connector-schema, connector>> |Object containing the connector's
configuration. |No
|`description` |String |The updated case description. |No
|`settings` |<<create-case-settings-schema-update, settings>> |Object containing the case's
settings. |No
|`status` |String a|The updated case status, which can be:

* `open`
* `in-progress`
* `closed`

|No
|`tags` |String[] |The updated case tags. |No
|`title` |String |The updated case title. |No
|`version` |String |The current case version (returned when calling
<<cases-api-get-case>> or <<cases-api-find-cases>>). |Yes
|==============================================

[[case-update-connector-schema]]
*`connector` schema*

[width="100%",options="header"]
|==============================================
|Name |Type |Description |Required

|`id` |String |ID of the <<actions-api-overview, connector>>
used for pushing case updates to external systems (returned when calling
<<cases-api-find-connectors>>). |Yes
|`name` |String a|The connector name. |Yes
|`type` |String a|The type of the connector. 

Must be one of these:

* `.servicenow`
* `.jira`
* `.resilient`
* `.none`
|Yes
|`fields` |Object a| Object containing the connector's fields.

For {sn} connectors:

* `urgency` (string \| null): The urgency of the incident.
* `severity` (string \| null): The severity of the incident.
* `impact` (string \| null): The impact of the incident.

For {jira} connectors:

* `issueType` (string): The issue type of the issue.
* `priority` (string \| null): The priority of the issue.
* `parent` (string \| null): The key of the parent issue (Valid when the issue type is `Sub-task`).

For {ibm-r} connectors:

* `issueTypes` (number[]): The issue types of the issue.
* `severityCode` (number): The severity code of the issue.

|Yes
|==============================================

[[create-case-settings-schema-update]]
*`settings` schema*

[width="100%",options="header"]
|==============================================
|Name |Type |Description |Required
|`syncAlerts` |Boolean| Turn on or off synching with alerts. | Yes
|==============================================

===== Example request

Updates the description, tags, and connector of case ID
`a18b38a0-71b0-11ea-a0b2-c51ea50a58e2`:

[source,sh]
--------------------------------------------------
PATCH api/cases
{
  "cases": [
    {
      "connector": {
        "id": "131d4448-abe0-4789-939d-8ef60680b498",
        "name": "My connector",
        "type": ".jira",
        "fields": {
          "issueType": "10006",
          "priority": null,
        }
      },
      "id": "a18b38a0-71b0-11ea-a0b2-c51ea50a58e2",
      "description": "James Bond clicked on a highly suspicious email
      banner advertising cheap holidays for underpaid civil servants.
      Operation bubblegum is active. Repeat - operation bubblegum is
      now active!",
      "tags": [
        "phishing",
        "social engineering",
        "bubblegum"
      ],
      "settings": {
        "syncAlerts": true
      }
      "version": "WzIzLDFd"
    }
  ]
}
--------------------------------------------------
// KIBANA

==== Response code

`200`:: 
   Indicates a successful call.

==== Response payload

The updated case with a new `version` value.

===== Example response

[source,json]
--------------------------------------------------
[
  {
    "id": "66b9aa00-94fa-11ea-9f74-e7e108796192",
    "version": "WzU0OCwxXQ==",
    "comments": [],
    "totalComment": 0,
    "connector": {
      "id": "131d4448-abe0-4789-939d-8ef60680b498",
      "name": "My connector",
      "type": ".jira",
      "fields": {
        "issueType": "10006",
        "priority": null,
      }
    },
    "title": "This case will self-destruct in 5 seconds",
    "description": "James Bond clicked on a highly suspicious email banner advertising cheap holidays for underpaid civil servants. Operation bubblegum is active. Repeat - operation bubblegum is now active!",
    "tags": [
      "phishing",
      "social engineering",
      "bubblegum"
    ],
    "settings": {
      "syncAlerts": true
    }
    "closed_at": null,
    "closed_by": null,
    "created_at": "2020-05-13T09:16:17.416Z",
    "created_by": {
      "email": "ahunley@imf.usa.gov",
      "full_name": "Alan Hunley",
      "username": "ahunley"
    },
    "external_service": {
      "external_title": "IS-4",
      "pushed_by": {
        "full_name": "Classified",
        "email": "classified@hms.oo.gov.uk",
        "username": "M"
      },
      "external_url": "https://hms.atlassian.net/browse/IS-4",
      "pushed_at": "2020-05-13T09:20:40.672Z",
      "connector_id": "05da469f-1fde-4058-99a3-91e4807e2de8",
      "external_id": "10003",
      "connector_name": "Jira"
    },
    "status": "open",
    "updated_at": "2020-05-13T09:48:33.043Z",
    "updated_by": {
      "email": "classified@hms.oo.gov.uk",
      "full_name": "Classified",
      "username": "M"
    }
  }
]
--------------------------------------------------