[[ers-requirements]]
= Entity Risk Scoring prerequisites

To use Entity Risk Scoring, your role must have certain cluster, index, and {kib} privileges. This feature requires a https://www.elastic.co/pricing[Platinum subscription] or higher.

This page covers the requirements and guidelines for using the Entity Risk Scoring feature, as well as its known limitations.

[discrete]
== Privileges

To turn on the risk scoring engine, you need the following privileges:

[discrete]
[width="100%",options="header"]
|==============================================

| Cluster      | Index | {kib} 
a| 
* `manage_index_templates`
* `manage_transform`

| `all` privilege for `risk-score.risk-score-*`

a| 
* **All** for the **Saved Objects Management** feature under **Management**
* **Read** for the **Security** feature 

|==============================================

[discrete]
== {es} resource guidelines

Follow these guidelines to ensure clusters have adequate memory to handle data volume:

* With 2GB of Java Virtual Machine (JVM) heap memory, the risk scoring engine can safely process around 44 million documents, or 30 days of risk data with an ingest rate of 1000 documents per minute.

* With 1GB of JVM heap, the risk scoring engine can safely process around 20 million documents, or 30 days of risk data with an ingest rate of around 450 documents per minute.

[discrete]
== Known limitations

* You can only enable the risk scoring engine in a single {kib} space within a cluster.

* The risk scoring engine uses an internal user role to score all hosts and users, and doesn't respect privileges applied to custom users or roles. After you turn on the risk scoring engine for a {kib} space, all alerts in the space will contribute to host and user risk scores.
