[[sec-requirements]]
= Elastic Security system requirements

{elastic-sec} is an inbuilt part of {kib}. To use {elastic-sec}, you only need an {stack}
deployment (an {es} cluster and {kib}). 

{ecloud} offers all of the features of {es}, {kib}, and {elastic-sec} as a hosted service 
available on AWS, GCP, and Azure. 
To get started, sign up for a {ess-trial}[free {ecloud} trial].

For information about installing and managing the {stack} yourself, 
see {stack-ref}/installing-elastic-stack.html[Installing the {stack}].

The https://www.elastic.co/support/matrix[Support Matrix] page lists officially
supported operating systems, platforms, and browsers on which {es}, {kib}, {beats}, and
Elastic Endpoint have been tested.

[discrete]
[[node-role-requirements]]
== Node role requirements
To use Elastic Security, at least one node in your Elasticsearch cluster must have the {ref}/transform-settings.html[`transform` role]. Nodes are automatically given this role when they’re created, so changes are not required if default role settings remain the same. This applies to on-premise and cloud deployments.

Changes might be required if your nodes have customized roles. When updating node roles, nodes are only assigned the roles you specify, and default roles are removed. If you need to reassign the `transform` role to a node, {ref}/modules-node.html#transform-node[create a dedicated transform node].

[discrete]
== {kib} space and index privileges

To use {elastic-sec}, you must have at least:

* `Read` privilege for the `Security` feature in the {kib} space (see
{kibana-ref}/xpack-spaces.html[Spaces]). This grants you `Read` access to all features in {elastic-sec} except cases. Additional <<case-permissions, minimum privileges>> are needed to use cases.
* `Read` and `view_index_metadata` privileges for all {elastic-sec} indices, such as
`filebeat-*`, `packetbeat-*`, `logs-*`, and `endgame-*` indices.

NOTE: <<advanced-settings>> describes how to modify {elastic-sec} indices.

For more information about index privileges, see
{ref}/security-privileges.html[{es} security privileges].

[discrete]
== Feature-specific requirements

There are some additional requirements for specific features:

* <<detections-permissions-section>>
* <<case-permissions>>
* <<ers-requirements>>
* <<ml-requirements>>
* <<elastic-endpoint-deploy-reqs, {elastic-endpoint} requirements>>
* <<conf-map-ui>>

[discrete]
== License requirements

All features are available as part of the free Basic plan *except*:

* <<rule-notifications, Alert notifications via external systems>>
* <<machine-learning, {ml-cap} jobs and rules>>
* <<cases-ui-integrations, Cases integration with third-party ticketing
systems>>

https://www.elastic.co/subscriptions[Elastic Stack subscriptions] lists the
required subscription plans for all features.

[discrete]
== Advanced configuration and UI options

<<advanced-settings>> describes how to modify advanced settings, such as the
{elastic-sec} indices, default time intervals used in filters, and IP reputation
links.

[discrete]
== Third-party collectors mapped to ECS

The {ecs-ref}[Elastic Common Schema (ECS)] defines a common set of fields to be used for storing event data in Elasticsearch. ECS helps users normalize their event data
to better analyze, visualize, and correlate the data represented in their
events. {elastic-sec} can ingest and normalize events from any ECS-compliant data source.

IMPORTANT: {elastic-sec} requires {ecs-ref}[ECS-compliant data]. If you use third-party data collectors to ship data to {es}, the data must be mapped to ECS.
<<siem-field-reference>> lists ECS fields used in {elastic-sec}.

[discrete]
== Cross-cluster searches

For information on how to perform cross-cluster searches on {elastic-sec}
indices, see:

* {ref}/modules-cross-cluster-search.html[Search across cluster]
(for self-managed {stack} deployments)
* {cloud}/ec-enable-ccs.html[Enable cross-cluster search] (for hosted deployments)
