[[self-healing-rollback]]
= Configure self-healing rollback for Windows endpoints

{elastic-defend}'s self-healing feature rolls back file changes on Windows endpoints when a prevention alert is generated by enabled protection features. File changes that occurred on the host within five minutes before the prevention alert will revert to their previous state (which may be up to two hours before the alert).

This can help contain the impact of malicious activity, as {elastic-defend} not only stops the activity but also erases any attack artifacts deployed prior to detection.

Self-healing rollback is a https://www.elastic.co/pricing[Platinum or Enterprise subscription] feature and is only supported for Windows endpoints.

[CAUTION]
====
This feature can cause permanent data loss since it overwrites recent changes and deletes recently added files on the host. Self-healing rollback targets the changes related to a detected threat, but may also include incidental actions that aren't directly related to the threat.

Also, rollback is triggered by _every_ {elastic-defend} prevention alert, so you should tune your system to eliminate false positives before enabling this feature.
====

. In the {security-app}, go to *Manage* -> *Policies*, then select the integration policy you want to configure.
. Scroll down to the bottom of the policy and click *Show advanced settings*.
. Enter `true` for the setting `windows.advanced.alerts.rollback.self_healing.enabled`.
. Click *Save*.
