[[self-healing-rollback]]
= Configure self-healing rollback for Windows endpoints

{endpoint-cloud-sec}'s self-healing feature rolls back file changes and processes on Windows endpoints when enabled protection features generate a prevention alert. All activity on the host reverts to its state five minutes before the prevention alert.

This can help contain the impact of an attack, as {endpoint-cloud-sec} not only stops suspicious activity, but also erases changes and artifacts that the attacker made prior to detection.

Self-healing rollback is a https://www.elastic.co/pricing[Platinum or Enterprise subscription] feature, and it's only supported for Windows endpoints.

[CAUTION]
====
This feature can cause data loss, since it reverts _all_ recent changes on the host, not just changes directly related to a threat.

Also, rollback is triggered by _every_ {endpoint-cloud-sec} prevention alert, so you should tune your system to limit false positives before enabling this feature.
====

. In the {security-app}, go to *Manage* -> *Policies*, then select the integration policy you want to configure.
. Scroll down to the bottom of the policy and click *Show advanced settings*.
. Enter `true` for the setting `windows.advanced.alerts.rollback.self_healing.enabled`.
. Click *Save*.
