[[exceptions-api-summary-exception-container]]
=== Summary exception container

Retrieves an exception container summary.

NOTE: Console supports only Elasticsearch APIs. You cannot interact with {kib} APIs with Console and must use `curl` or another HTTP tool instead. For more information, refer to https://www.elastic.co/guide/en/kibana/current/console-kibana.html[Console].

==== Request URL

`POST <kibana host>:<port>/api/exception_lists/summary`

==== Request body

A JSON object with these fields:

[width="100%",options="header"]
|==============================================
|Name |Type |Description |Required

|`id` |String |Exception container id. |Yes
|`list_id` |String |Unique identifier. |Yes
|`namespace_type` |String a|Determines whether the exception container is available in all {kib} spaces or just the space in which it is created, where:

* `single`: Only available in the {kib} space in which it is created.
* `agnostic`: Available in all {kib} spaces.

|Yes

|==============================================

===== Example requests

Gets the summary from an exception container:

[source,console]
--------------------------------------------------
GET api/exception_lists/summary
{
  "id": "allowes-process-id",
  "list_id": "allowed-processes",
  "namespace_type": "single",
}
--------------------------------------------------
// KIBANA

==== Response code

`200`::
    Indicates a successful call.


==== Response payload

A summary of the exception container:

[source,json]
--------------------------------------------------
{
    windows: 1,
    linux: 3,
    macos: 2,
    total: 6,
}
--------------------------------------------------
