[[exceptions-api-summary-exception-container]]
=== Summary exception container

.New API Reference
[sidebar]
--
For the most up-to-date API details, refer to {api-kibana}/group/endpoint-security-exceptions-api[exceptions APIs].
--

Retrieves an exception container summary.

==== Request URL

`POST <kibana host>:<port>/api/exception_lists/summary`

==== Request body

A JSON object with these fields:

[width="100%",options="header"]
|==============================================
|Name |Type |Description |Required

|`filter` |String |Search filter clause. |Yes
|`id` |String |Exception container ID. |Yes
|`list_id` |String |Unique identifier. |Yes
|`namespace_type` |String a|Determines whether the exception container is available in all {kib} spaces or just the space in which it is created, where:

* `single`: Only available in the {kib} space in which it is created.
* `agnostic`: Available in all {kib} spaces.

|Yes

|==============================================

===== Example requests

Gets the summary from an exception container:

[source,console]
--------------------------------------------------
GET api/exception_lists/summary
{
  "filter": "filter-clause",
  "id": "allowed-process-id",
  "list_id": "allowed-processes",
  "namespace_type": "single",
}
--------------------------------------------------
// KIBANA

==== Response code

`200`::
    Indicates a successful call.


==== Response payload

A summary of the exception container:

[source,json]
--------------------------------------------------
{
    windows: 1,
    linux: 3,
    macos: 2,
    total: 6,
}
--------------------------------------------------

NOTE: For a host isolation exception, the values for `windows`, `linux`, `macos`, and `total` are all the same, as each host isolation exception entry applies to all operating systems.
For example:

[source,json]
--------------------------------------------------
{
    windows: 5,
    linux: 5,
    macos: 5,
    total: 5,
}
--------------------------------------------------
