[[lists-index-api-overview]]
=== Lists index endpoint

Before using exceptions and lists, use the `index` endpoint to create `.lists`
and `.items` system data streams in the relevant
{kibana-ref}/xpack-spaces.html[{kib} space].

For information about the permissions and privileges required to create
`.lists` and `.items` data streams, refer to <<enable-detections-ui>>.

[discrete]
=== Create data stream

Creates `.lists` and `.items` data streams. The data streams naming convention is
`.lists-<space name>` and `.items-<space name>`.

[discrete]
==== Request URL

`POST  <kibana host>:<port>/api/lists/index`

[discrete]
===== Example request

Creates `.lists` and `.items` data streams.

[source,console]
--------------------------------------------------
POST api/lists/index
--------------------------------------------------
// KIBANA

[discrete]
==== Response code

`200`::
    Indicates a successful call.

[discrete]
=== Get data stream

Verifies `.lists` and `.items` data streams exist.

[discrete]
==== Request URL

`GET <kibana host>:<port>/api/lists/index`

[discrete]
===== Example request

Verifies the `lists` data stream for the {kib} `security` exists:

[source,console]
--------------------------------------------------
GET api/lists/index
--------------------------------------------------
// KIBANA

[discrete]
==== Response code

`200`::
    Indicates a successful call.
`404`::
    Indicates no data stream exists.

[discrete]
===== Example responses

Example response when the data streams exist:

[source,json]
--------------------------------------------------
{
  "list_index": true,
  "list_item_index": true
}
--------------------------------------------------

Example response when the data streams do not exist:

[source,json]
--------------------------------------------------
{
  "message": "data stream .lists-default and data stream .items-default does not exist",
  "status_code": 404
}
--------------------------------------------------

[discrete]
=== Delete data streams

Deletes the `.lists` and `.items` data streams.

[discrete]
==== Request URL

`DELETE <kibana host>:<port>/api/lists/index`

[discrete]
===== Example request

Deletes the `.lists` and `.items` data streams:

[source, js]
--------------------------------------------------
DELETE api/lists/index
--------------------------------------------------
// KIBANA

[discrete]
==== Response code

`200`::
    Indicates a successful call.
