[[lists-api-find-list-items]]
=== Find list items

Retrieves a paginated subset of list items in the specified container. By
default, the first page is returned with 20 results per page.

NOTE: Console supports only Elasticsearch APIs. Console doesn't allow interactions with {kib} APIs. You must use `curl` or another HTTP tool instead. For more information, refer to {kibana-ref}/console-kibana.html[Run {es} API requests].

==== Request URL

`GET <kibana host>:<port>/api/lists/items/_find`

===== URL query parameters

[width="100%",options="header"]
|==============================================
|Name |Type |Description |Required

|`list_id` |String |ID of the <<lists-api-create-container, list container>>. |Yes

|`page` |Integer |The page number to return. |No

|`per_page` |Integer |The number of items to return per page. |No

|`sort_field` |String |Determines which field is used to sort the results. |No

|`sort_order` |String |Determines the sort order, which can be `desc` or `asc`.
|No
|`cursor` |String |Returns the items that come after the last item
returned in the previous call (use the `cursor` value returned in the previous
call). This parameter uses the `tie_breaker_id` field to ensure all items
are sorted and returned correctly.
See {ref}/search-request-body.html#request-body-search-search-after[Search After] for more information. |No

|==============================================

===== Example request

Retrieves list items in the `external-ip-excludes` list container:

[source,console]
--------------------------------------------------
GET api/lists/items/_find?list_id=external-ip-excludes
--------------------------------------------------
// KIBANA

==== Response code

`200`::
    Indicates a successful call.

==== Response payload

[source,json]
--------------------------------------------------
{
  "cursor": "WzIwLFsiZmFjZmZmOTQtNzIzZS00YmQ0LTk4ZTUtNzI2OGJjNTA3NWNmIl1d",
  "data": [
    {
      "_version": "WzgsMV0=",
      "created_at": "2020-08-11T11:22:13.670Z",
      "created_by": "elastic",
      "id": "bpdB3XMBx7pemMHopQ6M",
      "list_id": "internal-ip-excludes-meta",
      "tie_breaker_id": "17d3befb-dc22-4b3c-a286-b5504c4fbeeb",
      "type": "ip",
      "updated_at": "2020-08-11T11:22:13.670Z",
      "updated_by": "elastic",
      "value": "127.0.0.6"
    },
    {
      "_version": "WzMsMV0=",
      "created_at": "2020-08-11T11:22:13.669Z",
      "created_by": "elastic",
      "id": "aZdB3XMBx7pemMHopQ6L",
      "list_id": "internal-ip-excludes-meta",
      "tie_breaker_id": "26115356-c2c2-4f1c-a4ed-19b81191775a",
      "type": "ip",
      "updated_at": "2020-08-11T11:22:13.669Z",
      "updated_by": "elastic",
      "value": "127.0.0.1"
    },
    ...
    {
      "_version": "WzksMV0=",
      "created_at": "2020-08-11T11:22:13.670Z",
      "created_by": "elastic",
      "id": "b5dB3XMBx7pemMHopQ6M",
      "list_id": "internal-ip-excludes-meta",
      "tie_breaker_id": "facfff94-723e-4bd4-98e5-7268bc5075cf",
      "type": "ip",
      "updated_at": "2020-08-11T11:22:13.670Z",
      "updated_by": "elastic",
      "value": "127.0.0.7"
    }
  ],
  "page": 1,
  "per_page": 20,
  "total": 11
}
--------------------------------------------------
