[[automated-response-actions]]
= Automated response actions

:description: Automatically respond to events with endpoint response actions triggered by detection rules.
:keywords: serverless, security, defend, how-to, manage

preview:[]

Add {elastic-defend}'s <<response-actions,response actions>> to detection rules to automatically perform actions on an affected host when an event meets the rule's criteria. Use these actions to support your response to detected threats and suspicious events.

.Requirements
[NOTE]
====
* Automated response actions require the Endpoint Protection Complete https://www.elastic.co/docs/current/serverless/elasticsearch/manage-project[project feature].
* Hosts must have {agent} installed with the {elastic-defend} integration.
* Your user role must have the ability to create detection rules and the privilege to perform <<response-action-commands,specific response actions>> (for example, custom roles require the **Host Isolation** privilege to isolate hosts).
* You can only add automated response actions to <<create-custom-rule,custom query>>, <<create-eql-rule,event correlation (EQL)>>, <<create-new-terms-rule,new terms>>, and <<create-esql-rule,{esql}>> type rules.
====

To add automated response actions to a new or existing rule:

. Do one of the following:
+
** **New rule**: On the last step of rule creation, go to the **Response Actions** section and select **{elastic-defend}**.
** **Existing rule**: Edit the rule's settings, then go to the **Actions** tab. In the tab, select **{elastic-defend}** under the **Response Actions** section.
. Select an option in the **Response action** field:
+
** **Isolate**: <<isolate-host,Isolate the host>>, blocking communication with other hosts on the network.
** **Kill process**: Terminate a process on the host.
** **Suspend process**: Temporarily suspend a process on the host.
+
[IMPORTANT]
====
Be aware that automatic host isolation can result in unintended consequences, such as disrupting legitimate user activities or blocking critical business processes.
====
. For process actions, specify how to identify the process you want to terminate or suspend:
+
** Turn on the toggle to use the alert's **process.pid** value as the identifier.
** To use a different alert field value to identify the process, turn off the toggle and enter the **Custom field name**.
. Enter a comment describing why you’re performing the action on the host (optional).
. To finish adding the response action, click **Create & enable rule** (for a new rule) or **Save changes** (for existing rules).
