[[timeline-api-create]]
=== Create timeline or timeline template

Creates a new timeline or timeline template.

Use the `timeline` object's <<timeline-object-typeField, `timelineType`>> field
to determine whether a timeline or a timeline template is created, where:

* `default` creates a new timeline (`"timelineType": "default"`)
* `template` creates a new timeline template (`"timelineType": "template"`)

NOTE: If you do not specify the `timelineType` field, a new timeline is created.

==== Request URL

`POST <kibana host>:<port>/api/timeline`

==== Request body

A JSON object defining the timeline or timeline template query and time filter.

NOTE: For detailed information about the Timeline object schema and its
corresponding UI components, see <<timeline-object-schema>>.

[width="100%",options="header"]
|==============================================
|Name |Type |Description |Required

|`timeline` |<<timeline-object-schema, timeline>> |The timeline object, which
defines the search criteria and time range. The only required field is `title`.
|Yes
|`timelineId` |String |If provided, must be `null` for a new timeline or
template.
|No
|`version` |String |If provided, must be `null` for a new timeline or template.
|No
|==============================================




===== Example request



[source,console]
--------------------------------------------------

--------------------------------------------------
// KIBANA


==== Response code

`200`:: 
    Indicates a successful call.
    
==== Response payload

