[[prebuilt-rules-downloadable-updates]]
[role="xpack"]
== Downloadable rule updates

This section lists all updates to prebuilt detection rules, made available with the *Prebuilt Security Detection Rules* integration in Fleet.

To update your installed rules to the latest versions, follow the instructions in <<update-prebuilt-rules>>.

For previous rule updates, please navigate to the https://www.elastic.co/guide/en/security/8.13/prebuilt-rules-downloadable-updates.html[last version].

[width="100%",options="header"]
|==============================================
|Update version |Date | New rules | Updated rules | Notes


|<<prebuilt-rule-8-14-8-prebuilt-rules-8-14-8-summary, 8.14.8>> | 06 Aug 2024 | 7 | 44 | 
This release includes new rules for Windows and AWS integration. New rules for Windows include detection for credential access and command and control. New rules for AWS include detection for execution, credential access, persistence and lateral movement. Additionally, significant rule tuning for Windows and Linux rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-14-7-prebuilt-rules-8-14-7-summary, 8.14.7>> | 25 Jul 2024 | 14 | 72 | 
This release includes new rules for Windows, Linux , and AWS integration. Deprecated rules include `Suspicious File Changes Activity Detected`. New rules for Windows include detection for lateral movement, credential access and defense evasion. New rules for Linux include detection for privilege escalation, execution, and persistence. New rules for AWS include detection for exfiltration, defense evasion and impact. Additionally, significant rule tuning for Windows, Linux, AWS, Google Workplace and Okta integration rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-14-6-prebuilt-rules-8-14-6-summary, 8.14.6>> | 09 Jul 2024 | 10 | 15 | 
This release includes new rules for Windows, Linux , AWS and Azure integration. New rules for Windows include detection for credential access and defense evasion. New rules for Linux include detection for persistence. New rules for AWS include detection for exfiltration, persistence and impact. New rules for Azure include detection for credential access. Additionally, significant rule tuning for Windows, Linux, AWS, Google Workplace and Microsoft 365 integration rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-14-5-prebuilt-rules-8-14-5-summary, 8.14.5>> | 28 Jun 2024 | 12 | 28 | 
This release includes new rules and tuned for Windows, Linux and AWS integration. New rules for Windows include detection for persistence and execution. New rules for Linux include detection for persistence and privilege escalation. New rules for AWS include detection for defense evasion. Additionally, significant rule tuning for Windows, Linux and AWS rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-14-4-prebuilt-rules-8-14-4-summary, 8.14.4>> | 25 Jun 2024 | 10 | 55 | 
This release includes new rules for Windows, Okta and AWS integration and tuned rules for Okta and AWS. New rules for Windows include detection for defense evasion, privilege escalation, and credential access. New rules for AWS include detection for persistence. New rules for Okta include detection for credential access. Additionally, significant rule tuning for Okta and AWS rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-14-3-prebuilt-rules-8-14-3-summary, 8.14.3>> | 11 Jun 2024 | 24 | 29 | 
This release includes new rules for Linux and AWS integration and tuned rules for Windows , Linux, AWS and Microsoft 365. New rules for Linux include detection for persistence. New rules for AWS include detection for execution, persistence, credential access, impact, exfiltration, privilege escalation and discovery. Additionally, significant rule tuning for Windows ,Linux and Microsoft 365 rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-14-2-prebuilt-rules-8-14-2-summary, 8.14.2>> | 29 May 2024 | 4 | 123 | 
This release includes new rules for Linux and AWS integration and tuned rules for Windows ,Linux and MacOS. New rules for Linux include detection for persistence. New rules for AWS include detection for lateral movement, defense evasion and discovery. Additionally, significant rule tuning for Windows ,Linux and MacOS rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-14-1-prebuilt-rules-8-14-1-summary, 8.14.1>> | 15 May 2024 | 11 | 40 | 
This release includes new rules for  Windows and AWS integration and tuned rules for Windows and MacOS. 
New rules for Windows include detection for impact, execution, command and control and defense evasion. 
New rules for AWS include detection for persistence, defense evasion, exfiltration and credential access. 
Additionally, significant rule tuning for Windows and MacOS rules has been added for better rule efficacy and performance.


|==============================================

include::downloadable-packages/8-14-1/prebuilt-rules-8-14-1-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-14-2/prebuilt-rules-8-14-2-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-14-3/prebuilt-rules-8-14-3-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-14-4/prebuilt-rules-8-14-4-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-14-5/prebuilt-rules-8-14-5-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-14-6/prebuilt-rules-8-14-6-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-14-7/prebuilt-rules-8-14-7-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-14-8/prebuilt-rules-8-14-8-summary.asciidoc[leveloffset=+1]
