[[prebuilt-rules-downloadable-updates]]
[role="xpack"]
== Downloadable rule updates

This section lists all updates to prebuilt detection rules, made available with the *Prebuilt Security Detection Rules* integration in Fleet.

To update your installed rules to the latest versions, follow the instructions in <<update-prebuilt-rules>>.

For previous rule updates, please navigate to the https://www.elastic.co/guide/en/security/8.12/prebuilt-rules-downloadable-updates.html[last version].

[width="100%",options="header"]
|==============================================
|Update version |Date | New rules | Updated rules | Notes


|<<prebuilt-rule-8-13-2-prebuilt-rules-8-13-2-summary, 8.13.2>> | 25 Mar 2024 | 5 | 549 | 
This release includes new rules for Linux and Windows and tuned rules for Linux, Windows and macOS.
New rules for Linux include detection for execution.
New rules for Windows include detection for credential access.
Additionally, significant rule tuning for Windows, Linux and macOS rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-13-1-prebuilt-rules-8-13-1-summary, 8.13.1>> | 07 Mar 2024 | 9 | 7 | 
 This release includes significant rule tuning for Linux rules for better rule efficacy and performance.


|==============================================

include::downloadable-packages/8-13-1/prebuilt-rules-8-13-1-summary.asciidoc[leveloffset=+1]include::downloadable-packages/8-13-2/prebuilt-rules-8-13-2-summary.asciidoc[leveloffset=+1]
