[[prebuilt-rules-downloadable-updates]]
[role="xpack"]
== Downloadable rule updates

This section lists all updates to prebuilt detection rules, made available with the *Prebuilt Security Detection Rules* integration in Fleet.

To update your installed rules to the latest versions, follow the instructions in <<update-prebuilt-rules>>.

For previous rule updates, please navigate to the https://www.elastic.co/guide/en/security/8.11/prebuilt-rules-downloadable-updates.html[last version].

[width="100%",options="header"]
|==============================================
|Update version |Date | New rules | Updated rules | Notes


|<<prebuilt-rule-8-12-1-prebuilt-rules-8-12-1-summary, 8.12.1>> | 14 Dec 2023 | 7 | 35 |
This release includes new Windows, Linux and Okta rules.
New rules for Windows include detection for processes created with duplicated tokens and interactive logons.
Linux rules include detection for Out-of-Tree kernel module loading, persistence through Systemd-udevd and Kworker UID elevation.
New rules for Okta include detection for stolen credentials being used to reset MFA and suspicious authentication events.
Additionally, significant rule tuning for Windows, Linux and Okta rules has been added for better rule efficacy.


|==============================================

include::downloadable-packages/8-12-1/prebuilt-rules-8-12-1-summary.asciidoc[leveloffset=+1]
