[[prebuilt-rules-downloadable-updates]]
[role="xpack"]
== Downloadable rule updates

This section lists all updates to prebuilt detection rules, made available with the *Prebuilt Security Detection Rules* integration in Fleet.

To update your installed rules to the latest versions, follow the instructions in <<update-prebuilt-rules>>.

For previous rule updates, please navigate to the https://www.elastic.co/guide/en/security/8.15/prebuilt-rules-downloadable-updates.html[last version].

[width="100%",options="header"]
|==============================================
|Update version |Date | New rules | Updated rules | Notes


|<<prebuilt-rule-8-16-14-prebuilt-rules-8-16-14-summary, 8.16.14>> | 20 May 2025 | 1 | 7 | 
This release includes new rules for Azure and Microsoft 365. New rules for Azure include detection for initial access and collection. New rules for Microsoft 365 include detection for credential access. Additionally, significant rule tuning for Windows, Azure and Microsoft 365 rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-16-13-prebuilt-rules-8-16-13-summary, 8.16.13>> | 07 May 2025 | 33 | 41 | 
This release includes new rules for Windows, Linux, Azure, AWS and Microsoft 365. New rules for Windows include detection for defense evasion and credential access. New rules for Linux include detection for command and control, defense evasion, exfiltration, discovery, persistence, execution, privilege escalation and credential access. New rules for Azure include detection for initial access, credential access, collection, defense evasion and command and control. New rules for AWS include detection for impact. New rules for Microsoft 365 include defense evasion, initial access and credential access. Additionally, significant rule tuning for Windows, Linux and Azure rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-16-12-prebuilt-rules-8-16-12-summary, 8.16.12>> | 30 Apr 2025 | 0 | 55 | 
Version parity to ensure future updates are more meaningful and informative


|<<prebuilt-rule-8-16-11-prebuilt-rules-8-16-11-summary, 8.16.11>> | 28 Apr 2025 | 21 | 11 | 
This release includes new rules for Windows, Linux, Azure and AWS. New rules for Windows include detection for defense evasion and execution New rules for Linux include detection for credential access, execution, privilege escalation, credential access, lateral movement and discovery. New rules for Azure include detection for initial access. New rules for AWS include detection for initial access and persistence. Additionally, significant rule tuning for MacOS, Windows, Microsoft 365, Linux and Azure rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-16-10-prebuilt-rules-8-16-10-summary, 8.16.10>> | 08 Apr 2025 | 5 | 75 | 
This release includes new rules for MacOS, Microsoft 365, AWS and PAD. New rules for MacOS include detection for command and control. New rules for Microsoft 365 include detection for initial access. New rules for AWS include detection for exfiltration. New rules for PAD include detection for privilege escalation. Elastic Defend for Container rules are deprecated. Additionally, significant rule tuning for Linux, Windows, Microsoft 365 and Azure rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-16-9-prebuilt-rules-8-16-9-summary, 8.16.9>> | 13 Mar 2025 | 33 | 200 | 
This release includes new rules for Linux, Windows, Microsoft 365, AWS, Azure and Azure OpenAI. New rules for Linux include detection for defense evasion, persistence, command and control, discovery, impact, initial access, exfiltration and lateral movement. New rules for Windows include detection for defense evasion. New rules for Microsoft 365 include detection for collection. New rules for AWS include detection for resource development. New rules for Azure include detection for initial access and credential access. Additionally, significant rule tuning for Linux, Windows and AWS rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-16-8-prebuilt-rules-8-16-8-summary, 8.16.8>> | 17 Feb 2025 | 0 | 20 | 
This release includes significant rule tuning for Windows, Linux and MacOS rules for better rule efficacy and performance.


|<<prebuilt-rule-8-16-7-prebuilt-rules-8-16-7-summary, 8.16.7>> | 10 Feb 2025 | 0 | 191 | 
This release includes significant rule tuning for Windows and PanOS rules for better rule efficacy and performance.


|<<prebuilt-rule-8-16-6-prebuilt-rules-8-16-6-summary, 8.16.6>> | 04 Feb 2025 | 7 | 1047 | 
This release includes new rules for Linux and Windows. New rules for Linux include detection for execution and persistence. New rules for Windows include detection for defense evasion, execution and command and control. Additionally, significant rule tuning for Linux, Windows, MacOS, and AWS rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-16-5-prebuilt-rules-8-16-5-summary, 8.16.5>> | 21 Jan 2025 | 29 | 109 | 
This release includes new rules for Linux, Windows and AWS integration. Deprecated rules include `Deprecated - Suspicious JAVA Child Process` and `Deprecated - Potential Password Spraying of Access ['Microsoft 365']`. New rules for Linux include detection for execution, discovery, persistence and defense evasion. New rules for Windows include detection for defense evasion. New Rules for AWS include detection for lateral movement, discovery, collection, impact and defense evasion. Additionally, significant rule tuning for Linux, Windows, Crowdstrike and SentinelOne rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-16-4-prebuilt-rules-8-16-4-summary, 8.16.4>> | 08 Jan 2025 | 20 | 10 | 
This release includes new rules for Linux, Azure and Elastic Defend integration. Deprecated rules include `Suspicious File Changes Activity Detected` New rules for Linux include detection for persistence and defense evasion. New rules for Azure include detection for credential access. New Rules for Elastic Defend include detection for defense evasion, execution and impact. Additionally, significant rule tuning for Linux, Windows and Okta rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-16-3-prebuilt-rules-8-16-3-summary, 8.16.3>> | 10 Dec 2024 | 5 | 6 | 
This release includes new rules for AWS, and AWS Bedrock integration. New rules for AWS include detection for persistence. New rules for AWS Bedrock include detection for LLM prompt injection and LLM jailbreak. Additionally, significant rule tuning for AWS, Github, AWS Bedrock and Azure rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-16-2-prebuilt-rules-8-16-2-summary, 8.16.2>> | 27 Nov 2024 | 1 | 0 | 
This release includes a new rule for AWS integration privilege escalation detection.


|<<prebuilt-rule-8-16-1-prebuilt-rules-8-16-1-summary, 8.16.1>> | 11 Nov 2024 | 21 | 116 | 
This release includes new rules for Windows, Linux, AWS, and Azure integration. New rules for Windows include detection for initial access. New rules for Linux include detection for defense evasion, command and control, impact, discovery, execution and exfiltration. New rules for AWS include detection for privilege escalation, exfiltration, execution, discovery and persistence. New rules for Azure include detection for credential access.  Additionally, significant rule tuning for Windows and AWS rules has been added for better rule efficacy and performance.

|==============================================
include::downloadable-packages/8-16-1/prebuilt-rules-8-16-1-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-16-2/prebuilt-rules-8-16-2-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-16-3/prebuilt-rules-8-16-3-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-16-4/prebuilt-rules-8-16-4-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-16-5/prebuilt-rules-8-16-5-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-16-6/prebuilt-rules-8-16-6-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-16-7/prebuilt-rules-8-16-7-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-16-8/prebuilt-rules-8-16-8-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-16-9/prebuilt-rules-8-16-9-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-16-10/prebuilt-rules-8-16-10-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-16-11/prebuilt-rules-8-16-11-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-16-12/prebuilt-rules-8-16-12-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-16-13/prebuilt-rules-8-16-13-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-16-14/prebuilt-rules-8-16-14-summary.asciidoc[leveloffset=+1]
