[[prebuilt-rules-downloadable-updates]]
[role="xpack"]
== Downloadable rule updates

This section lists all updates to prebuilt detection rules, made available with the *Prebuilt Security Detection Rules* integration in Fleet.

To update your installed rules to the latest versions, follow the instructions in <<update-prebuilt-rules>>.

For previous rule updates, please navigate to the https://www.elastic.co/guide/en/security/8.11/prebuilt-rules-downloadable-updates.html[last version].

[width="100%",options="header"]
|==============================================
|Update version |Date | New rules | Updated rules | Notes


|<<prebuilt-rule-8-12-14-prebuilt-rules-8-12-14-summary, 8.12.14>> | 11 Jun 2024 | 19 | 29 | 
This release includes new rules for Linux and AWS integration and tuned rules for Windows , Linux, AWS and Microsoft 365. New rules for Linux include detection for persistence. New rules for AWS include detection for execution, persistence, credential access, impact, exfiltration, privilege escalation and discovery. Additionally, significant rule tuning for Windows ,Linux and Microsoft 365 rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-12-13-prebuilt-rules-8-12-13-summary, 8.12.13>> | 29 May 2024 | 4 | 123 | 
This release includes new rules for Linux and AWS integration and tuned rules for Windows ,Linux and MacOS. New rules for Linux include detection for persistence. New rules for AWS include detection for lateral movement, defense evasion and discovery. Additionally, significant rule tuning for Windows ,Linux and MacOS rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-12-12-prebuilt-rules-8-12-12-summary, 8.12.12>> | 15 May 2024 | 10 | 40 | 
This release includes new rules for  Windows and AWS integration and tuned rules for Windows and MacOS. New rules for Windows include detection for impact, execution, command and control and defense evasion. New rules for AWS include detection for persistence, defense evasion, exfiltration and credential access. Additionally, significant rule tuning for Windows and MacOS rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-12-11-prebuilt-rules-8-12-11-summary, 8.12.11>> | 06 May 2024 | 0 | 0 | 
This version bump is a result of an out of band update.
No rules require an update to this version.


|<<prebuilt-rule-8-12-10-prebuilt-rules-8-12-10-summary, 8.12.10>> | 30 Apr 2024 | 2 | 2 | 
This release includes new rules for Linux and Windows and tuned rules for Linux. 
New rules for Linux include detection for persistence. 
New rules for Windows include detection for privilege escalation. 
Additionally, significant rule tuning for Linux rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-12-9-prebuilt-rules-8-12-9-summary, 8.12.9>> | 23 Apr 2024 | 11 | 110 | 
This release includes new rules and tuned rules for Windows.
New rules for Windows include detection for  potential windows session hijacking via CcmExec.
Additionally, significant rule tuning for Windows rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-12-8-prebuilt-rules-8-12-8-summary, 8.12.8>> | 03 Apr 2024 | 8 | 238 | 
This release includes new rules for Linux and Windows and tuned rules for Windows.
Deprecated rules include `Remote File Creation on a Sensitive Directory`
New rules for Linux include detection for persistence.
New rules for Windows include detection for credential access, initial access, discovery and command and control.
Additionally, significant rule tuning for Windows rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-12-7-prebuilt-rules-8-12-7-summary, 8.12.7>> | 25 Mar 2024 | 5 | 549 | 
This release includes new rules for Linux and Windows and tuned rules for Linux, Windows and macOS.
New rules for Linux include detection for execution.
New rules for Windows include detection for credential access.
Additionally, significant rule tuning for Windows, Linux and macOS rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-12-6-prebuilt-rules-8-12-6-summary, 8.12.6>> | 07 Mar 2024 | 9 | 7 | 
 This release includes significant rule tuning for Linux rules for better rule efficacy and performance.


|<<prebuilt-rule-8-12-5-prebuilt-rules-8-12-5-summary, 8.12.5>> | 23 Feb 2024 | 5 | 33 |
This release includes a new rule for Windows detection of suspicious execution from INET cache.
Additionally, significant rule tuning for Windows and Linux rules has been added for better rule efficacy and performance.

|<<prebuilt-rule-8-12-4-prebuilt-rules-8-12-4-summary, 8.12.4>> | 08 Feb 2024 | 10 | 6 |
This release includes new and tuned rules for Linux and Windows.
New rules for Linux include detection for discovery, persistence, privilege escalation and defense evasion.
New rules for Windows include detection for Active Directory enumeration.
Additionally, significant rule tuning for Windows, Linux and macOS rules has been added for better rule efficacy and performance.

|<<prebuilt-rule-8-12-3-prebuilt-rules-8-12-3-summary, 8.12.3>> | 25 Jan 2024 | 19 | 165 |
This release includes new rules for Windows, Linux, Containers and GitHub.
New rules for Windows include detection for evasion via Windows Filtering Platform.
Linux rules for endpoints include detection for kernel driver loading and buffer overflow exploitation.
Container rules for Linux include detection for container breakout via modified release agent files.
Several new GitHub rules have been added for detection of suspicious activity related to IP addresses, tokens and repositories.
Additionally, significant rule tuning for Windows, Linux and macOS rules has been added for better rule efficacy and performance.

|<<prebuilt-rule-8-12-2-prebuilt-rules-8-12-2-summary, 8.12.2>> | 03 Jan 2024 | 1 | 64 |
This release includes a new Linux rule for detecting reverse TCP shells through child processes.
Deprecated rules include `Malicious Remote File Creation` and `Potential Process Herpaderping Attempt`.
Several Windows rules with EQL queries have been tuned for better rule efficacy and performance.
An Okta rule for MFA deactivation has been tuned to reduce false positives.
Rule content has been updated for several Windows, Linux and Okta rules to improve clarity and accuracy.

|<<prebuilt-rule-8-12-1-prebuilt-rules-8-12-1-summary, 8.12.1>> | 14 Dec 2023 | 7 | 35 |
This release includes new Windows, Linux and Okta rules.
New rules for Windows include detection for processes created with duplicated tokens and interactive logons.
Linux rules include detection for Out-of-Tree kernel module loading, persistence through Systemd-udevd and Kworker UID elevation.
New rules for Okta include detection for stolen credentials being used to reset MFA and suspicious authentication events.
Additionally, significant rule tuning for Windows, Linux and Okta rules has been added for better rule efficacy.


|==============================================

include::downloadable-packages/8-12-1/prebuilt-rules-8-12-1-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-12-2/prebuilt-rules-8-12-2-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-12-3/prebuilt-rules-8-12-3-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-12-4/prebuilt-rules-8-12-4-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-12-5/prebuilt-rules-8-12-5-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-12-6/prebuilt-rules-8-12-6-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-12-7/prebuilt-rules-8-12-7-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-12-8/prebuilt-rules-8-12-8-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-12-9/prebuilt-rules-8-12-9-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-12-10/prebuilt-rules-8-12-10-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-12-11/prebuilt-rules-8-12-11-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-12-12/prebuilt-rules-8-12-12-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-12-13/prebuilt-rules-8-12-13-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-12-14/prebuilt-rules-8-12-14-summary.asciidoc[leveloffset=+1]
