[[prebuilt-rules-downloadable-updates]]
[role="xpack"]
== Downloadable rule updates

This section lists all updates to prebuilt detection rules, made available with the *Prebuilt Security Detection Rules* integration in Fleet.

To update your installed rules to the latest versions, follow the instructions in <<update-prebuilt-rules>>.

For previous rule updates, please navigate to the https://www.elastic.co/guide/en/security/8.12/prebuilt-rules-downloadable-updates.html[last version].

[width="100%",options="header"]
|==============================================
|Update version |Date | New rules | Updated rules | Notes


|<<prebuilt-rule-8-14-1-prebuilt-rules-8-14-1-summary, 8.14.1>> | 15 May 2024 | 11 | 40 | 
This release includes new rules for  Windows and AWS integration and tuned rules for Windows and MacOS. 
New rules for Windows include detection for impact, execution, command and control and defense evasion. 
New rules for AWS include detection for persistence, defense evasion, exfiltration and credential access. 
Additionally, significant rule tuning for Windows and MacOS rules has been added for better rule efficacy and performance.


|==============================================

include::downloadable-packages/8-14-1/prebuilt-rules-8-14-1-summary.asciidoc[leveloffset=+1]
