[[prebuilt-rules-downloadable-updates]]
[role="xpack"]
== Downloadable rule updates

This section lists all updates to prebuilt detection rules, made available with the *Prebuilt Security Detection Rules* integration in Fleet.

To update your installed rules to the latest versions, follow the instructions in <<update-prebuilt-rules>>.

For previous rule updates, please navigate to the https://www.elastic.co/guide/en/security/8.18/prebuilt-rules-downloadable-updates.html[last version].

[width="100%",options="header"]
|==============================================
|Update version |Date | New rules | Updated rules | Notes


|<<prebuilt-rule-8-19-28-prebuilt-rules-8-19-28-summary, 8.19.28>> | 22 Jul 2026 | 55 | 95 | 
This release includes new rules for Linux, AWS, GCP, Windows, Azure, and Microsoft 365.  New rules for Linux include detection for persistence.  New rules for AWS include detection for defense evasion, impact, privilege escalation, credential access, and initial access.  New rules for GCP include detection for privilege escalation, persistence, credential access, initial access, execution, impact, and discovery.  New rules for Windows include detection for execution.  New rules for Azure include detection for initial access, persistence, defense evasion, credential access, execution, and lateral movement.  New rules for Microsoft 365 include detection for initial access.  Additionally, significant tuning for Linux, Windows, macOS, AWS, GCP, Azure, and network rules improves efficacy and performance.


|<<prebuilt-rule-8-19-27-prebuilt-rules-8-19-27-summary, 8.19.27>> | 07 Jul 2026 | 55 | 22 | 
This release includes new rules for Linux, AWS, GCP, Windows, Azure, Network Traffic, and Elastic Defend.  New rules for Linux include detection for command and control, privilege escalation, execution, discovery, persistence, and defense evasion.  New rules for AWS include detection for impact, persistence, execution, privilege escalation, defense evasion, initial access, and exfiltration.  New rules for GCP include detection for privilege escalation, credential access, persistence, discovery, and execution.  New rules for Windows include detection for command and control, exfiltration, credential access, and initial access.  New rules for Azure include detection for persistence and initial access.  New rules for Network Traffic include detection for initial access, credential access, discovery, command and control, and impact.  New rules for Elastic Defend include detection for defense evasion.  Additionally, significant tuning for Linux, Windows, macOS, Kubernetes, Microsoft 365, and network rules improves efficacy and performance.


|<<prebuilt-rule-8-19-26-prebuilt-rules-8-19-26-summary, 8.19.26>> | 25 Jun 2026 | 44 | 44 | 
This release includes new rules for AWS, Windows, Azure, Microsoft 365, Azure AD Graph, Network Packet Capture, and Network Traffic.  New rules for AWS include detection for persistence, defense evasion, impact, discovery, and execution.  New rules for Windows include detection for command and control, defense evasion, and execution.  New rules for Azure include detection for lateral movement, execution, and credential access.  New rules for Microsoft 365 include detection for initial access, persistence, and credential access.  New rules for Azure AD Graph include detection for discovery.  New rules for Network Packet Capture include detection for persistence and initial access.  New rules for Network Traffic include detection for credential access.  Additionally, significant tuning for Linux, Windows, macOS, Azure, Google Workspace, and network rules improves efficacy and performance.


|<<prebuilt-rule-8-19-25-prebuilt-rules-8-19-25-summary, 8.19.25>> | 02 Jun 2026 | 18 | 29 | 
8.19 Docs and News Feed  This release includes new rules for Linux, AWS, Azure, Microsoft 365, Google Workspace, Network Packet Capture, and Elastic Defend.  New rules for Linux include detection for credential access, discovery, and persistence.  New rules for AWS include detection for credential access.  New rules for Azure include detection for execution.  New rules for Microsoft 365 include detection for defense evasion, initial access, and collection.  New rules for Google Workspace include detection for initial access and persistence.  New rules for Network Packet Capture include detection for credential access.  New rules for Elastic Defend include detection for command and control and credential access.  Additionally, significant tuning for Linux, Windows, macOS, Kubernetes, AWS, Microsoft 365, Google Workspace, and network rules improves efficacy and performance.


|<<prebuilt-rule-8-19-24-prebuilt-rules-8-19-24-summary, 8.19.24>> | 19 May 2026 | 33 | 102 | 
This release includes new rules for Linux, AWS, Kubernetes, Microsoft 365, Google Workspace, and Network Packet Capture. New rules for Linux include detection for privilege escalation, lateral movement, execution, credential access, persistence, and discovery. New rules for AWS include detection for defense evasion, persistence, and privilege escalation. New rules for Kubernetes include detection for persistence, privilege escalation, credential access, execution, and impact. New rules for Microsoft 365 include detection for initial access, persistence, and discovery. New rules for Google Workspace include detection for persistence. New rules for Network Packet Capture include detection for initial access. Additionally, significant tuning for Linux, Windows, Kubernetes, macOS, and Microsoft 365 rules improves efficacy and performance.


|<<prebuilt-rule-8-19-23-prebuilt-rules-8-19-23-summary, 8.19.23>> | 05 May 2026 | 27 | 377 | 
This release includes new rules for Linux, AWS, Windows and Kubernetes. New rules for Linux include detection for privilege escalation, execution and credential access. New rules for Windows include detection for execution and credential access. New rules for AWS include detection for privilege execution, discovery, persistence, lateral movement and execution. New rules for Kubernetes include detection for discovery, privilege escalation, execution and credential access. Additionally, significant tuning for Linux, Windows, Kubernetes, AWS and MacOS rules improves efficacy and performance.


|<<prebuilt-rule-8-19-22-prebuilt-rules-8-19-22-summary, 8.19.22>> | 29 Apr 2026 | 0 | 6 | 
This release fixes ESQL prebuilt rules that broke after the previous release due to unmapped data_stream.dataset on security alert indices.


|<<prebuilt-rule-8-19-21-prebuilt-rules-8-19-21-summary, 8.19.21>> | 23 Apr 2026 | 6 | 708 | 
This release includes new rules for Linux, AWS and Windows. New rules for Linux and Windows include detection for defense evasion. New rules for AWS include detection for initial access. Additionally, significant tuning across multiple data-source rules improves efficacy and performance.


|<<prebuilt-rule-8-19-20-prebuilt-rules-8-19-20-summary, 8.19.20>> | 09 Apr 2026 | 1 | 985 | 
This release adds new AWS prebuilt rules, including coverage for credential access. MITRE ATT&CK alignment is improved across many rules through additional mappings and tags metadata. Additionally, significant rule tuning for Microsoft 365, Azure, Linux, macOS, Windows, and AWS rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-19-19-prebuilt-rules-8-19-19-summary, 8.19.19>> | 26 Mar 2026 | 5 | 6 | 
Update latest docs


|<<prebuilt-rule-8-19-18-prebuilt-rules-8-19-18-summary, 8.19.18>> | 24 Mar 2026 | 25 | 44 | 
This release includes new rules for Linux, Azure, MacOS, Microsoft 365, Kubernetes, AWS and Windows. New rules for Linux 365 include detection for privilege escalation, exfiltration and defense evasion. New rules for Azure include detection for initial access, credential access and initial access. New rules for MacOS include detection for credential access, persistence, and execution. New rules for Microsoft 365 include detection for defense evasion and privilege escalation. New rules for Kubernetes include detection for credential access. New rules for AWS include detection for exfiltration and execution. New rules for Windows include detection for command and control, exfiltration, and execution. Additionally, significant rule tuning for Windows, Azure, Linux, MacOS, Nginx and Fortinet rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-19-17-prebuilt-rules-8-19-17-summary, 8.19.17>> | 11 Mar 2026 | 10 | 34 | 
This release includes new rules for Microsoft 365, Kubernetes, Okta and Windows. New rules for Microsoft 365 include detection for initial access, collection, discovery, credential access and defense evasion. New rules for Kubernetes include detection for privilege escalation. New rules for Windows include detection for privilege escalation, command and control and initial access. Additionally, significant rule tuning for Windows, Linux, Kubernetes, PAN-OS, Microsoft 365 and AWS rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-19-16-prebuilt-rules-8-19-16-summary, 8.19.16>> | 24 Feb 2026 | 18 | 93 | 
This release includes new rules for Windows, Linux, Okta, Azure, Fortinet and AWS. New rules for Windows include detection for execution and defense evasion. New rules for Linux include detection for persistence, defense evasion and discovery. New rules for Okta include detection for credential access. New rules for Fortinet include detection for initial access. New rules for Azure include detection for initial access. New rules for AWS include detection for persistence, defense evasion and discovery. Additionally, significant rule tuning for Windows, Okta, Azure, Linux, Microsoft 365 and AWS rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-19-15-prebuilt-rules-8-19-15-summary, 8.19.15>> | 10 Feb 2026 | 53 | 36 | 
This release includes new rules for MacOS, Windows, Linux, Fortinet and AWS. New rules for MacOS command and control, persistence, execution, discovery, lateral movement and collection New rules for Windows include detection for command and control and initial access. New rules for Linux include detection for command and control and execution. New rules for Fortinet include detection for persistence, collection, defense evasion and initial access. New rules for AWS include detection for defense evasion. Rules that consistently demonstrated low true-positive rates across data sources have been deprecated. Additionally, significant rule tuning for Windows, Linux, Kubernetes, MacOS, Microsoft 365 and AWS rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-19-14-prebuilt-rules-8-19-14-summary, 8.19.14>> | 30 Jan 2026 | 12 | 147 | 
This release includes new rules for Windows and Linux. New rules for Windows include detection for lateral movement and execution. New rules for Linux include detection for initial access and execution. Selected AWS rules on RDS, EC2 and ElastiCache Security Group have been deprecated. Additionally, significant rule tuning for Windows, Linux, Kubernetes and Azure rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-19-13-prebuilt-rules-8-19-13-summary, 8.19.13>> | 16 Jan 2026 | 33 | 459 | 
This release includes new rules for Windows, Linux, Github, PAN-OS, Azure and GCP. New rules for Windows include detection for persistence, initial access and command and control. New rules for Linux include detection for initial access, collection and command and control. New rules for Github include detection for initial access, impact, exfiltration, persistence and defense evasion. New rules for PAN-OS include detection for initial access. New rules for Azure include detection for initial access. New rules for GCP include detection for initial access. Additionally, significant rule tuning for Windows, Linux, MacOS, AWS, Microsoft 365, and Azure rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-19-12-prebuilt-rules-8-19-12-summary, 8.19.12>> | 09 Dec 2025 | 21 | 79 | 
This release includes new rules for Windows, Linux, MacOS, AWS, Azure Github, Network Packet Capture and Nginx. New rules for Windows include detection for initial access, execution, defense evasion, command and control and credential access. New rules for Linux include detection for initial access, execution, defense evasion, command and control and credential access. New rules for MacOS include detection for initial access, execution, defense evasion, command and control and credential access. New rules for AWS include detection for credential access. New rules for Azure include detection for credential access. New rules for Github include detection for initial access. New rules for Network Packet Capture include detection for initial access. New rules for Nginx include persistence, discovery and defence evasion. Additionally, significant rule tuning for Windows, Linux, MacOS, AWS, Microsoft 365, Fortinet, and Nginx rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-19-11-prebuilt-rules-8-19-11-summary, 8.19.11>> | 25 Nov 2025 | 19 | 71 | 
This release includes new rules for Windows, Linux, Azure, OKTA and MacOS. New rules for Windows include detection for defense evasion and command and control. New rules for Linux include detection for command and control, defense evasion, execution and initial access. New rules for Azure include detection for impact. New rules for OKTA include detection for credential access. New rules for MacOS include detection for command and control. Additionally, significant rule tuning for Windows, Linux, AWS, Microsoft 3 65and Azure rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-19-10-prebuilt-rules-8-19-10-summary, 8.19.10>> | 11 Nov 2025 | 6 | 48 | 
This release includes new rules for Windows, AWS and Linux. New rules for Windows include detection for initial access and lateral movement. New rules for AWS include detection for exfiltration. New rules for Linux include detection for privilege escalation and credential access. Additionally, significant rule tuning for Windows, Linux, AWS, AWS Bedrock and Microsoft 365 rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-19-9-prebuilt-rules-8-19-9-summary, 8.19.9>> | 20 Oct 2025 | 7 | 18 | 
This release includes new rules for Windows, AWS and Azure. New rules for Windows include detection for execution. New rules for AWS include detection for initial access. New rules for Azure include detection for impact, initial access and exfiltration. Additionally, significant rule tuning for Windows, Linux, AWS and Azure rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-19-8-prebuilt-rules-8-19-8-summary, 8.19.8>> | 07 Oct 2025 | 14 | 105 | 
This release includes new rules for Windows, Linux and Azure. New rules for Windows include detection for privilege escalation. New rules for Linux include detection for privilege escalation, persistence, credential access, defense evasion and command and control. New rules for Azure include detection for privilege escalation, collection, credential access, initial access and command and control. Additionally, significant rule tuning for Windows, Linux, AWS, Okta and Azure rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-19-7-prebuilt-rules-8-19-7-summary, 8.19.7>> | 18 Sep 2025 | 1 | 100 | 
This release includes significant rule tuning for Windows, Linux, Okta and AWS rules for better rule efficacy and performance. 


|<<prebuilt-rule-8-19-6-prebuilt-rules-8-19-6-summary, 8.19.6>> | 02 Sep 2025 | 22 | 112 | 
This release includes new rules for Windows, Linux, Microsoft 365 and Network Traffic. New rules for Windows include detection for impact, credential access, execution, command and control, discovery and defense evasion. New rules for Linux include detection for defense evasion. New rules for Microsoft 365 and Network Traffic include detection for initial access. Additionally, significant rule tuning for Windows, AWS, Microsoft 365, MacOS and Azure rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-19-5-prebuilt-rules-8-19-5-summary, 8.19.5>> | 19 Aug 2025 | 2 | 19 | 
This release includes new rules for Windows, Linux and MacOS. New rules for Windows include detection for persistence and defense evasion. New rules for  Linux and MacOS include detection for defense evasion. Additionally, significant rule tuning for Windows, Okta and Azure rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-19-4-prebuilt-rules-8-19-4-summary, 8.19.4>> | 06 Aug 2025 | 0 | 70 | 
This release includes tuned and deprecated rules. Deprecated rule includes Deprecated - Azure Entra Sign-in Brute Force Microsoft 365 Accounts by Repeat Source. Additionally, ESQL-based rules were tuned for dynamic field standardization along with rule tuning for Elastic Security promotion rule. 


|<<prebuilt-rule-8-19-3-prebuilt-rules-8-19-3-summary, 8.19.3>> | 05 Aug 2025 | 8 | 3 | 
This release includes new rules for Windows and SOC integrations New rules for Windows include detection for credential access. New rules for SOC integrations include promotion rules for Google SecOps, Elastic Security, Microsoft Sentinel, SentinelOne,  CrowdStrike and Splunk. Additionally, significant rule tuning for Windows and Azure rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-19-2-prebuilt-rules-8-19-2-summary, 8.19.2>> | 23 Jul 2025 | 8 | 37 | 
This release includes new rules for Linux, Azure and Kubernetes. The deprecated rules includes Deprecated - Azure Virtual Network Device Modified or Deleted and Deprecated - AWS EC2 Snapshot Activity   New rules for Linux include detection for defense evasion. New rules for Azure include detection for persistence, credential access and discovery. New rules for Kubernetes include detection for execution. Additionally, significant rule tuning for Linux, AWS and Azure rules has been added for better rule efficacy and performance.


|<<prebuilt-rule-8-19-1-prebuilt-rules-8-19-1-summary, 8.19.1>> | 08 Jul 2025 | 15 | 73 | 
This release includes new rules for Linux, Azure, Kubernetes and Microsoft 365. The deprecated rule includes Suspicious File Creation in /etc for Persistence New rules for Linux include detection for persistence, defense evasion, discovery, command and control and execution. New rules for Azure include detection for persistence, initial access and defense evasion. New rules for Kubernetes include detection for defense evasion and execution. New rules for Microsoft 365 include detection for collection. Additionally, significant rule tuning for Windows, Linux, AWS, Azure and Microsoft 365 rules has been added for better rule efficacy and performance.

|==============================================
include::downloadable-packages/8-19-1/prebuilt-rules-8-19-1-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-19-2/prebuilt-rules-8-19-2-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-19-3/prebuilt-rules-8-19-3-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-19-4/prebuilt-rules-8-19-4-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-19-5/prebuilt-rules-8-19-5-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-19-6/prebuilt-rules-8-19-6-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-19-7/prebuilt-rules-8-19-7-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-19-8/prebuilt-rules-8-19-8-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-19-9/prebuilt-rules-8-19-9-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-19-10/prebuilt-rules-8-19-10-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-19-11/prebuilt-rules-8-19-11-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-19-12/prebuilt-rules-8-19-12-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-19-13/prebuilt-rules-8-19-13-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-19-14/prebuilt-rules-8-19-14-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-19-15/prebuilt-rules-8-19-15-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-19-16/prebuilt-rules-8-19-16-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-19-17/prebuilt-rules-8-19-17-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-19-18/prebuilt-rules-8-19-18-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-19-19/prebuilt-rules-8-19-19-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-19-20/prebuilt-rules-8-19-20-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-19-21/prebuilt-rules-8-19-21-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-19-22/prebuilt-rules-8-19-22-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-19-23/prebuilt-rules-8-19-23-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-19-24/prebuilt-rules-8-19-24-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-19-25/prebuilt-rules-8-19-25-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-19-26/prebuilt-rules-8-19-26-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-19-27/prebuilt-rules-8-19-27-summary.asciidoc[leveloffset=+1]
include::downloadable-packages/8-19-28/prebuilt-rules-8-19-28-summary.asciidoc[leveloffset=+1]
