[[security-create-project]]
= Create a Security project

:description: Get started with {serverless-short} {elastic-sec} in a few steps.
:keywords: serverless, security, how-to, get-started

preview:[]

A {serverless-short} project allows you to run {elastic-sec} in an autoscaled and fully-managed environment, where you don't have to manage the underlying {es} cluster and {kib} instances.

[discrete]
[[security-create-project-create-project]]
== Create project

Use your {ecloud} account to create a fully-managed {elastic-sec} project:

. Navigate to https://cloud.elastic.co/[cloud.elastic.co].
. Log in to your {ecloud} account and select **Create project** from the **Serverless projects** panel.
. Select **Next** from the **Security** panel.
. Edit your project settings. (Click **Edit settings** to access all settings.)
+
** **Name**: A unique name for your project.
** **Cloud provider**: The cloud platform where you’ll deploy your project. We currently support Amazon Web Services (AWS).
** **Region**: The cloud platform’s https://www.elastic.co/docs/current/serverless/regions[region] where your project will live.
+
You can also check https://cloud.elastic.co/pricing[the pricing details] to see how you consume {serverless-short} {elastic-sec}.
. Select **Create project**. It takes a few minutes before your project gets created.
. Once the project is ready, select **Continue** to open the **Get started** page. (You might need to log into {ecloud} again.)
+
From here, you can learn more about {elastic-sec} features and start setting up your workspace.
