[[prebuilt-rule-8-12-14-statistical-model-detected-c2-beaconing-activity]]
=== Statistical Model Detected C2 Beaconing Activity

A statistical model has identified command-and-control (C2) beaconing activity. Beaconing can help attackers maintain stealthy communication with their C2 servers, receive instructions and payloads, exfiltrate data and maintain persistence in a network.

*Rule type*: query

*Rule indices*: 

* ml_beaconing.all

*Severity*: low

*Risk score*: 21

*Runs every*: 5m

*Searches indices from*: now-1h ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*: 

* https://www.elastic.co/guide/en/security/current/prebuilt-ml-jobs.html
* https://docs.elastic.co/en/integrations/beaconing
* https://www.elastic.co/security-labs/identifying-beaconing-malware-using-elastic

*Tags*: 

* Domain: Network
* Use Case: C2 Beaconing Detection
* Tactic: Command and Control

*Version*: 6

*Rule authors*: 

* Elastic

*Rule license*: Elastic License v2


==== Setup



*Setup*


The rule requires the Network Beaconing Identification integration assets to be installed, as well as network logs collected by the Elastic Defend or Network Packet Capture integrations.


*Network Beaconing Identification Setup*

The Network Beaconing Identification integration consists of a statistical framework to identify C2 beaconing activity in network logs.


*Prerequisite Requirements:*

- Fleet is required for Network Beaconing Identification.
- To configure Fleet Server refer to the https://www.elastic.co/guide/en/fleet/current/fleet-server.html[documentation].
- Network events collected by the https://docs.elastic.co/en/integrations/endpoint[Elastic Defend] or https://docs.elastic.co/integrations/network_traffic[Network Packet Capture] integration.
- To install Elastic Defend, refer to the https://www.elastic.co/guide/en/security/current/install-endpoint.html[documentation].
- To add the Network Packet Capture integration to an Elastic Agent policy, refer to https://www.elastic.co/guide/en/fleet/current/add-integration-to-policy.html[this] guide.


*The following steps should be executed to install assets associated with the Network Beaconing Identification integration:*

- Go to the Kibana homepage. Under Management, click Integrations.
- In the query bar, search for Network Beaconing Identification and select the integration to see more details about it.
- Follow the instructions under the **Installation** section.


==== Rule query


[source, js]
----------------------------------
beacon_stats.is_beaconing: true and
not process.name: ("WaAppAgent.exe" or "metricbeat.exe" or "packetbeat.exe" or "WindowsAzureGuestAgent.exe" or "HealthService.exe" or "Widgets.exe" or "lsass.exe" or "msedgewebview2.exe" or 
                   "MsMpEng.exe" or "OUTLOOK.EXE" or "msteams.exe" or "FileSyncHelper.exe" or "SearchProtocolHost.exe" or "Creative Cloud.exe" or "ms-teams.exe" or "ms-teamsupdate.exe" or 
                   "curl.exe" or "rundll32.exe" or "MsSense.exe" or "wermgr.exe" or "java" or "olk.exe" or "iexplore.exe" or "NetworkManager" or "packetbeat" or "Ssms.exe" or "NisSrv.exe" or 
                   "gamingservices.exe" or "appidcertstorecheck.exe" or "POWERPNT.EXE" or "miiserver.exe" or "Grammarly.Desktop.exe" or "SnagitEditor.exe" or "CRWindowsClientService.exe" or
                   "agentbeat" or "dnf" or "yum" or "apt"
                  )

----------------------------------

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Command and Control
** ID: TA0011
** Reference URL: https://attack.mitre.org/tactics/TA0011/
* Technique:
** Name: Web Service
** ID: T1102
** Reference URL: https://attack.mitre.org/techniques/T1102/
* Sub-technique:
** Name: Bidirectional Communication
** ID: T1102.002
** Reference URL: https://attack.mitre.org/techniques/T1102/002/
