[[benchmark-rules]]
= Benchmark rules
The Benchmark Integrations page helps you view and manage the cloud security posture (CSP) benchmark rules that are active for each of your <<kspm, Kubernetes security posture management (KSPM) integrations>>. Benchmark rules define security best practices for Kubernetes configuration, and form the basis of the results on the <<kspm, Findings page>>.

<<<<<<< HEAD
To find this page, go to **Security -> Manage -> CSP Benchmarks**. From there, to view the benchmark rules associated with a particular integration, click that integration's name. You can then click on a benchmark rule's name to see details, including information about how to remediate failures, and related links.

You can't edit benchmark rules, but you can enable and disable them for each integration policy. They default to `Enabled`. You can enable or disable them individually, or in bulk by using the *Bulk Actions* menu.
=======
To view the benchmark rules associated with a policy, click that policy's name. You can then click on a benchmark rule's name to see details, including information about how to remediate failures and related links.

You can enable or disable benchmark rules for each integration policy, either individually or in bulk using the *Bulk Actions* menu. By default, benchmark rules are enabled. 
>>>>>>> fb530bef64b81763305902b19fd0e7e1334d648e
