[[cloud-native-security-overview]]
= Cloud native security
Elastic Security for Cloud helps you improve your cloud security posture by comparing your cloud configuration to best practices, and scanning for vulnerabilities. It also helps you monitor and investigate your cloud workloads inside and outside Kubernetes.

This page describes what each solution does and provides links to more information.

[discrete]
== Cloud Security Posture Management (CSPM)
Discovers and evaluates the services in your cloud environment — like storage, compute, IAM, and more — against configuration security guidelines defined by the https://www.cisecurity.org/[Center for Internet Security] (CIS) to help you identify and remediate risks that could undermine the confidentiality, integrity, and availability of your cloud data.

To learn more, refer to <<cspm, Read the CSPM docs>>.

[discrete]
== Kubernetes Security Posture Management (KSPM)
Allows you to identify configuration risks in the various components that make up your Kubernetes cluster.
It does this by evaluating your Kubernetes clusters against secure configuration guidelines defined by the Center for Internet Security (CIS) and generating findings with step-by-step instructions for remediating potential security risks.

<<kspm, Read the KSPM docs>>.

[discrete]
== Cloud Native Vulnerability Management (CNVM)
Scans your cloud workloads for known vulnerabilities. When it finds a vulnerability, it supports your risk assessment by quickly providing information such as the vulnerability's CVSS and severity, which software versions it affects, and whether a fix is available.

<<vuln-management-overview, Read the CNVM docs>>.

[discrete]
== Cloud Workload Protection for Kubernetes
Provides cloud-native runtime protections for containerized environments by identifying and (optionally) blocking unexpected system behavior in Kubernetes containers. These capabilities are sometimes referred to as container drift detection and prevention. The solution also captures detailed process and file telemetry from monitored containers, allowing you to set up custom alerts and protection rules.

<<d4c-overview, Read the CWP for Kubernetes docs>>.

[discrete]
== Cloud Workload Protection for VMs
Helps you monitor and protect your Linux VMs. It uses {elastic-defend} to instantly detect and prevent malicious behavior and malware, and captures workload telemetry data for process, file, and network activity. You can use this data with Elastic's out-of-the-box detection rules and {ml} models. These detections generate alerts that quickly help you identify and remediate threats.

<<cloud-workload-protection, Read the CWP for VMs docs>>.

include::security-posture-management.asciidoc[leveloffset=+1]

include::cspm.asciidoc[leveloffset=+1]
include::cspm-get-started-aws.asciidoc[leveloffset=+2]
include::cspm-get-started-gcp.asciidoc[leveloffset=+2]
include::cspm-get-started-azure.asciidoc[leveloffset=+2]
include::cspm-findings.asciidoc[leveloffset=+2]
include::cspm-benchmark-rules.asciidoc[leveloffset=+2]
include::cspm-cloud-posture-dashboard.asciidoc[leveloffset=+2]
include::cspm-faq.asciidoc[leveloffset=+2]

include::kspm.asciidoc[leveloffset=+1]
include::kspm-get-started.asciidoc[leveloffset=+2]
include::kspm-findings.asciidoc[leveloffset=+2]
include::kspm-benchmark-rules.asciidoc[leveloffset=+2]
include::kspm-cloud-posture-dashboard.asciidoc[leveloffset=+2]
include::kspm-faq.asciidoc[leveloffset=+2]

include::vuln-management-overview.asciidoc[leveloffset=+1]
include::vuln-management-get-started.asciidoc[leveloffset=+2]
include::vuln-management-findings.asciidoc[leveloffset=+2]
include::vuln-management-dashboard.asciidoc[leveloffset=+2]
include::vuln-management-faq.asciidoc[leveloffset=+2]

include::d4c-overview.asciidoc[leveloffset=+1]
include::d4c-get-started.asciidoc[leveloffset=+2]
include::d4c-policy-guide.asciidoc[leveloffset=+2]
include::cloud-nat-sec-kubernetes-dashboard.asciidoc[leveloffset=+2]

include::cloud-workload-protection.asciidoc[leveloffset=+1]
include::environment-variable-capture.asciidoc[leveloffset=+1]
