[[cloud-native-security-overview]]
= Cloud native security
Elastic’s cloud security solutions help you improve your cloud security posture by comparing your cloud configuration to best practices, and scanning for vulnerabilities. They also help you monitor and investigate your cloud workloads inside and outside Kubernetes.

This page describes what each solution does and provides links to more information.

[discrete]
== Cloud Security Posture Management (CSPM)
Helps you to harden your cloud security posture by assessing the configuration of your cloud accounts against security best practices defined by the Center for Internet Security (CIS). Once enabled, it runs regular scans which generate data that can inform your remediation efforts.

To learn more, refer to <<cspm, CSPM>>.

[discrete]
== Kubernetes Security Posture Management (KSPM)
Helps you to harden the security posture of your Kubernetes deployments by assessing their configuration against security best practices defined by the Center for Internet Security (CIS). Once enabled, it runs regular scans which generate data that can inform your remediation efforts.

To learn more, refer to <<kspm, KSPM>>.

[discrete]
== Cloud Native Vulnerability Management (CNVM)
Scans your cloud VMs for known vulnerabilities. When it finds a vulnerability, it supports your risk assessment by quickly providing information such as the CVE and CVSS, whether there is a known exploit of the vulnerability, and which software versions it affects.

To learn more, refer to <<vuln-management-overview, CNVM>>.

[discrete]
== Container Workload Protection
Provides cloud-native runtime protections for containerized environments by identifying and (optionally) blocking unexpected system behavior in Kubernetes containers. These capabilities are sometimes referred to as container drift detection and prevention. The solution also captures detailed process telemetry from monitored containers, allowing you to set up custom alerts and protection rules.

To learn more, refer to <<d4c-overview, Container workload protection>>.

[discrete]
== Cloud Workload Protection for VMs
Helps you monitor and protect your Linux VMs. It captures workload telemetry data containing process, file, and network activity. You can use this data — along with Elastic's out-of-the-box detection rules and machine learning models — to automate threat identification for your cloud VMs. Alerts that are generated from these detections help reduce the time to identify and remediate threats.

To learn more, refer to <<cloud-workload-protection, Cloud workload protection

include::security-posture-management.asciidoc[leveloffset=+1]

include::cspm.asciidoc[leveloffset=+1]
include::cspm-get-started.asciidoc[leveloffset=+2]
include::cspm-findings.asciidoc[leveloffset=+2]
include::cspm-benchmark-rules.asciidoc[leveloffset=+2]
include::cspm-cloud-posture-dashboard.asciidoc[leveloffset=+2]
include::cspm-faq.asciidoc[leveloffset=+2]

include::kspm.asciidoc[leveloffset=+1]
include::kspm-get-started.asciidoc[leveloffset=+2]
include::kspm-findings.asciidoc[leveloffset=+2]
include::kspm-benchmark-rules.asciidoc[leveloffset=+2]
include::kspm-cloud-posture-dashboard.asciidoc[leveloffset=+2]
include::kspm-faq.asciidoc[leveloffset=+2]

include::vuln-management-overview.asciidoc[leveloffset=+1]
include::vuln-management-get-started.asciidoc[leveloffset=+2]
include::vuln-management-findings.asciidoc[leveloffset=+2]
include::vuln-management-faq.asciidoc[leveloffset=+2]

include::d4c-overview.asciidoc[leveloffset=+1]
include::d4c-get-started.asciidoc[leveloffset=+2]
include::d4c-policy-guide.asciidoc[leveloffset=+2]

include::cloud-workload-protection.asciidoc[leveloffset=+1]
include::session-view.asciidoc[leveloffset=+1]
include::cloud-nat-sec-kubernetes-dashboard.asciidoc[leveloffset=+1]
include::environment-variable-capture.asciidoc[leveloffset=+1]
