[[cspm-get-started-azure]]
= Get started with CSPM for Azure

[discrete]
[[cspm-overview-azure]]
== Overview

This page explains how to get started monitoring the security posture of your cloud assets using the Cloud Security Posture Management (CSPM) feature.

.Requirements
[sidebar]
--
* The CSPM integration is available to all {ecloud} users. On-premise deployments require an https://www.elastic.co/pricing[Enterprise subscription].
* To view posture data, you need `read` privileges for the following {es} indices:
** `logs-cloud_security_posture.findings_latest-*`
** `logs-cloud_security_posture.scores-*`
** `Logs-cloud_security_posture.findings`
* The user who gives the CSPM integration GCP permissions must be an Azure subscription `admin`.
--

[discrete]
[[cspm-setup-azure]]
== Set up CSPM for Azure

To set up CSPM for Azure, first add the CSPM integration, then enable cloud account access.


[discrete]
[[cspm-add-and-name-integration-azure]]
=== Add your CSPM integration
. From the Elastic Security *Get started* page, click *Add integrations*.
. Search for `CSPM`, then click on the result.
. Click *Add Cloud Security Posture Management (CSPM)*.
. Under **Configure integration**, select **Azure**.
. Give your integration a name that matches the purpose or team of the Azure subscription you want to monitor, for example, `azure-dev-1`.

[discrete]
[[cspm-set-up-cloud-access-section-azure]]
=== Set up cloud account access

NOTE: To setup CSPM for an Azure subscription, you will need admin privileges for that subscription.

For most users, the simplest option is to use an Azure Resource Manager (ARM) template to automatically provision the necessary resources and permissions in Azure. This method, as well as manual options, are described below.

[discrete]
[[cspm-set-up-ARM]]
=== ARM template setup (recommended)

. Under *Setup Access*, select *ARM Template*.
. Under **Where to add this integration**:
.. Select **New Hosts**.
.. Name the {agent} policy. Use a name that matches the purpose or team of the cloud account or accounts you want to monitor. For example, `azure-dev-1`. Click **Save and continue**. The *ARM Template deployment* window appears.
.. In a new tab, log in to the Azure portal, then return to {kib} and click **Launch ARM Template**. This will open the ARM template in Azure.
.. Copy the `Fleet URL` and `Enrollment Token` that appear in {kib} to the corresponding fields in the ARM Template, then click *Review + create*.
. Return to {kib} and wait for the confirmation of data received from your new integration. Then you can click **View Assets** to see your data.

NOTE: Should there be a note here similar to what's in the GCP setup guide?

[discrete]
[[cspm-set-up-manual-azure]]
=== Manual authentication

To authenticate manually, you'll first need to generate credentials for a new Azure SOME PARTICULAR KIND OF ACCOUNT? with the necessary roles, then provide those credentials to the CSPM integration.

Generate Azure credentials:

The credentials JSON will download to your local machine. Keep it secure since it provides access to your GCP resources.

Provide credentials to the CSPM integration:

. On the CSPM setup screen under **Setup Access**, select **Manual**.

????????????

. Under **Where to add this integration**:
.. If you want to monitor a GCP project where you have not yet deployed {agent}:
... Select **New Hosts**.
... Name the {agent} policy. Use a name that matches the purpose or team of the cloud account or accounts you want to monitor. For example, `dev-gcp-account`.
... Click **Save and continue**, then **Add {agent} to your hosts**. The **Add agent** wizard appears and provides {agent} binaries, which you can download and deploy to a VM in your Azure account.
.. If you want to monitor a GCP project where you have already deployed {agent}:
... Select **Existing hosts**.
... Select an agent policy that applies the GCP project you want to monitor.
. Click **Save and continue**.

Wait for the confirmation that {kib} received data from your new integration. Then you can click **View Assets** to see your data.
