[[cspm]]
= Cloud security posture management

The Cloud Security Posture Management (CSPM) feature discovers and evaluates the services in your cloud environment — like storage, compute, IAM, and more — against configuration security guidelines defined by the https://www.cisecurity.org/[Center for Internet Security] (CIS) to help you identify and remediate risks that could undermine the confidentiality, integrity, and availability of your cloud data.

This feature currently supports Amazon Web Services (AWS), Google Cloud Platform (GCP), and Microsoft Azure. For step-by-step getting started guides, refer to <<cspm-get-started,Get started with CSPM for AWS>>, <<cspm-get-started-gcp, Get started with CSPM for GCP>>, or <<cspm-get-started-azure, Get started with CSPM for Azure>>.

.Requirements
[sidebar]
--
* CSPM is available to all {ecloud} users. On-premise deployments require an https://www.elastic.co/pricing[Enterprise subscription].
* {stack} version 8.10 or greater.
* CSPM only works in the `Default` {kib} space. Installing the CSPM integration on a different {kib} space will not work. 
* CSPM is supported only on AWS, GCP, and Azure commercial cloud platforms, and AWS GovCloud. Other government cloud platforms are not supported. https://github.com/elastic/kibana/issues/new/choose[Click here to request support].
* `Read` privileges for the following {es} indices:
** `logs-cloud_security_posture.findings_latest-*`
** `logs-cloud_security_posture.scores-*`
* The following {kib} privileges:
** Security: `Read`
** Integrations: `Read`
** Saved Objects Management: `Read` 
** Fleet: `All`
--

[discrete]
[[cspm-how-it-works]]
== How CSPM works

Using the read-only credentials you will provide during the setup process, it will evaluate the configuration of resources in your environment every 24 hours.
After each evaluation, the integration sends findings to Elastic. A high-level summary of the findings appears on the <<cloud-nat-sec-posture-dashboard,Cloud Security Posture dashboard>>, and detailed findings appear on the <<findings-page,Findings page>>.
