[[cspm]]
== Cloud Security Posture Management

The Cloud Security Posture Management (CSPM) integration discovers and evaluates the services in your cloud environment, like storage, compute, IAM, and more, against configuration security guidelines defined by the https://www.cisecurity.org/[Center for Internet Security] (CIS) to help you identify and remediate risks that could potentially undermine the confidentiality, integrity, and availability of your cloud data.

This integration currently supports Amazon Web Service (AWS). Support for other major cloud service providers is coming soon. For a step-by-step getting started guide, refer to <<cspm-get-started,Get started with CSPM>>.

.Requirements
[sidebar]
--
* The CSPM integration is available to all Elastic Cloud users. For on-prem deployments, it requires an https://www.elastic.co/pricing[Enterprise subscription].
* {stack} version 8.7 or greater.
--

[discrete]
[[cspm-how-it-works]]
== How CSPM works
When you set up the CSPM integration, you’ll install the {agent} in your cloud account.
Using the read-only credentials you provided during the setup process, it will evaluate the configuration of resources in your environment every 24 hours.
After each evaluation, the integration sends findings to Elastic. Findings appear on the <<cloud-nat-sec-posture-dashboard,Cloud posture dashboard and the <<findings-page,Findings page>>.
