[[cspm]]
= Cloud security posture management

The Cloud Security Posture Management (CSPM) feature discovers and evaluates the services in your cloud environment — like storage, compute, IAM, and more — against configuration security guidelines defined by the https://www.cisecurity.org/[Center for Internet Security] (CIS) to help you identify and remediate risks that could undermine the confidentiality, integrity, and availability of your cloud data.

This feature currently supports Amazon Web Services (AWS) and Google Cloud Platform (GCP). For step-by-step getting started guides, refer to <<cspm-get-started,Get started with CSPM for AWS>> or <<cspm-get-started-gcp, Get started with CSPM for GCP>>.

.Requirements
[sidebar]
--
* The CSPM integration is available to all {ecloud} users. On-premise deployments require an https://www.elastic.co/pricing[Enterprise subscription].
* {stack} version 8.10 or greater.
--

[discrete]
[[cspm-how-it-works]]
== How CSPM works

Using the read-only credentials you will provide during the setup process, it will evaluate the configuration of resources in your environment every 4 hours.
After each evaluation, the integration sends findings to Elastic. A high-level summary of the findings appears on the <<cloud-nat-sec-posture-dashboard,Cloud Security Posture dashboard>>, and detailed findings appear on the <<findings-page,Findings page>>.
