[[kspm-faq]]
== KSPM FAQ
Frequently asked questions related to the Kubernetes Security Posture Management (KSPM) integration.

[discrete]
== General KSPM FAQ

*Can I evaluate the security posture of my Amazon EKS clusters?*
Yes. KSPM currently supports the security posture evaluation of Amazon EKS and unmanaged Kubernetes clusters.

*How often is my cluster’s security posture evaluated?*
Clusters are evaluated upon deployment of a KSPM integration, and every four hours after that.

[discrete]
=== Findings page FAQ

*Are all the findings on the Findings page current?*
Yes. Only the most recent findings appear on the Findings page.

*Can I build custom visualizations and dashboards that incorporate findings data?*
Yes. You can use {kib}'s custom visualization capabilities with findings data. Current findings data can be accessed using the `logs-cloud_security_posture.findings_latest-*` index pattern, while historical findings data can be accessed using the `logs-cloud_security_posture.findings-*` index pattern. To learn more, refer to {kibana-ref}/dashboard.html[Dashboards and visualizations].

*Can I view past findings?*
Yes. Historical findings data is accessible using the `logs-cloud_security_posture.findings-*` index pattern.

[discrete]
=== Benchmark rules FAQ

*Do benchmark rules support multiple Kubernetes deployment types?*
Yes. There are different sets of benchmark rules for self-managed and EKS-managed deployments. Refer to <<get-started-with-kspm,Get started with KSPM>> for more information about setting up each deployment type.

*How often are my resources evaluated against benchmark rules?*
Resources are fetched and evaluated against benchmark rules when a KSPM integration is deployed, and every four hours after that.

*Can I configure the KSPM integration's fetch cycle?*
No, the four-hour fetch cycle is not configurable.

*Can I contribute to the CSP ruleset?*
You can't directly edit benchmark rules. The rules are defined https://github.com/elastic/csp-security-policies[in this repository], where you can raise issues with certain rules. They are written in https://www.openpolicyagent.org/docs/latest/policy-language/[Rego].

*How can I tell which specific version of the CIS benchmarks is in use?*
Refer to the `rule.benchmark.name` and `rule.benchmark.version` fields for documents in these datastreams: `logs-cloud_security_posture.findings-default` and `logs-cloud_security_posture.findings_latest-default`

[discrete]
=== Cluster enrollment FAQ

*When do newly-enrolled clusters appear on the dashboard?*
It can take up to 10 minutes for deployment, resource fetching, evaluation, and data processing before a newly-enrolled cluster appears on the dashboard.

*When do unenrolled clusters disappear from the dashboard?*
A cluster will disappear as soon as the KSPM integration fetches data while that cluster is not enrolled. The fetch process repeats every four hours, which means a newly unenrolled cluster can take a maximum of four hours to disappear from the dashboard.
