[[security-posture-management]]
= Security posture management overview

[discrete]
== Overview
Elastic's <<cspm,Cloud Security Posture Management>> (CSPM) and <<kspm,Kubernetes Security Posture Management>> (KSPM) features help you discover and evaluate the services and resources in your cloud environment — like storage, compute, IAM, and more — against security guidelines defined by the Center for Internet Security (CIS). They help you identify and remediate configuration risks that could undermine the confidentiality, integrity, and availability of your cloud assets, such as publicly exposed storage buckets or overly permissive networking objects.

The KSPM feature assesses the security of your Kubernetes assets, while the CSPM feature assesses the security of your AWS resources such as storage, compute, IAM, and more.

[discrete]
[[security-posture-management-get-started]]
== Getting started
For setup instructions, refer to:

* <<get-started-with-kspm, Get started with KSPM>>
* <<cspm-get-started, Get started with CSPM>>

[discrete]
[[security-posture-use-cases]]
== Use cases

Using the data generated by these features, you can:

*Identify and secure misconfigured infrastructure:*

. Go to the Cloud Security Posture dashboard (*Dashboards > Cloud Security Posture*).
. Click *View all failed findings*, either for an individual resource or a group of resources.
. Click a failed finding to open the Findings flyout.
. Follow the steps under Remediation to fix the misconfiguration.

*Identify the CIS Sections (security best practice categories) with which your resources are least compliant:*

. Go to the Cloud Security Posture dashboard (*Dashboards > Cloud Security Posture*).
. Do one of the following:
.. Under Failed findings by CIS section, click the name of a CIS section to view all failed findings from that section.
.. Go to the *Findings* page and filter by the `rule.section` field. For example, search for `rule.section : API Server` to view findings from the API Server category.

*Identify your least compliant cloud resources*

. Go to the *Findings* page.
. Click the *Group by* menu near the search box, and select *Resource* to sort resources by their number of failed findings.
. Click a resource ID to view associated findings.
