[[vuln-management-get-started]]
= Get started with CNVM

This page explains how to set up Cloud Native Vulnerability Management (CNVM).

.Requirements
[sidebar]
--
* CNVM is available to all {ecloud} users. On-premise deployments require an https://www.elastic.co/pricing[Enterprise subscription].
* {stack} version 8.8 or greater.
* To view vulnerability scan findings, you need access to the following indices:
** `logs-cloud_security_posture.vulnerabilities-*`
** `logs-cloud_security_posture.vulnerabilities_latest-*`
--

NOTE: CNVM currently supports only AWS EC2 Linux workloads.

[discrete]
[[vuln-management-setup]]
== Set up CNVM for AWS

To set up the CNVM integration for AWS, install the integration on a new {agent} policy, sign into the AWS account you want to scan, and run the CloudFormation template.

[discrete]
[[vuln-management-setup-step-1]]
=== Add the CNVM integration

. Go to the {es-sec} Get started page, and click *Add security integrations*.
. Search for `Cloud Native Vulnerability Management`, then click on the result.
. Click on "Add Cloud Native Vulnerability Management".
. Give your integration a name that matches its purpose or the region of the AWS account you want to scan for vulnerabilities, for example, `uswest2-aws-account`.
. Click *Save integration*. This integration will create a new elastic agent policy.
. Click *Add Elastic Agent to your hosts*.

IMPORTANT: Do not attempt to add the integration to an existing {agent} policy. It should always be installed to a new policy, since it should not run on your VMs with existing workloads. For more information refer to <<vuln-management-overview-how-it-works, Vulnerability Management Overview>>.

[discrete]
[[vuln-management-setup-step-2]]
=== Sign in to the AWS management console

. Sign into your AWS management console in a new browser tab.
. Switch to the cloud region with the workloads which you want to scan for vulnerabilities.

[discrete]
[[vuln-management-setup-step-3]]
=== Run the CloudFormation template

. Switch back to the tab where you have {kib} open.
. Click *Launch CloudFormation*.
. Wait for the confirmation of {agent} enrollment.
. Your data will start to appear on the Vulnerabilities tab of the <<vuln-management-findings, Findings page>>.
