[[prebuilt-rule-7-16-4-attempts-to-brute-force-a-microsoft-365-user-account]]
=== Attempts to Brute Force a Microsoft 365 User Account

Identifies attempts to brute force a Microsoft 365 user account. An adversary may attempt a brute force attack to obtain unauthorized access to user accounts.

*Rule type*: threshold

*Rule indices*: 

* filebeat-*
* logs-o365*

*Severity*: high

*Risk score*: 73

*Runs every*: 5m

*Searches indices from*: now-30m ({ref}/common-options.html#date-math[Date Math format], see also <<rule-schedule, `Additional look-back time`>>)

*Maximum alerts per execution*: 100

*References*: 

* https://blueteamblog.com/7-ways-to-monitor-your-office-365-logs-using-siem

*Tags*: 

* Elastic
* Cloud
* Microsoft 365
* Continuous Monitoring
* SecOps
* Identity and Access

*Version*: 10

*Rule authors*: 

* Elastic
* Willem D'Haese
* Austin Songer

*Rule license*: Elastic License v2


==== Investigation guide


[source, markdown]
----------------------------------
## Setup

The Office 365 Logs Fleet integration, Filebeat module, or similarly structured data is required to be compatible with this rule.
----------------------------------

==== Rule query


[source, js]
----------------------------------
event.dataset:o365.audit and event.provider:(AzureActiveDirectory or Exchange) and
  event.category:authentication and event.action:(UserLoginFailed or PasswordLogonInitialAuthUsingPassword) and
  not o365.audit.LogonError:(UserAccountNotFound or EntitlementGrantsNotFound or UserStrongAuthEnrollmentRequired or
                             UserStrongAuthClientAuthNRequired or InvalidReplyTo)

----------------------------------

*Framework*: MITRE ATT&CK^TM^

* Tactic:
** Name: Credential Access
** ID: TA0006
** Reference URL: https://attack.mitre.org/tactics/TA0006/
* Technique:
** Name: Brute Force
** ID: T1110
** Reference URL: https://attack.mitre.org/techniques/T1110/
