[[host-isolation-api]]
=== Isolate a host

Isolates a host running {elastic-defend} from the network.

`Isolated` is a persistent status until the endpoint is given a release command. You must have the *Host Isolation* <<endpoint-management-req,privilege>> and at least a Platinum license to perform this action.

==== Request URL

`POST <kibana host>:<port>/api/endpoint/action/isolate`

(Deprecated) `POST <kibana host>:<port>/api/endpoint/isolate` - This url will return a 308 permanent redirect to `POST <kibana host>:<port>/api/endpoint/action/isolate`

==== Request body

A JSON object with these fields:

include::_response-actions-api-reusable-content.asciidoc[tags=create-response-action-api-common-body-options]


===== Example requests

Isolates a single host with an `endpoint_id` value of `ed518850-681a-4d60-bb98-e22640cae2a8`:

[source,sh]
--------------------------------------------------
POST /api/endpoint/action/isolate
{
  "endpoint_ids": ["ed518850-681a-4d60-bb98-e22640cae2a8"]
}
--------------------------------------------------
// KIBANA

Isolates several hosts; includes a comment:

[source,sh]
--------------------------------------------------
POST /api/endpoint/action/isolate
{
  "endpoint_ids": [
  	"9972d10e-4b9e-41aa-a534-a85e2a28ea42",
  	"bc0e4f0c-3bca-4633-9fee-156c0b505d16",
  	"fa89271b-b9d4-43f2-a684-307cffddeb5a"
  ],
  "comment": "Locked down, pending further investigation"
}
--------------------------------------------------
// KIBANA

Isolates hosts with an associated case; includes a comment:

[source,sh]
--------------------------------------------------
POST /api/endpoint/action/isolate
{
  "endpoint_ids": [
  	"1aa1f8fd-0fb0-4fe4-8c30-92068272d3f0",
  	"b30a11bf-1395-4707-b508-fbb45ef9793e"
  ],
  "case_ids": ["4976be38-c134-4554-bd5e-0fd89ce63667"]
  "comment": "Isolating as initial response"
}
--------------------------------------------------
// KIBANA

===== Response code

`200`::
   Indicates a successful call.

`403`::
	Indicates insufficient user privilege (*Host Isolation* required), or unsupported license level (minimum Platinum license required).

`500`::
	General error. A response message will provide additional details.

==== Response payload

A JSON object with an `id` that refers to the submitted action.

===== Example response

[source,json]
--------------------------------------------------
{
  "action": "233db9ea-6733-4849-9226-5a7039c7161d",
  "data": {
    "id": "233db9ea-6733-4849-9226-5a7039c7161d",
    "agents": ["ed518850-681a-4d60-bb98-e22640cae2a8"],
    "command": "suspend-process",
    "agentType": "endpoint",
    "isExpired": false,
    "isCompleted": true,
    "wasSuccessful": true,
    "errors": [],
    "startedAt": "2022-07-29T19:08:49.126Z",
    "completedAt": "2022-07-29T19:09:44.961Z",
    "outputs": {
      "ed518850-681a-4d60-bb98-e22640cae2a8": {
        "type": "json",
        "content": {
          "key": "value"
        }
      }
    },
    "createdBy": "myuser",
    "comment": "suspend the process",
    "parameters": {
      "entity_id": "abc123"
    }
  }
}
--------------------------------------------------
