:endpoint-artifact-list-id:  endpoint_trusted_apps
[[trusted-applications-api]]
=== Trusted Applications

Create, retrieve, update and delete endpoint <<trusted-apps-ov>> via API. Trusted Applications are managed via the <<exceptions-api-overview>> using a static container id (`list_id`) of `{endpoint-artifact-list-id}` which must be created prior to adding a trusted application. Access to these APIs require that a user have authorization to manage endpoints.


NOTE: Console supports Elasticsearch APIs only. Console doesn't allow interactions with {kib} APIs. You must use `curl` or another HTTP tool instead. For more information, refer to https://www.elastic.co/guide/en/kibana/current/console-kibana.html[Run Elasticsearch API requests].


==== Create Trusted Applications Container

`POST <kibana host>:<port>/api/exception_lists`

===== Request body

A JSON object containing the fields listed below. The request must have the following:

include::_exceptions-api-reusable-content.asciidoc[tags=endpoint-exceptions-request-payload-requirements]

include::../../detections/api/exceptions/api-create-exception-container.asciidoc[tags=create-exception-container-request-body]

===== Example request

[source,console]
--------------------------------------------------
POST api/exception_lists
{
  "description": "Endpoint Security Trusted Apps List",
  "name": "Endpoint Security Trusted Apps List",
  "list_id": "endpoint_trusted_apps",
  "type": "endpoint",
  "namespace_type": "agnostic"
}
--------------------------------------------------
// KIBANA

===== Response code

`200`::
    Indicates a successful call.

===== Response payload

[source,json]
--------------------------------------------------
{
  "_tags": [],
  "created_at": "2020-07-13T09:33:46.187Z",
  "created_by": "elastic",
  "description": "Endpoint Security Trusted Apps List",
  "name": "Endpoint Security Trusted Apps List",
  "list_id": "endpoint_trusted_apps",
  "type": "endpoint",
  "namespace_type": "agnostic",
  "id": "f320c070-c4eb-11ea-80bb-11861bae2798",
  "tags": [],
  "tie_breaker_id": "2c08d5a5-2ecc-4d5a-acfb-0a367f25b3f3",
  "updated_at": "2020-07-13T09:33:46.359Z",
  "updated_by": "elastic"
}
--------------------------------------------------


==== Create Trusted Application

`POST <kibana host>:<port>/api/exception_lists/items`

===== Request Body

A JSON object containing the fields listed below. The request must have the following:

include::_exceptions-api-reusable-content.asciidoc[tags=endpoint-exceptions-request-payload-requirements]

include::_exceptions-api-reusable-content.asciidoc[tag=create-exception-container-request-body]


##### Example request


[source,console]
--------------------------------------------------
VERB_HERE api/exception_lists
{
  // some payload
}
--------------------------------------------------
// KIBANA


===== Response code

`200`::
    Indicates a successful call.

===== Response payload


[source,json]
--------------------------------------------------
{
  "key": "value"
}
--------------------------------------------------




==== Update Trusted Application

`VERB_HERE <kibana host>:<port>/api/exception_lists`

===== Request Body

body docs here


##### Example request


[source,console]
--------------------------------------------------
VERB_HERE api/exception_lists
{
  // some payload
}
--------------------------------------------------
// KIBANA


===== Response code

`200`::
Indicates a successful call.

===== Response payload


[source,json]
--------------------------------------------------
{
  "key": "value"
}
--------------------------------------------------




==== Delete Trusted Application

`VERB_HERE <kibana host>:<port>/api/exception_lists`

===== Request Body

body docs here


##### Example request


[source,console]
--------------------------------------------------
VERB_HERE api/exception_lists
{
  // some payload
}
--------------------------------------------------
// KIBANA


===== Response code

`200`::
Indicates a successful call.

===== Response payload


[source,json]
--------------------------------------------------
{
  "key": "value"
}
--------------------------------------------------





==== Find Trusted Apps

`VERB_HERE <kibana host>:<port>/api/exception_lists`

===== Request Body

body docs here


##### Example request


[source,console]
--------------------------------------------------
VERB_HERE api/exception_lists
{
  // some payload
}
--------------------------------------------------
// KIBANA


===== Response code

`200`::
Indicates a successful call.

===== Response payload


[source,json]
--------------------------------------------------
{
  "key": "value"
}
--------------------------------------------------





==== Retrieve single Trusted Application

`VERB_HERE <kibana host>:<port>/api/exception_lists`

===== Request Body

body docs here


##### Example request


[source,console]
--------------------------------------------------
VERB_HERE api/exception_lists
{
  // some payload
}
--------------------------------------------------
// KIBANA


===== Response code

`200`::
Indicates a successful call.

===== Response payload


[source,json]
--------------------------------------------------
{
  "key": "value"
}
--------------------------------------------------


