[[trusted-applications-api]]
=== Trusted Applications

Create, retrieve, update and delete endpoint <<trusted-apps-ov>> via API. Trusted Applications are managed via the <<exceptions-api-overview>> using a static container id (`list_id`) of `endpoint_trusted_apps` which must be created prior to adding a trusted application. Access to these APIs require that a user have authorization to manage endpoints. All Trusted Application entries for endpoint must be created with an namspace type (`namespace_type`) of `agnostic`.


NOTE: Console supports Elasticsearch APIs only. Console doesn't allow interactions with {kib} APIs. You must use `curl` or another HTTP tool instead. For more information, refer to https://www.elastic.co/guide/en/kibana/current/console-kibana.html[Run Elasticsearch API requests].


==== Create Trusted Application Container

`POST <kibana host>:<port>/api/exception_lists`

===== Request body

A JSON object containing the following:

include::../../detections/api/exceptions/api-create-exception-container.asciidoc[tags=create-exception-container-request-body]

===== Example request

[source,console]
--------------------------------------------------
POST api/exception_lists
{
  "description": "Endpoint Security Trusted Apps List",
  "name": "Endpoint Security Trusted Apps List",
  "list_id": "endpoint_trusted_apps",
  "type": "endpoint",
  "namespace_type": "agnostic"
}
--------------------------------------------------
// KIBANA

===== Response code

`200`::
    Indicates a successful call.

===== Response payload

[source,json]
--------------------------------------------------
{
  "_tags": [],
  "created_at": "2020-07-13T09:33:46.187Z",
  "created_by": "elastic",
  "description": "Endpoint Security Trusted Apps List",
  "name": "Endpoint Security Trusted Apps List",
  "list_id": "endpoint_trusted_apps",
  "type": "endpoint",
  "namespace_type": "agnostic",
  "id": "f320c070-c4eb-11ea-80bb-11861bae2798",
  "tags": [],
  "tie_breaker_id": "2c08d5a5-2ecc-4d5a-acfb-0a367f25b3f3",
  "updated_at": "2020-07-13T09:33:46.359Z",
  "updated_by": "elastic"
}
--------------------------------------------------


==== Create Trusted App

`GET <kibana host>:<port>/api/endpoint/metadata/<endpointID>`

===== Example request

Document how to create

[source,sh]
--------------------------------------------------
GET /../some/api
--------------------------------------------------
// KIBANA

===== Response


==== Retrieve

`GET <kibana host>:<port>/api/endpoint/metadata/<endpointID>`

===== Example request

Document how to create

[source,sh]
--------------------------------------------------
GET /../some/api
--------------------------------------------------
// KIBANA

===== Response


tbd


