[[security-endpoint-command-ref]]
= {elastic-endpoint} command reference

:description: Manage and troubleshoot {elastic-endpoint} using CLI commands.
:keywords: security, reference, manage

preview:[]

This page lists the commands for management and troubleshooting of {elastic-endpoint}, the installed component that performs {elastic-defend}'s threat monitoring and prevention.

[NOTE]
====
* {elastic-endpoint} is not added to the `PATH` system variable, so you must prepend the commands with the full OS-dependent path:
+
** On Windows: `"C:\Program Files\Elastic\Endpoint\elastic-endpoint.exe"`
** On macOS: `/Library/Elastic/Endpoint/elastic-endpoint`
** On Linux: `/opt/Elastic/Endpoint/elastic-endpoint`
* You must run the commands with elevated privileges—using `sudo` to run as the root user on Linux and macOS, or running as Administrator on Windows.
====

The following {elastic-endpoint} commands are available:

* <<security-endpoint-command-ref-elastic-endpoint-diagnostics,diagnostics>>
* <<security-endpoint-command-ref-elastic-endpoint-help,help>>
* <<security-endpoint-command-ref-elastic-endpoint-inspect,inspect>>
* <<security-endpoint-command-ref-elastic-endpoint-install,install>>
* <<security-endpoint-command-ref-elastic-endpoint-memorydump,memorydump>>
* <<security-endpoint-command-ref-elastic-endpoint-run,run>>
* <<security-endpoint-command-ref-elastic-endpoint-send,send>>
* <<security-endpoint-command-ref-elastic-endpoint-status,status>>
* <<security-endpoint-command-ref-elastic-endpoint-test,test>>
* <<security-endpoint-command-ref-elastic-endpoint-top,top>>
* <<security-endpoint-command-ref-elastic-endpoint-uninstall,uninstall>>
* <<security-endpoint-command-ref-elastic-endpoint-version,version>>

Each of the commands accepts the following logging options:

* `--log [stdout,stderr,debugview,file]`
* `--log-level [error,info,debug]`

[discrete]
[[security-endpoint-command-ref-elastic-endpoint-diagnostics]]
== elastic-endpoint diagnostics

Gather diagnostics information from {elastic-endpoint}. This command produces an archive that contains:

* `version.txt`: Version information
* `elastic-endpoint.yaml`: Current policy
* `metrics.json`: Metrics document
* `policy_response.json`: Last policy response
* `system_info.txt`: System information
* `analysis.txt`: Diagnostic analysis report
* `logs` directory: Copy of {elastic-endpoint} log files

[discrete]
[[security-endpoint-command-ref-example]]
=== Example

[source,txt]
----
elastic-endpoint diagnostics
----

[discrete]
[[security-endpoint-command-ref-elastic-endpoint-help]]
== elastic-endpoint help

Show help for the available commands.

[discrete]
[[security-endpoint-command-ref-example-1]]
=== Example

[source,txt]
----
elastic-endpoint help
----

[discrete]
[[security-endpoint-command-ref-elastic-endpoint-inspect]]
== elastic-endpoint inspect

Show the current {elastic-endpoint} configuration.

[discrete]
[[security-endpoint-command-ref-example-2]]
=== Example

[source,txt]
----
elastic-endpoint inspect
----

[discrete]
[[security-endpoint-command-ref-elastic-endpoint-install]]
== elastic-endpoint install

Install {elastic-endpoint} as a system service.

[NOTE]
====
We do not recommend installing {elastic-endpoint} using this command. {elastic-endpoint} is managed by {agent} and cannot function as a standalone service. Therefore, there is no separate installation package for {elastic-endpoint}, and it should not be installed independently.
====

[discrete]
[[security-endpoint-command-ref-options-3]]
=== Options

`--resources <string>`::
Specify a resources `.zip` file to be used during the installation. This option is required.

`--upgrade`::
Upgrade the existing installation.

[discrete]
[[security-endpoint-command-ref-example-4]]
=== Example

[source,txt]
----
elastic-endpoint install --upgrade --resources endpoint-security-resources.zip
----

[discrete]
[[security-endpoint-command-ref-elastic-endpoint-memorydump]]
== elastic-endpoint memorydump

Save a memory dump of the {elastic-endpoint} service.

[discrete]
[[security-endpoint-command-ref-options-5]]
=== Options

`--compress`::
Compress the saved memory dump.

`--timeout <duration>`::
Specify the memory collection timeout, in seconds; the default is 60 seconds.

[discrete]
[[security-endpoint-command-ref-example-6]]
=== Example

[source,txt]
----
elastic-endpoint memorydump --timeout 120
----

[discrete]
[[security-endpoint-command-ref-elastic-endpoint-run]]
== elastic-endpoint run

Run `elastic-endpoint` as a foreground process if no other instance is already running.

[discrete]
[[security-endpoint-command-ref-example-7]]
=== Example

[source,txt]
----
elastic-endpoint run
----

[discrete]
[[security-endpoint-command-ref-elastic-endpoint-send]]
== elastic-endpoint send

Send the requested document to the {stack}.

[discrete]
[[security-endpoint-command-ref-subcommands-8]]
=== Subcommands

`metadata`::
Send an off-schedule metrics document to the {stack}.

[discrete]
[[security-endpoint-command-ref-example-9]]
=== Example

[source,txt]
----
elastic-endpoint send metadata
----

[discrete]
[[security-endpoint-command-ref-elastic-endpoint-status]]
== elastic-endpoint status

Retrieve the current status of the running {elastic-endpoint} service. The command also returns the last known status of {agent}.

[discrete]
[[security-endpoint-command-ref-options-10]]
=== Options

`--output`::
Control the level of detail and formatting of the information. Valid values are:

* `human`: Returns limited information when {elastic-endpoint}'s status is `Healthy`. If any policy actions weren't successfully applied, the relevant details are displayed.
* `full`: Always returns the full status information.
* `json`: Always returns the full status information.

[discrete]
[[security-endpoint-command-ref-example-11]]
=== Example

[source,txt]
----
elastic-endpoint status --output json
----

[discrete]
[[security-endpoint-command-ref-elastic-endpoint-test]]
== elastic-endpoint test

Perform the requested test.

[discrete]
[[security-endpoint-command-ref-subcommands-12]]
=== Subcommands

`output`::
Test whether {elastic-endpoint} can connect to remote resources.

[discrete]
[[security-endpoint-command-ref-example-13]]
=== Example

[source,txt]
----
elastic-endpoint test output
----

[discrete]
[[security-endpoint-command-ref-example-output-14]]
=== Example output

[source,txt]
----
Testing output connections

Using proxy:

Elasticsearch server: https://example.elastic.co:443
        Status: Success

Global artifact server: https://artifacts.security.elastic.co
        Status: Success

Fleet server: https://fleet.example.elastic.co:443
        Status: Success
----

[discrete]
[[security-endpoint-command-ref-elastic-endpoint-top]]
== elastic-endpoint top

Show a breakdown of the executables that triggered {elastic-endpoint} CPU usage within the last interval. This displays which {elastic-endpoint} features are resource-intensive for a particular executable.

[NOTE]
====
The meaning and output of this command are similar, but not identical, to the POSIX `top` command. The `elastic-endpoint top` command aggregates multiple processes by executable. The utilization values aren't measured by the OS scheduler but by a wall clock in user mode. The output helps identify outliers causing excessive CPU utilization, allowing you to fine-tune the {elastic-defend} policy and exception lists in your deployment.
====

[discrete]
[[security-endpoint-command-ref-options-15]]
=== Options

`--interval <duration>`::
Specify the data collection interval, in seconds; the default is 5 seconds.

`--limit <number>`::
Specify the number of updates to collect; by default, data is collected until interrupted by **Ctrl+C**.

`--normalized`::
Normalize CPU usage values to a total of 100% across all CPUs on multi-CPU systems.

[discrete]
[[security-endpoint-command-ref-example-16]]
=== Example

[source,txt]
----
elastic-endpoint top --interval 10 --limit 5
----

[discrete]
[[security-endpoint-command-ref-example-output-17]]
=== Example output

[source,txt]
----
| PROCESS                                            | OVERALL | API | BHVR | DIAG BHVR | DNS | FILE   | LIB | MEM SCAN | MLWR  | NET | PROC | RANSOM | REG |
=============================================================================================================================================================
| MSBuild.exe                                        |  3146.0 | 0.0 |  0.8 |       0.7 | 0.0 | 2330.9 | 0.0 |    226.2 | 586.9 | 0.0 |  0.0 |    0.4 | 0.0 |
| Microsoft.Management.Services.IntuneWindowsAgen... |    30.0 | 0.0 |  0.0 |       0.0 | 0.0 |    0.0 | 0.2 |     29.8 |   0.0 | 0.0 |  0.0 |    0.0 | 0.0 |
| svchost.exe                                        |    27.3 | 0.0 |  0.1 |       0.1 | 0.0 |    0.4 | 0.2 |      0.0 |  26.6 | 0.0 |  0.0 |    0.0 | 0.0 |
| LenovoVantage-(LenovoServiceBridgeAddin).exe       |     0.1 | 0.0 |  0.0 |       0.0 | 0.0 |    0.0 | 0.1 |      0.0 |   0.0 | 0.0 |  0.0 |    0.0 | 0.0 |
| Lenovo.Modern.ImController.PluginHost.Device.exe   |     0.0 | 0.0 |  0.0 |       0.0 | 0.0 |    0.0 | 0.0 |      0.0 |   0.0 | 0.0 |  0.0 |    0.0 | 0.0 |
| msedgewebview2.exe                                 |     0.0 | 0.0 |  0.0 |       0.0 | 0.0 |    0.0 | 0.0 |      0.0 |   0.0 | 0.0 |  0.0 |    0.0 | 0.0 |
| msedge.exe                                         |     0.0 | 0.0 |  0.0 |       0.0 | 0.0 |    0.0 | 0.0 |      0.0 |   0.0 | 0.0 |  0.0 |    0.0 | 0.0 |
| powershell.exe                                     |     0.0 | 0.0 |  0.0 |       0.0 | 0.0 |    0.0 | 0.0 |      0.0 |   0.0 | 0.0 |  0.0 |    0.0 | 0.0 |
| WmiPrvSE.exe                                       |     0.0 | 0.0 |  0.0 |       0.0 | 0.0 |    0.0 | 0.0 |      0.0 |   0.0 | 0.0 |  0.0 |    0.0 | 0.0 |
| Lenovo.Modern.ImController.PluginHost.Device.exe   |     0.0 | 0.0 |  0.0 |       0.0 | 0.0 |    0.0 | 0.0 |      0.0 |   0.0 | 0.0 |  0.0 |    0.0 | 0.0 |
| Slack.exe                                          |     0.0 | 0.0 |  0.0 |       0.0 | 0.0 |    0.0 | 0.0 |      0.0 |   0.0 | 0.0 |  0.0 |    0.0 | 0.0 |
| uhssvc.exe                                         |     0.0 | 0.0 |  0.0 |       0.0 | 0.0 |    0.0 | 0.0 |      0.0 |   0.0 | 0.0 |  0.0 |    0.0 | 0.0 |
| explorer.exe                                       |     0.0 | 0.0 |  0.0 |       0.0 | 0.0 |    0.0 | 0.0 |      0.0 |   0.0 | 0.0 |  0.0 |    0.0 | 0.0 |
| taskhostw.exe                                      |     0.0 | 0.0 |  0.0 |       0.0 | 0.0 |    0.0 | 0.0 |      0.0 |   0.0 | 0.0 |  0.0 |    0.0 | 0.0 |
| Widgets.exe                                        |     0.0 | 0.0 |  0.0 |       0.0 | 0.0 |    0.0 | 0.0 |      0.0 |   0.0 | 0.0 |  0.0 |    0.0 | 0.0 |
| elastic-endpoint.exe                               |     0.0 | 0.0 |  0.0 |       0.0 | 0.0 |    0.0 | 0.0 |      0.0 |   0.0 | 0.0 |  0.0 |    0.0 | 0.0 |
| sppsvc.exe                                         |     0.0 | 0.0 |  0.0 |       0.0 | 0.0 |    0.0 | 0.0 |      0.0 |   0.0 | 0.0 |  0.0 |    0.0 | 0.0 |

Endpoint service (16 CPU): 113.0% out of 1600%

Collecting data.  Press Ctrl-C to cancel
----

[discrete]
[[security-endpoint-command-ref-column-abbreviations]]
==== Column abbreviations

* `API`: Event Tracing for Windows (ETW) API events
* `AUTH`: Authentication events
* `BHVR`: Malicious behavior protection
* `CRED`: Credential access events
* `DIAG BHVR`: Diagnostic malicious behavior protection
* `DNS`: DNS events
* `FILE`: File events
* `LIB`: Library load events
* `MEM SCAN`: Memory scanning
* `MLWR`: Malware protection
* `NET`: Network events
* `PROC`: Process events
* `PROC INJ`: Process injection
* `RANSOM`: Ransomware protection
* `REG`: Registry events

[discrete]
[[security-endpoint-command-ref-elastic-endpoint-uninstall]]
== elastic-endpoint uninstall

Uninstall {elastic-endpoint}.

[NOTE]
====
{elastic-endpoint} is managed by {agent}. To remove {elastic-endpoint} from the target machine permanently, remove the {elastic-defend} integration from the {fleet} policy. The <<security-uninstall-agent,elastic-agent uninstall>> command also uninstalls {elastic-endpoint}; therefore, in practice, the `elastic-endpoint uninstall` command is used only to troubleshoot broken installations.
====

[discrete]
[[security-endpoint-command-ref-options-18]]
=== Options

`--uninstall-token <string>`::
Provide the uninstall token. The token is required if <<security-agent-tamper-protection,agent tamper protection>> is enabled.

[discrete]
[[security-endpoint-command-ref-example-19]]
=== Example

[source,txt]
----
elastic-endpoint uninstall --uninstall-token 12345678901234567890123456789012
----

[discrete]
[[security-endpoint-command-ref-elastic-endpoint-version]]
== elastic-endpoint version

Show the version of {elastic-endpoint}.

[discrete]
[[security-endpoint-command-ref-example-20]]
=== Example

[source,txt]
----
elastic-endpoint version
----
