[[endpoint-protection-rules]]
= Endpoint protection rules

Endpoint protection rules are <<security-prebuilt-rules-management, prebuilt rules>> designed to help you manage and respond to alerts generated by {elastic-endpoint}, the installed component that performs {elastic-defend}'s threat monitoring and prevention. These rules include the {elastic-defend} rule as well as additional detection and prevention rules for different {elastic-defend} protection features.

IMPORTANT: To receive {elastic-endpoint} alerts, you must install {agent} and the {elastic-defend} integration on your hosts (see <<security-install-edr>>).

[discrete]
[[defend-rule]]
== {elastic-defend} rule

The {elastic-defend} rule automatically creates an alert from all incoming {elastic-endpoint} alerts. When this rule is enabled, the following Endpoint events are displayed as detection alerts:

** Malware Prevention Alert
** Malware Detection Alert

NOTE: When you load the prebuilt rules, this is the only rule that is enabled by default.

[discrete]
[[feature-protection-rules]]
== Feature-specific protection rules

The following endpoint protection rules give you more granular control over how you handle the generated alerts. These rules are tailored for each of {elastic-defend}'s endpoint protection features—malware, ransomware, memory threats, and malicious behavior. Enabling these rules allows you to configure more specific actions based on the protection feature and whether the malicious activity was prevented or detected.

* Behavior - Detected - Elastic Defend
* Behavior - Prevented - Endpoint Defend
* Malicious File - Detected - Elastic Defend
* Malicious File - Prevented - Elastic Defend
* Memory Signature - Detected - Elastic Defend
* Memory Signature - Prevented - Elastic Defend
* Ransomware - Detected - Elastic Defend
* Ransomware - Prevented - Elastic Defend

To use these rules, you need to manually enable them from the **Rules** page in the {security-app}. Follow the instructions for <<load-prebuilt-rules,installing and enabling Elastic prebuilt rules>>.

[discrete]
== Endpoint security exception handling

All endpoint protection rules share a common exception list called the Endpoint Security Exception List. This ensures that if you switch between using the {elastic-defend} rule and the feature-specific protection rules, your existing <<endpoint-rule-exceptions, {elastic-endpoint} exceptions>> continue to apply.