[[es-overview]]
[chapter, role="xpack"]
= Elastic Security overview

{elastic-sec} combines threat detection analytics, cloud native security, and endpoint protection capabilities in a single solution, so you can quickly detect, investigate, and respond to threats and vulnerabilities across your environment.

Elastic Security provides:

* A detection engine that identifies a wide range of threats
* A workspace for event triage, investigation, and case management
* Interactive data visualization tools 
* Integrations for collecting data from various sources

[discrete]
[[siem-integration]]
=== Learn more

To learn more about {elastic-sec}, use the left-side navigation menu, review the <<getting-started, Getting started>> documentation section (which covers topics including system requirements, workspaces, how to configure {elastic-sec}, and how to ingest data), or refer to the following resources:

* <<es-ui-overview, Elastic Security UI overview>> - learn about navigating among {elastic-sec}'s various tools and interfaces.
* <<about-rules, Detection rules>> - learn about {elastic-sec}'s detection engine, including how to build custom rules and how to use Elastic's prebuilt rules.
* <<cloud-native-security-overview, Cloud native security>> - learn how to enable cloud native security capabilities such as Cloud and Kubernetes security posture management, cloud native vulnerability management, and cloud workload protection for Kubernetes and VMs.
* <<install-endpoint, Install {elastic-defend}>> - learn how to enable key endpoint protection capabilities like event collection, and detection and prevention of malicious activity.
* https://www.elastic.co/products/stack/machine-learning[{ml-cap}] - learn about built-in {ml} tools that can help you identify malicious behavior.
* <<security-ref-intro, {elastic-sec} fields and object schemas>> — learn about how your data should be structured for use with {elastic-sec}.

{elastic-sec} uses {es} for data storage, management, and search, and {kib} is its main user interface. Learn more:

* https://www.elastic.co/products/elasticsearch[{es}]: A real-time,
distributed storage, search, and analytics engine. {elastic-sec} stores your data using {es}.
* https://www.elastic.co/products/kibana[{kib}]: An open-source analytics and
visualization platform designed to work with {es} and {elastic-sec}. {kib} allows you to search,
view, analyze and visualize data stored in {es} indices.

[discrete]
[[self-protection]]
==== Elastic Endpoint self-protection

For information about {endpoint}'s tamper-protection features, refer to <<endpoint-self-protection, {elastic-endpoint} self-protection>>.