[[es-overview]]
[chapter, role="xpack"]
= {elastic-sec} overview

{elastic-sec} combines threat detection analytics, cloud native security, and endpoint protection capabilities in a single solution, so you can quickly detect, investigate, and respond to threats and vulnerabilities across your environment.

{elastic-sec} provides:

* A detection engine that identifies a wide range of threats
* A workspace for event triage, investigation, and case management
* Interactive data visualization tools 
* Integrations for collecting data from various sources

[discrete]
[[siem-integration]]
=== Learn more

* <<getting-started, Get started>>: Learn about system requirements, workspaces, configuration, and data ingestion.
* <<es-ui-overview, {elastic-sec} UI overview>>: Navigate {elastic-sec}'s various tools and interfaces.
* <<about-rules, Detection rules>>: Use {elastic-sec}'s detection engine with custom and prebuilt rules.
* <<cloud-native-security-overview, Cloud native security>>: Enable cloud native security capabilities such as Cloud and Kubernetes security posture management, cloud native vulnerability management, and cloud workload protection for Kubernetes and VMs.
* <<install-endpoint, Install {elastic-defend}>>: Enable key endpoint protection capabilities like event collection and malicious activity prevention.
* https://www.elastic.co/products/stack/machine-learning[{ml-cap}]: Enable built-in {ml} tools to help you identify malicious behavior.
* <<advanced-entity-analytics-overview, Advanced entity analytics>>: Leverage {elastic-sec}'s detection engine and {ml} capabilities to generate comprehensive risk analytics for hosts and users.
* <<security-assistant, Elastic AI assistant>>: Ask AI Assistant questions about how to use {elastic-sec}, how to understand particular alerts and other documents, and how to write {esql} queries.
* <<security-ref-intro, {elastic-sec} fields and object schemas>>: Learn how to structure data for use with {elastic-sec}.

[discrete]
[[elastic-search-and-kibana]]
=== {es} and {kib}

{elastic-sec} uses {es} for data storage, management, and search, and {kib} is its main user interface. Learn more:

* https://www.elastic.co/products/elasticsearch[{es}]: A real-time,
distributed storage, search, and analytics engine. {elastic-sec} stores your data using {es}.
* https://www.elastic.co/products/kibana[{kib}]: An open-source analytics and
visualization platform designed to work with {es} and {elastic-sec}. {kib} allows you to search,
view, analyze and visualize data stored in {es} indices.

[discrete]
[[self-protection]]
==== Elastic Endpoint self-protection

For information about {elastic-endpoint}'s tamper-protection features, refer to <<endpoint-self-protection, {elastic-endpoint} self-protection>>.