[[post-upgrade-req]]
[role="xpack"]
= Enable process analyzer after an upgrade

After upgrading from {stack} version 7.9.x to >= 7.10.x from a previous minor release (e.g., 7.8.x, etc.), you need to update `.siem-signals*` system index mappings to enable <<alerts-analyze-events, graphical representations of process relationships>>.

NOTE: If you are upgrading from a minor release to {stack} version >=7.11.0, there is now a <<signals-migration-api>> that you can use instead of the manual process described below.

To update the `.siem-signals*` index:

. Create a new {ref}/index-templates.html[index template] for storing existing
detections alerts (see <<create-template>>).
. Deactivate all detection rules (see <<disable-all-rules>>).
. Copy existing `.siem-signals*` detection alerts to a new index (see
<<copy-alerts>>).
. Delete the original `.siem-signals*` index, as well as the original index
lifecycle management {ref}/index-lifecycle-management.html[(ILM) policy] and
template (see <<delete-existing-indices>>).
. Enable detection rules, which automatically creates the new `.siem-signals*`
system indices, ILM policy, and template (see <<enable-req-rules>>).
. Restore existing detection alerts to the new `.siem-signals*` index (see
<<restore-index>>).
. Add an alias to the `.siem-signals*` index for the restored detection alerts
index (see <<index-alias>>).

[discrete]
[[create-template]]
=== Create index template

. In {kib}, go to *Management* -> *Dev Tools*.
. Do *one* of the following:
* Copy and paste <<signals-index-template, this code>> into the console.
+
*OR*
* Follow these steps:
.. Run the following command in the console:
+
[source,console]
--------------------------------------------------
GET _template/.siem-signals-<space> <1>
--------------------------------------------------
<1> `<space>` is the name of the {kib} space in which the detection alerts
reside (for example, `GET _template/.siem-signals-default`).
+
The existing `.siem-signals` template is displayed in the console's output pane.
.. Copy the code in the console output pane and paste it into the console input
pane.
.. Edit the code in the input pane as follows:
** Add this line immediately above the code:
+
[source,txt]
--------------------------------------------------
PUT _template/temp-signals
--------------------------------------------------
** Delete this line:
+
[source,txt]
--------------------------------------------------
".siem-signals-default" : {
--------------------------------------------------
** Delete the `lifecycle` object:
+
[source,js]
--------------------------------------------------
"lifecycle" : {
    "name" : ".siem-signals-default",
    "rollover_alias" : ".siem-signals-default"
},
--------------------------------------------------
** Change the value of the `index_pattern` element to `temp-signals`:
+
[source,js]
--------------------------------------------------
"index_patterns" : [
    "temp-signals"
],
--------------------------------------------------
.. Make sure the first few lines of the code are identical to this:
+
[source,txt]
--------------------------------------------------
PUT _template/temp-signals
{
    "order" : 0,
    "version" : 1,
    "index_patterns" : [
      "temp-signals"
    ],
    "settings" : {
      "index" : {
        "mapping" : {
          "total_fields" : {
            "limit" : "10000"
          }
        }
      }
    },
--------------------------------------------------
. Run the code (click on the run icon).
+
The console output pane displays this text:
+
[source,console-result]
--------------------------------------------------
{
  "acknowledged" : true
}
--------------------------------------------------

[discrete]
[[disable-all-rules]]
=== Disable all detection rules

To disable all detection rules:

. Go to *Security* -> *Detections* -> *Manage detection rules*.
. Scroll to the bottom of the page.
. Click the `Rows per page` menu, and then select _300 rows_.
. When the page reloads, select all the rules.
. Click _Bulk actions_ -> _Deactivate selected_.

[discrete]
[[copy-alerts]]
=== Add existing detection alerts to a new index

To enable restoring existing detection alerts after recreating the
`.siem-signals-*` index mapping, add (reindex) existing alerts to the
`temp-signals` index:

. Go to *Management* -> *Dev Tools*.
. Run this code in the console:
+
[source,console]
--------------------------------------------------
POST _reindex
{
  "source": {
    "index": ".siem-signals-<space>-*" <1>
  },
  "dest": {
    "index": "temp-signals"
  }
}
--------------------------------------------------
<1> `<space>` is the name of the {kib} space in which the detection alerts
reside (for example, `"index": ".siem-signals-default-*"`).
+
The console output pane displays text similar to this:
+
[source,console-result]
--------------------------------------------------
{
  "took" : 603,
  "timed_out" : false,
  "total" : 15,
  "updated" : 0,
  "created" : 15,
  "deleted" : 0,
  "batches" : 1,
  "version_conflicts" : 0,
  "noops" : 0,
  "retries" : {
    "bulk" : 0,
    "search" : 0
  },
  "throttled_millis" : 0,
  "requests_per_second" : -1.0,
  "throttled_until_millis" : 0,
  "failures" : [ ]
}
--------------------------------------------------

[discrete]
[[delete-existing-indices]]
=== Delete existing `.siem-signals-*` indices and templates

The existing `.siem-signals-*` system indices, templates, and ILM policy must be
deleted before the new indices are created:

. Go to *Management* -> *Dev Tools*.
. Run these commands in the console:
+
[source,console]
--------------------------------------------------
DELETE .siem-signals-<space>-* <1>
DELETE _template/.siem-signals-<space>
DELETE _ilm/policy/.siem-signals-<space>
--------------------------------------------------
<1> `<space>` is the name of the {kib} space (for example,
`DELETE .siem-signals-default-*`).
+
NOTE: You must run each command individually.
+
Foe each command, the console output pane displays this text:
+
[source,console-result]
--------------------------------------------------
{
  "acknowledged" : true
}
--------------------------------------------------

[discrete]
[[enable-req-rules]]
=== Enable detection rules

Enabling detections rules automatically creates the new indices:

. Go to *Security* -> *Detections* -> *Manage detection rules*.
. Select the rules you want to activate.
. Click _Bulk actions_ -> _Activate selected_.
+
The selected rules are activated and the new index, index template, and ILM
policy are created.
. To verify the new index has been created:
.. Go to *Management* -> *Dev Tools*.
.. Run the following command:
+
[source,console]
--------------------------------------------------
GET .siem-signals-<space>-*/_mapping/field/process.entity_id <1>
--------------------------------------------------
<1> `<space>` is the name of the {kib} space (for example,
`GET .siem-signals-default-*/_mapping/field/process.entity_id`).
+
The console output pane displays text similar to this:
+
[source,console-result]
--------------------------------------------------
{
  ".siem-signals-default-000001" : {
    "mappings" : {
      "process.entity_id" : {
        "full_name" : "process.entity_id",
        "mapping" : {
          "entity_id" : {
            "type" : "keyword",
            "ignore_above" : 1024
          }
        }
      }
    }
  }
}
--------------------------------------------------

[discrete]
[[restore-index]]
=== Restore previously existing detections alerts

To restore detection alerts:

. Go to *Management* -> *Dev Tools*.
. Run the following command:
+
[source,console]
--------------------------------------------------
POST _reindex
{
  "source": {
    "index": "temp-signals" <1>
  },
  "dest": {
    "index": ".siem-signals-<space>-mappingfix" <2>
  }
}
--------------------------------------------------
<1> The name of the index in which existing alerts were stored when you
performed <<copy-alerts>>.
<2> Name of the new index with the correct mappings to which previously existing
alerts are restored. `<space>` is the name of the {kib} space (for example,
`"index": ".siem-signals-default-mappingfix"`).
+
The console output pane displays text similar to this:
+
[source,console-result]
--------------------------------------------------
#! Deprecation: index name [.siem-signals-default-mappingfix] starts with a dot
'.', in the next major version, index names starting with a dot are reserved for
hidden indices and system indices
{
  "took" : 170,
  "timed_out" : false,
  "total" : 15,
  "updated" : 0,
  "created" : 15,
  "deleted" : 0,
  "batches" : 1,
  "version_conflicts" : 0,
  "noops" : 0,
  "retries" : {
    "bulk" : 0,
    "search" : 0
  },
  "throttled_millis" : 0,
  "requests_per_second" : -1.0,
  "throttled_until_millis" : 0,
  "failures" : [ ]
}
--------------------------------------------------

NOTE: Ignore the deprecation warning.

[discrete]
[[index-alias]]
=== Set up index alias

To display reindexed alerts in the {es-sec-app}, create an index alias:

. Go to *Management* -> *Dev Tools*.
. Run the following command:
+
[source,console]
--------------------------------------------------
POST /_aliases
{
    "actions" : [
        { "add" : { "index" : ".siem-signals-<space>-mappingfix",
        "alias" : ".siem-signals-<space>" } } <1>
    ]
}
--------------------------------------------------
<1> The name of the index created when you performed <<restore-index>>.
`<space>` is the {kib} space name (for example:
`.siem-signals-default-mappingfix`).
+
The console output pane displays this text:
+
[source,console-result]
--------------------------------------------------
{
  "acknowledged" : true
}
--------------------------------------------------
. To confirm the alias exists, run this command:
+
[source,console]
--------------------------------------------------
GET .siem-signals-<space>/_alias
--------------------------------------------------
+
The console output pane should display text similar to this:
+
[source,console-result]
--------------------------------------------------
{
  ".siem-signals-default-000001" : {
    "aliases" : {
      ".siem-signals-default" : {
        "is_write_index" : true
      }
    }
  },
  ".siem-signals-default-mappingfix" : {
    "aliases" : {
      ".siem-signals-default" : { }
    }
  }
}
--------------------------------------------------
