[[whats-new]]
[chapter]
= What's new

[discrete]
[[sec-7.12-release]]
== 7.12 release

[discrete]
[[sec-enhancements-7.12]]
=== New features

* <<ransomware-prevention, Ransomware protection>> is enabled on Windows and macOS protected hosts for customers with a Platinum or Enterprise license.
* Enhanced <<malware-prevention, malware prevention>> capabilities of the {agent} to increase accuracy.
* 86 new <<prebuilt-rules, prebuilt detection rules>>.
* Write an Event Query Language (EQL) query directly in the Timeline to <<filter-with-eql, view matched, ordered events>> directly in the Timeline table.
* Support for multiple <<create-threshold-rule, aggregations in threshold rules>> by enabling grouping across multiple fields and adding a new `Count` field to check cardinality.
* Threshold rules are now compatible with <<detection-rule-exceptions, creating an exception>>.
* A new <<cases-ui-integrations, connector>> with ServiceNow Security Incident Response (SIR) to enable orchestration and response workflows.


[discrete]
[[sec-7.11-release]]
== 7.11 release

[discrete]
[[sec-enhancements-7.11]]
=== New features

* New <<prebuilt-rules, prebuilt detection rules>>.
* <<detections-ui-exceptions, Exceptions>> can be assigned to to threshold and {ml} rules.
* Enhanced UI to <<manage-exceptions, view and manage exceptions>>.
* Add MITRE ATT&CK sub-techniques in <<rule-ui-advanced-params, advanced rule settings>>.
* New <<rule-notifications, rule actions>> and enhanced <<rule-action-variables, alert notifications>>.
* New support for <<cold-tier-detections, cold tier data>> and searchable snapshots for specific {es} indices.
* <<self-protection, Self-protection>> enabled on Windows and macOS by default.
* Register {es-sec} as an <<register-as-antivirus, antivirus solution>> on Windows.
* Customize <<malware-protection, malware>> notification messages.
* Enhanced <<timelines-ui, Timeline>> design with accessibility features.
* Enhanced capability to add a <<trusted-apps-ov, trusted application>> by signer.
* Enhanced <<visual-event-analyzer, event visualization>> for Endpoint and Windows process events.
* New <<signals-migration-api, detection alerts migration API>> feature, which can be used to enable new features on existing detection alerts.
* Fourteen new {ml} {anomaly-jobs} have been added, which support multi-index analysis for Linux or Windows data and detect anomalous user, process, and network port activity. See <<security-linux-jobs>> and <<security-windows-jobs>>.

[discrete]
[[sec-7.10-release]]
== 7.10 release

[discrete]
[[sec-7.10-term-changes]]
=== Terminology changes

* *Ingest Manager* has been renamed to *Fleet*.
* *Configuration* has been renamed to *Policy*.

[discrete]
[[enhancements-7.10]]
=== New features
* New support for macOS 11.0 (Big Sur).
* Enhanced user interface for the <<admin-page-ov, Endpoint Administration>> page.
* Add <<trusted-apps-ov, trusted applications>> to avoid performance or compatibility issues.
* New <<create-eql-rule, Event Correlation rule type>> based on {ref}/eql.html[EQL (Event Query Language)].
* New <<create-indicator-rule, Indicator Match rule type>> to create alerts for index field values that match threat indices.
* Free, open detections in the https://github.com/elastic/detection-rules#detection-rules[Detection Rules repo].
* New <<timelines-ui, Timeline enhancements>> that include detection alert actions.
* Connect and send <<cases-overview, cases>> to external systems (ServiceNow, Jira, Resilient).
* In addition to new <<prebuilt-rules, prebuilt rules>> for 7.10, {elastic-sec} now provides additional {anomaly-jobs} for {auditbeat} and
{winlogbeat} data. Twelve new metadata and discovery analysis jobs have been
added to enable threat detection on metadata services, system and discovery
processes, and compiler events. For the full list, see <<prebuilt-ml-jobs>>.

[discrete]
[[sec-7.9-release]]
== 7.9 release

In the 7.9 release, Elastic SIEM and Endpoint Security combined into a single unified app, *Elastic Security*. The following lists the new changes as a result of the merge.

[discrete]
[[sec-terminology-changes]]
=== Terminology changes

* *Signal detection rules* have been renamed to *detection rules*.
* *Signals* are now called *detection alerts*, which fall into one of the
following categories:
** *Detection alerts:* Alerts occurring within the Elastic Security from the
rules engine.
** *External alerts:* Alerts originating outside of Elastic Security.
** *Kibana alerts:* Alerts native to Kibana (may not be security related).
* *Whitelist* is now called the *Exception list*. Items added to the Exception
list are known as *exceptions*.

[discrete]
[[sec-nav-changes]]
=== Navigation changes

* The former *Alerts* tab has been renamed to *Detections*.
** The *Alerts* title page in the Detections tab has been renamed to *Detection
alerts*.
** *Alert count* has been renamed to *Trend*.
* In the *Overview* tab:
** *Alert count* has been renamed to *Detection alert trend*.
** *External alert count* has been renamed to *External alert trend*.
* A new tab, *Administration*, allows analysts to view and manage hosts running
Elastic Endpoint Security. From this page you can also manage integrations and
check the configuration status of hosts to ensure they're protected.

[discrete]
[[enhancements-7.9]]
=== New features

* <<detections-ui-exceptions, Rule exceptions to allow trusted processes and network activity>>
* <<rules-ui-create, Detection rules based on threshold values>>
* <<install-endpoint, Integration with the endpoint security agent>>
* <<timeline-templates-ui, Timeline templates>>
* <<cases-ui-integrations, IBM Resilient integration with Cases>>
* Persistence for all UI table customizations
