[[index-api-overview]]
=== Index endpoint

You use the index endpoint to create, get, and delete
`.siem-signals-<Kibana-space>` system indices in a {kib} space.

NOTE: Console supports only Elasticsearch APIs. Console doesn't allow interactions with {kib} APIs. You must use `curl` or another HTTP tool instead. For more information, refer to https://www.elastic.co/guide/en/kibana/current/console-kibana.html[Console].

NOTE: Signal indices store detection alerts.

For information about the permissions and privileges required to create
`.siem-signals-<Kibana-space>` indices, see <<enable-detections-ui>>.

When you create a signal index, the following
{ref}/getting-started-index-lifecycle-management.html[{ilm} ({ilm-init})]
policy is created for the signal index:
[source,js]
--------------------------------------------------
{
  "policy": {
    "phases": {
      "hot": {
        "min_age": "0ms",
        "actions": {
          "rollover": {
            "max_size": "50gb",
            "max_age": "30d"
          }
        }
      }
    }
  }
}
--------------------------------------------------

The `policy` and `rollover_alias` use the same name as the signal index.

==== Create index

Creates a signal index. The naming convention for the index is
`.siem-signals-<space name>`.

===== Request URL

`POST  <kibana host>:<port>/api/detection_engine/index`

====== Example request

Creates a signal index in the {kib} `siem` space.

[source,console]
--------------------------------------------------
POST s/siem/api/detection_engine/index
--------------------------------------------------
// KIBANA

===== Response code

`200`::
    Indicates a successful call.

==== Get index

Gets the signal index name if it exists.

===== Request URL

`GET <kibana host>:<port>/api/detection_engine/index`

====== Example request

Gets the signal index for the {kib} `siem` space:

[source,console]
--------------------------------------------------
GET s/siem/api/detection_engine/index
--------------------------------------------------
// KIBANA

===== Response code

`200`::
    Indicates a successful call.
`404`::
    Indicates no index exists.

====== Example responses

Example response when index exists:

[source,json]
--------------------------------------------------
{
  "name": ".siem-signals-siem"
}
--------------------------------------------------

Example response when no index exists:

[source,json]
--------------------------------------------------
{
  "statusCode": 404,
  "error": "Not Found",
  "message": "index for this space does not exist"
}
--------------------------------------------------

==== Delete index

Deletes the signal index.

===== Request URL

`DELETE <kibana host>:<port>/api/detection_engine/index`

====== Example request

Deletes the signal index for the {kib} `siem` space:

[source, js]
--------------------------------------------------
DELETE s/siem/api/detection_engine/index
--------------------------------------------------
// KIBANA

===== Response code

`200`::
    Indicates a successful call.
