[[detections-ui-exceptions]]
== Rule exceptions

Rule exceptions are associated with detection and endpoint rules, and are used to prevent a rule from generating an alert from incoming events even when the rule's other criteria are met. 

Exceptions contain the source event conditions that determine when alerts are _not_ generated. They can be used to reduce the number of false positives, and to prevent trusted processes and network activity from generating unnecessary alerts. You can also use value lists to define exceptions for detection rules. Refer to <<value-lists-exceptions>> to learn more.

The exceptions feature is made up of several components:

* *Exception item*: A single exception. You can add an exception item to a default rule list or a shared exception list.
* *Default rule list*: A group of exception items that belong to a single detection rule. Exception items within a rule's default rule list _cannot_ be used by any other rules.
* *Shared exception list*: A group of exception items that _can_ be used by multiple detection rules.

