[[exclude-cold-frozen-data-individual-rules]]
== Exclude cold and frozen data from rule executions

:frontmatter-description: Configure a rule to ignore cold and frozen data during execution. 
:frontmatter-tags-products: [security]
:frontmatter-tags-content-type: [how-to]
:frontmatter-tags-user-goals: [manage]

Rules that query cold and frozen {ref}/data-tiers.html[data tiers] might perform more slowly. To exclude query results from cold and frozen tiers, add a Query DSL filter that ignores cold and frozen documents when executing. This can help Elasticsearch exclude cold and frozen data more efficiently. You can add the filter when creating a new rule or updating an existing one.

NOTE: This method is not supported for {esql} and {ml} rules.

TIP: To ensure that _all_ rules in a {kib} space exclude cold and frozen documents when executing, configure the `excludedDataTiersForRuleExecution` <<exclude-cold-frozen-data-rule-executions,advanced setting>>.

Here is a sample Query DSL filter that excludes documents from a frozen tier during a rule's execution:

[source,console]
----
{
   "bool":{
      "must_not":{
         "terms":{
            "_tier":[
               "data_frozen"
            ]
         }
      }
   }
}
----

Here is another sample Query DSL filter that excludes documents from cold and frozen tiers during a rule’s execution:

[source,console]
----
{
   "bool":{
      "must_not":{
         "terms":{
            "_tier":[
               "data_frozen", "data_cold"
            ]
         }
      }
   }
}
----

