[[detections-ui-exceptions]]
== Rule exceptions

Rule exceptions are associated with detection and endpoint rules, and are used to prevent a rule from generating an alert from incoming events even when the rule's other criteria are met. 

Exceptions contain the source event conditions that determine when alerts are _not_ generated. They can be used to reduce the number of false positives, and to prevent trusted processes and network activity from generating unnecessary alerts.

The exceptions feature is made up of several components:

* *Exception items*: An individual exception. 
* *Value lists*: A list that holds multiple values of the same Elasticsearch data type, such as IP addresses, which are used to determine when an exception prevents an alert from being generated. You can use value lists to define rule exceptions. 
+
IMPORTANT: You cannot use lists with endpoint rule exceptions.
* *Default rule list*: A list of exceptions for an individual rule.
* *Shared exception list*: A logical group of exceptions that can be shared by multiple rules.


