[[rules-cross-cluster-search]]
== Cross-cluster search and detection rules

{ref}/modules-cross-cluster-search.html[Cross-cluster search] is an {es} feature that allows one cluster (the _local_ cluster) to query data in a separate cluster (the _remote_ cluster). {elastic-sec}'s detection rules can perform cross-cluster search to query security data in remote clusters, but it requires additional configuration and considerations.

* Both the local and remote clusters must have the same {ref}/remote-clusters-privileges.html[role privileges] to access the indices being queried on the remote cluster.

* If there are any changes made to the role on the local cluster, you must update the API keys for any detection rules using that role for cross-cluster search. You can do this in {kib} -> *Stack Management* -> *Rules* on the local cluster. Refer to <<update-api-keys>> below for instructions.

[discrete]
[[update-api-keys]]
=== Update API keys for rules

If the role on the local cluster is changed, you'll need to update the API keys for detection rules that use that role.

. On the local cluster, to {kib} -> *Stack Management* -> *Rules*.
. Use the search box and drop-down filters to find the rules you want to update. For example, you can use the *Type* filter to find rules under the *Security* category.
. Select the checkbox next to each rule's name, then select *Selected _x_ rules* -> *Update API keys*.
+
TIP: You can also update a single rule by selecting the rule's actions menu (*...*) -> *Update API key*.