[[use-osquery]]
== Use Osquery 

https://osquery.io[Osquery] is an open source tool that lets you query operating systems like a database, providing you with visibility into your infrastructure and operating systems.
Using basic SQL commands, you can ask questions about devices, such as servers, Docker containers, and computers running Linux, macOS, or Windows.
The https://osquery.io/schema[extensive schema] helps with a variety of use cases, including vulnerability detection, compliance monitoring, incident investigations, and more.

With Osquery in {elastic-sec}, you can:

 * Run live queries for one or more agents
 * Schedule query packs to capture changes to OS state over time
 * View a history of past queries and their results
 * Save queries and build a library of queries for specific use cases

[float]
[[osquery-prereqs]]
=== Prerequisites 
To use Osquery in {elastic-sec}, you must complete the following:

* Enable the {kibana-ref}/manage-osquery-integration.html[Osquery manager integration] on the hosts you want to query.
* Set the appropriate {kibana-ref}/osquery.html[role's privileges] to allow access to Osquery.
* Verify that {fleet-guide}/view-elastic-agent-status.html[{agent}'s status] is *Healthy*. Refer to {fleet-guide}/fleet-troubleshooting.html[{fleet} Troubleshooting] if it is not.


[float]
[[osquery-role-privs]]
== Osquery Manager required privileges

To use *Osquery Manager*, you must be assigned to a role with the following privileges:

* `Read` privileges for the `logs-osquery_manager.result*` index.
* {kib} privileges for **Osquery Manager**. The `All` privilege
enables you to run, schedule, and save queries. `Read` enables you to
view live and scheduled query results, but you cannot run live queries or edit.
