[[use-osquery]]
== Use Osquery

Osquery is an open source tool that lets you query operating systems like a database using SQL. When you add the {kibana-ref}/manage-osquery-integration.html[Osquery manager integration] to an {agent} policy, Osquery is deployed to all agents assigned to that policy. Once you've completed this setup, you can {kibana-ref}/osquery.html[run live queries and schedule recurring queries] for those agents to gather data from your entire environment. These capabilities help with real time incident response, threat hunting, and regular monitoring to detect vulnerability or compliance issues.

You can use Osquery with {elastic-sec} to perform any of the following:

* <<osquery-response-action,Add Osquery Response Actions>> to custom query rules to gather additional information about alerts.
* <<invest-guide-run-osquery,Incorporate live queries into investigation guides>> to enhance your research capabilities while investigating possible security issues.
* <<alerts-run-osquery,Run live queries from alerts>> to uncover real-time information about your environment.
