[[data-quality-dash]]
= Data Quality dashboard

The Data Quality dashboard shows you whether your data is effectively mapped to the https://www.elastic.co/guide/en/ecs/current/ecs-reference.html[Elastic Common Schema] (ECS). Successful mapping enables you to search, visualize, and interact with your data throughout {es-sec} and {kib}.

[image]

You can use the Data Quality dashboard to:
* Check one or multiple indices (by default, the indices used by {es-sec}) for unsuccessful mappings, helping you quickly remediate problems.
* View detailed information about the fields in assessed indices.
* Create a case based on Data Quality results.
* Share comprehensive reports in Markdown.

NOTE: The Data Quality dashboard does not show data from cold or frozen {ref}/data-tiers.html[data tiers].

[discrete]
== Check indices
When you open the dashboard, data does not appear until you select which indices to check.

*Check multiple indices:*
To check all indices in the current data view, click *Check all* at the top of the dashboard. A progress indicator will appear.

*Check a single index:*
To check a single index, expand it using the arrow on the left. Checking a single index is faster than checking all indices.

[discrete]
== Data Quality dashboard user interface

[discrete]
== Create a case based on Data Quality results
