name: Docs Preview Links

on:
  pull_request_target:
    types: [opened]

jobs:
  doc-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        name: Add doc preview links
        with:
          script: |
            const pr = context.payload.pull_request;
            const comment = `Documentation previews:
              - ✨ [HTML diff](https://${context.repo.repo}_${pr.number}.docs-preview.app.elstc.co/diff)
              - 📙 [Elastic Security Guide](https://${context.repo.repo}_${pr.number}.docs-preview.app.elstc.co/guide/en/security/master/index.html)`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment,
            });
